### ISSUE TITLE
导入兼容性不好

### ISSUE THREAD

**Issue by wangyongpenga** [OpenFlutter/fluwx#1]
android引入fluwx进行分享报kotlin错误

**Comment by wangyongpenga** [comment]
* Error running Gradle:
Exit code 1 from: C:\Users\Administrator\Desktop\flutter_refresh-master\flutter_refresh-master\android\gradlew.bat app:properties:
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
WARNING: The specified Android SDK Build Tools version (25.0.0) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluwx'.
> Could not resolve all files for configuration ':fluwx:classpath'.
   > Could not download kotlin-android-extensions.jar (org.jetbrains.kotlin:kotlin-android-extensions:1.2.60)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-android-extensions/1.2.60/kotlin-android-extensions-1.2.60.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-android-extensions/1.2.60/kotlin-android-extensions-1.2.60.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.154, d29vzk4ow07wi7.cloudfront.net/54.230.86.166, d29vzk4ow07wi7.cloudfront.net/54.230.86.7, d29vzk4ow07wi7.cloudfront.net/54.230.86.86] failed: Read timed out
   > Could not download kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.60)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.2.60/kotlin-compiler-embeddable-1.2.60.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.2.60/kotlin-compiler-embeddable-1.2.60.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.154, d29vzk4ow07wi7.cloudfront.net/54.230.86.166, d29vzk4ow07wi7.cloudfront.net/54.230.86.7, d29vzk4ow07wi7.cloudfront.net/54.230.86.86] failed: Read timed out
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.2.60)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.60/kotlin-reflect-1.2.60.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.60/kotlin-reflect-1.2.60.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.154, d29vzk4ow07wi7.cloudfront.net/54.230.86.166, d29vzk4ow07wi7.cloudfront.net/54.230.86.7, d29vzk4ow07wi7.cloudfront.net/54.230.86.86] failed: Read timed out
   > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.2.60)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.60/kotlin-stdlib-1.2.60.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.60/kotlin-stdlib-1.2.60.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.154, d29vzk4ow07wi7.cloudfront.net/54.230.86.166, d29vzk4ow07wi7.cloudfront.net/54.230.86.7, d29vzk4ow07wi7.cloudfront.net/54.230.86.86] failed: Read timed out
   > Could not download kotlin-build-common.jar (org.jetbrains.kotlin:kotlin-build-common:1.2.60)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.2.60/kotlin-build-common-1.2.60.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.2.60/kotlin-build-common-1.2.60.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.7, d29vzk4ow07wi7.cloudfront.net/54.230.86.154, d29vzk4ow07wi7.cloudfront.net/54.230.86.166, d29vzk4ow07wi7.cloudfront.net/54.230.86.86] failed: Read timed out
   > Could not download kotlin-daemon-client.jar (org.jetbrains.kotlin:kotlin-daemon-client:1.2.60)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-client/1.2.60/kotlin-daemon-client-1.2.60.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-client/1.2.60/kotlin-daemon-client-1.2.60.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.7, d29vzk4ow07wi7.cloudfront.net/54.230.86.154, d29vzk4ow07wi7.cloudfront.net/54.230.86.166, d29vzk4ow07wi7.cloudfront.net/54.230.86.86] failed: Read timed out

**Comment by wangyongpenga** [comment]
报上面的kotlin依赖无法下载应该怎么搞？？

**Comment by JarvanMo** [comment]
kotlin需要更新到１.2.60。

**Comment by JarvanMo** [comment]
@wangyongpenga 正常来说都是网络引起的。换一个好一点的网，或者翻墙。

**Comment by JarvanMo** [comment]
挂个代理也行。你要是懂Android的话可以手动更新Kotlin。
