### ISSUE TITLE
请教这个报错怎么解决！打包的时候

### ISSUE THREAD

**Issue by FanChael** [OpenFlutter/fluwx#100]
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :fluwx.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

* Try:

**Comment by JarvanMo** [comment]
gradle kotlin版本分别多少？

**Comment by FanChael** [comment]
gradle-4.10.2-all.zip

ext.kotlin_version = '1.3.0'

**Comment by JarvanMo** [comment]
kotlin升级到1.3.41 ------------------ 原始邮件 ------------------
发件人: "HuangLei"<notifications@github.com>
发送时间: 2019年8月29日(星期四) 晚上6:19
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 请教这个报错怎么解决！打包的时候 (#100)



gradle-4.10.2-all.zip
 
ext.kotlin_version = '1.3.0'
 
&mdash;
