### ISSUE TITLE
有没可能支持去支付版

### ISSUE THREAD

**Issue by qq125183592** [OpenFlutter/fluwx#103]
作者你好：
    是否可以考虑做一个无微信支付的阉割版插件呢，我们目前只使用了登录和分享等功能，但是发布到苹果市场审核时被拒，就是检测到有支付功能的内容，苹果那边也不允许接入微信支付这些部分。盼回复～

**Comment by JarvanMo** [comment]
我现在时间精力有限。如果有需求，可以PR。------------------ 原始邮件 ------------------
发件人: "qq125183592"<notifications@github.com>
发送时间: 2019年9月5日(星期四) 中午11:41
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 有没可能支持去支付版 (#103)



作者你好：
 是否可以考虑做一个无微信支付的阉割版插&#x4EF6;呢，我们目前只使用了登录和分享等功能，但是发布到苹果市场审核时被拒，就是检测到有支付功能的内容，苹果那边也不允许接入微信支付这些部分。盼回复～
 
&mdash;

**Comment by qq125183592** [comment]
明白，谢谢～

**Comment by JarvanMo** [comment]
换用一下SDK，删除支付相关的就行了。打个分支，做好了可以PR，方便有同样需求的朋友。

**Comment by qq125183592** [comment]
如果找不到适合的，尝试看会不会弄 😄

**Comment by JarvanMo** [comment]
要么你就去我们群里发悬赏，看看有没有人可以帮你做一下。

**Comment by qq125183592** [comment]
我们先研究下，自己动手更能理解。有困难我们再看，如果有分离的版本再给大家分享。

**Comment by JarvanMo** [comment]
换依赖，删代码就行了

**Comment by qq125183592** [comment]
嗯，之前改过一个播放器的，原理应该就是import我们改的代码，payment相关的删掉就行对吧

**Comment by unclexiao** [comment]
再加个内置支付(build in purches)或者钱包支付(payment)选项就好了呀

**Comment by JakeWoki** [comment]
只有微信支付，没有其它的功能版本是不是也可以有？

**Comment by JarvanMo** [comment]
看readme啊。。。。------------------ 原始邮件 ------------------
发件人: "Jake Woki"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午5:29
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 有没可能支持去支付版 (#103)




 
只有微信支付，没有其它的功能版本是不是也可以有？
 
&mdash;

**Comment by JakeWoki** [comment]
@JarvanMo 我是说只有微信支付，没有分享、登录、拉起小程序、订阅等功能

**Comment by JarvanMo** [comment]
看分支啊------------------ 原始邮件 ------------------
发件人: "Jake Woki"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午5:32
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 有没可能支持去支付版 (#103)




 
@JarvanMo 我是说只有微信支付，没有分享、登录、拉起小程序、订阅等功能
 
&mdash;

**Comment by JarvanMo** [comment]
现在就有这个分支，不过已经不维护了，没有什么意义------------------ 原始邮件 ------------------
发件人: "Jake Woki"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午5:32
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 有没可能支持去支付版 (#103)




 
@JarvanMo 我是说只有微信支付，没有分享、登录、拉起小程序、订阅等功能
 
&mdash;

**Comment by JakeWoki** [comment]
@JarvanMo 看到了，readme上没说明，忘记看分支了

**Comment by JakeWoki** [comment]
@JarvanMo 还是有意义的，毕竟flutter开发出来的安装包已经非常大了，第三方so库jar等一般都不小，用不到的功能不加上，减小包大小还是有必要的

**Comment by JarvanMo** [comment]
没有意义，底层的包没有变动，只是API级别，微信没有这样的SDK------------------ 原始邮件 ------------------
发件人: "Jake Woki"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午5:41
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 有没可能支持去支付版 (#103)




 
@JarvanMo 还是有意义的，毕竟flutter开发出来的安装包已经非常大了，第三方so库jar等一般都不小，用不到的功能不加上，减小包大小还是有必要的
 
&mdash;

**Comment by JakeWoki** [comment]
才注意到微信没区分sdk，那就意义不大了
