### ISSUE TITLE
提示签名错误

### ISSUE THREAD

**Issue by xiejibiao** [OpenFlutter/fluwx#104]
微信分享，我开了微信分身的，在第一个微信上面，它会提示我签名错误，在分身微信倒是正常的，这个是为什么？？

**Comment by JarvanMo** [comment]
应该是微信缓存引起的。和fluwx没有任何关系。------------------ 原始邮件 ------------------
发件人: "xiejibiao"<notifications@github.com>
发送时间: 2019年9月5日(星期四) 晚上6:43
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 提示签名错误 (#104)



微信分享，我开了微信分身的，在第一个微信上面，它会提示我签名错误，在分身微信倒是正常的，这个是为什么？？
 
&mdash;
