### ISSUE TITLE
how get the access_token

### ISSUE THREAD

**Issue by caipeng-hrv** [OpenFlutter/fluwx#107]

**Comment by caipeng-hrv** [comment]
how get the access_token when use fluwx.sendAuth
fluwx.sendAuth(
                      scope: "snsapi_userinfo", state: "wechat_sdk_demo_test")
                  .then((data) {
                    print(data);//the data always ture.
                  });

**Comment by JarvanMo** [comment]
Take a look at [this guidance](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317851&token=&lang=zh_CN).
`sendAuth`  is the first step to get `code` and then follow the second step.  Usually , we do the second and the third in the server.

**Comment by caipeng-hrv** [comment]
I can not get the code by sendAuth,it is always get the True of the result.

**Comment by JarvanMo** [comment]
read fluwx documents very very very carefully------------------ 原始邮件 ------------------
发件人: "beyond"<notifications@github.com>
发送时间: 2019年9月10日(星期二) 上午9:39
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] how get the access_token (#107)



I can not get the code by sendAuth,it is always get the True of the result.
 
&mdash;

**Comment by caipeng-hrv** [comment]
ok,thank you
