### ISSUE TITLE
可以测试一下最新版的flutter么？ master channel 1.10.x

### ISSUE THREAD

**Issue by rockingdice** [OpenFlutter/fluwx#108]
我这里升级后，微信登录开始报错了：

_channel是空：
···
final MethodChannel _channel = const MethodChannel('com.jarvanmo/fluwx')
  ..setMethodCallHandler(_handler);
···

堆栈：
···
E/flutter (19846): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'invokeMethod' was called on null.
E/flutter (19846): Receiver: null
E/flutter (19846): Tried calling: invokeMethod<dynamic>("isWeChatInstalled")
E/flutter (19846): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (19846): #1      isWeChatInstalled (package:fluwx/src/fluwx_iml.dart:269:25)
E/flutter (19846): <asynchronous suspension>
E/flutter (19846): #2      _LoginPageState.loginWithWechat (package:mhwo/login/login_page.dart:130:5)
E/flutter (19846): #3      _LoginPageState._buildSignIn.<anonymous closure> (package:mhwo/login/login_page.dart:653:25)
E/flutter (19846): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19846): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (19846): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (19846): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (19846): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (19846): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (19846): #10     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (19846): #11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (19846): #12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (19846): #13     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (19846): #14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (19846): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (19846): #16     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (19846): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
···

···
          v 这里报错
fluwx.isWeChatInstalled().then((installed) {

    });
···

**Comment by JarvanMo** [comment]
本项目不基于mater开发。

**Comment by rockingdice** [comment]
好吧 我自己解决

**Comment by rockingdice** [comment]
给后面会遇到问题的人提个醒，如果遇到相同问题，在runApp之前调用：
WidgetsFlutterBinding.ensureInitialized();

应该是升级后会出现的问题。
