### ISSUE TITLE
When I share image from Uint8List，it crashed at "FlutterStandardTypedData typedDataWithBytes:"

### ISSUE THREAD

**Issue by HQApe** [OpenFlutter/fluwx#110]
Because the argument of this method ```FlutterStandardTypedData typedDataWithBytes:``` is ```NSDate```. While your input argument ```call.arguments[fluwxKeyImageData]``` is ```FlutterStandardTypedData```，so it crashed.
```
if ([StringUtil isBlank:imagePath]) {
        NSData *imageData = [FlutterStandardTypedData typedDataWithBytes:call.arguments[fluwxKeyImageData]].data;
        [self shareMemoryImage:call result:result imageData:imageData];
    }
```

**Comment by JarvanMo** [comment]
you can fix this by PR.
