### ISSUE TITLE
分享小程序导致闪退

### ISSUE THREAD

**Issue by xuexirong** [OpenFlutter/fluwx#112]
var model = fluwx.WeChatShareMiniProgramModel(
          webPageUrl: 'https://www.baidu.com',
          path: _webPageUrl,
          userName: WX_BASE_ID,
          title: "这么棒",
          description: 'dsdsds',
          thumbnail: data);

**Comment by JarvanMo** [comment]
请提供日志。

**Comment by xuexirong** [comment]
知道原因了，图片过大，导致闪退
