### ISSUE TITLE
ios授权后取不到code

### ISSUE THREAD

**Issue by niugengyun** [OpenFlutter/fluwx#113]
/// [universalLink] is required if you want to register on iOS.
  这个必须配置才可以取到吗？
具体怎么配置呢 能否详细说明下

**Comment by niugengyun** [comment]
经排查 ios发现：

fluwx.responseFromAuth.listen 授权后里面的代码没走

安卓走了

**Comment by JarvanMo** [comment]
关于universal link微信官方文档说的很清楚。

**Comment by JarvanMo** [comment]
至于怎么定义universal link ，怎么用，我也不会。

**Comment by niugengyun** [comment]
想授权的话，必须用这个东西吗

**Comment by JarvanMo** [comment]
是的。

**Comment by JarvanMo** [comment]
具体你看微信官方文档就知道了。

**Comment by niugengyun** [comment]
这就很尴尬了……看不懂

**Comment by JarvanMo** [comment]
我只知道universal link可以用来跳转app。你可以百度universal link配置教程。除此之外你还要配置url schema。

**Comment by niugengyun** [comment]
我这边用纯原声试了试 ，之前的跳转方式也是可以取到code的，也就是可以不配置Universal Links

微信文档如下：

> 由于苹果iOS 13系统版本安全升级，为此openSDK在1.8.6版本进行了适配。 1.8.6版本支持Universal Links方式跳转，对openSDK分享进行合法性校验，提升使用过程中的安全性。
> 我们建议开发者使用新版本SDK测试时，覆盖测试微信7.0.7版本、iOS12以及苹果新推出的iOS13，以验证所使用的接口的功能性和可用性。
> 

但是我们的为什么取到code呢

**Comment by JarvanMo** [comment]
ios 12.4 & 微信7.0.7上我已经验证过了，可以正常使用。`fluwx 1.1.0`使用的微信SDK是`1.8.6.1`，初始化必须要有universal link，以后你不升级到这个sdk的话肯定不行，审核过不了。[这个文章是univeral link教程]，还要看一下微信官方ios接入文档，添加了一个LSApplicationQueriesSchemes。以上，仔细阅读。

**Comment by JarvanMo** [comment]
最重要的是要兼容ios 13，所以universal link是必须的。

**Comment by niugengyun** [comment]
大神 现在授权后   fluwx.responseFromAuth.listen 里面的代码会走多次

按钮就点了一下

**Comment by niugengyun** [comment]
我测试了：
第1次登陆 监听会走1次
第2次登陆 监听会走2次
......
第10次登陆 监听会走10次


应该是退出时哪个方法每调用

**Comment by niugengyun** [comment]
@JarvanMo

**Comment by JarvanMo** [comment]
This issue has already been tracked by others. Read documents and issues carefully before submitting issues. Not responding from now.

**Comment by unclexiao** [comment]
@niugengyun 请提供核心代码，是不是注册监听的位置不对，或者页面跳转时忘了注销服务？一般情况下，是你们次进入页面后重新`listen`导致的，需要保持状态做个判断
