### ISSUE TITLE
当未配置weixinULAPI Schemes时，调用isWeChatInstalled方法提示有误

### ISSUE THREAD

**Issue by YaoShuwei** [OpenFlutter/fluwx#114]
现在提示的是please config  wxapi first，建议提示failed for URL: "weixinULAPI://" - error: "This app is not allowed to query for scheme weixinulapi"之类的，方便排查错误

**Comment by JarvanMo** [comment]
这个以我目前的经验来说，做不到。因为注册WxApi的时候返回值只是BOOL，具体错误并不知道。不过我计划取消在调用` isWeChatInstalled`之前判断`isWeChatRegistered`。
```
if (!isWeChatRegistered) {
        result([FlutterError errorWithCode:resultErrorNeedWeChat message:@"please config  wxapi first" details:nil]);
        return;
    }
```

如果你有任何主意，可以PR。

**Comment by YaoShuwei** [comment]
> 这个以我目前的经验来说，做不到。因为注册WxApi的时候返回值只是BOOL，具体错误并不知道。不过我计划取消在调用` isWeChatInstalled`之前判断`isWeChatRegistered`。
> 
> ```
> if (!isWeChatRegistered) {
>         result([FlutterError errorWithCode:resultErrorNeedWeChat message:@"please config  wxapi first" details:nil]);
>         return;
>     }
> ```
> 
> 如果你有任何主意，可以PR。

我也不会搞，只是今天在调试的时候一直报please config wxapi first，在xcode里调试才发现了This app is not allowed to query for scheme weixinulapi这个错误，希望大佬能找到一个好的解决方案，加油👍

**Comment by JarvanMo** [comment]
要么是系统打印的，要么是微信SDK打印的。我现在还不知道怎么获取错误。

**Comment by YaoShuwei** [comment]
> 要么是系统打印的，要么是微信SDK打印的。我现在还不知道怎么获取错误。

考虑一下在register的时候，用canOpen判断一下，如果返回false则未安装微信或者未正确配置scheme

**Comment by yuanzhiying** [comment]
也遇到了，怎么处理下呢？-canOpenURL: failed for URL: "weixinULAPI://" - error: "This app is not allowed to query for scheme weixinulapi"

**Comment by JarvanMo** [comment]
@yuanzhiying 去配置weixinULAPI啊。看微信官方的ios接入文档，我强调很多次了，要先看微信官方接入文档。

**Comment by speanut-land** [comment]
所以询问一下作者大佬目前来说有什么好的解决方案 对于配置了UL但还是无法isWeChatInstalled

**Comment by JarvanMo** [comment]
@speanut-land fluwx没有任何问题。你无法作用是因为你的配置有问题，导致wxapi注册失败。

**Comment by speanut-land** [comment]
@JarvanMo  没错是我这边的配置有问题,仔细看了一下微信官方的ios文档，发现得在LSApplicationQueriesSchemes增加一个UL的选项<string>weixinULAPI</string>  感谢作者大大的提醒，事实证明fluwx是完美的🙏

**Comment by cn1001wang** [comment]
> LSApplicationQueriesSchemes



> @JarvanMo 没错是我这边的配置有问题,仔细看了一下微信官方的ios文档，发现得在LSApplicationQueriesSchemes增加一个UL的选项weixinULAPI 感谢作者大大的提醒，事实证明fluwx是完美的🙏

请问LSApplicationQueriesSchemes在哪里配置，XCode工程配置项没找到
![image](https://user-images.githubusercontent.com/34416681/207218874-4dbc8894-0462-498a-b4eb-2a7cd1a10c11.png)

**Comment by cn1001wang** [comment]
> LSApplicationQueriesSchemes

我设置好了，因为他现在改名字了，叫Queried URL Schemes。成功了
