### ISSUE TITLE
WechatOpenSDK 版本降到1.8.6了，这边还依赖的是1.8.6.1，怎么解决

### ISSUE THREAD

**Issue by shuaishuai0814** [OpenFlutter/fluwx#116]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Flutter Version:**
Run `flutter doctor` in terminal or powershell , and copy the outputs.

**Testing Platform:**
Android or iOS?

**Additional context**

**Comment by JarvanMo** [comment]
see the official website download resource for more details. By the way please delete redundant details.

**Comment by shuaishuai0814** [comment]
没太理解什么意思哈
