### ISSUE TITLE
安卓无法使用转发 支付int is not a subtype of bool

### ISSUE THREAD

**Issue by Cyurainya** [OpenFlutter/fluwx#117]
微信分享： iOS测试可以，安卓测试显示 
  ----------》 微信：包名不对，请检查包名是否与开发平台上填写的一致
 但是我检查包名是没有问题的 
 
支付的参数没有问题 （iOS测试没有错误），但是安卓显示错误
-----------》 int is not a subtype of bool
但是是哪个bool类型的参数影响了这个支付呢 我不太清楚 请大佬们给我解答一下

**Comment by JarvanMo** [comment]
微信SDK提示包名不对就是包名不对，没有像任何异议。如果改过就要删除微信重装。
 int is not a subtype of bool 自己去对类型，fluwx支付参数都是强类型。
