### ISSUE TITLE
ios无法使用fluwx.register

### ISSUE THREAD

**Issue by speanut-land** [OpenFlutter/fluwx#118]
andriod测试是可以正常使用fluwx的api,前几天ios没有配置universalLink，也是可以正常的使用(还是1.0.4版本)，今天测试无法使用(1.0.4)，之后配置了universalLink之后(升级到1.1.0)，可以从ios的备忘录跳转到app(也就证明universalLink是可以使用的)，但还是无法使fluwx.register，使用fluwx的example也是同样的(且没有universalLink),实在解决不了 ，提一个issues打扰一下作者 看看是什么原因导致的

**Comment by JarvanMo** [comment]
什么叫无法使用？

**Comment by speanut-land** [comment]
就是突然就无法使用isWeChatInstalled这个api , 自己之后去配置了universalLink ，并且升级版本。之前是没有升级版本，没有使用universalLink，是可以正常使用的。现在报错
```
PlatformException(PlatformException(wxapi not configured, please config  wxapi first, null))
```
但自己确实可以从备忘录点击域名跳转到app，也比对了微信开发者中心到appId与universalLink

**Comment by JarvanMo** [comment]
Duplicate of #114

**Comment by zhaowenjian** [comment]
@speanut-land 同学你的解决了么

**Comment by zhaowenjian** [comment]
@speanut-land 最后是因为什么呀

**Comment by speanut-land** [comment]
@zhaowenjian 首先fluwx本身是没有问题的，你得去微信开发者平台的IOS配置看看你哪里没有配置，去按照官网一步步配置就成功了
