### ISSUE TITLE
安卓版项目构建报错

### ISSUE THREAD

**Issue by lianjianjie** [OpenFlutter/fluwx#12]
更新到0.1.6，可以分享本地文件了，但是构建安卓项目时报错，iOS没问题。
<img width="801" alt="wx20180920-212519 2x" src="https://user-images.githubusercontent.com/16377699/45821407-b5ffb180-bd1b-11e8-8b87-e8618fa52f10.png">

**Comment by JarvanMo** [comment]
@lianjianjie 可能你的本地环境有问题了。

**Comment by lianjianjie** [comment]
嗯，应该不是包的问题，已经解决了，具体啥原因，我也没弄明白
