### ISSUE TITLE
ios端跳转小程序失败

### ISSUE THREAD

**Issue by xuexirong** [OpenFlutter/fluwx#120]
会先跳转到微信  显示正在连接微信
然后就会退回到应用

**Comment by JarvanMo** [comment]
百度或者去微信开放平台论坛查。

**Comment by xuexirong** [comment]
> 百度或者去微信开放平台论坛查。

在有些iphone手机上是可以的，有些不可以，目前是用户反馈的，我自己的手机不知道是不是因为用的最新beta版 也不行

**Comment by JarvanMo** [comment]
你可以选择排查一下是不是universal link的问题。

**Comment by xuexirong** [comment]
> 你可以选择排查一下是不是universal link的问题。

好的  谢谢

**Comment by xuexirong** [comment]
> 你可以选择排查一下是不是universal link的问题。

我们的微信支付是没问题的   只有打开微信小程序有问题，实际上它跳进微信了  也显示正在打开小程序   然后就退回app了，我再去微信里看  小程序已经在最近打开的小程序列表里面了

**Comment by JarvanMo** [comment]
那我不清楚

**Comment by xuexirong** [comment]
> 那我不清楚

好的  我再排查一下吧 辛苦了

**Comment by kennenfromchina** [comment]
> > 那我不清楚
> 
> 好的 我再排查一下吧 辛苦了

请问你解决这个问题了吗？我的分享也是这样，点击分享按钮 -- 打开微信 -- 显示正在连接 -- 然后就跳回自己的APP了，按照[官方文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html)进行排查
1.确认微信的Universal Links正常
![IMG_0437](https://user-images.githubusercontent.com/14858668/69927813-678b9c80-14f4-11ea-8190-d4ca6e29ed98.PNG)
2.确认App的Universal Links配置成功
![IMG_0436](https://user-images.githubusercontent.com/14858668/69927845-85f19800-14f4-11ea-8bef-6c02cd95b9fb.PNG)
check:
配置应用的Universal Links
```
{
	"applinks": {
		"apps": [],
		"details": [{
			"appID": "F5489L598R.com.zhilunkeji.driver-custom",
			"paths": ["/*"]
		}, {
			"appID": "2J25226HMZ.com.zhilunkeji.driver-custom-inhouse",
			"paths": ["/*"]
		}, {
			"appID": "F5489L598R.com.zhilunkeji.business",
			"paths": ["/*"]
		}, {
			"appID": "2J25226HMZ.com.zhilunkeji.business-inhouse",
			"paths": ["/*"]
		}]
	}
}
```

**Comment by xuexirong** [comment]
> > > 那我不清楚
> > 
> > 
> > 好的 我再排查一下吧 辛苦了
> 
> 请问你解决这个问题了吗？我的分享也是这样，点击分享按钮 -- 打开微信 -- 显示正在连接 -- 然后就跳回自己的APP了，按照[官方文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html)进行排查
> 1.确认微信的Universal Links正常
> ![IMG_0437](https://user-images.githubusercontent.com/14858668/69927813-678b9c80-14f4-11ea-8190-d4ca6e29ed98.PNG)
> 2.确认App的Universal Links配置成功
> ![IMG_0436](https://user-images.githubusercontent.com/14858668/69927845-85f19800-14f4-11ea-8bef-6c02cd95b9fb.PNG)
> check:
> 配置应用的Universal Links
> 
> ```
> {
> 	"applinks": {
> 		"apps": [],
> 		"details": [{
> 			"appID": "F5489L598R.com.zhilunkeji.driver-custom",
> 			"paths": ["/*"]
> 		}, {
> 			"appID": "2J25226HMZ.com.zhilunkeji.driver-custom-inhouse",
> 			"paths": ["/*"]
> 		}, {
> 			"appID": "F5489L598R.com.zhilunkeji.business",
> 			"paths": ["/*"]
> 		}, {
> 			"appID": "2J25226HMZ.com.zhilunkeji.business-inhouse",
> 			"paths": ["/*"]
> 		}]
> 	}
> }
> ```
> 
> 每次点击分享都是这样，并不会像官方文档上面写的：跳转微信-正在连接-跳回APP-跳回微信-显示好友列表

我的解决了  是因为在微信网站上配置的ios用的那个文件  路径有问题

**Comment by kennenfromchina** [comment]
> > > > 那我不清楚
> > > 
> > > 
> > > 好的 我再排查一下吧 辛苦了
> > 
> > 
> > 请问你解决这个问题了吗？我的分享也是这样，点击分享按钮 -- 打开微信 -- 显示正在连接 -- 然后就跳回自己的APP了，按照[官方文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html)进行排查
> > 1.确认微信的Universal Links正常
> > ![IMG_0437](https://user-images.githubusercontent.com/14858668/69927813-678b9c80-14f4-11ea-8190-d4ca6e29ed98.PNG)
> > 2.确认App的Universal Links配置成功
> > ![IMG_0436](https://user-images.githubusercontent.com/14858668/69927845-85f19800-14f4-11ea-8bef-6c02cd95b9fb.PNG)
> > check:
> > 配置应用的Universal Links
> > ```
> > {
> > 	"applinks": {
> > 		"apps": [],
> > 		"details": [{
> > 			"appID": "F5489L598R.com.zhilunkeji.driver-custom",
> > 			"paths": ["/*"]
> > 		}, {
> > 			"appID": "2J25226HMZ.com.zhilunkeji.driver-custom-inhouse",
> > 			"paths": ["/*"]
> > 		}, {
> > 			"appID": "F5489L598R.com.zhilunkeji.business",
> > 			"paths": ["/*"]
> > 		}, {
> > 			"appID": "2J25226HMZ.com.zhilunkeji.business-inhouse",
> > 			"paths": ["/*"]
> > 		}]
> > 	}
> > }
> > ```
> > 
> > 
> > 每次点击分享都是这样，并不会像官方文档上面写的：跳转微信-正在连接-跳回APP-跳回微信-显示好友列表
> 
> 我的解决了 是因为在微信网站上配置的ios用的那个文件 路径有问题

嗯呐，刚才排查了一下我项目的代码，需要在appdelegate增加这个函数
```objc
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable restorableObjects))restorationHandler API_AVAILABLE(ios(8.0)) {
    return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
```
之前我这个函数写的有问题
