### ISSUE TITLE
Android: 小程序返回App不成功

### ISSUE THREAD

**Issue by ErosZy** [OpenFlutter/fluwx#122]
**Describe the bug**
Android 9，拉起小程序正常，但是从小程序返回App的时候，程序能通过事件拿到返回内容，但是App没有被吊起到前台。

**To Reproduce**

**Expected behavior**
小程序返回时，App正常启动到前台

**Flutter Version:**
1.9

**Testing Platform:**
Android

**Additional context**

**Comment by JarvanMo** [comment]
这个问题应该和fluwx无关。建议去百度或者去微信SDK论坛。

**Comment by ErosZy** [comment]
目前一加会出现这样的情况

**Comment by hjc22** [comment]
一样失败了，安卓三星s8

**Comment by hjc22** [comment]
我的修复了，把 fluwx 的  android:launchMode="singleTop" 改为  android:launchMode="singleTask"，就好了

**Comment by hjc22** [comment]
看官方示例就是 android:launchMode="singleTask"

**Comment by JarvanMo** [comment]
@hjc22  麻烦提一下PR，谢谢。

**Comment by hjc22** [comment]
> @hjc22 麻烦提一下PR，谢谢。

提了
