### ISSUE TITLE
ios微信登陆后不走回调方法

### ISSUE THREAD

**Issue by YellowDoing** [OpenFlutter/fluwx#123]
ios微信登陆后不走`fluwx.responseFromAuth.listen`回调方法

微信版本7.0.8
fluwx版本  1.1.1

现在微信是通过Universal Links启动app了，不知道是不是跟这个有关系

**Comment by JarvanMo** [comment]
fluwx works well. Maybe you should check the documents or your code.

**Comment by liu2080019** [comment]
楼主解决没，是不是Universal Link的问题
