### ISSUE TITLE
最新插件报错未初始化，以前可以更新后就有问题Unhandled Exception: PlatformException(wxapi not configured, WxApi Not Registered, null)

### ISSUE THREAD

**Issue by 287291867** [OpenFlutter/fluwx#124]

**Comment by 287291867** [comment]
ios分享最新插件报错未初始化，以前可以更新后就有问题Unhandled Exception: PlatformException(wxapi not configured, WxApi Not Registered, null)

**Comment by JarvanMo** [comment]
Duplicate of #114

**Comment by wanlinmei** [comment]
为什么我都配置了，还说我没有注册,和universallink有关吗

**Comment by theecn** [comment]
作者能看下是什么问题吗 ？？ios无法唤起微信，Xcode也是报wxapi 未配置，但是 我反复把你上面的每个问题都看了几遍 也添加了 ulapi等，另外安卓是能够正常支付的 不懂为啥 ios等不行

**Comment by huoda1237** [comment]
> 作者能看下是什么问题吗 ？？ios无法唤起微信，Xcode也是报wxapi 未配置，但是 我反复把你上面的每个问题都看了几遍 也添加了 ulapi等，另外安卓是能够正常支付的 不懂为啥 ios等不行

我的是安卓不能调起微信iOS可以调起微信，不知道怎么解决，大佬有解决方式吗？没搞过安卓，按照微信开发文档的配置以后也是不行

**Comment by dingdangdog** [comment]
> 我的是安卓不能调起微信iOS可以调起微信，不知道怎么解决，大佬有解决方式吗？没搞过安卓，按照微信开发文档的配置以后也是不行

Android 解决了吗？怎么解决啊

**Comment by dingdangdog** [comment]
![Image](https://github.com/user-attachments/assets/459b2eea-75dd-45c7-a551-6e934227698b)

我的问题解决了， `isWeChatInstalled` 调整到 `registerApi` 之后调用就可以了。😅
