### ISSUE TITLE
compileSdkVersion需升级到28

### ISSUE THREAD

**Issue by yintaibing** [OpenFlutter/fluwx#125]
目前compileSdkVersion=27，导致安卓打release包时失败，报错：
error: resource android:attr/fontVariationSettings not found.
error: resource android:attr/ttcIndex not found.
升级到28可解决。

**Comment by JarvanMo** [comment]
you can fix by PR.

**Comment by yintaibing** [comment]
@JarvanMo 
PR已提交[PR 126](https://github.com/OpenFlutter/fluwx/pull/126)

**Comment by JarvanMo** [comment]
#126
