### ISSUE TITLE
请问能否创建一个不包含支付接口的版本

### ISSUE THREAD

**Issue by 39251474** [OpenFlutter/fluwx#129]
我们的项目没有使用微信支付，但是由于ios端使用的是包含支付的微信sdk导致ios无法通过审核。
请问能否像pay_only一样创建一个不包含支付的分支发布呢？谢谢！

**Comment by JarvanMo** [comment]
目前我的时间精力不足。有兴趣的可以PR，替换一下sdk，删除支付相关的就行。

**Comment by JarvanMo** [comment]
take a look at [fluwx_no_pay](https://pub.dev/packages/fluwx_no_pay).

**Comment by 39251474** [comment]
谢谢你，辛苦了
