### ISSUE TITLE
转型错误

### ISSUE THREAD

**Issue by ManhonSzeto** [OpenFlutter/fluwx#13]
fluwx/ios/Classes/handler/FluwxPaymentHandler.m 30行
原 UInt32 timeStamp = (UInt32) call.arguments[@"timeStamp"];
会转型错误，是否应该采用
UInt32 timeStamp = [call.arguments[@"timeStamp"] unsignedIntValue];
？

**Comment by JarvanMo** [comment]
用的是13位时间戳？

**Comment by ManhonSzeto** [comment]
10位，1537796664，iphonex真机签名失败，断点发现timeStamp不一样了，改成unsignedIntValue 就可以了
