### ISSUE TITLE
iOS 出现[!] No podspec found for `fluwx` in `.symlinks/plugins/fluwx/ios`

### ISSUE THREAD

**Issue by pheromone** [OpenFlutter/fluwx#131]
![image](https://user-images.githubusercontent.com/14305431/67180222-87b34080-f40b-11e9-930a-b0cd7241aba1.png)

  fluwx: ^1.1.0
packges get后,  iOS pod install 出现:
![image](https://user-images.githubusercontent.com/14305431/67180280-b6311b80-f40b-11e9-9218-f37b716b64fd.png)

**Comment by JarvanMo** [comment]
Maybe you should clean up  your cache.

**Comment by pheromone** [comment]
@JarvanMo  不行.我删除了lockfile不行.Xcode clean也不行

**Comment by JarvanMo** [comment]
Run `flutter clean`. Fluwx works well. It's your personal problem.

**Comment by JarvanMo** [comment]
Or you can specify your iOS platform target at least 9.0 or above.

**Comment by pheromone** [comment]
解决了.可能是我修改版本导致的.把旧版本缓存删除重新导入就好了

**Comment by qq857556266** [comment]
s.ios.deployment_target = '9.0'
