### ISSUE TITLE
iOS分享tumbnail>120K小程序失败

### ISSUE THREAD

**Issue by huntrist** [OpenFlutter/fluwx#136]
**Describe the bug**
iOS share miniapp with thumbnail size > 120k will fail (with no exception or error, just not doing anything)
should auto compress like described in doc, or throw exception?
iOS 分享tumbnail > 120k的小程序时失败（没有反应，无报错）
是否应该根据文档进行自动压缩？或报错？

**To Reproduce**
share a miniapp with thumbnail > 120k

**Expected behavior**

**Flutter Version:**
```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)
    • Flutter version 1.9.1+hotfix.5 at D:\Env\flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Env\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Env\Android\SDK
    • Java binary at: D:\Executable\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Executable\Android\AndroidStudio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Testing Platform:**
iOS?

**Additional context**
N/A

**Comment by JarvanMo** [comment]
As the official WeChat documentation says, the thumbnail image of mini-program must be smaller than 120k. That's the limit. Read the official documentation carefully and you'll get more. By the way, I'm not 
quiet sure the difference between `hdImage` and `thumbnailImage`.

**Comment by huntrist** [comment]
Thanks for the resposne.
I understand the 120K official limit, but as the Fluwx readme.md states: 
```
Fluwx will compress images before sharing if thumbnail is larger than that. But the result of compression is unpredictable.
```
so thumbnail>120K can be shared on Android, but NOT iOS (as I have experienced) is due to the compression being UNPREDICTABLE ? or the miniapp sharing on iOS does NOT actually compress the thumbnail, and we should implement image compression by ourselves?

Again, thank you for this excellent plugin.

**Comment by JarvanMo** [comment]
I'll have a check a later.  Before that, you'd better compress thumbnails on your own.  Maybe it's bug or something else. If you're familiar with iOS development, it would be very nice giving PR to fix this problem.

**Comment by JarvanMo** [comment]
@huntrist Hi, v2.0 is on the way, bug shall be fixed.
