### ISSUE TITLE
请问微信ios部分不是开源的吗？

### ISSUE THREAD

**Issue by hanabi1224** [OpenFlutter/fluwx#137]
我看到并没有使用官方的[WechatOpenSDK](https://cocoapods.org/pods/WechatOpenSDK) 而是用了一个闭源的.a文件，请问这是出于什么考虑呢？

**Comment by JarvanMo** [comment]
- 请注意，微信官方SDK自始至终都不是开源的。所以何来开源一说？
- 项目中使用的SDK都是从微信官网下载的。
- pod上的微信SDK并不总是最新的。
- 如果pod引入，一定要锁定版本号，因为任何时候微信SDK都可能是毁灭性的。
- 部分用户使用了其他SDK，我不确定pod引入能否方便用户修改静态库的依赖。

**Comment by hanabi1224** [comment]
明白啦  最后一点没看懂是什么意思  用户为什么要改静态库依赖？

**Comment by JarvanMo** [comment]
[Maybe this helps you](https://github.com/OpenFlutter/fluwx/issues/56).

**Comment by hanabi1224** [comment]
这个问题正是有库不引用官方的pod sdk非要自己打包导致的  解决办法也是魔改成一致的依赖  和fluwx是不是引用pod没关系啊  引用pod魔改的时候把dependency改成sharesdk那个就好了 也不用删文件了  而且 sharesdk那个本身打包的就不能直接用 文档说 还必须要魔改podspec加上appid   那就应该都去改它   这个库没必要迁就另一个胡乱打包的库自己也乱打包吧

**Comment by JarvanMo** [comment]
**pod上的微信SDK并不总是最新的。**

**Comment by JarvanMo** [comment]
为什么 一定要用pod？

**Comment by JarvanMo** [comment]
Flutter官方在哪说的？

**Comment by JarvanMo** [comment]
pod就安全？如果我换我自己的pod源不一样？

**Comment by hanabi1224** [comment]
https://github.com/flutter/flutter/issues/33227

**Comment by hanabi1224** [comment]
人家有个官方的pod为啥非要别出心裁自己打个包？微信难道都是拖延几个月才上传pod么  除此以外没有任何好处啊

**Comment by hanabi1224** [comment]
上面你给的例子正好也说明了  任何两个库把微信自己打包了就会冲突  然后就必须魔改  都用一样的包管理就没问题

**Comment by JarvanMo** [comment]
自己打包的不是很多？你去看看1.8.5的版本，9.18号微信才上传到pod，实际上1.8.5早就有了，而且pod上的1.8.6比官网的晚好几天，我都升级完好几天了才有的pod，而且官网的是1.8.6.1。你要是担心安全问题，完全可以去校验md5。

**Comment by hanabi1224** [comment]
你这个想法做自己的app没问题啊 做一个库的话完全无法苟同

**Comment by JarvanMo** [comment]
还是那句话，需要保持最新最快的微信SDK。因为1.8.6出来以前就有人反应被拒审的情况。什么时候官方 的pod稳定了，什么时候才再考虑使用pod。

**Comment by hanabi1224** [comment]
苹果市场又不是腾讯审核 为啥用pod上最新的sdk会拒审？

**Comment by JarvanMo** [comment]
不是因为用pod最新SDK会被拒，而是因为1.8.6之前SDK使用的是uiwebview。


 
---原始邮件---
发件人: "hanabi1224"<notifications@github.com&gt;
发送时间: 2019年10月24日 15:01:24
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"JarvanMo"<468122151@qq.com&gt;;
主题: Re: [OpenFlutter/fluwx] 请问微信ios部分不是开源的吗？ (#137)



苹果市场又不是腾讯审核 为啥用pod上最新的sdk会拒审？

**Comment by hanabi1224** [comment]
这种几年难遇的问题如果要特殊解决可以发行一个临时的beta版本  不应该在主分支和主版本乱打包啊

**Comment by unclexiao** [comment]
@JarvanMo 同意使用.a静态文件而非pod动态拉取。不过最近有个问题，就是发包的时候会收到邮件警告：

> We identified one or more issues with a recent delivery for your app,  Your delivery was successful, but you may wish to correct the following issues in your next delivery:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

查了以下确实是`libWeChatSDK.a`引起的，[微信开放平台](https://developers.weixin.qq.com/doc/oplatform/Downloads/iOS_Resource.html)最新的**1.8.6.1**同样有这个问题，大厂官方库为不可控因素，是否可以直接无视呢？

**Comment by JarvanMo** [comment]
@unclexiao 但是官方更新日志确实有说过已经使用WKWebview替代Uiwebview了，我们依赖别人的SDK，受限于人，所以只能干着急。但是更新到最新版的fluwx，我再没收到因为uiwebview被拒的反馈了。

**Comment by unclexiao** [comment]
是的感谢🙏，更新到最新版之后`UIWebView`的问题修复了

**Comment by JarvanMo** [comment]
刚更新的支付宝，支付宝的官方源已经和下载中心的包差了至少三个版本。

**Comment by JarvanMo** [comment]
补充：使用pod后带来更多的问题是，好多flutter开发者不会升级，更新pod

**Comment by JarvanMo** [comment]
> 人家有个官方的pod为啥非要别出心裁自己打个包？微信难道都是拖延几个月才上传pod么 除此以外没有任何好处啊

现在又面临微信不更pod的情况，而且是重大版本更新。请问您可以联系一下微信官方吗？

**Comment by JarvanMo** [comment]
@hanabi1224 兄弟，帮想想办法啊

**Comment by JarvanMo** [comment]
@hanabi1224 有方案吗

**Comment by JarvanMo** [comment]
@OHeroJ hello 老板，你有微信SDK得pod么。我还是得用pod的方式，要不然有点问题

**Comment by OHeroJ** [comment]
> @OHeroJ hello 老板，你有微信SDK得pod么。我还是得用pod的方式，要不然有点问题

写了个，[https://github.com/swiftdo/WechatOpenSDK_Fuck](https://github.com/swiftdo/WechatOpenSDK_Fuck)

pod search  WechatOpenSDK_Fuck
