### ISSUE TITLE
android支付成功后，点击返回商家会闪屏一个页面后才会返回

### ISSUE THREAD

**Issue by mutu123** [OpenFlutter/fluwx#146]
这里我是应该是我项目中修改android的配置，还是在你的plugin修改啊

网上查找：问题在微信支付回调里做了通知跳转自定义支付结果页面然后出现支付成功后，点击返回商家闪烁才会显示支付结果页面，之间可能经历了几个activity

<activity
    android:name=".wxapi.WXPayEntryActivity"
    android:exported="true"
    android:launchMode="singleInstance"
    android:screenOrientation="portrait"
    android:theme="@style/TranslucentTheme"/>
把launchMode修改了后，成功了
————————————————
版权声明：本文为CSDN博主「king_wz」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/wangzhen19891010/article/details/80366653

**Comment by JarvanMo** [comment]
both OK

**Comment by mutu123** [comment]
我安卓的项目不能这样改吧，改了编译不过的，我的android目录中是找不到对应的activity的，要加入微信的SDK吧；我看你的插件源码是里面AndroidManifes.xml是有注释掉项目的配置的，是用来干什么的呢？谢谢

**Comment by JarvanMo** [comment]
Fluwx allows users to define their own `WXEntryActivity`. Just have a try. It's Android knowledge. If you're not familiar with Android development, just change fluwx.

**Comment by JarvanMo** [comment]
The code in `AndroidManifest.xml` which under example folder is a way re-define your `WXEntryActivity`.

**Comment by mutu123** [comment]
thanks
