### ISSUE TITLE
最新版本iOS微信registerWxApi 返回result为false

### ISSUE THREAD

**Issue by ly918** [OpenFlutter/fluwx#151]
appid 和 universalLink 都设置了

**Comment by zhaowenjian** [comment]
我的也是registerWxApi 返回result为false， 但是  isWechatInstalled 返回的是true，  sendAuth 之后 监听不到返回值，，  和 registerWxApi 返回result为false 有关么，，

**Comment by JarvanMo** [comment]
registerWxApi返回false就说明初始化失败了，isWechatInstalled是检查微信是否安装了。

**Comment by JarvanMo** [comment]
registerWxApi返回false一定是配置有问题，要么是错的，要么是漏配，没有别的原因。

**Comment by JarvanMo** [comment]
#149

**Comment by JarvanMo** [comment]
#124

**Comment by zhaowenjian** [comment]
备忘录已经universalLink可以正常跳转可， 微信开发者universalLink 也配置了，isWechatInstalled也返回的true， sendAuth 就是拉不起微信， 还有哪些需要配置的么？

**Comment by JarvanMo** [comment]
能不能仔细看看给你的链接

**Comment by zhaowenjian** [comment]
和我的不一样呀  视频也买了的  视频只讲了 ios develop 配置 universallink ， 没有真机跑通这个流程的示例 ， 就不知道我这哪出问题了呀，，

**Comment by JarvanMo** [comment]
weixinULAPI你配置了吗？

**Comment by JarvanMo** [comment]
反复强调看别的issue就是不仔细看

**Comment by zhaowenjian** [comment]
> weixinULAPI你配置了吗？

呃呃呃   我记得配了这个的 结果配的是 weixin ，，  不好意思啊  感谢感谢！！

**Comment by xhp281** [comment]
注意：LSApplicationQueriesSchemes中 添加weixin 和 weixinULAPI  
观看这个文档：https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html
