### ISSUE TITLE
你好，微信分享能支持下普通文件分享么？

### ISSUE THREAD

**Issue by jabezGit** [OpenFlutter/fluwx#152]

**Comment by JarvanMo** [comment]
暂时没有计划。看看有没有志愿者愿意做这个。

**Comment by unclexiao** [comment]
> 微信分享及收藏目前支持文字、图片、音乐、视频、网页、小程序共六种类型（海外应用支持网页、小程序类型分享）。

[官方文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Share_and_Favorites/iOS.html)目前不支持文件分享，但你可以通过网页的形式承载文件。当然，问题又来了，微信浏览器里无法下载文件。

所以就需要从系统层面想办法了，指定文件调用系统的文件分享，让用户自己选择微信。于是就有很多社区方案拉，包括但不限于：
- [share_extend](https://pub.dev/packages/share_extend)
- [esys_flutter_share](https://pub.dev/packages/esys_flutter_share)
- [flutter_share_file](https://pub.dev/packages/flutter_share_file)
