### ISSUE TITLE
更新flutter之后，每个fluwx方法都出现了NoSuchMethodError

### ISSUE THREAD

**Issue by OIngSaaa** [OpenFlutter/fluwx#153]
场景发生：flutter upgrade之后，重新run

每个功能块都是出现这个异常
以下是异常信息
Unhandled Exception: NoSuchMethodError: The method 'invokeMethod' was called on null.
E/flutter ( 4571): Receiver: null
E/flutter ( 4571): Tried calling: invokeMethod<dynamic>("isWeChatInstalled")
E/flutter ( 4571): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4571): #1      isWeChatInstalled (package:fluwx/src/fluwx_iml.dart:412:25)

**Comment by unclexiao** [comment]
更新插件版本之后，dart文件仍在，但是Android和iOS工程可能会有缓存，所以你需要清除并重新构建：
```bash
flutter clean 
```

然后再执行run/build的时候，会自动拉取最新的gradle/pod依赖，应该就正常啦～

**Comment by OIngSaaa** [comment]
> 更新插件版本之后，dart文件仍在，但是Android和iOS工程可能会有缓存，所以你需要清除并重新构建：
> 
> ```shell
> flutter clean 
> ```
> 
> 然后再执行run/build的时候，会自动拉取最新的gradle/pod依赖，应该就正常啦～

明白了，我尝试一下，感谢您
