### ISSUE TITLE
华为mate30 pro无法跳转微信

### ISSUE THREAD

**Issue by rockingdice** [OpenFlutter/fluwx#154]
**Describe the bug**
有若干华为mate 30 pro的用户反馈无法登录/微信支付，原因是无法跳转至微信。

**To Reproduce**
尝试登录或者微信支付

**Expected behavior**
应该和其他安卓手机一样可以登录或者微信支付

**Flutter Version:**
[✓] Flutter (Channel master, v1.10.17-pre.50, on Mac OS X 10.15 19A602, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
[✓] Connected device (1 available)

**Testing Platform:**
Android

**Additional context**
无

**Comment by JarvanMo** [comment]
首先，fluwx不基于master。其次，这应该是微信SDK的问题或者flutter的问题。和fluwx关系不大。

**Comment by rockingdice** [comment]
我也怀疑是微信sdk对新出的mate30不太兼容。fluwx是使用最新版的微信sdk了吗？
flutter只限于引擎层和界面交互，我认为使用什么分支关系不会太大，当然你说你没在master上测试过所以无法判断是否是master引起的问题，这个好办，我出个stable的包测试一下就知道了，如果也有问题那么就不是分支的影响了。

**Comment by rockingdice** [comment]
最终发现问题了，是mate 30用的EMUI10的问题。
EMUI10会禁用第三方app的微信登录，开启微信和app的关联启动后才能正常登录。

**Comment by lizhaolin09** [comment]
> 最终发现问题了，是mate 30用的EMUI10的问题。
> EMUI10会禁用第三方app的微信登录，开启微信和app的关联启动后才能正常登录。

你好，我也遇到类似的问题了，「开启微信和app的关联启动」具体是怎么操作呢？

**Comment by gaoshanyu** [comment]
同样遇到了华为调不起微信支付的问题，关了微信分身，应用和微信的关联启动也勾上了，还是调不起。
请问有解决办法吗？

**Comment by gaoshanyu** [comment]
关联启动设置我是在：手机管家->应用启动管理->右上角->批量手动管理

**Comment by gaoshanyu** [comment]
又测试了更多的机型，发现不是华为机型的问题，是 Android 11 无法拉起微信。
看了很多文档，还未找到解决方案

**Comment by JarvanMo** [comment]
咨询微信官方------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;raniys.liao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月10日(星期四) 下午3:42
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 华为mate30 pro无法跳转微信 (#154)

**Comment by gaoshanyu** [comment]
找到问题了，微信开放后台配置问题，已修复

**Comment by jimmonster** [comment]
> 

大佬能说说具体是怎么解决的吗？

**Comment by jimmonster** [comment]
> 

大佬能说具体是怎么解决的吗？
