### ISSUE TITLE
flutter微信分享网页分享 , 网页分享功能传递 , 简介描述字段是那个?

### ISSUE THREAD

**Issue by luyi-word** [OpenFlutter/fluwx#155]
Future share() {
    var model = fluwx.WeChatShareWebPageModel(
        webPage: data['webPage'],
        title: data['title'],
        thumbnail: data['thumbnail'],
        scene:scene,
        transaction: data['transaction']);
        fluwx.share(model);
  }

**Comment by JarvanMo** [comment]
The fields name are the same as the official SDK. Please check the official documents.

**Comment by pheromone** [comment]
@luyi-word  这个问题你弄好了么?描述字段是不是不行
