### ISSUE TITLE
请问下仿造您插件封装的插件，编译时提示链接找不到xxx.a 是少修改了哪儿呢

### ISSUE THREAD

**Issue by bhui** [OpenFlutter/fluwx#156]
我的修改点如下：
1.在plugin下面放入a库文件
2.在podspec下加入s.vendored_libraries = "**/*.a"
3.Runner的other link flag加入-l"xxx.a"
编译时提示link 找不到xxx.a

请问还有其他地方需要修改吗，我可以检查哪些地方以定位问题呢，谢谢！

**Comment by JarvanMo** [comment]
s.preserve_paths = 'Lib/*.a'
  s.vendored_libraries = "**/*.a"

**Comment by bhui** [comment]
谢谢您的回复~
不过preserve_paths 加了 还是报一样的错误呢 。之前没加是因为我看本地没有Lib目录就没有加preserve_paths。

我的podspec是这样的
```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'fmod'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h', 'Classes/**/*.hpp'
  s.static_framework = true
  s.dependency 'Flutter'

  s.preserve_paths = 'Lib/.a'
  #s.vendored_libraries = 'Classes/ThridParty/OpenSource/FMOD/lib/*.a'
  s.vendored_libraries = "**/*.a"

  s.ios.deployment_target = '8.0'
end


```

我的flutter插件文件目录是这样的：
![image](https://user-images.githubusercontent.com/6930591/68913016-e82c6800-0794-11ea-98b8-34cbfb77f2a6.png)

请问下这样的目录有啥问题

**Comment by JarvanMo** [comment]
s.preserve_paths = 'Lib/.a'
你的.a哪在lib下？

**Comment by JarvanMo** [comment]
学习要认真点，看看为什么要这么写，而不是一味地cv

**Comment by bhui** [comment]
不好意思 我是flutter新手。小白问题见笑了o(╥﹏╥)o
我的.a和您是一样的层级，放在ios的Classes下面，我理解错了吗
您的：
![image](https://user-images.githubusercontent.com/6930591/68913301-c97aa100-0795-11ea-93b1-d39034acacd8.png)
我的：
![image](https://user-images.githubusercontent.com/6930591/68913342-e7480600-0795-11ea-8fad-264b6be17585.png)

**Comment by JarvanMo** [comment]
自己创建一个lib，我也不是ios开发者。不再回复。

**Comment by bhui** [comment]
好的 我再自己找找原因，谢谢啦~

**Comment by JarvanMo** [comment]
你可以加我们的QQ群交流。
