### ISSUE TITLE
如果未安装微信,是否会跳转网页微信登录方式呀? 还是说只能够隐藏?

### ISSUE THREAD

**Issue by pheromone** [OpenFlutter/fluwx#157]
使用 isWeChatInstalled 返回是否安装了微信.
如果未安装微信,是否会跳转网页微信登录方式呀? 还是说只能够隐藏?

**Comment by JarvanMo** [comment]
Fluwx不关心业务上的事情。


 
---原始邮件---
发件人: "少停"<notifications@github.com&gt;
发送时间: 2019年11月21日 13:27:16
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [OpenFlutter/fluwx] 如果未安装微信,是否会跳转网页微信登录方式呀? 还是说只能够隐藏? (#157)



使用 isWeChatInstalled 返回是否安装了微信.
 如果未安装微信,是否会跳转网页微信登录方式呀? 还是说只能够隐藏?

**Comment by unclexiao** [comment]
隐藏吧，网页版微信也需要扫码（还不能长按识别），流程非常长，目前来说从见过这种做法。

另外，你跳转到微信官网引导下载，是违反苹果规定的，也无法通过审核。

**Comment by pheromone** [comment]
恩恩.隐藏了.谢谢了 @unclexiao

**Comment by JarvanMo** [comment]
@unclexiao Hi,我发你的邮件收到了吗

**Comment by unclexiao** [comment]
@JarvanMo 很尴尬，在垃圾箱里找出来了，现已回复！
