### ISSUE TITLE
请问下为什么微信分享这个我已经配置好这个通用链接后

### ISSUE THREAD

**Issue by luyi-word** [OpenFlutter/fluwx#158]
![image](https://user-images.githubusercontent.com/54274687/69331535-e6c8d700-0c8f-11ea-80d8-176b72b51af2.png)
分享的时候还是出现这个异常 只有ios13以上的系统有问题

**Comment by unclexiao** [comment]
不仅仅是写在代码里就够的，需要与[微信开放平台](https://open.weixin.qq.com/)的配置保持一致，建议还写在iOS工程里，如：
```xml
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:your link</string>
	</array>
</dict>
```

如已加配置，请**clean**后重新**build**

**Comment by luyi-word** [comment]
不好使呀 我用官网验证还没有通过那

**Comment by JarvanMo** [comment]
不好用肯定就是你错配或漏配。

**Comment by luyi-word** [comment]
已经解决

**Comment by wc6221217** [comment]
> 已经解决

哈喽~请问怎么解决的？我也遇到这个问题了>_<
