### ISSUE TITLE
sendAuth  在授权登录的时候如果用户点击了取消.fluwx有没有回调方法?

### ISSUE THREAD

**Issue by pheromone** [OpenFlutter/fluwx#160]
sendAuth  在授权登录的时候如果用户点击了取消.fluwx有没有回调方法?

**Comment by unclexiao** [comment]
当然有的，不管是确定还是取消，只要从微信返回到APP，都会被监听器捕获：
```dart
fluwx.responseFromAuth.listen((dynamic data) {
      final int errCode = data.errCode;
      if (errCode != 0) {
        // 授权失败
      }
});
```

其中`errCode`也是微信返回的，常见的场景如下：
- 用户同意：0
- 用户拒绝授权：-4
- 用户取消授权：-2

只有为0才有`code`字段，用来换取`access_token`，更多的情形请查阅[微信开放平台](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_Login/Development_Guide.html)官方文档

**Comment by pheromone** [comment]
恩.谢谢.

**Comment by pheromone** [comment]
@unclexiao 
你好,取消授权并不会回调任何信息,只有同意授权才会返回0.
![image](https://user-images.githubusercontent.com/14305431/69505427-df8e1b80-0f64-11ea-8a4c-ef7871e229c4.png)

  fluwx: ^1.1.1+1

**Comment by unclexiao** [comment]
@pheromone 我重新测试了一遍，本地环境如下：
```bash
~ flutter doctor --version       
Flutter 1.9.1+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aedbb1835 (5 weeks ago) • 2019-10-17 08:37:27 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

插件版本为：**fluwx: 1.1.3**

取消授权后，是正常返回了-2的，首先确保`fluwx.sendWeChatAuth`在`fluwx.responseFromAuth.listen`之后执行，如果仍旧没有捕获，请提供**最小可复现仓库**。

**Comment by pheromone** [comment]
恩.谢谢. fluwx: 1.1.3 是可以的.

**Comment by pheromone** [comment]
恩.谢谢. fluwx: 1.1.3 是可以的.
