### ISSUE TITLE
1.1.3 sendWeChatAuth 登录验证有个问题想请教下

### ISSUE THREAD

**Issue by BadReese** [OpenFlutter/fluwx#161]
Future sendWeChatAuth({String openId, @required String scope, String state})

第一个参数是openId，请问这个openId哪里来呢？用户还没授权没有OPENID呀，麻烦指点一二，谢谢

**Comment by unclexiao** [comment]
只是个可选项，你可以无视它。

因为[Demo](https://github.com/OpenFlutter/fluwx/blob/master/doc/SEND_AUTH_CN.md)和[官网](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317851&token=)都没到这个参数，我猜只是个遗留的瑕疵，建议作者大佬后期找时间优化～

**Comment by BadReese** [comment]
@unclexiao 是吗？我还以为是必须的，因为用1.0.5版本的时候登录正常，但是换了这个版本即使我传空值也无法唤起微信了，很怪

**Comment by BadReese** [comment]
换回去登录又正常了 - -

**Comment by JarvanMo** [comment]
你

**Comment by BadReese** [comment]
@JarvanMo 抱歉，我从changelog里没有看出什么..

**Comment by JarvanMo** [comment]
下次问问题麻烦说一下你的环境。

**Comment by JarvanMo** [comment]
好好看年1.0.5以更新了什么，看看新的readme和以前有什么不一样。

**Comment by BadReese** [comment]
> 好好看1.0.5以后更新了什么，看看新的readme和以前有什么不一样。

恩 感谢大佬指点

不过这不是我第一次接入微信的sdk，但flutter倒是第一次。看了下大佬的中文readme很多都没更新，毕竟开源不易可以理解。这边贴下我的解决方案：

在iOS的target里info.plist，LSApplicationQueriesSchemes还要额外加入weixinULAPI才能正常注册接口，参考：https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html#jump
![image](https://user-images.githubusercontent.com/18170860/69838961-a02b3c00-1290-11ea-9caf-dd48bbebd3b4.png)

**Comment by unclexiao** [comment]
项目根目录的双语[README](https://github.com/OpenFlutter/fluwx/blob/master/README.md)不是加了注意事项么 @BadReese 你确定认真阅读过？

> 注意：尽管可以通过Fluwx完成微信注册，但一些操作依然需要在对应平台进行设置，如配置iOS的URLSchema,LSApplicationQueriesSchemes,universal link等。

> NOTE：Although we can register WXApi via Fluwx,but there's still some work you have to do on the particular platform.For example, add  *URLSchema, LSApplicationQueriesSchemes or universal link* for iOS. 

何况，这也是移动端的基础知识，跟此插件无关。如果你要跳转到支付宝、新浪微博之类的其它应用，同样要增加配置的，比如：
```xml
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>itms</string>
		<string>wechat</string>
		<string>weixin</string>
		<string>alipay</string>
		<string>sinaweibo</string>
		<string>alipayshare</string>
	</array>
```

顺便说一下，原生平台的规则还多着呢，比如推送、权限、支付，都有很多工作要做。

**最后，跨端框架不是银弹，别妄想一劳永逸。**
