### ISSUE TITLE
无法分享到微信

### ISSUE THREAD

**Issue by hqwlkj** [OpenFlutter/fluwx#163]
![image](https://user-images.githubusercontent.com/12181423/69895957-2a989c00-1374-11ea-98b8-48c059cce29e.png)

```

var path = 'https://ss0.bdstatic.com/6Ox1bjeh1BF3odCf/it/u=3166117822,2917161594&fm=74&app=80&f=PNG&size=f121,121?sec=1880279984&t=b65b3db42c7b64c034fe1ecfcdd19a1c';
    fluwx.share(fluwx.WeChatShareImageModel(
        image: path,
        thumbnail: path,
        transaction: path,
        scene: fluwx.WeChatScene.TIMELINE,
        description: "image"));

```

**Comment by JarvanMo** [comment]
可能是图片有问题。



值得信赖的莫先生~

&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yanghc"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月30日(星期六) 中午1:21
收件人:&nbsp;"OpenFlutter/fluwx"<fluwx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 无法分享到微信 (#163)





  var path = 'https://ss0.bdstatic.com/6Ox1bjeh1BF3odCf/it/u=3166117822,2917161594&amp;fm=74&amp;app=80&amp;f=PNG&amp;size=f121,121?sec=1880279984&amp;t=b65b3db42c7b64c034fe1ecfcdd19a1c';     fluwx.share(fluwx.WeChatShareImageModel(         image: path,         thumbnail: path,         transaction: path,         scene: fluwx.WeChatScene.TIMELINE,         description: "image"));

**Comment by hqwlkj** [comment]
图片路径必须是配置：`universalLink`链接访问的到的图片吗？
