### ISSUE TITLE
华为手机支付 -1

### ISSUE THREAD

**Issue by wangyangIMP** [OpenFlutter/fluwx#164]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Flutter Version:**
Run `flutter doctor` in terminal or powershell , and copy the outputs.

**Testing Platform:**
Android or iOS?

**Additional context**

**Comment by wangyangIMP** [comment]
华为手机微信支付,返回-1,无法打开微信 ?是为什么?

**Comment by JarvanMo** [comment]
提问请按模板提问
