### ISSUE TITLE
分享网址缩略图不显示

### ISSUE THREAD

**Issue by pan365wang** [OpenFlutter/fluwx#165]
var model = fluwx.WeChatShareWebPageModel(
        webPage: "htts://www.baidu.com",
        title: "测试",
        description:“测试”,
        thumbnail: "http://img.qudiaoyu.net/bbs/1/2019/10/19/b1db3f0e42b648d79c6da72fee511841/200x160.jpg",
        scene: type==ShareWeChatScene.SESSION,
        transaction: "http://img.qudiaoyu.net/bbs/1/2019/10/19/b1db3f0e42b648d79c6da72fee511841/200x160.jpg"
    );
    return await fluwx.shareToWeChat(model);

可以分享，标题内容都正确，单缩略显示一个默认别针的图标。提交的缩略图，不显示

**Comment by pan365wang** [comment]
@tenfar @efortuna @imknown @unclexiao

**Comment by wanglu1209** [comment]
我也遇到了这个问题，是怎么解决的？
