### ISSUE TITLE
iOS真机无法拉起微信 也没有报错信息

### ISSUE THREAD

**Issue by tongyangsheng** [OpenFlutter/fluwx#167]
![C2A7A5DC-B959-487F-BD0D-911881B6B2B6](https://user-images.githubusercontent.com/32046282/70585820-621f0800-1c00-11ea-9c86-253d7b3692e7.png)
![1EC25238C812DF75EAA39A8859F5BB91](https://user-images.githubusercontent.com/32046282/70585827-664b2580-1c00-11ea-81ac-bd99812bde00.JPG)
支付这个地方没有给返回值，也没有监听到返回值，在iOS真机上也没有拉起微信。初始化fluwx用的申请下来的appid 支付动态传的是商户appid  望解答 万分感谢🙏

**Comment by tongyangsheng** [comment]
info.plist 没配weixinULAPI

**Comment by theecn** [comment]
ios版本13.1.2 真机 ，无法唤起微信支付，infoPlist 已设置
![image](https://user-images.githubusercontent.com/22100544/71947764-d4d3d100-3208-11ea-995c-9e2b3a685cac.png)
univerlink 也已设置
![image](https://user-images.githubusercontent.com/22100544/71947854-1cf2f380-3209-11ea-9046-06403db42aa6.png)

**Comment by JarvanMo** [comment]
register的时候返回true就说明配置还是有问题，其他的就是支付参数有问题。

**Comment by theecn** [comment]
安卓都能正常支付的情况下，是不是说明支付参数没问题

**Comment by theecn** [comment]
![image](https://user-images.githubusercontent.com/22100544/71960386-dc5aa080-322f-11ea-8f61-8c44678ccbb7.png)
![image](https://user-images.githubusercontent.com/22100544/71960399-e41a4500-322f-11ea-9608-de399377482f.png)
注册也是没问题的

**Comment by chjsun** [comment]
怎么解决的？
