### ISSUE TITLE
大佬，来活了，微信sdk强制要求更新！！！！

### ISSUE THREAD

**Issue by dmlzj** [OpenFlutter/fluwx#168]
如题，不更新明年3月份就不让用了！
微信官方网址：[https://developers.weixin.qq.com/community/develop/doc/00062412e00e4878f8290f35457801](url)

**Comment by JarvanMo** [comment]
一万年前的事了，麻烦你看看release log

**Comment by dmlzj** [comment]
sorry，刚看到，要删除呢，你就关闭了，😝！
