### ISSUE TITLE
thumbData 支持传入二进制数据

### ISSUE THREAD

**Issue by guanggenzhang** [OpenFlutter/fluwx#169]
目前thumbData只支持本地(SCHEMA_ASSETS/SCHEMA_FILE/SCHEMA_CONTENT)以及远程文件（HTTP/HTTPS）的形式，然后由plugin加载文件转化为二进制数据，不支持直接传入二进制数据，希望能够提供plugin api thumbData 直接传入二进制数据。

可提供pull request。

**Comment by JarvanMo** [comment]
欢迎PR.

**Comment by JarvanMo** [comment]
Fixed in 2.0.
