### ISSUE TITLE
如何分享一个unit8list格式的图片啊?

### ISSUE THREAD

**Issue by pheromone** [OpenFlutter/fluwx#170]
如图所示:如何分享一个unit8list格式的图片啊?
![image](https://user-images.githubusercontent.com/14305431/70901662-2dfb7b00-2036-11ea-8df3-ddaa79a63b78.png)

**Comment by zhujinsheng** [comment]
你把unit8list图片数据保存到本地，再根据本地路径进行获取

**Comment by mafanwei** [comment]
新版已经支持
