### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zhuxiujia** [OpenFlutter/fluwx#173]
Execution failed for task ':fluwx:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\mayn\.gradle\caches\transforms-2\files-2.1\dcd76181e04892ba3a5e36f17fe1bbff\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\mayn\.gradle\caches\transforms-2\files-2.1\dcd76181e04892ba3a5e36f17fe1bbff\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JarvanMo** [comment]
Make sure your project's `compileSdkVersion` is the same as [fluwx](https://github.com/OpenFlutter/fluwx/blob/master/android/build.gradle#L28).

**Comment by zhuxiujia** [comment]
> compileSdkVersion

some library needs height version,  so   my  project  compileSdkVersion is  `compileSdkVersion 29`

**Comment by JarvanMo** [comment]
You can fork this project and change `compileSdkVersion` to 29 for quick fix. Once it works, you can create a PR, or I'll do it when I have time.

**Comment by JarvanMo** [comment]
Was it fixed?
