### ISSUE TITLE
第一次点跳转正常，然后第二次会报PlatformException(wxapi not configured, WxApi Not Registered, null)问题

### ISSUE THREAD

**Issue by pleasecallmelm** [OpenFlutter/fluwx#177]
iOS平台，运行时第一次跑能正常跳转，然后点了取消或者支付成功后回到App。再点就会报这个问题。。。有点懵，求指点

**Comment by JarvanMo** [comment]
没遇到过，你的universal link，还有URL schema, weixinulapi之类的都正确吗

**Comment by pleasecallmelm** [comment]
> 没遇到过，你的universal link，还有URL schema, weixinulapi之类的都正确吗

检查过好多次了。而且如果不对的话第一次也不会成功吧。。。第一次都能跳过去并且支付成功。

**Comment by JarvanMo** [comment]
这是支付之前的判断，显然`isWeChatRegistered`这个值被修改过了。
```
    if (!isWeChatRegistered) {
        result([FlutterError errorWithCode:resultErrorNeedWeChat message:resultMessageNeedWeChat details:nil]);
        return;
    }
```

**Comment by JarvanMo** [comment]
我现在怀疑， 是不是换了不同的appId然后registerWxApi

**Comment by pleasecallmelm** [comment]
> 我现在怀疑，是不是换了不同的appId然后registerWxApi

不好意思，我沙雕了。。。app同名了，跳回的不是那个app了。但是还是有输出。。。flutter还能这样吗，感谢你这句”是不是换了不同的appId然后registerWxApi“指了方向
