### ISSUE TITLE
IOS13 无法分享，支付没有回调信息

### ISSUE THREAD

**Issue by EchoPuda** [OpenFlutter/fluwx#182]
跳转到微信后显示数秒的“正在连接”，然后就自动跳回了应用。没有明显的错误信息。
只有一条信息
PBItemCollectionServicer connection disconnected.

支付完成后返回应用，没有回调（android是有的），订单也支付成功了

**Comment by pheromone** [comment]
@EchoPuda  你怎么处理的?
