### ISSUE TITLE
Android 分享本机图片应用闪退了

### ISSUE THREAD

**Issue by hqwlkj** [OpenFlutter/fluwx#183]
**my code**
  ```
_initFluwx() async {
    await fluwx.registerWxApi(
        appId: "wxcc1ab7228b19261b",
        doOnAndroid: true,
        doOnIOS: true,
        universalLink: "https://help.wechat.com/beeapp/");
    var result = await fluwx.isWeChatInstalled();
    print("is installed $result");

    /// 初始化 fluwx 分享组件
    fluwx.responseFromShare.listen((data) {
      LogUtil.e(data.errCode.toString(), tag: '微信分享：');
    });
  }


  /// 分享我的二维码
  /// 更多分享看见 https://github.com/OpenFlutter/fluwx/blob/master/doc/SHARE.md
  void _shareMyQRCode(BuildContext context) async {
    if (_shareImagesPath == null) {
      await _capturePng();
    }
    LogUtil.e(_shareImagesPath, tag: '_shareImagesPath');
    String _thumbnail = "assets://images/icon_logo.png";
    await fluwx.shareToWeChat(fluwx.WeChatShareImageModel(
        image: _shareImagesPath,
        thumbnail: _thumbnail,
        transaction: _shareImagesPath,
        scene: fluwx.WeChatScene.TIMELINE,
        description: "这是我的营销二维码，请使用微信扫一扫可以开始询价哦！"));
  }
```

本地图片地址：file:///storage/emulated/0/%E8%9C%9C%E8%9C%82%E8%BD%A6%E7%AE%A1%E5%AE%B6/1578884796397.png

Lost connection to device.

**Flutter Version:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!

**Testing Platform:**
Android or iOS?    Android

顺便问问 关于ios 的 `universalLink` 配置有没有相关的中文文档。

**Comment by JarvanMo** [comment]
1.没有日志。
2.universalLink可以看项目的视频，或者百度和微信官方文档。

**Comment by hqwlkj** [comment]
就是没有其他的错误日志， 程序就直接闪退了。

> 2.universalLink可以看项目的视频

这个视频有链接吗？

**Comment by JarvanMo** [comment]
[video](https://study.163.com/course/introduction.htm?share=2&shareId=480000001896427&courseId=1209174838&_trace_c_p_k2_=e72467dc0df540579287a8ea996344a4)

麻烦仔细看看文档

**Comment by hqwlkj** [comment]
看了视频，问题处理了。

**Comment by unclexiao** [comment]
@hqwlkj 默认的启动/调试只打印dart相关的日志，下次遇到这种原生代码导致的闪退，可以开启详细日志，如：
```bash
flutter run -v # 详细日志
adb logcat 你的包名:I *S  # 真机调试
```

**Comment by hqwlkj** [comment]
@unclexiao   谢谢，我是原生小白，从后端转前端，感谢指到

**Comment by unclexiao** [comment]
@hqwlkj 哈哈没事，我也是小白，现在前端转到移动端，感谢一起建设生态～
