### ISSUE TITLE
分享图片无图片后缀问题

### ISSUE THREAD

**Issue by DizzyYang** [OpenFlutter/fluwx#184]
val suffix = when {
                        imagePath.isNullOrBlank() -> ".jpeg"
                        imagePath.lastIndexOf(".") == -1 -> ".jpeg"
                        else -> imagePath.substring(imagePath.lastIndexOf("."))
                    }

imagePath.substring(imagePath.lastIndexOf(".")) 

如果图片链接 = http://*****/index.php/*****/*****/
后台生成的图片

最好强制增加图片后缀

**Comment by JarvanMo** [comment]
这个问题我会在2.0的时候考虑。
