### ISSUE TITLE
图片分享：Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress

### ISSUE THREAD

**Issue by DizzyYang** [OpenFlutter/fluwx#185]
异常日志：

Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference

top.zibin.luban.Engine.compress(Engine.java:79)
top.zibin.luban.Luban.get(Luban.java:152)
top.zibin.luban.Luban.access$1100(Luban.java:21)
top.zibin.luban.Luban$Builder.get(Luban.java:354)
com.jarvan.fluwx.utils.WeChatThumbnailUtil.compress(WeChatThumbnailUtil.java:113)
com.jarvan.fluwx.utils.WeChatThumbnailUtil.thumbnailForCommon(WeChatThumbnailUtil.java:99)
com.jarvan.fluwx.handler.FluwxShareHandler$getThumbnailByteArrayCommon$2.invokeSuspend(FluwxShareHandler.kt:165)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by mafanwei** [comment]
please show your code

**Comment by JarvanMo** [comment]
图片的问题。

**Comment by kingofglory** [comment]
图片什么问题呢？

> 异常日志：
> 
> Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
> 
> top.zibin.luban.Engine.compress(Engine.java:79)
> top.zibin.luban.Luban.get(Luban.java:152)
> top.zibin.luban.Luban.access$1100(Luban.java:21)
> top.zibin.luban.Luban$Builder.get(Luban.java:354)
> com.jarvan.fluwx.utils.WeChatThumbnailUtil.compress(WeChatThumbnailUtil.java:113)
> com.jarvan.fluwx.utils.WeChatThumbnailUtil.thumbnailForCommon(WeChatThumbnailUtil.java:99)
> com.jarvan.fluwx.handler.FluwxShareHandler$getThumbnailByteArrayCommon$2.invokeSuspend(FluwxShareHandler.kt:165)
> kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
> kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
> kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
> kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

这个问题还有呢，请问怎么解决的？

**Comment by kingofglory** [comment]
> 图片的问题。

能问下具体是什么问题么？还有解决方案是？

**Comment by JarvanMo** [comment]
@kingofglory 可以更新到最新版试试
