### ISSUE TITLE
怎么删除fluwx的支付模块？

### ISSUE THREAD

**Issue by 5454267364** [OpenFlutter/fluwx#192]
我在项目引用了fluwx在腾讯WeTest的ios预审核出现错误，请问这个要怎么解决？
 ‘error	检查第三方支付SDK：不通过：检查出如下第三方支付SDK[partnerId, prepayId]。	建议: 开发核实支付方式是否合规后再提交审核	IPA问题’

**Comment by 5454267364** [comment]
有没有哪位大佬解答一下啊，现在要提交appstore审核，他们怀疑我们的app有隐藏功能

**Comment by JarvanMo** [comment]
你可以更新一下no_pay分支。
