### ISSUE TITLE
分享回调问题

### ISSUE THREAD

**Issue by CAM1113** [OpenFlutter/fluwx#193]
在initState中注册了监听的回调，但是分享结束后，代码没有进入回调的逻辑。
  @override
  void initState() {
    super.initState();
    print("initState");
    fluwx.responseFromShare.listen((fluwx.WeChatShareResponse value){
      print("responseFromShare:   ${value.errStr}");
      Navigator.pop(context);
    });
  }

**Comment by JarvanMo** [comment]
ios还是android啊

**Comment by CAM1113** [comment]
android
