### ISSUE TITLE
通过分享的小程序 拉起未启动的App，白屏，如果拉已启动的app没问题

### ISSUE THREAD

**Issue by hjc22** [OpenFlutter/fluwx#194]
通过分享的小程序 拉起未启动的App，白屏，如果拉已启动的app没问题

做了一下调试，发现拉起了微信的activity，执行了onCreate，然后报错了， 所以也没有回到MainActivity,所以就白屏了 

我在onCreate 里做了个判断 可以临时解决一下 ，但是没有通用的方案好处理

如果没有flutter activity，就主动跳到主main
val activity = FluwxRequestHandler.getRegistrar()?.activity()
        if(activity !is Activity) {
            val intent:Intent =  Intent();
            intent.setAction("com.zhou.money_topic.main");
            startActivity(intent);
            finish();
        }

**Comment by hjc22** [comment]
修改了下 可以做成通用的方案了

```
val activity = FluwxRequestHandler.getRegistrar()?.activity()
        if(activity == null) {
            val intent:Intent =  Intent();
            val packageName:String = this.getPackageName();
            intent.setClassName(packageName, packageName + ".MainActivity");
            startActivity(intent);
            finish();
        }
```

**Comment by JarvanMo** [comment]
> 修改了下 可以做成通用的方案了
> 
> ```
> val activity = FluwxRequestHandler.getRegistrar()?.activity()
>         if(activity == null) {
>             val intent:Intent =  Intent();
>             val packageName:String = this.getPackageName();
>             intent.setClassName(packageName, packageName + ".MainActivity");
>             startActivity(intent);
>             finish();
>         }
> ```

如果入口不是MainActivity呢。

**Comment by hjc22** [comment]
那还是不行  那如何在代码里获取到主Activity名称呢

**Comment by JarvanMo** [comment]
倒是可以通过隐式的方式启动。

**Comment by JarvanMo** [comment]
这个问题我稍后修复一下吧。

**Comment by JarvanMo** [comment]
这段代码放哪？

**Comment by hjc22** [comment]
android/src/main/kotlin/com/jarvan/fluwx/wxapi/FluwxWXEntryActivity.kt

![image](https://user-images.githubusercontent.com/17647420/76073680-f537c600-5fd4-11ea-8d50-90655b2fe93f.png)

**Comment by JarvanMo** [comment]
2.0马上发布。2.0的时候可以试试在Manifest里添加：
```
    <action android:name="${applicationId}.FlutterActivity"/>
```
[例子](https://github.com/OpenFlutter/fluwx/blob/master/example/android/app/src/main/AndroidManifest.xml#L21)，我不太确定这样是否可行。

**Comment by zhuxiangqing** [comment]
<action android:name="${applicationId}.FlutterActivity"/>
                <category android:name="android.intent.category.DEFAULT" />
                
                两个都添加到MainActivity下

**Comment by zhuxiangqing** [comment]
` <action android:name="${applicationId}.FlutterActivity"/>
                <category android:name="android.intent.category.DEFAULT" />`
                
                两个都要添加到MainActivity下

**Comment by lsmayday** [comment]
val activity = FluwxRequestHandler.getRegistrar()?.activity()

FluwxRequestHandler 并没有 getRegistrar 方法？

**Comment by JarvanMo** [comment]
这个问题在3.4.0修复了。具体请参看文档以及demo。
