### ISSUE TITLE
苹果授权登录  与  支付  都收不到回调了啊，紧急中

### ISSUE THREAD

**Issue by qiuguian** [OpenFlutter/fluwx#198]
苹果授权登录  与  支付  都收不到回调了啊，紧急中

**Comment by JarvanMo** [comment]
你从哪个版本升级过来的啊？登录有回调啊。

**Comment by qiuguian** [comment]
@JarvanMo  从pub上升级的最新包 2.0.1

**Comment by qiuguian** [comment]
之前是可以有回调的，今天跑发现没回调了，所以重新升级包，发现还是没收到回调

**Comment by JarvanMo** [comment]
之前是哪个版本？我这登录是有回调的。支付我没法测试。

**Comment by qiuguian** [comment]
忘记是哪个版本了  原来那个版本发现也不行了，才升级的，登录无回调，我发现监听回调的方法有重新调整，以为你们修复过了，没想到还是监听不到

**Comment by qiuguian** [comment]
授权后   没有自动返回应用，而是停留在微信了  这个版本

**Comment by JarvanMo** [comment]
那你是因为没有看看有有没有配置URL schema，还有universal Link，还有application queries------------------ 原始邮件 ------------------
发件人: "qiuguian"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:05
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 苹果授权登录  与  支付  都收不到回调了啊，紧急中 (#198)



授权后   没有自动返回应用，而是停留在微信了  这个版本
 
&mdash;

**Comment by qiuguian** [comment]
配置有的  不然我一个月前就不可能测跑的成功了，universal Link这个原来没配置时 调不起微信，后面配置后就调过来了

**Comment by JarvanMo** [comment]
那可以清空缓存之类的试试。总之，我是无法复现 ------------------ 原始邮件 ------------------
发件人: "qiuguian"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:11
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 苹果授权登录  与  支付  都收不到回调了啊，紧急中 (#198)



配置有的  不然我一个月前就不可能测跑的成功了，universal Link这个原来没配置时 调不起微信，后面配置后就调过来了
 
&mdash;

**Comment by qiuguian** [comment]
如果你确定你那有回调的话 我再看看吧

**Comment by qiuguian** [comment]
@JarvanMo  请教一下  universal Link 的 域名  怎么定义的，还是说一定要是help.wechat.com？

**Comment by JarvanMo** [comment]
得是自己的服务器，网上教程很多------------------ 原始邮件 ------------------
发件人: "qiuguian"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:39
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 苹果授权登录  与  支付  都收不到回调了啊，紧急中 (#198)



@JarvanMo  请教一下  universal Link 的 域名  怎么定义的，还是说一定要是help.wechat.com？
 
&mdash;

**Comment by qiuguian** [comment]
服务器上要做什么相应的配置的吗

**Comment by JarvanMo** [comment]
你去看看我的视频吧，一句两句话说不清楚------------------ 原始邮件 ------------------
发件人: "qiuguian"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:42
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 苹果授权登录  与  支付  都收不到回调了啊，紧急中 (#198)



&#x670D;务器上要做什么相应的配置的吗
 
&mdash;

**Comment by jiangyh1024** [comment]
@qiuguian 我也遇到了这个问题 请问是怎么解决的

**Comment by qiuguian** [comment]
@jiangyh1024 universalLink 的配置问题，配置对就好了

**Comment by jiangyh1024** [comment]
@qiuguian 能加个QQ 么 
univeral link 是对了的  难道有什么规则？

**Comment by qiuguian** [comment]
xcode上也要配置  你配置了吗

**Comment by jiangyh1024** [comment]
Xcode 配置了 URL SCHEMA  放入了 微信appiD 
info.list 里面也加了 lsapplicationschema

**Comment by qiuguian** [comment]
我的微信号 qiuguian_168999

**Comment by YQjiuhao** [comment]
同样的问题

**Comment by JarvanMo** [comment]
不已经有给解决方案了吗------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;YQjiuhao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月8日(星期一) 下午5:56
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 苹果授权登录  与  支付  都收不到回调了啊，紧急中 (#198)

**Comment by YQjiuhao** [comment]
> 不已经有给解决方案了吗------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;YQjiuhao&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年6月8日(星期一) 下午5:56 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 苹果授权登录 与 支付 都收不到回调了啊，紧急中 (#198)

没看到你的解决办法在哪啊？

**Comment by amentan** [comment]
我遇到一种情况就是在集成支付宝时，弄了 “配置返回 URL 处理方法”，在AppDelegate.m中添加了 openUrl 方法，把他去掉就可以了。
