### ISSUE TITLE
2.0.1 Android 在调用registerWxApi时报错

### ISSUE THREAD

**Issue by wdongxv** [OpenFlutter/fluwx#199]
E/flutter ( 4103): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null)
E/flutter ( 4103): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 4103): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 4103): <asynchronous suspension>
E/flutter ( 4103): #2      registerWxApi (package:fluwx/src/fluwx_iml.dart:75:25)
E/flutter ( 4103): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter ( 4103): #4      registerWxApi (package:fluwx/src/fluwx_iml.dart:64:27)

**Comment by JarvanMo** [comment]
定位一下Android报错的地方 ------------------ 原始邮件 ------------------
发件人: "dx.wang"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 晚上9:28
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 2.0.1 Android 在调用registerWxApi时报错 (#199)



E/flutter ( 4103): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null)
 E/flutter ( 4103): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
 E/flutter ( 4103): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
 E/flutter ( 4103): 
 E/flutter ( 4103): #2      registerWxApi (package:fluwx/src/fluwx_iml.dart:75:25)
 E/flutter ( 4103): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
 E/flutter ( 4103): #4      registerWxApi (package:fluwx/src/fluwx_iml.dart:64:27)
 
&mdash;

**Comment by wdongxv** [comment]
E/MethodChannel#com.jarvanmo/fluwx(13289): Failed to handle method call
E/MethodChannel#com.jarvanmo/fluwx(13289): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.tencent.mm.opensdk.openapi.BaseWXApiImplV10.<init>(Unknown Source:41)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.tencent.mm.opensdk.openapi.WXApiImplV10.<init>(Unknown Source:0)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.tencent.mm.opensdk.openapi.WXAPIFactory.createWXAPI(Unknown Source:29)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.tencent.mm.opensdk.openapi.WXAPIFactory.createWXAPI(Unknown Source:1)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.jarvan.fluwx.handlers.WXAPiHandler.registerApp(WXAPiHandler.kt:54)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.jarvan.fluwx.FluwxPlugin.onMethodCall(FluwxPlugin.kt:52)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#com.jarvanmo/fluwx(13289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by JarvanMo** [comment]
我知道了，你是旧plugin。 ------------------ 原始邮件 ------------------
发件人: "dx.wang"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 晚上9:28
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 2.0.1 Android 在调用registerWxApi时报错 (#199)



E/flutter ( 4103): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null)
 E/flutter ( 4103): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
 E/flutter ( 4103): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
 E/flutter ( 4103): 
 E/flutter ( 4103): #2      registerWxApi (package:fluwx/src/fluwx_iml.dart:75:25)
 E/flutter ( 4103): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
 E/flutter ( 4103): #4      registerWxApi (package:fluwx/src/fluwx_iml.dart:64:27)
 
&mdash;

**Comment by JarvanMo** [comment]
最晚明天修复这个问题------------------ 原始邮件 ------------------
发件人: "dx.wang"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 晚上9:28
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 2.0.1 Android 在调用registerWxApi时报错 (#199)



E/flutter ( 4103): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null)
 E/flutter ( 4103): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
 E/flutter ( 4103): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
 E/flutter ( 4103): 
 E/flutter ( 4103): #2      registerWxApi (package:fluwx/src/fluwx_iml.dart:75:25)
 E/flutter ( 4103): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
 E/flutter ( 4103): #4      registerWxApi (package:fluwx/src/fluwx_iml.dart:64:27)
 
&mdash;

**Comment by wdongxv** [comment]
OK，感谢

**Comment by wdongxv** [comment]
我调试了一下确实 这个函数没有被调用
    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        WXAPiHandler.setContext(binding.activity.applicationContext)
    }

**Comment by JarvanMo** [comment]
因为这个函数是embedding plugin里，v1是不会调用的。在registrar with里给context赋值就OK了。------------------ 原始邮件 ------------------
发件人: "dx.wang"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 晚上9:39
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 2.0.1 Android 在调用registerWxApi时报错 (#199)



我调试了一下确实 这个函数没有被调用
 override fun onAttachedToActivity(binding: ActivityPluginBinding) {
 WXAPiHandler.setContext(binding.activity.applicationContext)
 }
 
&mdash;

**Comment by Zzed666** [comment]
我在2.0.3又碰到了这个问题，请问是什么原因呀
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
    #3      registerWxApi (package:fluwx/src/fluwx_iml.dart:75:25)
    #4      _LoginPageState._initFluwx (package:flutter_gratuscn/page/login/login_page.dart:59:11)
    #5      _LoginPageState.initState (package:flutter_gratuscn/page/login/login_page.dart:50:5)
    #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
    #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
    #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
    #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
    #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
    #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
    #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5

也是在android上运行
