### ISSUE TITLE
分享问题 （1.2.1+1正常，2.0.0+1 及以上新版本有问题）

### ISSUE THREAD

**Issue by BuildingTheWorld** [OpenFlutter/fluwx#200]
分享图片及小程序 1.2.1+1 正常 2.0.0+1 及以上新版本有问题
具体：1. 安卓，真机调试 release  2.0.0+1 及以上新版本 一切正常
2. 安卓，打 release 包， 2.0.0+1 及以上新版本，可以跳转至微信，但选择联系人的时候没有反应（正常应该微信内部有弹窗）
3. iOS 暂未测试

**Comment by JarvanMo** [comment]
先把混淆关闭一下试试。------------------ 原始邮件 ------------------
发件人: "BuildingTheWorld"<notifications@github.com>
发送时间: 2020年3月10日(星期二) 下午5:32
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 分享问题 （1.2.1+1正常，2.0.0+1 及以上新版本有问题） (#200)



分享图片及小程序 1.2.1+1 正常 2.0.0+1 及以上新版本有问题
 具体：1. 安卓，真机调试 release  2.0.0+1 及以上新版本 一切正常
 2. 安卓，打 release 包， 2.0.0+1 及以上新版本，可以跳转至微信，但选择联系人的时候没有反应（正常应该微信内部有弹窗）
 3. iOS 暂未测试
 
&mdash;

**Comment by JarvanMo** [comment]
Duplicate of #201
