### ISSUE TITLE
did not find header 'FluwxResponseHandler.h' in framework 'fluwx 

### ISSUE THREAD

**Issue by lalilajiao** [OpenFlutter/fluwx#206]
#flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```
#include <fluwx/FluwxResponseHandler.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/zhancheng/Code/haipei-flutter/ios/Runner/AppDelegate.m:3:10: note: did not find header 'FluwxResponseHandler.h' in framework 'fluwx' (loaded from '/Users/zhancheng/Code/haipei-flutter/build/ios/Debug-iphonesimulator/fluwx')
    1 error generated.
```

**Comment by JarvanMo** [comment]
请使用最新版，也不要重写app delegate------------------ 原始邮件 ------------------
发件人: "lalilajiao"<notifications@github.com>
发送时间: 2020年3月21日(星期六) 中午11:03
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] did not find header 'FluwxResponseHandler.h' inframework 'fluwx  (#206)




 
#flutter doctor
 
Doctor summary (to see all details, run flutter doctor -v):
 [&#x2713;] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
 ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
 [&#x2713;] Xcode - develop for iOS and macOS (Xcode 11.2.1)
 [&#x2713;] Android Studio (version 3.5)
 [&#x2713;] Connected device (2 available)
 
! Doctor found issues in 1 category.
 #include <fluwx/FluwxResponseHandler.h>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     /Users/zhancheng/Code/haipei-flutter/ios/Runner/AppDelegate.m:3:10: note: did not find header 'FluwxResponseHandler.h' in framework 'fluwx' (loaded from '/Users/zhancheng/Code/haipei-flutter/build/ios/Debug-iphonesimulator/fluwx')     1 error generated.  
&mdash;

**Comment by lalilajiao** [comment]
@JarvanMo 多谢，已解决
