### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method openWXApp on channel com.jarvanmo/fluwx)

### ISSUE THREAD

**Issue by asanant** [OpenFlutter/fluwx#207]
升级  ^2.0.6+2  版本   
fluwx.openWeChatApp()  使用打开微信方法报异常

E/flutter (28499): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method openWXApp on channel com.jarvanmo/fluwx)
E/flutter (28499): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499): #1      openWeChatApp (package:fluwx/src/fluwx_iml.dart:56:25)

**Comment by JarvanMo** [comment]
Will fix ASAP.------------------ 原始邮件 ------------------
发件人: "asanant"<notifications@github.com>
发送时间: 2020年3月30日(星期一) 下午4:34
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] Unhandled Exception: MissingPluginException(Noimplementation found for method openWXApp on channel com.jarvanmo/fluwx)(#207)




 
升级  ^2.0.6+2  版本
 fluwx.openWeChatApp()  使用打开微信方法报异常
 
E/flutter (28499): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method openWXApp on channel com.jarvanmo/fluwx)
 E/flutter (28499): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
 E/flutter (28499): 
 E/flutter (28499): #1      openWeChatApp (package:fluwx/src/fluwx_iml.dart:56:25)
 
&mdash;
