### ISSUE TITLE
ios分享失败

### ISSUE THREAD

**Issue by weiyinqing** [OpenFlutter/fluwx#208]
Fluwx 2.07版本：

ios可以唤起微信，并且提示app和微信连接界面，但是分享的时候不显示要分享的内容。

info.plish配置文件如下：
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>åå
			<string>wx51caf287c784a9f7</string>
		</dict>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>weixin</string>
		<string>weixinULAPI</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
```

**Comment by JarvanMo** [comment]
确保universal Link没问题。------------------ 原始邮件 ------------------
发件人: "weiyinqing"<notifications@github.com>
发送时间: 2020年4月3日(星期五) 下午3:56
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] ios分享失败 (#208)




 
Fluwx 2.07版本：
 
ios可以唤起微信，并且提示app和微信连接界面，但是分享的时候不显示要分享的内容。
 
info.plish配置文&#x4EF6;如下：
 CFBundleURLTypes
 
 
 CFBundleTypeRole
 Editor
 CFBundleURLName&#xE5;&#xE5;
 wx51caf287c784a9f7
 
 
 LSApplicationQueriesSchemes
 
 weixin
 weixinULAPI
 
 LSRequiresIPhoneOS
 
 
&mdash;
