### ISSUE TITLE
调起微信一次性服务消息授权，用户点取消app会crash

### ISSUE THREAD

**Issue by leyi422** [OpenFlutter/fluwx#212]
iOS系统，使用subscribeWeChatMsg方法调起微信一次性服务消息授权，用户点确认接受一切正常，点取消app会crash。

iOS版本：13.3.1
Fultter版本：v1.12.13+hotfix.8
fluwx版本：2.0.7

**Comment by leyi422** [comment]
btw，安卓上测试ok

**Comment by JarvanMo** [comment]
抓crash的日志啊------------------ 原始邮件 ------------------
发件人: "leyi422"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午3:06
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 调起微信一次性服务消息授权，用户点取消app会crash (#212)




 
btw，安卓上测试ok
 
&mdash;

**Comment by leyi422** [comment]
2020-04-09 16:38:07.276153+0800 Runner[9708:14362722] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

**Comment by leyi422** [comment]
能否尽快修一下这个bug？产品准备上线，谢谢！

**Comment by JarvanMo** [comment]
你要是实在是着急可以PR。 我现在有点忙。------------------ 原始邮件 ------------------
发件人: "leyi422"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 下午2:32
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 调起微信一次性服务消息授权，用户点取消app会crash (#212)




 
能否尽快修一下这个bug？产品准备上线，谢谢！
 
&mdash;
