### ISSUE TITLE
微信分享时，app经历了两次进入后台和两次进入前台

### ISSUE THREAD

**Issue by Zhaimm** [OpenFlutter/fluwx#213]
当我执行分享到微信时，我的app，1进入后台，2进入前台，3进入后台；等我微信回来有经历了4进入前台。当我监听app进入前台去执行一些事情（比如：弹框），就会造成执行两次问题（例如：弹框两次）。
![WeChatf6ce8c5aed2f79ffc15271624f860b3b](https://user-images.githubusercontent.com/32920612/78871990-221b4500-7a7b-11ea-9fcd-816fab6e956d.png)

**Comment by JarvanMo** [comment]
这不是fluwx的问题吧 ------------------ 原始邮件 ------------------
发件人: "Zhaimm"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午4:00
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 微信分享时，app经历了两次进入后台和两次进入前台 (#213)




 
当我执行分享到微信时，我的app，1进入后台，2进入前台，3进入后台；等我微信回来有经历了4进入前台。当我监听app进入前台去执行一些事情（比如：弹框），就会造成执行两次问题（例如：弹框两次）。
 
 
&mdash;

**Comment by Zhaimm** [comment]
我使用fluwx.openWeChatApp()这个方法就不会出现问题

**Comment by JarvanMo** [comment]
这是一回事吗。。。------------------ 原始邮件 ------------------
发件人: "Zhaimm"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 下午4:17
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 微信分享时，app经历了两次进入后台和两次进入前台 (#213)




 
我使用fluwx.openWeChatApp()这个方法就不会出现问题
 
&mdash;

**Comment by Zhaimm** [comment]
我不知道是怎么回事，所以来请求帮助的。thanks

**Comment by zhuliang007** [comment]
我也遇到相同问题，分享后返回app，前台跳了两次页面

**Comment by zhuliang007** [comment]
你看看你的状态管理是怎么去管理的，可能是在这块在循环执行

**Comment by fangmd** [comment]
这是你 applinks 没有设置好的问题。

**Comment by MrQiu920702** [comment]
我也出现了同样问题  解决了吗

**Comment by MrQiu920702** [comment]
> 这是你 applinks/universalLink 没有设置好的问题。
指导一下 大神

**Comment by MrQiu920702** [comment]
> 当我执行分享到微信时，我的app，1进入后台，2进入前台，3进入后台；等我微信回来有经历了4进入前台。当我监听app进入前台去执行一些事情（比如：弹框），就会造成执行两次问题（例如：弹框两次）。
> ![WeChatf6ce8c5aed2f79ffc15271624f860b3b](https://user-images.githubusercontent.com/32920612/78871990-221b4500-7a7b-11ea-9fcd-816fab6e956d.png)

楼主解决了吗/》？？？

**Comment by zhuyongbo100** [comment]
遇到了同样的问题，ios设备跳转微信时会返回app两次，android不会，像是框架的bug

**Comment by Zuozihao** [comment]
iOS需要配置universal link才行 之前做rn的时候也遇到过 配置universal link，服务器上传apple-app-site-association就可以了

**Comment by Zhaimm** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zuozihao"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 中午11:16
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com&gt;; 
抄送: "迈步丶出唐突"<907940038@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/fluwx] 微信分享时，app经历了两次进入后台和两次进入前台 (#213)





 
iOS需要配置universal link才行 之前做rn的时候也遇到过 配置universal link，服务器上传apple-app-site-association就可以了

**Comment by ixugo** [comment]
请问这个问题解决了嘛?

**Comment by Witcher-jufei** [comment]
配置完后别忘了这个https://upload-images.jianshu.io/upload_images/22959119-5663e98a0460514f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240 [简书地址](https://www.jianshu.com/p/3d8b2d65e57a)
