### ISSUE TITLE
【2.0.8+1】版本 安卓使用本地图片分享崩溃

### ISSUE THREAD

**Issue by xienas** [OpenFlutter/fluwx#214]
![截屏2020-04-15 下午4 24 02](https://user-images.githubusercontent.com/48667306/79315475-92234280-7f35-11ea-9bba-56ba9346d1e9.png)
![截屏2020-04-15 下午4 18 48](https://user-images.githubusercontent.com/48667306/79314967-ff82a380-7f34-11ea-82f7-80e167a5cfce.png)

**Comment by JarvanMo** [comment]
看文档。新版已经不需要前缀了。

**Comment by xunzzz** [comment]
去前缀也不行，还有文档在哪？能说清楚点吗？
