### ISSUE TITLE
微信分享的几个疑问

### ISSUE THREAD

**Issue by gaoyong06** [OpenFlutter/fluwx#224]
我参考了示例代码打印了编写了下面的demo代码，打印了一些日志如下：

` 
//微信分享回调
//参考文档：https://github.com/OpenFlutter/fluwx/blob/4875aab61fab9c3678cd36e2d72d9e4857255c53/doc/BASIC_KNOWLEDGE_CN.md
    weChatResponseEventHandler.listen((res) {

      print("执行 微信分享回调 ");

      //分享微信好友打印日志：
      //成功：res.errCode: 0, res.errStr: null, res.type: 2 res.isSuccessful: true
      //取消：res.errCode: 0, res.errStr: null, res.type: 2 res.isSuccessful: true

      //分享朋友圈打印日志：
      //成功：res.errCode: 0, res.errStr: null, res.type: 2 res.isSuccessful: true
      //取消：res.errCode: 0, res.errStr: null, res.type: 2 res.isSuccessful: true
      if (res is WeChatShareResponse) {

          print(" res.errCode: ${res.errCode}, res.errStr: ${res.errStr}, res.type: ${res.type} res.isSuccessful: ${res.isSuccessful}" );   
      }
    });

`

问题是：
1. 区分不开分享的是“微信好友”， 还是“朋友圈”
2. 区分不开分享的成功，失败，取消 这3个状态

无论分享“微信好友”， 还是“朋友圈”， 是分享成功，或是取消分享 （测试是未出现分享失败的情况）

打印的日志都是相同的：
 res.errCode: 0, res.errStr: null, res.type: 2 res.isSuccessful: true

是我哪里搞错了？还是fluwx的实现bug了？

**Comment by JarvanMo** [comment]
关于分享结果的问题，已经有人问过了，现在只有成功。至于为什么，请看之前的issue或者微信论坛。其他的问题去看微信原生SDK文档。
