### ISSUE TITLE
微信支付可以成功，微信三方登陆/微信分享，总是提示universal link校验不通过

### ISSUE THREAD

**Issue by 472125266** [OpenFlutter/fluwx#226]
使用fluwx的2.0.8+3版本时，初始化微信，调用registerWxApi，并设置universalLink，但调用时，微信支付可以成功，微信三方登陆/微信分享，总是提示universal link校验不通过

**Comment by JarvanMo** [comment]
微信说不通过就是不通过，没有什么可质疑的。------------------ 原始邮件 ------------------
发件人: "YanTao"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 下午2:50
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 微信支付可以成功，微信三方登陆/微信分享，总是提示universal link校验不通过 (#226)




 
使用fluwx的2.0.8+3版本时，初始化微信，调用registerWxApi，并设置universalLink，但调用时，微信支付可以成功，微信三方登陆/微信分享，总是提示universal link校验不通过
 
&mdash;

**Comment by 472125266** [comment]
我想知道下原因，因为微信支付成功不是也要通过universalLink回来么？请多给一些指导，谢谢

**Comment by JarvanMo** [comment]
具体的要看微信官方文档，或者咨询微信官方。我只能保证调通，其他的很多SDK细节我并不了解。 ------------------ 原始邮件 ------------------
发件人: "YanTao"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 下午2:57
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 微信支付可以成功，微信三方登陆/微信分享，总是提示universal link校验不通过 (#226)




 
我想知道下原因，因为微信支付成功不是也要通过universalLink回来么？请多给一些指导，谢谢
 
&mdash;
