### ISSUE TITLE
很卡顿不知道为什么

### ISSUE THREAD

**Issue by DavidMGT** [OpenFlutter/fluwx#228]
只是分享简单的网页，但是都要很久。感觉特别卡顿

**Comment by JarvanMo** [comment]
和fluwx没有关系。------------------ 原始邮件 ------------------
发件人: "DavidMc"<notifications@github.com>
发送时间: 2020年5月7日(星期四) 下午3:35
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 很卡顿不知道为什么 (#228)




 
只是分享简单的网页，但是都要很久。感觉特别卡顿
 
&mdash;

**Comment by JarvanMo** [comment]
即使有关系，应该是缩略图的压缩问题。------------------ 原始邮件 ------------------
发件人: "DavidMc"<notifications@github.com>
发送时间: 2020年5月7日(星期四) 下午3:35
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 很卡顿不知道为什么 (#228)




 
只是分享简单的网页，但是都要很久。感觉特别卡顿
 
&mdash;

**Comment by JarvanMo** [comment]
你可以试试没有缩略图------------------ 原始邮件 ------------------
发件人: "DavidMc"<notifications@github.com>
发送时间: 2020年5月7日(星期四) 下午3:35
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/fluwx] 很卡顿不知道为什么 (#228)




 
只是分享简单的网页，但是都要很久。感觉特别卡顿
 
&mdash;
