### ISSUE TITLE
集成fluwx 后，打开iOS端编译失败！

### ISSUE THREAD

**Issue by Davia2017** [OpenFlutter/fluwx#229]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PayReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXChooseInvoiceReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_OpenWebviewReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_SendAuthReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXChooseCardReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_AddCardToWXCardPackageReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXCardItem", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXAppExtendObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXMiniProgramObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXFileObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXEmoticonObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXVideoObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_SendAuthResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXMediaMessage", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_GetMessageFromWXReq", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXLaunchMiniProgramReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXApi", referenced from:
      objc-class-ref in fluwx(FluwxPlugin.o)
      objc-class-ref in fluwx(WXApiRequestHandler.o)
     (maybe you meant: _OBJC_CLASS_$_WXApiRequestHandler)
  "_OBJC_CLASS_$_WXImageObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_LaunchFromWXReq", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_PayResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_ShowMessageFromWXReq", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXSubscribeMsgReq", referenced from:
      objc-class-ref in fluwx(FluwxPlugin.o)
  "_OBJC_CLASS_$_SendMessageToWXReq", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXInvoiceAuthInsertResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXOpenBusinessWebViewResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXLaunchMiniProgramResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXChooseInvoiceResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXChooseCardResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_AddCardToWXCardPackageResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXMusicObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WXSubscribeMsgResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_SendMessageToWXResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXWebpageObject", referenced from:
      objc-class-ref in fluwx(WXApiRequestHandler.o)
  "_OBJC_CLASS_$_WechatAuthSDK", referenced from:
      objc-class-ref in fluwx(FluwxAuthHandler.o)
  "_OBJC_CLASS_$_WXNontaxPayResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
  "_OBJC_CLASS_$_WXOpenBusinessWebViewReq", referenced from:
      objc-class-ref in fluwx(FluwxPlugin.o)
  "_OBJC_CLASS_$_WXPayInsuranceResp", referenced from:
      objc-class-ref in fluwx(FluwxResponseHandler.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CyJaySong** [comment]
解决了？

**Comment by chezhiliang** [comment]
相同问题，求解

**Comment by karedem** [comment]
解决了 更新到2.0.9 记得podfile.lock一并改动

**Comment by cv0cv0** [comment]
怎么解决的？

**Comment by chezhiliang** [comment]
把podfile.lock删除自动重建，应该就好了

**Comment by cv0cv0** [comment]
> 把podfile.lock删除自动重建，应该就好了

什么原理？

**Comment by CyJaySong** [comment]
项目问题，我备份了 IOS 资源文件，重建 IOS 项目，放回去就好了

**Comment by karedem** [comment]
解决办法: 
在Runner项目的 Targets - Build Phases - LinkBinaryWith Libraries  中添加对应缺失的库
   这里是libWechatSDK.a
