### ISSUE TITLE
ios handleLaunchMiniProgram build error

### ISSUE THREAD

**Issue by sidealice** [OpenFlutter/fluwx#23]
- (void)handleLaunchMiniProgram:(FlutterMethodCall *)call result:(FlutterResult)result {
    NSString *userName = call.arguments[@"userName"];
    NSString *path = call.arguments[@"path"];
    WXMiniProgramType *miniProgramType = (call.arguments[@"miniProgramType"]

    [WXApiRequestHandler launchMiniProgramWithUserName:userName
                                        path:path
                                        type:miniProgramType;
}

**Comment by JarvanMo** [comment]
error resolved
