### ISSUE TITLE
Flutter 升级 1.17.0 后编译失败

### ISSUE THREAD

**Issue by CyJaySong** [OpenFlutter/fluwx#231]
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_PayReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXChooseInvoiceReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_OpenWebviewReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_SendAuthReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXChooseCardReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_AddCardToWXCardPackageReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXCardItem", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXMiniProgramObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXFileObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXEmoticonObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXVideoObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXWebpageObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_LaunchFromWXReq", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_GetMessageFromWXReq", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXOpenBusinessWebViewResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_PayResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXPayInsuranceResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXMusicObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXSubscribeMsgResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXChooseInvoiceResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXChooseCardResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_AddCardToWXCardPackageResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_SendMessageToWXResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_MPushNotificationConfiguration", referenced from:
          objc-class-ref in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_AlipaySDK", referenced from:
          objc-class-ref in tobias(TobiasPlugin.o)
      "_OBJC_CLASS_$_WechatAuthSDK", referenced from:
          objc-class-ref in fluwx(FluwxAuthHandler.o)
      "_OBJC_CLASS_$_SMSSDKUserInfo", referenced from:
          objc-class-ref in mobsms(MobsmsPlugin.o)
      "_OBJC_CLASS_$_WXLaunchMiniProgramResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_MPushNotification", referenced from:
          objc-class-ref in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_WXAppExtendObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_MobPush", referenced from:
          objc-class-ref in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_SMSSDK", referenced from:
          objc-class-ref in mobsms(MobsmsPlugin.o)
      "_OBJC_CLASS_$_MobSDK", referenced from:
          objc-class-ref in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_WXOpenBusinessWebViewReq", referenced from:
          objc-class-ref in fluwx(FluwxPlugin.o)
      "_OBJC_CLASS_$_WXNontaxPayResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXLaunchMiniProgramReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXImageObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXApi", referenced from:
          objc-class-ref in fluwx(FluwxPlugin.o)
          objc-class-ref in fluwx(WXApiRequestHandler.o)
         (maybe you meant: _OBJC_CLASS_$_WXApiRequestHandler)
      "_OBJC_CLASS_$_WXInvoiceAuthInsertResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_MPushMessage", referenced from:
          objc-class-ref in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_WXMediaMessage", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_MOBFJson", referenced from:
          objc-class-ref in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_SendAuthResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_MobPushDidReceiveMessageNotification", referenced from:
          -[MobpushPlugin addObserver] in mobpush_plugin(MobpushPlugin.o)
      "_OBJC_CLASS_$_SendMessageToWXReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_ShowMessageFromWXReq", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXSubscribeMsgReq", referenced from:
          objc-class-ref in fluwx(FluwxPlugin.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by karedem** [comment]
the same

**Comment by cv0cv0** [comment]
一样。

**Comment by karedem** [comment]
解决了 更新到2.0.9 记得podfile.lock一并改动

**Comment by cv0cv0** [comment]
@karedem 改成 2.0.9 ？

**Comment by cv0cv0** [comment]
> 解决了 更新到2.0.9 记得podfile.lock一并改动

好像不用改，运行一下 pod update 就可以了。

**Comment by cv0cv0** [comment]
@karedem @CyJaySong 你们怎么解决的？

**Comment by CyJaySong** [comment]
> @karedem @CyJaySong 你们怎么解决的？

目前还没解决呢

**Comment by CyJaySong** [comment]
我是更新到 2.0.9 的，但是还是不行

cv0cv0 <notifications@github.com> 于2020年5月8日周五 下午3:49写道：

**Comment by cv0cv0** [comment]
解决了？

**Comment by CyJaySong** [comment]
> 解决了？

解决了，备份 IOS 项目的资源、info文件,重建一下 IOS ，再把文件替换回去就好了

**Comment by karedem** [comment]
我发现example里是静态库  但是我依赖的好像都是动态库  这个会有影响吗

**Comment by cv0cv0** [comment]
> 我发现example里是静态库 但是我依赖的好像都是动态库 这个会有影响吗

我是 Android 开发，对 iOS 不太了解。

**Comment by xuwankang** [comment]
升级到2.0.9 Specs satisfying the `WechatOpenSDK (= 1.8.6.2), WechatOpenSDK (= 1.8.7.1)` dependency were found,

**Comment by Davia2017** [comment]
同样遇到 编译不通过，我引入了wechatsdk 的.a 文件后可以编译通过，但是分享时又有其它问题
