### ISSUE TITLE
无法分享动图

### ISSUE THREAD

**Issue by huntrist** [OpenFlutter/fluwx#232]
分享
WeChatImage.network
网络图片确定是动图gif
即使把suffix手动设置成gif
分享到微信Session/Timeline中依然是jpg静态图

**Comment by zinwalin** [comment]
gif文件有多大？

**Comment by xiangzy1** [comment]
同样的问题，多大的gif文件都不行

**Comment by MAO-MAX** [comment]
请问官方有对应的支持动图的日程安排吗？

**Comment by 625341062** [comment]
这个问题什么时候能修复一下，我看原生的sendEmotionData方法在的，只不过flutter没有提供接口
![截屏2022-06-06 15 09 08](https://user-images.githubusercontent.com/15033062/172112768-073e6122-6b75-40d3-84f1-466bd1e676ce.png)

**Comment by JarvanMo** [comment]
这个问题等我研究下，我对ios也不太懂，不会处理gif。不过这个方法应该是分享表情的，而不是gif。

**Comment by JarvanMo** [comment]
Probably fixed in 5.0
