### ISSUE TITLE
Flutter 1.17.0 iOS 编译失败

### ISSUE THREAD

**Issue by cv0cv0** [OpenFlutter/fluwx#234]
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_PayReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXChooseInvoiceReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_OpenWebviewReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_SendAuthReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXChooseCardReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_AddCardToWXCardPackageReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXCardItem", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXAppExtendObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXMiniProgramObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXFileObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXEmoticonObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXVideoObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_SendAuthResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXMediaMessage", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_GetMessageFromWXReq", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXLaunchMiniProgramReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXApi", referenced from:
          objc-class-ref in fluwx(FluwxPlugin.o)
          objc-class-ref in fluwx(WXApiRequestHandler.o)
         (maybe you meant: _OBJC_CLASS_$_WXApiRequestHandler)
      "_OBJC_CLASS_$_WXImageObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_LaunchFromWXReq", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_PayResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_ShowMessageFromWXReq", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXSubscribeMsgReq", referenced from:
          objc-class-ref in fluwx(FluwxPlugin.o)
      "_OBJC_CLASS_$_SendMessageToWXReq", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXInvoiceAuthInsertResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXOpenBusinessWebViewResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXLaunchMiniProgramResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXChooseInvoiceResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXChooseCardResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_AddCardToWXCardPackageResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXMusicObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WXSubscribeMsgResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_SendMessageToWXResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXWebpageObject", referenced from:
          objc-class-ref in fluwx(WXApiRequestHandler.o)
      "_OBJC_CLASS_$_WechatAuthSDK", referenced from:
          objc-class-ref in fluwx(FluwxAuthHandler.o)
      "_OBJC_CLASS_$_WXNontaxPayResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
      "_OBJC_CLASS_$_WXOpenBusinessWebViewReq", referenced from:
          objc-class-ref in fluwx(FluwxPlugin.o)
      "_OBJC_CLASS_$_WXPayInsuranceResp", referenced from:
          objc-class-ref in fluwx(FluwxResponseHandler.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zlg0613** [comment]
同遇到此问题，期待解决方案

**Comment by 530209190** [comment]
同遇到此问题，期待解决方案

**Comment by LvJson** [comment]
不是作者的问题，先把自己的项目重新构建下
没科学上网的要科学上网，不然很多东西下载不了

**Comment by zlg0613** [comment]
一直是可以科学上网的，应该是有依赖重复的问题，对IOS不熟悉，正在慢慢解决

**Comment by 530209190** [comment]
把ios项目重新弄一次就可以了。已经解决了

**Comment by cv0cv0** [comment]
> 把ios项目重新弄一次就可以了。已经解决了

试过了，还是报这个错误。

**Comment by zlg0613** [comment]
IOS项目，先备份，再将工程必须文件等复制回去，重新run，就可以了。
已解决

**Comment by cv0cv0** [comment]
> IOS项目，先备份，再将工程必须文件等复制回去，重新run，就可以了。
> 已解决

一样的错误。

**Comment by theecn** [comment]
求解

**Comment by karedem** [comment]
解决办法: 
在Runner项目的 Targets - Build Phases - LinkBinaryWith Libraries  中添加对应缺失的库
   这里是libWechatSDK.a 
其他库找不到对应类同理

**Comment by karedem** [comment]
是不是1.17.0对iOS依赖的传递可能不一样了 
主项目里没法直接拿到plugin里的依赖?
有没有大佬解答一下

**Comment by JarvanMo** [comment]
你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮件 ------------------
发件人: "karedem"<notifications@github.com>
发送时间: 2020年5月13日(星期三) 下午5:07
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234)




 
是不是1.17.0对iOS依赖的传递可能不一样了
 主项目里没法直接拿到plugin里的依赖?
 有没有大佬解答一下
 
&mdash;

**Comment by karedem** [comment]
> 你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮件 ------------------ 发件人: "karedem"<notifications@github.com> 发送时间: 2020年5月13日(星期三) 下午5:07 收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


> 你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮件 ------------------ 发件人: "karedem"<notifications@github.com> 发送时间: 2020年5月13日(星期三) 下午5:07 收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我的只是fluwx

**Comment by JarvanMo** [comment]
这个问题也有别的解决方案。 当然了更多的人是没有这个问题------------------ 原始邮件 ------------------
发件人: "karedem"<notifications@github.com>
发送时间: 2020年5月13日(星期三) 下午5:12
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234)




  
你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "karedem"notifications@github.com 发送时间: 2020年5月13日(星期三) 下午5:07 收&#x4EF6;人: "OpenFlutter/fluwx"fluwx@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "karedem"notifications@github.com 发送时间: 2020年5月13日(星期三) 下午5:07 收&#x4EF6;人: "OpenFlutter/fluwx"fluwx@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我的只是fluwx
 
&mdash;

**Comment by cv0cv0** [comment]
> 解决办法:
> 在Runner项目的 Targets - Build Phases - LinkBinaryWith Libraries 中添加对应缺失的库
> 这里是libWechatSDK.a
> 其他库找不到对应类同理

我的找不到 libWechatSDK.a

**Comment by cv0cv0** [comment]
原来要添加文件。

**Comment by karedem** [comment]
> 这个问题也有别的解决方案。 当然了更多的人是没有这个问题------------------ 原始邮件 ------------------ 发件人: "karedem"<notifications@github.com> 发送时间: 2020年5月13日(星期三) 下午5:12 收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>; 抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "karedem"notifications@github.com 发送时间: 2020年5月13日(星期三) 下午5:07 收&#x4EF6;人: "OpenFlutter/fluwx"fluwx@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "karedem"notifications@github.com 发送时间: 2020年5月13日(星期三) 下午5:07 收&#x4EF6;人: "OpenFlutter/fluwx"fluwx@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我的只是fluwx &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是的

**Comment by cv0cv0** [comment]
> 解决办法:
> 在Runner项目的 Targets - Build Phases - LinkBinaryWith Libraries 中添加对应缺失的库
> 这里是libWechatSDK.a
> 其他库找不到对应类同理

    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Undefined symbols for architecture arm64:
      "___cxa_begin_catch", referenced from:
          ___clang_call_terminate in libWeChatSDK.a(WechatAuthSDK.o)
      "operator new[](unsigned long)", referenced from:
          +[WeChatApiUtil EncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
          +[WeChatApiUtil NsDataEncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
          +[WeChatApiUtil DecodeWithBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
          +[WeChatApiUtil DecodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
      "std::terminate()", referenced from:
          ___clang_call_terminate in libWeChatSDK.a(WechatAuthSDK.o)
      "___gxx_personality_v0", referenced from:
          -[WechatAuthSDK init] in libWeChatSDK.a(WechatAuthSDK.o)
          -[WechatAuthSDK dealloc] in libWeChatSDK.a(WechatAuthSDK.o)
          -[WechatAuthSDK resetAll] in libWeChatSDK.a(WechatAuthSDK.o)
          -[WechatAuthSDK resetConnection] in libWeChatSDK.a(WechatAuthSDK.o)
          -[WechatAuthSDK Auth:nonceStr:timeStamp:scope:signature:schemeData:] in
          libWeChatSDK.a(WechatAuthSDK.o)
          -[WechatAuthSDK StopAuth] in libWeChatSDK.a(WechatAuthSDK.o)
          -[WechatAuthSDK sendAuthRequest:] in libWeChatSDK.a(WechatAuthSDK.o)
          ...
      "operator delete[](void*)", referenced from:
          +[WeChatApiUtil EncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
          +[WeChatApiUtil NsDataEncodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
          +[WeChatApiUtil DecodeWithBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
          +[WeChatApiUtil DecodeBase64:] in libWeChatSDK.a(WeChatApiUtil.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cv0cv0** [comment]
> 你是fluwx还是no pay。fluwx至始至终就没有遇到这个问题------------------ 原始邮件 ------------------ 发件人: "karedem"<notifications@github.com> 发送时间: 2020年5月13日(星期三) 下午5:07 收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [OpenFlutter/fluwx] Flutter 1.17.0 iOS 编译失败 (#234) 是不是1.17.0对iOS依赖的传递可能不一样了 主项目里没法直接拿到plugin里的依赖? 有没有大佬解答一下 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

在 Xcode 里编译也报错。

**Comment by cv0cv0** [comment]
Flutter: 1.17.3
fluwx: ^1.2.1+2
编译通过了。
