### ISSUE TITLE
Error installing WechatOpenSDK

### ISSUE THREAD

**Issue by wtdu** [OpenFlutter/fluwx#235]
flutter 中 在配置文件中添加 fluwx:^2.0.9  ,build 时候一直卡在 running pod 这一步，手动cd 到ios目录下执行pod install 或者pod update 也不成功，具体错误如下：

[!] Error installing WechatOpenSDK
[!] /usr/bin/curl -f -L -o /var/folders/st/622vwr6d24q1gdwmybb6tg3h0000gp/T/d20200509-20769-1xplt5b/file.zip https://res.wx.qq.com/op_res/DHI055JVxYur-5c7ss5McQZj2Y9KZQlp24xwD7FYnF88x8LA8rWCzSfdStN5tiCD --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 8001: Connection refused

**Comment by JarvanMo** [comment]
你可以使用pod镜像或者科学上网。这和fluwx没有任何关系。关闭了。
