### ISSUE TITLE
将flutter工程包括fluwx的模块打包成aar，在其他应用调用时候报错:MissingPluginException

### ISSUE THREAD

**Issue by chdyiboke** [OpenFlutter/fluwx#238]
**Describe the bug**
现在需要把微信登录封装成SDK供原生APP使用，flutter工程调用登录正常。打包成AAR后，调用报错MissingPluginException，不知道原因。希望得到帮助，有没有人在这方面有成功的案例，感谢.

**To Reproduce**
1. 注册-时就已经报错，invokeMethod
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method registerApp on channel com.jarvanmo/fluwx)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      registerWxApi (package:fluwx/src/fluwx_iml.dart:75:25)

![error](https://user-images.githubusercontent.com/37524044/81767210-6e3e2700-950a-11ea-867c-a3c3c0b22d38.jpg)

3. flutter build aar 的命令是否就可以编译fluwx的包，在原生APP中调用。

**Which version of Fluwx do you use?**
fluwx: ^2.0.9

**Which device do you run on**
HUAWEI JSN-AL00a Android 10, API 29

**Which Flutter do you use?**

[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

希望给出指导性建议，在方案选型中，如果可以我将继续努力解决这个问题。如果不可以，我将换用原生方案，谢谢。前端一枚，刚入flutter的坑，希望不要见怪。再次感谢。

**Comment by JarvanMo** [comment]
没接触过

**Comment by JarvanMo** [comment]
我感觉是没有对plugin进行注册，FluwxPlugin.registartWith之类的，就是flutter会自己生成GeneratedPluginRegistrant类。可能是缺少这个。

**Comment by chdyiboke** [comment]
@JarvanMo 非常感谢你的建议，我在原生app里尝试注册FluwxPlugin，成功调起了微信登录。
`package com.***.***;

import android.os.Bundle;

import com.jarvan.fluwx.FluwxPlugin;
import io.flutter.app.FlutterActivity;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;

public class MyFlutterActivity extends FlutterActivity {
    private static final String CHANNEL = "****";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FluwxPlugin.registerWith(this.registrarFor("com.jarvan.fluwx.FluwxPlugin"));

        new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
                new MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, Result result) {
                        if (call.method.equals("loginResult")) {
                            // 获取Flutter传递的参数
                            //Log.e(call.arguments);
                            System.out.println(call.arguments);
                            // 回传给Flutter
                            result.success(call.arguments);
                        }
                    }
                });
    }
}`

MissingPluginException 的问题解决，thanks~

**Comment by ZakAnun** [comment]
<details>
<summary>展开查看</summary>
<pre><code>
> @JarvanMo 非常感谢你的建议，我在原生app里尝试注册FluwxPlugin，成功调起了微信登录。 `package com._**.**_;
> 
> import android.os.Bundle;
> 
> import com.jarvan.fluwx.FluwxPlugin; import io.flutter.app.FlutterActivity; import io.flutter.plugin.common.MethodCall; import io.flutter.plugin.common.MethodChannel; import io.flutter.plugin.common.MethodChannel.MethodCallHandler; import io.flutter.plugin.common.MethodChannel.Result;
> 
> public class MyFlutterActivity extends FlutterActivity { private static final String CHANNEL = "****";
> 
> ```
> @Override
> public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     FluwxPlugin.registerWith(this.registrarFor("com.jarvan.fluwx.FluwxPlugin"));
> 
>     new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
>             new MethodCallHandler() {
>                 @Override
>                 public void onMethodCall(MethodCall call, Result result) {
>                     if (call.method.equals("loginResult")) {
>                         // 获取Flutter传递的参数
>                         //Log.e(call.arguments);
>                         System.out.println(call.arguments);
>                         // 回传给Flutter
>                         result.success(call.arguments);
>                     }
>                 }
>             });
> }
> ```
> 
> }`
> 
> MissingPluginException 的问题解决，thanks~
</code></pre>
</details>

你好，请问一下 FluwxPlugin 这个类是怎么获取的，原生工程有引入相关依赖吗

**Comment by ZakAnun** [comment]
> @JarvanMo 非常感谢你的建议，我在原生app里尝试注册FluwxPlugin，成功调起了微信登录。 `package com._**.**_;
> 
> import android.os.Bundle;
> 
> import com.jarvan.fluwx.FluwxPlugin; import io.flutter.app.FlutterActivity; import io.flutter.plugin.common.MethodCall; import io.flutter.plugin.common.MethodChannel; import io.flutter.plugin.common.MethodChannel.MethodCallHandler; import io.flutter.plugin.common.MethodChannel.Result;
> 
> public class MyFlutterActivity extends FlutterActivity { private static final String CHANNEL = "****";
> 
> ```
> @Override
> public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     FluwxPlugin.registerWith(this.registrarFor("com.jarvan.fluwx.FluwxPlugin"));
> 
>     new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
>             new MethodCallHandler() {
>                 @Override
>                 public void onMethodCall(MethodCall call, Result result) {
>                     if (call.method.equals("loginResult")) {
>                         // 获取Flutter传递的参数
>                         //Log.e(call.arguments);
>                         System.out.println(call.arguments);
>                         // 回传给Flutter
>                         result.success(call.arguments);
>                     }
>                 }
>             });
> }
> ```
> 
> }`
> 
> MissingPluginException 的问题解决，thanks~

你好，请问一下 FluwxPlugin 这个类是怎么获取的，原生工程有引入相关依赖吗

**Comment by ZakAnun** [comment]
@chdyiboke 

<details>
<summary>展开查看</summary>
<pre><code>
> @JarvanMo 非常感谢你的建议，我在原生app里尝试注册FluwxPlugin，成功调起了微信登录。 `package com._**.**_;
> 
> import android.os.Bundle;
> 
> import com.jarvan.fluwx.FluwxPlugin; import io.flutter.app.FlutterActivity; import io.flutter.plugin.common.MethodCall; import io.flutter.plugin.common.MethodChannel; import io.flutter.plugin.common.MethodChannel.MethodCallHandler; import io.flutter.plugin.common.MethodChannel.Result;
> 
> public class MyFlutterActivity extends FlutterActivity { private static final String CHANNEL = "****";
> 
> ```
> @Override
> public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     FluwxPlugin.registerWith(this.registrarFor("com.jarvan.fluwx.FluwxPlugin"));
> 
>     new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
>             new MethodCallHandler() {
>                 @Override
>                 public void onMethodCall(MethodCall call, Result result) {
>                     if (call.method.equals("loginResult")) {
>                         // 获取Flutter传递的参数
>                         //Log.e(call.arguments);
>                         System.out.println(call.arguments);
>                         // 回传给Flutter
>                         result.success(call.arguments);
>                     }
>                 }
>             });
> }
> ```
> 
> }`
> 
> MissingPluginException 的问题解决，thanks~
</code></pre>
</details>

你好，请问一下 FluwxPlugin 这个 plugin 是怎么获取的，有额外新增依赖吗？
