### ISSUE TITLE
微信分享小程序thumbnail被压缩严重，图片不清晰

### ISSUE THREAD

**Issue by robin12210325** [OpenFlutter/fluwx#240]
微信分享小程序thumbnail被压缩严重，图片不清晰

**Comment by robin12210325** [comment]
能否给一个变量 让开发自己选择是否进行压缩，不然还要再源码上进行修改 不方便 谢谢

**Comment by JarvanMo** [comment]
提issue请按模板提问------------------ 原始邮件 ------------------
发件人: "robin12210325"<notifications@github.com>
发送时间: 2020年5月14日(星期四) 中午11:44
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [OpenFlutter/fluwx] 微信分享小程序thumbnail被压缩严重，图片不清晰 (#240)




 
能否给一个变量 让开发自己选择是否进行压缩，不然还要再源码上进行修改 不方便 谢谢
 
&mdash;
