### ISSUE TITLE
微信支付获取不到回调问题

### ISSUE THREAD

**Issue by liao5836** [OpenFlutter/fluwx#242]
调试多次微信支付获取不到支付结果回调，看到帖子说这样处理，亲测有效
#import "FluwxResponseHandler.h"
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler{
    return [WXApi handleOpenUniversalLink:userActivity delegate:[FluwxResponseHandler defaultManager]];
}

**Comment by JarvanMo** [comment]
最新版的就有这个代码啊

**Comment by larryluo123** [comment]
> FluwxResponseHandler

FluwxResponseHandler.h文件引用不了，找不到，我也想自己在continueUserActivity自己处理
