### ISSUE TITLE
现在还需要手动创建并注册WXEntryActivity和WXPayEntryActivity吗？

### ISSUE THREAD

**Issue by aplixy** [OpenFlutter/fluwx#243]
1、现在还需要在android下创建wxapi包，在包下创建WXEntryActivity和WXPayEntryActivity两个继承自FluwxWXEntryActivity的Activity吗？
2、还需要在AndroidManifest.xml文件中注册这两个Activity吗？

**Comment by JarvanMo** [comment]
不------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;xinyuli&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月26日(星期二) 晚上8:24
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 现在还需要手动创建并注册WXEntryActivity和WXPayEntryActivity吗？ (#243)
