### ISSUE TITLE
Flutter build apk error

### ISSUE THREAD

**Issue by andansky** [OpenFlutter/fluwx#25]
E:\androidProject\buso>Flutter build apk
Running "flutter packages get" in buso...                        0.8s
Initializing gradle...                                           2.5s
Resolving dependencies...                                       16.9s
Gradle task 'assembleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :fluwx.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)
在dev 0.10.2版本上

**Comment by JarvanMo** [comment]
classpath 'com.android.tools.build:gradle:3.2.1'
kotlin->1.3.0
gradle-wrapper->4.10.2

**Comment by andansky** [comment]
可以了，谢谢

**Comment by daidi** [comment]
什么意思，我也遇到了，囧

**Comment by JarvanMo** [comment]
看楼上。
