### ISSUE TITLE
hdImagePath 无效

### ISSUE THREAD

**Issue by yongplus** [OpenFlutter/fluwx#252]
设置hdImagePath 无效，Android无效，依然使用thumbnail，IOS 超过32KB 分享没任何反应。 望修复~！

**Comment by JarvanMo** [comment]
///
/// the default value is [MINI_PROGRAM_TYPE_RELEASE]
///[hdImagePath] only works on iOS, not sure the relationship between [thumbnail] and [hdImagePath].
class WeChatShareMiniProgramModel implements WeChatShareBaseModel {
