### ISSUE TITLE
可以分享文件吗？

### ISSUE THREAD

**Issue by QGBZ** [OpenFlutter/fluwx#253]
我在依赖中看到了WeChatShareFileModel，但是官方的文档并没有说明支持分享文件，我想分享Excel到微信中，可以实现吗？非常感谢

`class WeChatShareFileModel implements WeChatShareBaseModel {
  final WeChatFile source;
  final WeChatImage thumbnail;
  final String title;
  final String description;
  final WeChatScene scene;
  final String messageExt;
  final String messageAction;
  final String mediaTagName;

  WeChatShareFileModel(this.source,
      {this.title: "",
      this.description: "",
      this.thumbnail,
      this.scene = WeChatScene.SESSION,
      this.mediaTagName,
      this.messageAction,
      this.messageExt})
      : assert(source != null),
        assert(scene != null);`

**Comment by JarvanMo** [comment]
可以。官方没有文档，文件大小也有限制。其他的自己研究吧。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;QGBZ&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月17日(星期五) 下午5:44
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 可以分享文件吗？ (#253)

**Comment by QGBZ** [comment]
非常感谢，已解决
