### ISSUE TITLE
This file can not be opened as a file descriptor; it is probably compressed

### ISSUE THREAD

**Issue by yangsk94** [OpenFlutter/fluwx#257]
fluwx_no_pay: ^2.1.1 
Android 9.1
E/AndroidRuntime(14659): java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
E/AndroidRuntime(14659): 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
E/AndroidRuntime(14659): 	at android.content.res.AssetManager.openFd(AssetManager.java:889)
E/AndroidRuntime(14659): 	at com.jarvan.fluwx.handlers.FluwxShareHandlerEmbedding$assetFileDescriptor$1.invoke(FluwxShareHandler.kt:40)
E/AndroidRuntime(14659): 	at com.jarvan.fluwx.handlers.FluwxShareHandlerEmbedding$assetFileDescriptor$1.invoke(FluwxShareHandler.kt:30)
E/AndroidRuntime(14659): 	at com.jarvan.fluwx.io.WeChatFile$Companion.createWeChatFile(WeChatFiles.kt:132)
E/AndroidRuntime(14659): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$DefaultImpls.readThumbnailByteArray(FluwxShareHandler.kt:274)
E/AndroidRuntime(14659): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$DefaultImpls.readThumbnailByteArray$default(FluwxShareHandler.kt:271)
E/AndroidRuntime(14659): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$shareWebPage$1.invokeSuspend(FluwxShareHandler.kt:226)
E/AndroidRuntime(14659): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(14659): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/AndroidRuntime(14659): 	at android.os.Handler.handleCallback(Handler.java:907)
E/AndroidRuntime(14659): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(14659): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(14659): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(14659): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14659): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(14659): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by JarvanMo** [comment]
It's not caused by fluwx. Please read [this](https://juejin.im/post/6844904160081494030) for detail.
