### ISSUE TITLE
由于不支持的分享类型，无法分享到微信

### ISSUE THREAD

**Issue by JeremyGuo** [OpenFlutter/fluwx#261]
使用了公众号提供的appId

在registerWechat的时候返回的true

调用ShareToWechat后，微信返回结果为由于不支持的分享类型，无法分享到微信。

请问这是appId不能使用公众号的appId导致的，还是我程序的使用方法有问题

**Comment by JarvanMo** [comment]
这个问题问微信官方更好------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;JeremyGuo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月8日(星期六) 中午11:42
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 由于不支持的分享类型，无法分享到微信 (#261)

**Comment by JeremyGuo** [comment]
好的

**Comment by JeremyGuo** [comment]
大概解决了，似乎要去绑定一下移动应用获得的appId才能用（听说），先去试一下
