### ISSUE TITLE
你好，目前遇到audio_service 0.13.0版本和fluwx2.3.0在项目中如果音频服务一旦开始播放，微信登录无法接收到返回值

### ISSUE THREAD

**Issue by GitHub9527** [OpenFlutter/fluwx#265]

**Comment by JarvanMo** [comment]
找找之前类似的issue应该是一个原因。

**Comment by GitHub9527** [comment]
> 找找之前类似的issue应该是一个原因。

我们测试发现，配置

**Comment by GitHub9527** [comment]
> 找找之前类似的issue应该是一个原因。
我们排查发现在androidmanifest.xml 文件中去掉以下配置，Fluwx插件正常工作
<service android:name="com.ryanheise.audioservice.AudioService">
  <intent-filter>
    <action android:name="android.media.browse.MediaBrowserService" />
  </intent-filter>
</service>

**Comment by GitHub9527** [comment]
> 找找之前类似的issue应该是一个原因。

我们只是单纯的引入了插件，并未做任何改动

**Comment by JarvanMo** [comment]
再提示一次，查找之前的issue。之前有人问过类似的，和fluwx没有任何关系。

**Comment by GitHub9527** [comment]
> 再提示一次，查找之前的issue。之前有人问过类似的，和fluwx没有任何关系。

经排查我们引用的audio_service插件因为要使用到服务，在插件初始化的时候重新开启了一个FlutterEngine导致微信消息无法通过Flutter代码初始化的通道返回，以下是我的解决方案：

public class FluwxPlugin : FlutterPlugin, MethodCallHandler, ActivityAware {
    companion object {
        @JvmStatic
        var isFluwxPluginLoaded = false;

        @JvmStatic
        fun registerWith(registrar: PluginRegistry.Registrar) {
            if (!isFluwxPluginLoaded) {
                isFluwxPluginLoaded =true;
                val channel = MethodChannel(registrar.messenger(), "com.jarvanmo/fluwx")
                val authHandler = FluwxAuthHandler(channel)
                FluwxResponseHandler.setMethodChannel(channel)
                WXAPiHandler.setContext(registrar.activity().applicationContext)
                channel.setMethodCallHandler(FluwxPlugin().apply {
                    this.authHandler = authHandler
                    this.shareHandler = FluwxShareHandlerCompat(registrar).apply {
                        permissionHandler = PermissionHandler(registrar.activity())
                    }
                })
            }
        }
    }

.................

**Comment by GitHub9527** [comment]
> 再提示一次，查找之前的issue。之前有人问过类似的，和fluwx没有任何关系。

This audio_service plugin creates an additional FlutterEngine in order to run  audio code in the background separate from the UI. This additional FlutterEngine has its own plugin registry so that Dart code in its isolate is able to use plugins, i.e. so i can do normal coding.

Since this feature was introduced into Flutter almost 2 years ago, flutter plugins should be designed in such a way that they function correctly when loaded into different different engines simultaneously, and if a plugin does not function correctly, then the issue lies with that plugin. In this case, the issue lies with fluwx and you should submit an issue with that project asking them to make it function correctly in this situation.
