### ISSUE TITLE
2.2.0打开小程序后，关闭小程序，并没有回到app，而是在微信

### ISSUE THREAD

**Issue by moc-master** [OpenFlutter/fluwx#266]
**Describe the bug**
2.2.0打开小程序后，关闭小程序，并没有回到app，而是在微信
而且监听的事件没有任何返回

void initState() {
    super.initState();
    weChatResponseEventHandler.listen((res) {
      if (res is WeChatLaunchMiniProgramResponse) {
        if (mounted) {
          setState(() {
            _result = "isSuccessful:${res.isSuccessful}";
          });
        }
      }
    });
  }

**Which version of Fluwx do you use?**
2.2.0

**Comment by JarvanMo** [comment]
你说的是哪个平台？

**Comment by D-Rusty** [comment]
ios

**Comment by youwuxiangsheng** [comment]
我的ios也是 分享出去 点击返回应用  停留在微信  没有返回应用
