### ISSUE TITLE
2.3.0运行不起来

### ISSUE THREAD

**Issue by 15079283571** [OpenFlutter/fluwx#270]
![image](https://user-images.githubusercontent.com/31639628/90725694-255cf200-e2f3-11ea-9e64-77f7e33a2ff9.png)

e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated

**Comment by JarvanMo** [comment]
kotlint版本产问题。很多人问过

**Comment by Crazy-MT** [comment]
怎么解决啊？

**Comment by JarvanMo** [comment]
找之前的issue，升级kotlin到1.4.10.
