### ISSUE TITLE
    [!] Unable to find a specification for `WechatOpenSDK (= 1.8.7.1)` depended upon by `fluwx`

### ISSUE THREAD

**Issue by Observer-jin** [OpenFlutter/fluwx#272]
Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed
      in repo update
    [!] Unable to find a specification for `WechatOpenSDK (= 1.8.7.1)` depended upon by `fluwx`

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install
     --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

**Comment by JakeWoki** [comment]
请问这个怎么解决的？只能下1.8.7，1.8.7.1下不下来，用了代理也不行

**Comment by JarvanMo** [comment]
你的pod可能根本就没有走代理。给pod设置个镜像吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jake&amp;nbsp;Woki&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 下午3:36
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx]     [!] Unable to find a specification for `WechatOpenSDK (= 1.8.7.1)` depended upon by `fluwx` (#272)
