### ISSUE TITLE
fluwx_no_pay 实际上还是有 pay相关的代码，尤其是微信支付的回调页面，FluwxWXEntryActivity

### ISSUE THREAD

**Issue by huntersha** [OpenFlutter/fluwx#274]
微信支付的回调 WXEntryActivity，在manifest中，如果集成其他包含微信支付的SDK，将会有冲突。
Attribute activity-alias#com.sichewang.app.wxapi.WXPayEntryActivity@targetActivity value=(com.jarvan.fluwx.wxapi.FluwxWXEntryActivity) from [:fluwx_no_pay] AndroidManifest.xml:22:13-81
	is also present at *******

**Comment by JarvanMo** [comment]
No pay只针对iOS------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hunter&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月27日(星期四) 下午2:09
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] fluwx_no_pay 实际上还是有 pay相关的代码，尤其是微信支付的回调页面，FluwxWXEntryActivity (#274)

**Comment by huntersha** [comment]
哦哦 原来如此，谢谢及时回复。
如果是专门不做pay的话，建议删除相关代码，在manifest里面配置了，如果用银联支付（微信），如果要处理回调逻辑，就有冲突了。

**Comment by JarvanMo** [comment]
冲突可以通过个性化设置解决。大部分人只是不需要ios的微信支付，但Android需要保留。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hunter&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月27日(星期四) 晚上8:03
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] fluwx_no_pay 实际上还是有 pay相关的代码，尤其是微信支付的回调页面，FluwxWXEntryActivity (#274)

**Comment by huntersha** [comment]
> 冲突可以通过个性化设置解决。大部分人只是不需要ios的微信支付，但Android需要保留。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;hunter&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年8月27日(星期四) 晚上8:03 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] fluwx_no_pay 实际上还是有 pay相关的代码，尤其是微信支付的回调页面，FluwxWXEntryActivity (#274)

请教下你说的个性化设置方案是指？ 因为在两边都加入
  <activity-alias
            android:name="${applicationId}.wxapi.WXEntryActivity"
编译会通不过。
我现在只能禁用掉其他微信支付的 回调页面。

**Comment by adger-me** [comment]
请问这个怎么解决呢

**Comment by JarvanMo** [comment]
@adger-me  fork一份然后删除WxEntryActivity也可以
