### ISSUE TITLE
接入应用宝, 微信SDK冲突

### ISSUE THREAD

**Issue by sxd1140** [OpenFlutter/fluwx#277]
之前用fluwx微信登录支付和分享都成功了,现在要接入应用宝的`YSDK`, 里面带了`微信的SDK`.

应该可以删除fluwx带的`微信SDK` 来解决,但是如果下一个`平台SDK`不带`微信SDK`而需要`fluwx带的微信SDK`,那就每次编译都要手动修改?

请问这种情况应该怎么处理比较好?

**Comment by JarvanMo** [comment]
你可以自己fork本项目啊
