### ISSUE TITLE
java.lang.IllegalStateException:Expected Android API level 21+ but was 19

### ISSUE THREAD

**Issue by yy1300326388** [OpenFlutter/fluwx#278]
**Describe the bug**
用户在 Android 4.4.4 设备上出现了崩溃，我查阅了相关资料是[ okhttp ](https://github.com/square/okhttp/issues/4622#issuecomment-465447196)导致的。

1、会考虑兼容 Android 5.0 一下的设备吗？
2、哪些地方使用到了okhttp ？是否可以放在非初始化的时候，目前错误是在初始化的时候？

- https://medium.com/square-corner-blog/okhttp-3-13-requires-android-5-818bb78d07ce

** Log **

```
java.lang.ExceptionInInitializerError:
--
2 h.y.<init>()
3 ......
4 Caused by:
5 java.lang.IllegalStateException:Expected Android API level 21+ but was 19
6 h.i0.h.a$c.a()
7 h.i0.h.e$a.c()
8 h.i0.h.e$a.a()
9 h.i0.h.e.<clinit>()
10 h.y.<init>()
11 h.y$a.a()
12 com.jarvan.fluwx.c.h$a.b()
13 com.jarvan.fluwx.c.h$a.a()
14 kotlinx.coroutines.y1.b.a()
15 kotlinx.coroutines.d.a()
16 kotlinx.coroutines.c.a()
17 com.jarvan.fluwx.c.h.a()
18 com.jarvan.fluwx.c.c.a()
19 com.jarvan.fluwx.c.c$a.b()
20 g.w.k.a.a.a()
21 kotlinx.coroutines.k0.run()
22 kotlinx.coroutines.z1.a.a()
23 kotlinx.coroutines.z1.a$b.a()
24 kotlinx.coroutines.z1.a$b.f()
25 kotlinx.coroutines.z1.a$b.run()


```

**To Reproduce**

微信登录

**Which version of Fluwx do you use?**
`fluwx_no_pay: 2.1.1`

**Which device do you run on**
`小米 MI PAD Android 4.4.4,level 19`

**Which Flutter do you use?**
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)
```

**Comment by JarvanMo** [comment]
不考虑------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Zero&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月3日(星期四) 中午11:53
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] java.lang.IllegalStateException:Expected Android API level 21+ but was 19 (#278)

**Comment by yy1300326388** [comment]
好的，那我先关闭了
