### ISSUE TITLE
ios  swift  版本微信分享 一直链接 然后返回APP 无法正常吊起微信分享

### ISSUE THREAD

**Issue by Lshaoxun** [OpenFlutter/fluwx#286]
后台打印的错误日志为:PBItemCollectionServicer connection disconnected.

**Comment by JarvanMo** [comment]
去问微信官方------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Lshaoxun&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月16日(星期三) 下午4:24
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] ios  swift  版本微信分享 一直链接 然后返回APP 无法正常吊起微信分享 (#286)

**Comment by Lshaoxun** [comment]
请问下ios原生中集成了flutter代码,倒入什么头文件可以引入 WXApi类吗?

**Comment by judastatus** [comment]
> 请问下ios原生中集成了flutter代码,导入什么头文件可以引入 WXApi类吗?

你好，你解决这个问题了吗？

**Comment by JarvanMo** [comment]
你的universial link对吗、
