### ISSUE TITLE
flutter工程嵌入到原生iOS工程,微信分享 一直链接 然后返回APP 无法正常吊起微信分享

### ISSUE THREAD

**Issue by Lshaoxun** [OpenFlutter/fluwx#287]
universalLink配置是没问题的,因为我用原生代码接入分享sdk的时候是能够分享正常的.链接只会出现一次,并且后面都不会出现.
但是调用fluwx的时候每次都是出现链接界面,并且自动返回到了app中,调用shareToWeChat方法分享,返回的结果是true,
后台重复答应错误:
 Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x2830cba20, domain=1, instance=1>
我appdelegate中下面的3个方法全部没有写:
-(BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url 
-(BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable restorableObjects))restorationHandler)

**Comment by Lshaoxun** [comment]
flutter直接在xcode中编译分享正常,flutter以嵌入的方式,嵌入到原生的ios工程中,分享出现上面描述的问题

**Comment by lalaMiao** [comment]
找到原因了吗, 我也是.,但是没任何报错

**Comment by Lshaoxun** [comment]
找了好久了,一直没有找到原因..

**Comment by lalaMiao** [comment]
我找到原因了,  是冲突了, 我另外一个 插件里也重写了上面三个方法,  你看看你项目里有没有其他插件也重写了上面三个方法. 去掉或者 改一改 应该就可以了

**Comment by lalaMiao** [comment]
看了下插件文档, 是按注册顺序调用所有为回调注册的插件，直到某些插件处理请.   在工程里吧这个插件放在第一个注册,就可以了
