### ISSUE TITLE
安装fluwx 2.3.0后运行失败

### ISSUE THREAD

**Issue by zhuiyidanfei** [OpenFlutter/fluwx#288]
Execution failed for task ':fluwx:compileDebugKotlin'.

**Comment by godghost** [comment]
modify kotlin version in  **_android/build.gradle_** solve my problem

```
 buildscript {
-    ext.kotlin_version = '1.3.50'
+    ext.kotlin_version = '1.4.10'
     repositories {
         google()
         jcenter()
```

**Comment by zhuiyidanfei** [comment]
thank you

**Comment by heqikang** [comment]
> modify kotlin version in **_android/build.gradle_** solve my problem
> 
> ```
>  buildscript {
> -    ext.kotlin_version = '1.3.50'
> +    ext.kotlin_version = '1.4.10'
>      repositories {
>          google()
>          jcenter()
> ```

我改了对应的版本还是不行

**Comment by godghost** [comment]
> > modify kotlin version in **_android/build.gradle_** solve my problem
> > ```
> >  buildscript {
> > -    ext.kotlin_version = '1.3.50'
> > +    ext.kotlin_version = '1.4.10'
> >      repositories {
> >          google()
> >          jcenter()
> > ```
> 
> 我改了对应的版本还是不行

"flutter run -v" to see the detail error log

**Comment by Tangshenghao1** [comment]
> > 修改**_android / build.gradle中的_**kotlin版本解决我的问题
> > ```
> >  buildscript {
> > -    ext.kotlin_version = '1.3.50'
> > +    ext.kotlin_version = '1.4.10'
> >      repositories {
> >          google()
> >          jcenter()
> > ```
> 
> 我改了对应的版本还是不行

upgrade gradle
https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle

**Comment by JarvanMo** [comment]
那就是你没改对。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;TangShengHao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月10日(星期二) 中午11:53
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安装fluwx 2.3.0后运行失败 (#288)
