### ISSUE TITLE
安装后真机运行报错,模拟器可以

### ISSUE THREAD

**Issue by heqikang** [OpenFlutter/fluwx#289]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluwx:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1

IDE: Android studio 4.0.1
pubspec.yaml删除fluwx配置后真机运行正常

**Comment by heqikang** [comment]
把ext.kotlin_version = '1.3.50'更改为ext.kotlin_version = '1.3.72'后报错


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by JarvanMo** [comment]
.dex file cannot exceed 64K，百度去吧

**Comment by JarvanMo** [comment]
这是一个android原生问题，和fluwx关系不是很大。
