### ISSUE TITLE
你好，我用VSCode 跑在真机上面 授权登录一直掉不起来微信

### ISSUE THREAD

**Issue by 370966584** [OpenFlutter/fluwx#29]
![ed69b28f-74a6-4508-ba64-5a5ff6cd5601](https://user-images.githubusercontent.com/26058251/48595039-17e03e80-e98e-11e8-847c-5183c925d6a8.png)
![47a30ba1-002d-4177-9649-a5eb9a74437a](https://user-images.githubusercontent.com/26058251/48595108-583fbc80-e98e-11e8-809e-a9b55868da0d.png)
这是签名文件
![43d9b1a9-efdb-462d-a092-27b057bc6314](https://user-images.githubusercontent.com/26058251/48595240-c6847f00-e98e-11e8-8fbc-1b18768c2788.png)
![8140e5e3-05e8-4624-8e34-a78409bec94b](https://user-images.githubusercontent.com/26058251/48595260-dd2ad600-e98e-11e8-9b4b-beaf007f6a74.png)

信息，签名也对 请问下这可能是哪的问题，我是做iOS的不是很懂安卓

**Comment by JarvanMo** [comment]
debug 和release的签名默认不一样。不会的更改的话，请用release测试

**Comment by 370966584** [comment]
> debug 和release的签名默认不一样。不会的更改的话，请用release测试

我已经设置签名一样了啊

**Comment by 370966584** [comment]
又可以了
