### ISSUE TITLE
weChatResponseEventHandler 监听事件不能销毁和重复监听的问题

### ISSUE THREAD

**Issue by DNetORM** [OpenFlutter/fluwx#290]
class _LoginPageState extends State<LoginPage> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    weChatResponseEventHandler.distinct((a, b) => a == b).listen((res) async {
      if (res is WeChatAuthResponse) {
        code = res.code;
        print(code);

我登陆页面设置了监听
第一次登陆的时候没什么问题，然后我关闭了登陆页面，不登录，再打开登陆页面，就会监听了两次，
原因，页面关闭的时候没有销毁掉监听导致的，从而导致了重复的监听执行
这个bug还是比较严重的，建议作者尽快修复
![image](https://user-images.githubusercontent.com/32695729/94829588-41e56180-043d-11eb-8e15-463b426ce171.png)

**Comment by DNetORM** [comment]
页面关闭的时候 提供移除监听的方法调用

**Comment by sec7et** [comment]
listen方法会返回一个StreamSubscription<BaseWeChatResponse>对象啊，声明个变量持有它，在dispose()方法里，_flag?.cancel()就好了

**Comment by 3111279132** [comment]
我也发现了同样的问题 demo文档没有说明

**Comment by JarvanMo** [comment]
这个问题已经被问了一万次，而且文档里还有------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yiJun&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月17日(星期二) 下午2:55
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] weChatResponseEventHandler 监听事件不能销毁和重复监听的问题 (#290)
