### ISSUE TITLE
iOS微信分享报错：[SendMessageToWXReq requestWithText:OrMediaMessage:bText:InScene:]: unrecognized selector sent to class 0x100c2a660

### ISSUE THREAD

**Issue by niteapps** [OpenFlutter/fluwx#291]
ios版，不管是分享文字还是图片，都报错[SendMessageToWXReq requestWithText:OrMediaMessage:bText:InScene:]: unrecognized selector sent to class 0x100c2a660。有人知道怎么解决吗？

**Comment by JarvanMo** [comment]
应该是有的字段传null了
