### ISSUE TITLE
小米10，检测不到微信

### ISSUE THREAD

**Issue by tianzhilan0** [OpenFlutter/fluwx#293]
```
    var result = await isWeChatInstalled;
    if (result) {
      fluwx
          .sendWeChatAuth(
              scope: "snsapi_userinfo", state: "wechat_sdk_demo_test")
          .then((data) {
        LogUtil.log(data);
      });
    } else {
      //未安装微信
      EasyLoading.showToast('未安装微信或微信版本太低');
    }
```
小米10 检测不到微信，微信是最新版本，有人遇到过吗？

**Comment by JarvanMo** [comment]
这个问题去问微信官方，都是调用的SDK

**Comment by lizhuoyuan** [comment]
是android11吗？

**Comment by JarvanMo** [comment]
Android 11的似乎是要增加Query Package权限

**Comment by zhangruiyu** [comment]
https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/Android.html#jump2

**Comment by zhangruiyu** [comment]
放个文档 帮助后来人

**Comment by cdk8s-zelda** [comment]
> https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/Android.html#jump2

感谢朋友！
红米K40Pro
miui 12.5
遇到同样问题，已经解决。

其中官网文档第二点文字有点小，大家注意记得细看
