### ISSUE TITLE
吊起被双开的微信，拿不到回调。

### ISSUE THREAD

**Issue by Menusyes** [OpenFlutter/fluwx#295]
系统：Android MIUI 12.0.13
Flutter：1.22.0
插件版本：2.4.0

具体操作如下：
- 吊起微信
- 系统弹窗选择双开的微信（此时拿到成功打开微信的回调）
- 但系统弹窗点取消后监听不到此操作回调

因支付前有阻止操作的Loading弹窗，使用WillPopScope拦截了返回操作，拿不到回调导致弹窗无法关闭，只能杀进程。

我该如何处理？

**Comment by JarvanMo** [comment]
双开微信和SDK无关。微信SDK本身也没有支持双开。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Menus丶&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月28日(星期三) 上午10:59
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 吊起被双开的微信，拿不到回调。 (#295)

**Comment by JarvanMo** [comment]
微信双开是os的事------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Menus丶&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月28日(星期三) 上午10:59
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 吊起被双开的微信，拿不到回调。 (#295)

**Comment by JarvanMo** [comment]
微信双开是OS的事------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Menus丶&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月28日(星期三) 上午10:59
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 吊起被双开的微信，拿不到回调。 (#295)

**Comment by Menusyes** [comment]
> 双开微信和SDK无关。微信SDK本身也没有支持双开。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;Menus丶&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年10月28日(星期三) 上午10:59 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[OpenFlutter/fluwx] 吊起被双开的微信，拿不到回调。 (#295)

好的。
