### ISSUE TITLE
小程序打开 App 停留在了WXEntryActivity 页面，出现白屏幕

### ISSUE THREAD

**Issue by yy1300326388** [OpenFlutter/fluwx#297]
**Describe the bug**
小程序打开 App 停留在了WXEntryActivity 页面，出现白屏幕

**To Reproduce**
从小程序打开 App 出现白屏
![image](https://user-images.githubusercontent.com/8764899/97523512-779a4d80-19dd-11eb-9596-8252269de92f.png)
然后通过 ` adb shell dumpsys window | grep mCurrentFocus` 获取到当前 Activity 是
```
 mCurrentFocus=Window{701e929 u0 com.banjixiaoguanjia.app/com.banjixiaoguanjia.app.wxapi.WXEntryActivity}
```

**Which version of Fluwx do you use?**
fluwx_no_pay: 2.1.1

**Which device do you run on**
华为 p40 OS is Android 10.

**Which Flutter do you use?**

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)
```

**Comment by JarvanMo** [comment]
没记错的话，这是一个微信SDK的bug.试试在FlutterActivity的manifest加上
`<action android:name="${applicationId}.FlutterActivity"/>`

**Comment by yy1300326388** [comment]
> 没记错的话，这是一个微信SDK的bug.试试在FlutterActivity的manifest加上
> `<action android:name="${applicationId}.FlutterActivity"/>`

我试试

**Comment by yy1300326388** [comment]
> 没记错的话，这是一个微信SDK的bug.试试在FlutterActivity的manifest加上
> `<action android:name="${applicationId}.FlutterActivity"/>`

可以非常棒

**Comment by JarvanMo** [comment]
这个问题在3.4.0修复了。具体请参看文档以及demo。
