### ISSUE TITLE
ios分享微信好友/朋友圈，缩略图无法显示

### ISSUE THREAD

**Issue by zlfnn** [OpenFlutter/fluwx#301]
ios分享到微信，无法显示缩略图，而安卓没有问题
fluwx版本^2.4.0
flutter版本1.22.1

**Comment by goodxianping** [comment]
好像是分享的图片链接有中文等字符

**Comment by goodxianping** [comment]
对图片地址进行encode一下，如：
WeChatImage.network(Uri.encodeFull(img));

**Comment by zlfnn** [comment]
已经解决了，是ios没有配置允许加载http图片
