### ISSUE TITLE
Android 11分享图片失败

### ISSUE THREAD

**Issue by larryluo123** [OpenFlutter/fluwx#305]
**Android 11**要求使用FileProdider的方式分享图片，FluwxShareHandlerEmbedding这个文件，else那个地方使用的是分享byte

`private fun shareImage(call: MethodCall, result: MethodChannel.Result) {
        launch {
            val map: Map<String, Any> = call.argument("source") ?: mapOf()
            val sourceImage = WeChatFile.createWeChatFile(map, assetFileDescriptor)
            val thumbData = readThumbnailByteArray(call)

            val sourceByteArray = sourceImage.readByteArray()
            val imageObject = when {
                sourceByteArray.isEmpty() -> {
                    WXImageObject()
                }
                sourceByteArray.size > 500 * 1024 -> {
                    WXImageObject().apply {
                        if (supportFileProvider && targetHigherThanN) {
                            setImagePath(getFileContentUri(sourceByteArray.toCacheFile(context, sourceImage.suffix)))
                        } else {
                            if (ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED) {
                                setImagePath(sourceByteArray.toExternalCacheFile(context, sourceImage.suffix)?.absolutePath)
                            } else {
                                permissionHandler?.requestStoragePermission()
                            }
                        }
                    }
                }
                else -> {
                    WXImageObject(sourceByteArray)
                }
            }
            val msg = WXMediaMessage()
            msg.mediaObject = imageObject
            msg.thumbData = thumbData

            msg.description = call.argument(keyDescription)

            val req = SendMessageToWX.Req()
            setCommonArguments(call, req, msg)
            req.message = msg

            sendRequestInMain(result, req)
        }
    }`

改成这样能分享成功
`sourceByteArray.size > 500 * 1024 -> {
                    WXImageObject().apply {
                        if (supportFileProvider && targetHigherThanN) {
                            setImagePath(getFileContentUri(sourceByteArray.toCacheFile(context, sourceImage.suffix)))
                        } else {
                            if (ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED) {
                                setImagePath(sourceByteArray.toExternalCacheFile(context, sourceImage.suffix)?.absolutePath)
                            } else {
                                permissionHandler?.requestStoragePermission()
                            }
                        }
                    }
                }
                else -> {
//                    WXImageObject(sourceByteArray)
                    //把上面的拿下来
                    WXImageObject().apply {
                        if (supportFileProvider && targetHigherThanN) {
                            setImagePath(getFileContentUri(sourceByteArray.toCacheFile(context, sourceImage.suffix)))
                        } else {
                            if (ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED) {
                                setImagePath(sourceByteArray.toExternalCacheFile(context, sourceImage.suffix)?.absolutePath)
                            } else {
                                permissionHandler?.requestStoragePermission()
                            }
                        }
                    }
                }`

希望大佬升级一下插件

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.5 19F101, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

**Comment by larryluo123** [comment]
https://developers.weixin.qq.com/community/develop/doc/000ce64ea40e1840803b142ca56000?_at=1605076062449

**Comment by JarvanMo** [comment]
您可以PR以修复此问题。谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月11日(星期三) 下午2:59
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

**Comment by larryluo123** [comment]
> 您可以PR以修复此问题。谢谢------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月11日(星期三) 下午2:59 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

好的 大佬 已提交

**Comment by JarvanMo** [comment]
没收到PR------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月11日(星期三) 晚上6:34
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

**Comment by larryluo123** [comment]
> 没收到PR------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月11日(星期三) 晚上6:34 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

没有注意点提交按钮，抱歉，现在好了

**Comment by larryluo123** [comment]
你好，pub上什么时候更新新版本 @JarvanMo

**Comment by JarvanMo** [comment]
得下周，目前没有环境------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月12日(星期四) 中午11:38
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

**Comment by JarvanMo** [comment]
现在可以通过依赖git的方式使用------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月12日(星期四) 中午11:38
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

**Comment by larryluo123** [comment]
> 得下周，目前没有环境------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;larryluo123&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月12日(星期四) 中午11:38 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] Android 11分享图片失败 (#305)

好 谢谢了

**Comment by JarvanMo** [comment]
发布了2.4.1

**Comment by larryluo123** [comment]
已修护android 11分享图片问题
