### ISSUE TITLE
微信登录功能没法使用

### ISSUE THREAD

**Issue by iecanfly** [OpenFlutter/fluwx#308]
**To Reproduce**
fluwx.sendWeChatAuth(scope: "snsapi_userinfo", state: "wechat_sdk_demo_test").then((data) {});
这个代码没有任何反应（不打开WeChat）。

**Which version of Fluwx do you use?**
2.3.0

**Which device do you run on**
iOS 14.1 / 14.2

**Which Flutter do you use?**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H15, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

**Comment by JarvanMo** [comment]
universial link什么的都配置了吗
