### ISSUE TITLE
调用sendWeChatAuth方法成功后，只返回一个true；

### ISSUE THREAD

**Issue by chinafelix** [OpenFlutter/fluwx#311]
final success = await registerWxApi(appId: Utils.appId);
if(success) {
     final **data** = sendWeChatAuth(scope: "snsapi_userinfo");
}

返回的data是true；无法拿到code；那么在用户点击统一之后，该怎么进行下一步呢？

**Comment by JarvanMo** [comment]
看文档------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;tourism&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月20日(星期五) 下午5:10
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 调用sendWeChatAuth方法成功后，只返回一个true； (#311)

**Comment by chinafelix** [comment]
github的文档就一句调用，没有别的了；

**Comment by JarvanMo** [comment]
仔细看，除了文档不还有demo。不回。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;tourism&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月20日(星期五) 下午5:16
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 调用sendWeChatAuth方法成功后，只返回一个true； (#311)
