### ISSUE TITLE
问一下：如果只想接入微信登录，支付等其他的东西是不是都集成了？这样iOS审核能过？

### ISSUE THREAD

**Issue by fuyunmanbu** [OpenFlutter/fluwx#312]
**Describe the bug**

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

**Comment by JarvanMo** [comment]
有不带支付的版本。
