### ISSUE TITLE
如何获取微信通过<wx-open-launch-app>开标签，打开App时所携带的extinfo等信息

### ISSUE THREAD

**Issue by weoil** [OpenFlutter/fluwx#316]
**Describe the bug**
微信内H5页面通过用户点击微信开放标签<wx-open-launch-app>跳转App，在这个插件中如何获取参数？

[https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html)

**Comment by JarvanMo** [comment]
不知道什么意思。这是原生app的库。

**Comment by weoil** [comment]
啊，就是那个OpenSDK现在新加了一个功能，是可以在微信浏览器中通过一个开放标签唤醒App，可以传递自定义参数，会调用onReq，可以从这里取到相应的参数啥的，将来会有计划更新支持这个吗？

```
	@Override
	public void onReq(BaseReq req) {
	   //获取开放标签传递的extinfo数据逻辑
		if(req.getType() == ConstantsAPI.COMMAND_SHOWMESSAGE_FROM_WX && req instanceof ShowMessageFromWX.Req) {
			ShowMessageFromWX.Req showReq = (ShowMessageFromWX.Req) req;
			WXMediaMessage mediaMsg = showReq.message;
			String extInfo = mediaMsg.messageExt;
			//Handle...
		}
```

关于这个的相关文档在[这里](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/APP_GET_EXTINF.html)

**Comment by JarvanMo** [comment]
有拉起小程序的功能，自行看文档。

**Comment by weoil** [comment]
嗯确实可以拉起小程序，但是反过来 小程序拉起App的时候  在源码的[FluwxWXEntryActivity.kt](https://github.com/OpenFlutter/fluwx/blob/dd2597271d1022ead1526b1aac7e5d13d358d8de/android/src/main/kotlin/com/jarvan/fluwx/wxapi/FluwxWXEntryActivity.kt#L59)里面没有转发参数，虽然可以正常打开App但是获取不到baseReq中携带的参数。

```
 override fun onReq(baseReq: BaseReq) { 
        // FIXME: 可能是官方的Bug，从微信拉起APP的Intent类型不对，无法跳转回Flutter Activity
        // 稳定复现场景：微信版本为7.0.5，小程序SDK为2.7.7
        if (baseReq.type == 4) {
            // com.tencent.mm.opensdk.constants.ConstantsAPI.COMMAND_SHOWMESSAGE_FROM_WX = 4
            startSpecifiedActivity()
        }
```

**Comment by JarvanMo** [comment]
上面这段代码是修改无法跳转到FlutterActivity的

**Comment by JarvanMo** [comment]
你要转发参数你可以自行PR解决。

**Comment by weoil** [comment]
好的谢谢

**Comment by JarvanMo** [comment]
而且我也没有可测试这种功能的环境。

**Comment by weoil** [comment]
嗯嗯，主要是ios的Objective-C看着有点懵不知道怎么兼容，之后有时间学一下语法试试能不能加上。

**Comment by JarvanMo** [comment]
你可以先加上android的，ios我看看能不能加上

**Comment by JarvanMo** [comment]
Duplicate of #216

**Comment by yy1300326388** [comment]
Android 打开白屏的问题我已经解决了

**Comment by yy1300326388** [comment]
目前冷启动还是无法获取参数，热启动可以获取到参数，已经解决了我
