### ISSUE TITLE
Execution failed for task ':fluwx:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by wmslei** [OpenFlutter/fluwx#324]

**Comment by wmslei** [comment]
Execution failed for task ':fluwx:compileDebugKotlin'.

**Comment by wmslei** [comment]
.pub-cache/hosted/pub.flutter-io.cn/fluwx-2.5.0/android/src/main/kotlin/com/jarvan/fluwx/handlers/FluwxRequestHandler.kt: (36, 52): Expecting an argument

**Comment by JarvanMo** [comment]
Kotlin 1.4.20

**Comment by wmslei** [comment]
> Kotlin 1.4.20

Thanks.

**Comment by nickzhuo** [comment]
我是stable通道的kotlin1.4.21也过不了build
