### ISSUE TITLE
微信分享后闪退，提示找不到 WXEntryActivity 

### ISSUE THREAD

**Issue by judastatus** [OpenFlutter/fluwx#326]
Caused by: java.lang.ClassNotFoundException: Didn't find class "XXXX.wxapi.WXEntryActivity" on path: DexPathList[[zip file "/data/app/com.xingerzhi.zhiya2-PPNTlZlEOLE3Jbwvj4xZxw==/base.apk", zip file "/system/framework/org.apache.http.legacy.jar"],nativeLibraryDirectories=[/data/app/XXXX-PPNTlZlEOLE3Jbwvj4xZxw==/lib/arm64, /data/app/XXXX-PPNTlZlEOLE3Jbwvj4xZxw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]

**Comment by judastatus** [comment]
android设备， fluwx 版本号2.3.0， 打开微信分享可以成功，然后返回app时候，就闪退
看了一些其他issue，代码里也添加里  <action android:name="${applicationId}.FlutterActivity"/>

**Comment by judastatus** [comment]
![WechatIMG4686](https://user-images.githubusercontent.com/15098424/102302712-9310e600-3f94-11eb-9003-2b48e655b831.png)

**Comment by JarvanMo** [comment]
```
     <activity-alias
            android:name="${applicationId}.wxapi.WXEntryActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:targetActivity="com.jarvan.fluwx.wxapi.FluwxWXEntryActivity"
            android:taskAffinity="${applicationId}"
            android:theme="@style/DisablePreviewTheme">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:scheme="sdksample" />
            </intent-filter>
        </activity-alias>
```
正常来说是没这个问题的。

**Comment by judastatus** [comment]
> ```
>      <activity-alias
>             android:name="${applicationId}.wxapi.WXEntryActivity"
>             android:exported="true"
>             android:launchMode="singleTop"
>             android:targetActivity="com.jarvan.fluwx.wxapi.FluwxWXEntryActivity"
>             android:taskAffinity="${applicationId}"
>             android:theme="@style/DisablePreviewTheme">
> 
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <data android:scheme="sdksample" />
>             </intent-filter>
>         </activity-alias>
> ```
> 
> 正常来说是没这个问题的。

你的这个是  /Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluwx-2.3.0/android/src/main/AndroidManifest.xml 里的配置文件吧，  项目目录中 android/app/src/main/AndroidManifest.xml 这个文件还需要额外配置什么吗？ 
还有，还需要手动创建 WXEntryActivity 类吗？

**Comment by JarvanMo** [comment]
不需要------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;judastatus&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月16日(星期三) 中午1:57
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 微信分享后闪退，提示找不到 WXEntryActivity  (#326)

**Comment by judastatus** [comment]
> 不需要------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;judastatus&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年12月16日(星期三) 中午1:57 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 微信分享后闪退，提示找不到 WXEntryActivity (#326)

项目目录中 android/app/src/main/AndroidManifest.xml 这个文件还需要额外配置什么吗？

**Comment by JarvanMo** [comment]
说了，不需要------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;judastatus&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月16日(星期三) 中午1:58
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 微信分享后闪退，提示找不到 WXEntryActivity  (#326)

**Comment by judastatus** [comment]
> 说了，不需要------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;judastatus&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年12月16日(星期三) 中午1:58 收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;; 抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 微信分享后闪退，提示找不到 WXEntryActivity (#326)

好的，谢谢

**Comment by judastatus** [comment]
往复尝试了好多次，手动创建了 WXEntryActivity 文件，终于可以了

**Comment by Leo-Shen** [comment]
> 往复尝试了好多次，手动创建了 WXEntryActivity 文件，终于可以了

@judastatus 请问你是在fluwx的插件里手动创建WXEntryActivity，还是在自己的项目里？

**Comment by judastatus** [comment]
> > 往复尝试了好多次，手动创建了 WXEntryActivity 文件，终于可以了
> 
> @judastatus 请问你是在fluwx的插件里手动创建WXEntryActivity，还是在自己的项目里？

自己的项目里
app/src/main/kotlin/com/XXX/XXX/wxapi/WXEntryActivity

`
package com.XXX.XXX.wxapi
import com.jarvan.fluwx.wxapi.FluwxWXEntryActivity

/** 微信客户端回调activity示例  */
class WXEntryActivity : FluwxWXEntryActivity() {

}`

**Comment by Leo-Shen** [comment]
> > > 往复尝试了好多次，手动创建了 WXEntryActivity 文件，终于可以了
> > 
> > 
> > @judastatus 请问你是在fluwx的插件里手动创建WXEntryActivity，还是在自己的项目里？
> 
> 自己的项目里
> app/src/main/kotlin/com/XXX/XXX/wxapi/WXEntryActivity
> 
> `
> package com.XXX.XXX.wxapi
> import com.jarvan.fluwx.wxapi.FluwxWXEntryActivity
> 
> /** 微信客户端回调activity示例 */
> class WXEntryActivity : FluwxWXEntryActivity() {
> 
> }`

好的，谢谢！
