### ISSUE TITLE
原生+flutter开发，使用插件，分享崩溃

### ISSUE THREAD

**Issue by Alzzzz** [OpenFlutter/fluwx#327]
**Describe the bug**
native嵌入flutter开发，一开始的闪屏页和登录页面都是native，但是此时flutterboost进行初始化插件，不会走onAttackToActivity，导致context为空，发起请求时报初始化失败直接崩溃退出

**Comment by Alzzzz** [comment]
修改办法，是在onAttachToEngine的时候也设置一下Handler的setContext

**Comment by JarvanMo** [comment]
此类问题请PR。
