### ISSUE TITLE
ios端微信支付无法调起微信

### ISSUE THREAD

**Issue by taizhenhua1987** [OpenFlutter/fluwx#332]
**环境**
fluwx: 2.5.0
Xcode: 12

**错误描述**
无法调起微信，无响应。Xcode控制台报错信息：
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'invokeMethod' was called on null

**补充**
* universalLink正常，可以在Safari调起应用
* URL scheme已经添加
* LSApplicationQueriesSchemes已经添加weixin 和weixinULAPI

**Comment by JarvanMo** [comment]
支付参数有问题，fluwx肯定没有问题。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;taizhenhua&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月7日(星期四) 上午10:30
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] ios端微信支付无法调起微信 (#332)
