### ISSUE TITLE
华为P30 pro 手机，微信分身，没有提示选择微信？

### ISSUE THREAD

**Issue by wskkhn-hezhong** [OpenFlutter/fluwx#333]
在使用微信分身时，华为的p30 Pro  10.0的系统，微信分身，在点击支付的时候，不提示选择微信，直接就跳主微信进行支付了

**Comment by JarvanMo** [comment]
这种问题不要在这里问，和fluwx一点关系都没有------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;he&amp;nbsp;zhong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月13日(星期三) 下午4:44
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 华为P30 pro 手机，微信分身，没有提示选择微信？ (#333)

**Comment by ichukai** [comment]
https://blog.csdn.net/u010816580/article/details/109391726　降级SDK即可

**Comment by JarvanMo** [comment]
作为微信SDK在Flutter上的实现，不会对微信SDK进行降级操作。fluwx追随微信官方sdk，有需要的用户可以自行降级。
