### ISSUE TITLE
Back-end (JVM) Internal error: wrong bytecode generated   @Lorg/jetbrains/annotations/Nullable;() 

### ISSUE THREAD

**Issue by agavrel** [OpenFlutter/fluwx#334]
**Describe the bug**
Cannot compile a clean project following the Example page on flutter.

**To Reproduce**
I took the example and added empty classes the following way:
```
import 'package:flutter/material.dart';

class SendAuthPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Which version of Fluwx do you use?**
Using latest version 2.5.0+1.

**Which device do you run on**
Pixel 4 XL API 30 (emulated), on a Linux OS.

**Which Flutter do you use?**
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.296, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)
```

**Comment by JarvanMo** [comment]
Can you show more error log? Did you try the null-safety version ` 3.0.0-nullsafety.2`?
