### ISSUE TITLE
微信支付回调

### ISSUE THREAD

**Issue by a1156552185** [OpenFlutter/fluwx#336]
responseFromPayment 这个方法是已经被移除了吗

**Comment by JarvanMo** [comment]
是的，具体可以看demo------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;a1156552185&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月20日(星期三) 下午5:50
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 微信支付回调 (#336)
