### ISSUE TITLE
iOS微信分享提示未验证应用 

### ISSUE THREAD

**Issue by youwuxiangsheng** [OpenFlutter/fluwx#337]
![image](https://user-images.githubusercontent.com/14975026/105964107-bb742000-60bc-11eb-8f98-0244807e8067.png)

**Comment by JarvanMo** [comment]
www.baidu.com ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zjc&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月27日(星期三) 下午4:29
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] iOS微信分享提示未验证应用  (#337)
