### ISSUE TITLE
fluwx 和 flutter_isolate 一起使用时，会导致 dart 层接受不到 native 通过 methodChannel 发出的消息

### ISSUE THREAD

**Issue by zhshijie** [OpenFlutter/fluwx#338]
**Describe the bug**
fluwx 和 flutter_isolate 一起使用时，会导致 dart 层接受不到 native 通过 methodChannel 发出的消息

**To Reproduce**
项目中同时引入 fluwx 和 flutter_isolate，在 dart 层调用 FlutterIsolate.spawn，然后就会发现 dart 接受不到 fluwx 的回调了，好像是因为 flutter_isolate 会导致 fluwx 插件的 registerWithRegistrar 多次被调用，重复生成多个 channel 导致的。尝试将 channel 作为一个全局变量，只初始化一次就可以解决该问题，希望官方可以关注后解决下，谢谢。

**Which version of Fluwx do you use?**
fluwx_no_pay: ^2.4.0

**Which device do you run on**
iOS 14.2 iPhone12

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

**Comment by JarvanMo** [comment]
Plugin v1不再更新。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sky&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月29日(星期五) 下午2:18
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] fluwx 和 flutter_isolate 一起使用时，会导致 dart 层接受不到 native 通过 methodChannel 发出的消息 (#338)

**Comment by JarvanMo** [comment]
或者有愿意解决的可以PR。 注意no pay，还有no safety等分支------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sky&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月29日(星期五) 下午2:18
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] fluwx 和 flutter_isolate 一起使用时，会导致 dart 层接受不到 native 通过 methodChannel 发出的消息 (#338)

**Comment by fwh007** [comment]
Android端有类似的问题。
Fluwx和某些库一起使用时，FluwxPlugin会被多次调用，生成了多个channel，导致回调失败。

`W/FlutterJNI(12866): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.jarvanmo/fluwx. Response ID: 0`

已经提交PR，麻烦开发者留意下，十分感谢！
