### ISSUE TITLE
解决问题：no known class method for selector 'sendReq:'

### ISSUE THREAD

**Issue by caoyanglee** [OpenFlutter/fluwx#339]
2021年01年29日
插件对应的微信IOS Sdk代码，不能支持最新的ios Sdk导致提示
> no known class method for selector 'sendReq:'

的问题，需要在**FlutterNativePlugin**的`[WXApi sendReq:req];` **改为** `[WXApi sendReq:req completion:nil];`

**Comment by JarvanMo** [comment]
麻烦PR。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;你需要一台永动机&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月29日(星期五) 下午2:24
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 解决问题：no known class method for selector &#39;sendReq:&#39; (#339)

**Comment by caoyanglee** [comment]
好的！
