### ISSUE TITLE
iOS端微信支付回调方法没走。

### ISSUE THREAD

**Issue by AccomPy** [OpenFlutter/fluwx#340]

**Comment by JarvanMo** [comment]
麻烦查找以前的issue和readme.

**Comment by judastatus** [comment]
> _No description provided._

你解决了吗

**Comment by JarvanMo** [comment]
插件肯定没有问题，别乱重写app delegate，确保各种配置都配置正确。排查是不是其他插件引起的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月27日(星期四) 中午11:19
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] iOS端微信支付回调方法没走。 (#340)
