### ISSUE TITLE
fluwx-2.6.0+1 error

### ISSUE THREAD

**Issue by CocoaJerry** [OpenFlutter/fluwx#341]
fluwx-2.6.0+1/android/src/main/kotlin/com/jarvan/fluwx/handlers/FluwxRequestHandler.kt: (60, 51): The feature "trailing commas" is only available since language version 1.4
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':fluwx:compileReleaseKotlin'.                
> Compilation error. See log for more details                           
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by JarvanMo** [comment]
Kotlin 1.4.10 以上------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jerry&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月7日(星期天) 晚上7:05
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] fluwx-2.6.0+1 error (#341)

**Comment by CocoaJerry** [comment]
抱歉没注意，加新的插件自动更新了

**Comment by JarvanMo** [comment]
先升级解决吧，等有时间我改一个代码。

**Comment by flytrap** [comment]
意思是要把Kotlin的版本降下来才能用？
