### ISSUE TITLE
使用sendWeChatAuth 方法，ios 和 android 授权页面不一样

### ISSUE THREAD

**Issue by yichengzou** [OpenFlutter/fluwx#346]
ios的授权形式是弹窗的形式 
![WechatIMG44](https://user-images.githubusercontent.com/11916879/110059451-36f17d00-7d9f-11eb-849d-ec573ee72348.jpeg)
andorid的为
<img width="413" alt="WechatIMG1848" src="https://user-images.githubusercontent.com/11916879/110059683-a49da900-7d9f-11eb-9f39-114887ec33fe.png">

🙏

**Comment by JarvanMo** [comment]
这个你不应该去问腾讯么？？？？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yichengzou&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 上午10:44
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 使用sendWeChatAuth 方法，ios 和 android 授权页面不一样 (#346)
