### ISSUE TITLE
微信分身 分享网络图片到朋友圈 打开不了微信

### ISSUE THREAD

**Issue by zhengxiangke** [OpenFlutter/fluwx#347]
错误信息如下
E/AndroidRuntime(17568): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mm/com.tencent.mm.plugin.sns.ui.SnsUploadUI}: java.lang.ClassCastException: java.io.FileNotFoundException cannot be cast to java.lang.SecurityException
E/AndroidRuntime(17568): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3476)
E/AndroidRuntime(17568): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3648)
E/AndroidRuntime(17568): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5505)
E/AndroidRuntime(17568): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5394)
E/AndroidRuntime(17568): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
E/AndroidRuntime(17568): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:117)
E/AndroidRuntime(17568): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:74)
E/AndroidRuntime(17568): 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
E/AndroidRuntime(17568): 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5464)
E/AndroidRuntime(17568): 	at android.app.ActivityThread.access$4300(ActivityThread.java:259)
E/AndroidRuntime(17568): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
E/AndroidRuntime(17568): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(17568): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(17568): 	at android.app.ActivityThread.main(ActivityThread.java:7586)
E/AndroidRuntime(17568): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17568): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(17568): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by JarvanMo** [comment]
分身的事，管不了。再一个这是微信SDK的错误------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月11日(星期四) 下午2:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 微信分身 分享网络图片 打开不了微信 (#347)

**Comment by zhengxiangke** [comment]
我用了微信的demo 用的是api 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:6.6.19'。分享图片到朋友圈用的是微信分身那个账号。是可以分享出去的
而你这边我用的是网络图片地址传递 是不会分享到微信分身的。应该是你android 内部代码 有待优化哦 内容如下 
    var model = WeChatShareImageModel(
      WeChatImage.network(_thumbnail),
      thumbnail: WeChatImage.network(_thumbnail),
      scene: type,
      title: _title,
      description: _description,
    );
    shareToWeChat(model);
