### ISSUE TITLE
在android/MainActivity.java中引用FluwxRequestHandler.handleRequestInfoFromIntent(intent);报错

### ISSUE THREAD

**Issue by huntrist** [OpenFlutter/fluwx#349]
在 android/MainActivity.java 中引用FluwxRequestHandler.handleRequestInfoFromIntent(intent);会报错

MainActivity.java 错误: 无法从静态上下文中引用非静态 方法 handleRequestInfoFromIntent(Intent)
    FluwxRequestHandler.handleRequestInfoFromIntent(intent);
                       ^

```
@Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    super.configureFlutterEngine(flutterEngine);
    Intent intent = getIntent();
    FluwxRequestHandler.handleRequestInfoFromIntent(intent);
  }
```

另外希望能有java版本的教程。谢谢~

fluwx 2.6.2
Flutter 1.22.5

**Comment by JarvanMo** [comment]
试试`FluwxRequestHandler.INSTANCE.handleRequestInfoFromIntent(intent)`

**Comment by huntrist** [comment]
感谢：
```FluwxRequestHandler.INSTANCE.handleRequestInfoFromIntent(intent)```
管用。
然而安卓端从微信打开依然进入白屏页。不知道是什么问题。

在console中可以看到以下消息：
```
I/MicroMsg.SDK.WXMediaMessage(22948): pathOldToNew, oldPath = com.tencent.mm.sdk.openapi.WXAppExtendObject
I/Fluwx   (22948): can't load meta-data handleWeChatRequestByFluwx
```
不知道是否相关。

另外请问：
 WXAPiHandler.setupWxApi("wxd930ea5d5a258f4f",this)
这一句，是不是在Flutter中调用了registerWxApi(appId: weChatAppId, universalLink: universalLink);
就不需要设置了？

麻烦帮忙。谢谢大神。

**Comment by JarvanMo** [comment]
不需要

**Comment by huntrist** [comment]
安卓端从微信打开依然进入白屏页。该如何处理呢？

**Comment by JarvanMo** [comment]
这个问题在3.4.0修复了。具体请参看文档以及demo。
