### ISSUE TITLE
iOS 小程序分享标题展示为title

### ISSUE THREAD

**Issue by charsunny** [OpenFlutter/fluwx#35]
FluwxShareHandler.m的第354行和355行，作者应该是忘记用key取map中内容了，直接传了key的值，麻烦修复一下，谢谢！
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1472820/50548687-3d01e580-0c8c-11e9-9384-23b480df2982.png">

**Comment by JarvanMo** [comment]
你可以发起个PR。

**Comment by charsunny** [comment]
> 你可以发起个PR。

好的，辛苦作者，这个库很棒。

**Comment by JarvanMo** [comment]
@charsunny 0.0.5 released
