### ISSUE TITLE
Flutter nullsafety warning

### ISSUE THREAD

**Issue by chachaxw** [OpenFlutter/fluwx#350]
flux-3.2.2-nullsafety.1 出现语法warning

```
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/fluwx-3.2.2-nullsafety.1/lib/src/wechat_file.dart:71:60: Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
      {"source": source, "schema": schema.index, "suffix": suffix ?? ""};
```

**Flutter Doctor**

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.3 20E5210c darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

**Comment by JarvanMo** [comment]
稍后修复，感谢。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月22日(星期一) 中午1:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] Flutter nullsafety warning (#350)
