### ISSUE TITLE
分享文件到微信 超过10M 报 MicroMsg.SDK.WXFileObject(10827): checkArgs fail, fileSize is too large

### ISSUE THREAD

**Issue by CoderFieYe** [OpenFlutter/fluwx#353]
**Describe the bug**

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.
华为 
**Which Flutter do you use?**
1.22
Run `flutter doctor` and paste the output here.

**Comment by JarvanMo** [comment]
这种问题请去咨询维修------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月31日(星期三) 下午3:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 分享文件到微信 超过10M 报 MicroMsg.SDK.WXFileObject(10827): checkArgs fail, fileSize is too large (#353)

**Comment by JarvanMo** [comment]
关于文件大小限制，请咨询微信官方
