### ISSUE TITLE
bug report：type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by shangguanyanyan** [OpenFlutter/fluwx#354]
文件： wechat_response.dart 53 行
 BaseWechatResponse 的参数 errStr 为不可空参数，但是在子类 fromMap 方法的 map 中传入的 errStr 字段为 null，导致生成WechatAuthResponse 时报错，这个错误不会直接出现在控制台中，需要 debug 单步执行复现。

复现场景：调用 sendWeChatAuth 时接收不到回调内容。

package版本：fluwx_no_pay: ^3.2.0

flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

**Comment by JarvanMo** [comment]
Fixed in #355
