### ISSUE TITLE
WeChat Auth not work

### ISSUE THREAD

**Issue by liqiang1995** [OpenFlutter/fluwx#356]
How are you?
I want to integrate WeChat Auth to my app.
but it does not work for me.
Here is my code.

  void _loginWeChat()async{
    sendWeChatAuth(scope: "snsapi_userinfo",state: "wechat_sdk_demo_test").then(print);
  }

  @override
  void initState() {
   registerWxApi(
        appId: 'wx_my_app_id',
        doOnAndroid: true,
        doOnIOS: true,
        universalLink: 'https://mydomain.com/'
    )
    weChatResponseEventHandler.distinct((a, b) => a == b).listen((res) {
      if (res is WeChatAuthResponse) {
        print('[WeChatAuthResponse]${[res.code,res.type,res.country,res.errCode,res.errStr]}');
      }
    });
    super.initState();
  }

I got these values.
res.code = null
res.type = 1
res.state = null
res.errCode = -6
res.errStr = null
Do you have any idea?
Thank you.

**Comment by JarvanMo** [comment]
You can search errorCode=-6. Perhaps the apk signature is not correct.

**Comment by liqiang1995** [comment]
thank you.
What do I have to do to fix it?

**Comment by JarvanMo** [comment]
Read the WeChat offical documents please.

**Comment by liqiang1995** [comment]
OK, sure

**Comment by reverseapp** [comment]
@JarvanMo 
This library has very poor ducumentation.
You can answer:

> Read the WeChat offical documents please.
to any question.

Please provide some useful information or links. It is very hard to work with this library, especially if you a foreigner..
Thank you!

**Comment by amanokerim** [comment]
This answer helped me to solve the problem:
https://stackoverflow.com/a/47454625/4693979

**Comment by liu2080019** [comment]
@liqiang1995  解决了吗
