### ISSUE TITLE
ios14.4微信分享失败

### ISSUE THREAD

**Issue by CallMeInk** [OpenFlutter/fluwx#358]
ios14.4微信分享失败，14.0可以分享成功，其他版本未知。14.4调用分享方法后跳转微信，不会弹出选择要分享的联系人，而是会直接跳转微信的消息列表（就跟刚打开微信一样）。
从点击分享开始到停留微信的消息列表，xcode有一行日志：
PBItemCollectionServer connection disconnected

**Comment by JarvanMo** [comment]
这个问题去微信论坛问更好。

**Comment by cubegao** [comment]
这个问题有点诡异。iPhone8  iOS 14.5.1正常，iPhone12 Pro iOS 14.6不弹出联系人，具体原因还没找到。

**Comment by gucck513** [comment]
解决了没有
