### ISSUE TITLE
android 11 报 sendReq failed for wechat app signature check failed，部分机型正常

### ISSUE THREAD

**Issue by ITmxs** [OpenFlutter/fluwx#359]
**Describe the bug**

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

**Comment by GrapevineLin** [comment]
同样的问题

**Comment by JarvanMo** [comment]
去微信论坛搜

**Comment by nayoTT** [comment]
我也遇到了这个错误 去搜了一下 有一个办法亲测可行 完美解决安卓11 调不起来的问题
去 android\app\src\main\AndroidManifest.xml 然后在<manifest>   </manifest>中 加入

    <queries>
        <package android:name="com.tencent.mm" />   
    </queries>

**Comment by nayoTT** [comment]
在《manifest》    ........   《/manifest》 这里面

**Comment by hugaveme** [comment]
> 在《manifest》 ........ 《/manifest》 这里面
没效果啊

**Comment by nayoTT** [comment]
@hugaveme  没效果的话你那边具体是什么错误咧

**Comment by goforu** [comment]
> 我也遇到了这个错误 去搜了一下 有一个办法亲测可行 完美解决安卓11 调不起来的问题 去 android\app\src\main\AndroidManifest.xml 然后在 中 加入
> 
> ```
> <queries>
>     <package android:name="com.tencent.mm" />   
> </queries>
> ```

you saved my life, bro
