### ISSUE TITLE
listen多次调用

### ISSUE THREAD

**Issue by jlcool** [OpenFlutter/fluwx#36]
每次打开页面listen被多次赋值？导致之前的listen 也被调用，打开过多少次就有多少个listen被调用，Stream需要在dispose注销掉？
官方例子也有这个问题，请处理

**Comment by jlcool** [comment]
怎么关闭了？

**Comment by jlcool** [comment]
在这个项目https://github.com/v7lin/fake_tencent找到一个解决办法，提供给其他使用者
``` dart
StreamSubscription<WeChatAuthResponse> _wxlogin;    
_wxlogin = fluwx.responseFromAuth.listen((val) {})
@override
  void dispose() {
_wxlogin.cancel();
}
```

**Comment by jlcool** [comment]
发现那个作者还写了微信插件，很不错，还可以本地获取用户信息

**Comment by JarvanMo** [comment]
> 每次打开页面listen被多次赋值？导致之前的listen 也被调用，打开过多少次就有多少个listen被调用，Stream需要在dispose注销掉？
> 官方例子也有这个问题，请处理

这个问题并不是lib本身的问题。

**Comment by zhangzhenxi** [comment]
```dart
import 'package:fluwx/fluwx.dart' as fluwx;
void sendAuth({
  @required ValueChanged<fluwx.WeChatAuthResponse> onAuthResp,
  String openId,
}) async {
  await fluwx.sendAuth(
    scope: 'snsapi_userinfo',
    openId: openId,
    state: '${DateTime.now().millisecondsSinceEpoch}',
  );
  StreamSubscription subscription;
  var callback = (fluwx.WeChatAuthResponse resp) {
    subscription?.cancel();
    onAuthResp(resp);
  };
  subscription = fluwx.responseFromAuth.listen(callback);
}
```

**Comment by hizzd** [comment]
```dart
import 'package:fluwx/fluwx.dart' as fluwx;

Future<fluwx.WeChatAuthResponse> requestLoginAuth({
    String openId,
  }) async {
    await fluwx.sendAuth(
      scope: "snsapi_userinfo",
      openId: openId,
      state: DateTime.now().millisecondsSinceEpoch.toString(),
    );
    return await fluwx.responseFromAuth.first;
  }
```

**Comment by yangfanyu** [comment]
这TM会不会导致内存泄漏？

**Comment by Raphon** [comment]
建议哈，这里可以把解决方案添加到demo中，方便大家参考。
目前demo中不包含这部分，大家都是先安好demo实现，然后发现问题再来找解决方案....

**Comment by JarvanMo** [comment]
那你为什么不PR呢。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Raphon&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月4日(星期四) 下午5:44
收件人:&nbsp;&quot;OpenFlutter/fluwx&quot;<fluwx@noreply.github.com&gt;;
抄送:&nbsp;&quot;JarvanMo&quot;<468122151@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] listen多次调用 (#36)

**Comment by Crazy-MT** [comment]
`StreamController<BaseWeChatResponse> _weChatResponseEventHandlerController =
    StreamController.broadcast();

/// Response answers from WeChat after sharing, payment etc.
Stream<BaseWeChatResponse> get weChatResponseEventHandler =>
    _weChatResponseEventHandlerController.stream;`


现在这块代码 _weChatResponseEventHandlerController 是私有的，造成 weChatResponseEventHandler 不能关闭掉，确实存在问题。
