### ISSUE TITLE
安卓-微信授权登录，一闪而过，无法登录

### ISSUE THREAD

**Issue by paintingStyle** [OpenFlutter/fluwx#365]
**Describe the bug**
点击微信登录，跳转到微信，显示正在登录中，一两秒后又返回到App了，weChatResponseEventHandler 没有调用
![图像](https://user-images.githubusercontent.com/22866404/114535414-9be3a100-9c82-11eb-8b67-5bef0ff32e4c.GIF)

**To Reproduce**
启动时日志:
```

 fluwx.registerWxApi(appId: Constant.weChatID, universalLink: Constant.universalLink);
  fluwx.weChatResponseEventHandler.listen((event) {
  
  });


D/MicroMsg.SDK.WXMsgImplComm(10751): check signature:308202eb30820254a00302010202044d36f7a4300d06092a864886f70d01010505003081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e74301e170d3131303131393134333933325a170d3431303131313134333933325a3081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e7430819f300d06092a864886f70d010101050003818d0030818902818100c05f34b231b083fb1323670bfbe7bdab40c0c0a6efc87ef2072a1ff0d60cc67c8edb0d0847f210bea6cbfaa241be70c86daf56be08b723c859e52428a064555d80db448cdcacc1aea2501eba06f8bad12a4fa49d85cacd7abeb68945a5cb5e061629b52e3254c373550ee4e40cb7c8ae6f7a8151ccd8df582d446f39ae0c5e930203010001300d06092a864886f70d0101050500038181009c8d9d7f2f908c42081b4c764c377109a8b2c70582422125ce545842d5f520aea69550b6bd8bfd94e987b75a3077eb04ad341f481aac266e89d3864456e69fba13df018acdc168b9a19dfd7ad9d9cc6f6ace57c746515f71234df3a053e33ba93ece5cd0fc15f3e389a3f365588a9fcb439e069d3629cd7732a13fff7b891499
D/MicroMsg.SDK.WXMsgImplComm(10751): pass
2
D/MicroMsg.SDK.WXApiImplV10(10751): registerApp, appId = wx302961d20177bd6b
D/MicroMsg.SDK.WXApiImplV10(10751): register app com.liuxue.wrongset.app
D/MicroMsg.SDK.MMessage(10751): send mm message, intent=Intent { act=com.tencent.mm.plugin.openapi.Intent.ACTION_HANDLE_APP_REGISTER (has extras) }, perm=com.tencent.mm.permission.MM_MESSAGE
```

执行 fluwx.sendWeChatAuth(scope: "snsapi_userinfo", state: "wechat_sdk_demo_test");  的日志
```
D/MicroMsg.SDK.WXMsgImplComm(10751): check signature:308202eb30820254a00302010202044d36f7a4300d06092a864886f70d01010505003081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e74301e170d3131303131393134333933325a170d3431303131313134333933325a3081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e7430819f300d06092a864886f70d010101050003818d0030818902818100c05f34b231b083fb1323670bfbe7bdab40c0c0a6efc87ef2072a1ff0d60cc67c8edb0d0847f210bea6cbfaa241be70c86daf56be08b723c859e52428a064555d80db448cdcacc1aea2501eba06f8bad12a4fa49d85cacd7abeb68945a5cb5e061629b52e3254c373550ee4e40cb7c8ae6f7a8151ccd8df582d446f39ae0c5e930203010001300d06092a864886f70d0101050500038181009c8d9d7f2f908c42081b4c764c377109a8b2c70582422125ce545842d5f520aea69550b6bd8bfd94e987b75a3077eb04ad341f481aac266e89d3864456e69fba13df018acdc168b9a19dfd7ad9d9cc6f6ace57c746515f71234df3a053e33ba93ece5cd0fc15f3e389a3f365588a9fcb439e069d3629cd7732a13fff7b891499
D/MicroMsg.SDK.WXMsgImplComm(10751): pass
I/MicroMsg.SDK.WXApiImplV10(10751): sendReq, req type = 1
D/MicroMsg.SDK.MMessageAct(10751): send, targetPkgName = com.tencent.mm, targetClassName = com.tencent.mm.plugin.base.stub.WXEntryActivity
I/Timeline(10751): Timeline: Activity_launch_request time:28392359 intent:Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras) }
D/MicroMsg.SDK.MMessageAct(10751): send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras) }
```

**Which version of Fluwx do you use?**
fluwx: 2.6.2，项目暂时没有接入空安全，使用的旧的版本

**Which device do you run on**
红米5Plus， Android 7.1.2

**Which Flutter do you use?**

```
rsf@rsfdeMac-mini ios % flutter doctor        
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Proxy Configuration
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by itMcdull** [comment]
遇到同样得问题 不同的是我是自动授权登录 。可以拿到返回的code

**Comment by itMcdull** [comment]
> 遇到同样得问题 不同的是我是自动授权登录 。可以拿到返回的code

点击去微信 然后转了下圈 自动回到app 然后code也拿得到

**Comment by wanghuasheng** [comment]
一样的问题，进群问他，他说是配置问题，但是确认了很多遍，不是配置的原因。估计他也解不了了。

**Comment by JarvanMo** [comment]
别犟，每个这样问我的人都信心满满的说自己没有问题，结果一个个脸都被打肿了。而且文档说过闪退问题。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月11日(星期二) 上午10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

**Comment by chachaxw** [comment]
解决了吗？我的也是这个问题，之前还好好的，最近升级到最新版的就不行了

**Comment by tianzhiguo123** [comment]
> > 遇到同样得问题 不同的是我是自动授权登录 。可以拿到返回的code
> 
> 点击去微信 然后转了下圈 自动回到app 然后code也拿得到
解决了没

**Comment by JarvanMo** [comment]
去了解了解什么是授权有效时间------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

**Comment by tianzhiguo123** [comment]
> 去了解了解什么是授权有效时间------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年7月6日(星期二) 下午3:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

但是也不应该我刚安装就进不去呀。iOS 都不会这样

**Comment by JarvanMo** [comment]
Android iOS是一个系统。百度去吧------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

**Comment by JarvanMo** [comment]
Android ios是一个系统？百度去吧------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

**Comment by JarvanMo** [comment]
都拿到code了还有啥可说的啊------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

**Comment by tianzhiguo123** [comment]
> Android ios是一个系统？百度去吧------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年7月6日(星期二) 下午4:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

我仅仅在寻找原因

**Comment by JarvanMo** [comment]
这就是微信机制，还找啥原因啊------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

**Comment by tianzhiguo123** [comment]
> 这就是微信机制，还找啥原因啊------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年7月6日(星期二) 下午4:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)

那行吧

**Comment by bxrhhy** [comment]
能不能别再这里聊天？？？？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tyrone_Bill ***@***.***&gt;
发送时间: 2021年7月6日 16:05
收件人: OpenFlutter/fluwx ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)





  
这就是微信机制，还找啥原因啊------------------&nbsp;原始邮件&nbsp;------------------ @.&gt; 发送时间:&nbsp;2021年7月6日(星期二) 下午4:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [OpenFlutter/fluwx] 安卓-微信授权登录，一闪而过，无法登录 (#365)
  
那行吧
