### ISSUE TITLE
can't load meta-data handleWeChatRequestByFluwx

### ISSUE THREAD

**Issue by Adrift001** [OpenFlutter/fluwx#367]
我是缺少什么配置吗?

**Comment by JarvanMo** [comment]
看demo。把那个meta加上。上次更新了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月16日(星期五) 中午12:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] can&#39;t load meta-data handleWeChatRequestByFluwx (#367)

**Comment by Adrift001** [comment]
加上了, 但是用的版本是2.6.2, 要更新到最新版吗?

**Comment by JarvanMo** [comment]
看2.6.2的demo------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月16日(星期五) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] can&#39;t load meta-data handleWeChatRequestByFluwx (#367)

**Comment by JarvanMo** [comment]
两个版本不一样------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月16日(星期五) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] can&#39;t load meta-data handleWeChatRequestByFluwx (#367)

**Comment by JarvanMo** [comment]
一个application下一个activity下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月16日(星期五) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] can&#39;t load meta-data handleWeChatRequestByFluwx (#367)

**Comment by Adrift001** [comment]
嗯, 非常感谢.

**Comment by wangyan-png** [comment]
2.6.2 按照2.6.2的配置好后还是出现cannot load meta-data handleWeChatRequestByFluwx
