### ISSUE TITLE
微信分身出现选择框取消时貌似没有回调

### ISSUE THREAD

**Issue by wdaglb** [OpenFlutter/fluwx#369]
不知道如何监听选择框的取消事件？

```
# 出现选择框时提示
D/ZrHung.AppEyeUiProbe( 9119): not watching, wait.
# 取消后提示这个
D/ZrHung.AppEyeUiProbe( 9119): restart watching
```

**Comment by JarvanMo** [comment]
你先想想这个选择框是你的app弹的还是微信弹的。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月19日(星期一) 上午9:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 微信分身出现选择框取消时貌似没有回调 (#369)

**Comment by wdaglb** [comment]
> 你先想想这个选择框是你的app弹的还是微信弹的。------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年4月19日(星期一) 上午9:31 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[OpenFlutter/fluwx] 微信分身出现选择框取消时貌似没有回调 (#369)

应该是系统弹的

**Comment by JarvanMo** [comment]
那还有什么疑问？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月19日(星期一) 上午9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 微信分身出现选择框取消时貌似没有回调 (#369)
