### ISSUE TITLE
新版本启动报错

### ISSUE THREAD

**Issue by GeniusYang** [OpenFlutter/fluwx#371]
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.3.0\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (19, 7): Redeclaration: FluwxPlugin
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.3.0\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxRequestHandler.kt: (30, 8): Redeclaration: FluwxRequestHandler
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.3.0\android\src\main\kotlin\com\jarvan\fluwx\handlers\WXAPiHandler.kt: (27, 8): Redeclaration: WXAPiHandler
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.3.0\android\src\main\kotlin\com\jarvan\fluwx\wxapi\FluwxWXEntryActivity.kt: (29, 12): Redeclaration: FluwxWXEntryActivity
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (21, 7): Redeclaration: FluwxPlugin
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (35, 22): Cannot access 'fluwxChannel': it is private in 'FluwxPlugin'
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (36, 22): Cannot access 'authHandler': it is private in 'FluwxPlugin'
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (37, 22): Cannot access 'shareHandler': it is private in 'FluwxPlugin'
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxRequestHandler.kt: (32, 8): Redeclaration: FluwxRequestHandler
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxRequestHandler.kt: (58, 21): Unresolved reference: extMsg
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxRequestHandler.kt: (67, 31): Unresolved reference: isCoolBoot
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxRequestHandler.kt: (77, 42): Unresolved reference: setCoolBool
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\WXAPiHandler.kt: (27, 8): Redeclaration: WXAPiHandler
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\WXAPiHandler.kt: (54, 22): Cannot access 'context': it is private in 'WXAPiHandler'
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\wxapi\FluwxWXEntryActivity.kt: (31, 12): Redeclaration: FluwxWXEntryActivity
e: C:\Users\lenovo\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fluwx-3.4.1\android\src\main\kotlin\com\jarvan\fluwx\wxapi\FluwxWXEntryActivity.kt: (44, 34): Unresolved reference: setCoolBool

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluwx:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by JarvanMo** [comment]
Clean cache------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月20日(星期二) 下午2:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 新版本启动报错 (#371)
