### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by lmmzhan** [OpenFlutter/fluwx#372]
为啥运行您的demo，报错呢：
Launching lib\main.dart on LIO AN00 in debug mode...
package identifier or launch activity not found.
Please check D:\zhan\development\flutter\flutterWork\mydemo\fluwx-master\fluwx-master\example\android\app\src\main\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_x86.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.
请问这个怎么解决呢？

**Comment by jb522185660** [comment]
请问解决了吗？如何解决
