### ISSUE TITLE
微信h5打开应用（wx-open-launch-app），热启动不会出现白屏，冷启动必现

### ISSUE THREAD

**Issue by RyanDyn** [OpenFlutter/fluwx#375]
**Describe the bug**
微信h5打开应用（wx-open-launch-app），热启动不会出现白屏，冷启动必现

**Which version of Fluwx do you use?**
fluwx:3.4.2

**Which device do you run on**
华为p20, android 10

**Which Flutter do you use?**

[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

**Comment by JarvanMo** [comment]
文档里有详细针对配置------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月27日(星期二) 下午4:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 微信h5打开应用（wx-open-launch-app），热启动不会出现白屏，冷启动必现 (#375)

**Comment by RyanDyn** [comment]
是按配置走的，修复了热启动白屏的问题，但冷启动一直没生效

**Comment by JarvanMo** [comment]
把微信id配置进去------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月27日(星期二) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 微信h5打开应用（wx-open-launch-app），热启动不会出现白屏，冷启动必现 (#375)

**Comment by RyanDyn** [comment]
除了android11的兼容和extinfo没加，其它的都已补全

**Comment by RyanDyn** [comment]
<meta-data
                android:name="handleWeChatRequestByFluwx"
                android:value="true" />

**Comment by RyanDyn** [comment]
<meta-data
       android:name="handleWeChatRequestByFluwx"
       android:value="true" />
       
       该项没有配置会有影响吗

**Comment by JarvanMo** [comment]
你可以追踪一下是不是wxapi没有被初始化------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月27日(星期二) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 微信h5打开应用（wx-open-launch-app），热启动不会出现白屏，冷启动必现 (#375)

**Comment by RyanDyn** [comment]
<meta-data
      android:name="handleWeChatRequestByFluwx"
      android:value="true" />

 该项没有配置会有影响吗

**Comment by RyanDyn** [comment]
<meta-data
                android:name="handleWeChatRequestByFluwx"
                android:value="true" />

**Comment by RyanDyn** [comment]
已经解决了，是配置项的问题，微信id注册的位置放置错误，感谢你的帮助。
