### ISSUE TITLE
包冲突怎么解决

### ISSUE THREAD

**Issue by Reinoal** [OpenFlutter/fluwx#376]
duplicate symbol '_channel' in:
    XXX/aliossflutter/libaliossflutter.a(AliossflutterPlugin.o)
   XXX/fluwx_no_pay/libfluwx_no_pay.a(FluwxPlugin.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JarvanMo** [comment]
需要指出具体位置

**Comment by JarvanMo** [comment]
最新的fluwx没有_channel啊
