### ISSUE TITLE
双微信的手机，不是主微信调不起app，主微信可以，想不明白

### ISSUE THREAD

**Issue by liumingsongning** [OpenFlutter/fluwx#384]
安卓双微信的手机，不是主微信调不起app，主微信可以，想不明白，用微信开放标签

**Comment by JarvanMo** [comment]
这个问题你可以去问问微信------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月26日(星期三) 上午10:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 双微信的手机，不是主微信调不起app，主微信可以，想不明白 (#384)

**Comment by liumingsongning** [comment]
大众点评的可以，所以才这么问

**Comment by JarvanMo** [comment]
别大众点评，我们版本一样吗？我改过微信SDK代码么？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月26日(星期三) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 双微信的手机，不是主微信调不起app，主微信可以，想不明白 (#384)

**Comment by JarvanMo** [comment]
双开的微信是你写的还是我写的？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月26日(星期三) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 双微信的手机，不是主微信调不起app，主微信可以，想不明白 (#384)

**Comment by liumingsongning** [comment]
这个问题过，帮看看ios冷启动获取不到参数那个，是微信的sdk的原因还是别的原因啊，android的没问题
