### ISSUE TITLE
微信开放标签调起ios 冷启动时获取不到getExtMsg信息

### ISSUE THREAD

**Issue by liumingsongning** [OpenFlutter/fluwx#385]
微信开放标签调起ios 冷启动时获取不到getExtMsg信息

**Comment by liumingsongning** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    //向微信注册
    [WXApi registerApp:APP_ID
universalLink:UNIVERSAL_LINK];
    return YES;
}
这个地方的WXApi怎么引进来啊？

**Comment by shenggen1987** [comment]
哥们你是怎么解决的，我也是冷启动有问题
