### ISSUE TITLE
iOS微信支付后收不到回调，Android是能正常收到回调的

### ISSUE THREAD

**Issue by judastatus** [OpenFlutter/fluwx#386]
fluwx: 2.3.0
flutter: 2.0.6

<img width="697" alt="Screen Shot 2021-05-27 at 11 37 16 AM" src="https://user-images.githubusercontent.com/15098424/119762236-e5f5ae80-bedf-11eb-8156-2daf001afde9.png">

如图，在 initState() 方法里监听微信支付回调，Android是可以正常收到回调的，iOS上是可以正常拉起微信支付的，只不过是回调都没有走。请问，这大概是什么原因呢？

ps：历史的issue都看了

**Comment by JarvanMo** [comment]
不用想，也不用说Android，Android和iOS一样么。几乎所有可能我都说了。还有就是一般我们都是保持最新版本。fluwx肯定没有问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月27日(星期四) 中午11:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] iOS微信支付后收不到回调，Android是能正常收到回调的 (#386)

**Comment by judastatus** [comment]
ok
