### ISSUE TITLE
Android 11及以上系统的手机需要使用FileProvider方式分享

### ISSUE THREAD

**Issue by wangyan-png** [OpenFlutter/fluwx#387]
**Describe the bug**

**To Reproduce**
Android 11及以上系统的手机需要使用FileProvider方式分享
**Which version of Fluwx do you use?**   2.6.2
Tell us the version of your current Fluwx. 

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.
Android 11
**Which Flutter do you use?**
 Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (4 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

Run `flutter doctor` and paste the output here.  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-arm, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by yumi0629** [comment]
使用 FileProvider 方式分享文件，参考微信官方文档：https://developers.weixin.qq.com/community/develop/doc/0004886026c1a8402d2a040ee5b401

**Comment by JarvanMo** [comment]
很久很久以前就已经支持file provider了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月1日(星期二) 下午4:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] Android 11及以上系统的手机需要使用FileProvider方式分享 (#387)

**Comment by wangyan-png** [comment]
感谢回复 我看到了 但是部分安卓11还是有此问题怎么办

**Comment by halloweens1** [comment]
@wangyan-png 您好，请问您问题解决了吗，我在测试分享图片的过程中发现，测试数据为45KB大小，203KB大小的图片分享可以直接分享成功，而测试数据为1.41MB大小，1.53MB大小的图片分享失败，提示Android11及以上系统分享受到了限制，需要使用fileProvider方法，我得出的结论是现在在Android11上使用fluwx分享图片，是会有一个图片大小限制，该限制不知道是系统级别控制的还是微信sdk控制的，大概范围可以参考一下我的数据，我个人猜测大小限制值为1MB这样。分享较大的图片时应该还得通过官方文档上说明的去解决吧，如上面给出的官方文档链接，我个人还没试过，正准备试一下。
