### ISSUE TITLE
请问怎么实现安卓带支付，iOS不带支付呢？

### ISSUE THREAD

**Issue by liangdas** [OpenFlutter/fluwx#395]
请问怎么实现安卓带支付，iOS不带支付呢？担心过审问题

**Comment by JarvanMo** [comment]
Fluwx no pay------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月28日(星期一) 晚上10:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 请问怎么实现安卓带支付，iOS不带支付呢？ (#395)
