### ISSUE TITLE
和appscheme插件冲突了

### ISSUE THREAD

**Issue by kainy** [OpenFlutter/fluwx#398]
**Describe the bug**
ios只要引入appscheme插件，就无法使用fluwx，问题出在首次universelink 认证，回跳到

https://universal_link/wxidxxxx/refreshToken?wechat_auth_token=xxxx 后，就没有响应了。

**To Reproduce**
1. 引入appscheme插件
2. 修改开放平台的 Universal Links 为新值（创造首次授权的场景）
3. 调用fluwx
4. 跳转到微信，认证后回跳到app，然后没反应。多次重复操作，会来回跳转。

**Which version of Fluwx do you use?**
最新版本

**Which device do you run on**
iPhone7

**Which Flutter do you use?**

正常版本。

**Comment by guotao** [comment]
一样的问题，求解决方法。。

**Comment by thesnail** [comment]
@guotao @kainy  已修复,请升级了, 感谢
[```appscheme: ^1.0.5```](https://pub.flutter-io.cn/packages/appscheme/install)
