### ISSUE TITLE
支付成功后，回调的extra为null

### ISSUE THREAD

**Issue by Hackerofshi** [OpenFlutter/fluwx#399]
fluwx.weChatResponseEventHandler.listen((res) {
      if (res is fluwx.WeChatPaymentResponse) {
        print("===========${res.isSuccessful}${res.extData}${res.type}${res.toString()}");
      }
    });

===========true  null  5  Instance of 'WeChatPaymentResponse'

flutter 2.x

fluwx: ^3.4.3

红米note7 Android10

AS run

**Comment by JarvanMo** [comment]
```kotlin
    private fun handlePayResp(response: PayResp) {
        val result = mapOf(
                "prepayId" to response.prepayId,
                "returnKey" to response.returnKey,
                "extData" to response.extData,
                errStr to response.errStr,
                type to response.type,
                errCode to response.errCode
        )
        FluwxPlugin.callingChannel?.invokeMethod("onPayResponse", result)
    }
```
代码里已经处理了
