### ISSUE TITLE
给指导下！！

### ISSUE THREAD

**Issue by wangyongpenga** [OpenFlutter/fluwx#4]
配置完 public class WXEntryActivity extends FluwxWXEntryActivity{}运行项目报这个错误
Finished with error: FormatException: Bad UTF-8 encoding 0xb4 (at offset 156)

**Comment by JarvanMo** [comment]
你这叹号吓死我了。
在android工程下运行：
```
./gradlew assembleDebug
```
windows:
```
gradlew assembleDebug
```

**Comment by wangyongpenga** [comment]
还是不行  import com.jarvan.fluwx.wxapi.FluwxWXEntryActivity，感觉是这个类引入不进来

**Comment by JarvanMo** [comment]
让你看输出信息。

**Comment by wangyongpenga** [comment]
C:\Users\Administrator\Desktop\flutter_refresh-master\flutter_refresh-master\android\app\src\main\java\refresh\flutterrefresh\wxapi\WXEntryActivity.java:7: 错误: 无法访问IWXAPIEventHandler
public class WXEntryActivity extends FluwxWXEntryActivity {
       ^
  找不到com.tencent.mm.opensdk.openapi.IWXAPIEventHandler的类文件
1 个错误

**Comment by JarvanMo** [comment]
在你的android工程的`build.gradle`中加入依赖：
```
 implementation 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:5.1.4'
```

**Comment by wangyongpenga** [comment]
运行不报错了，点击分享后登陆上微信后，没有跳到朋友圈页面，而是出现了白屏。

**Comment by JarvanMo** [comment]
那我就不知道了。demo没问题的。
