### ISSUE TITLE
分享完成或者取消分享后App崩溃，重新打开会重新加载首页

### ISSUE THREAD

**Issue by qijunxin** [OpenFlutter/fluwx#40]
安卓现在调用分享功能后，分享完成或者取消分享或者取消登录，都会回到桌面，app需要手动打开，并且打开后会再次重新加载首页而不是回到之前的页面，有什么办法吗

**Comment by JarvanMo** [comment]
这个和fluwx应该没有关系。

**Comment by qijunxin** [comment]
会报这个错误
`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.qihoo.pumpkinapp/com.qihoo.pumpkinapp.wxapi.WXEntryActivity}: java.lang.ClassNotFoundException: Didn't find class "com.qihoo.pumpkinapp.wxapi.WXEntryActivity" on path: DexPathList[[zip file "/data/app/com.qihoo.pumpkinapp-FECiNqa92mkJ4RlV7oa4RQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.qihoo.pumpkinapp-FECiNqa92mkJ4RlV7oa4RQ==/lib/arm64, /data/app/com.qihoo.pumpkinapp-FECiNqa92mkJ4RlV7oa4RQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
`

**Comment by qijunxin** [comment]
不好意思，是我的问题，WXEntryActivity里面的包名写错了导致的，不好意思
