### ISSUE TITLE
Android11使用isWeChatInstalled无法识别是否安装了微信

### ISSUE THREAD

**Issue by PillarChen** [OpenFlutter/fluwx#403]
Android11以下的手机可以识别,在VIVO X60 Android11测试发现出问题了导致无法识别是否安装了微信,环境:Flutter version 2.2.3(flutter 1.22.2也有这样的问题)  集成库版本:fluwx: ^3.5.0

**Comment by PillarChen** [comment]
import 'package:fluwx/fluwx.dart' as fluwx;
 bool _isWXInstalled=await fluwx.isWeChatInstalled; 
是按异步方法写的

**Comment by JarvanMo** [comment]
see #359

**Comment by PillarChen** [comment]
OK 我试试看

**Comment by PillarChen** [comment]
解决了,
方案1:
targetSdkVersion 和compileSdkVersion不要设置30设置成29即可 

方案2:
XML文件里设置:
    <queries>
        <package android:name="com.tencent.mm"/>
    </queries>

但是版本号使用的(尤其com.android.tools.build:gradle:4.1.0 之前使用的低一些的版本号的总是提示找不到Key的提示):
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
  classpath 'com.android.tools.build:gradle:4.1.0'
