### ISSUE TITLE
🌱 新功能需求：📎 请求新增一个App拉起微信客服功能 🎊

### ISSUE THREAD

**Issue by mingsnx** [OpenFlutter/fluwx#407]
🍭 🍭 🍭 
[拉起微信客服功能文档链接](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/APP_launch_wechat_customer_service.html)
🚥 🚥 🚥

**Comment by JarvanMo** [comment]
等我抽时间搞一下

**Comment by JarvanMo** [comment]
更新：
我现在只能做Android部分的拉起微信客服功能，原是cocoapods上的微信sdk现在根本没有更新到1.9.2，至于为什么要用cocopod，请参看这位自由软件人士的解释。
see #137

**Comment by mingsnx** [comment]
ok，了解了

**Comment by JarvanMo** [comment]
我给腾讯发邮件了，过几天看看有没有回应，不行的话只能再想想办法或等着------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月15日(星期天) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 🌱 新功能需求：📎 请求新增一个App拉起微信客服功能 🎊 (#407)

**Comment by mingsnx** [comment]
ok

**Comment by JarvanMo** [comment]
3.6.0已发布，支持拉起客服功能

**Comment by OHeroJ** [comment]
> 3.6.0已发布，支持拉起客服功能

无法唤起，看了下实现：


```oc

- (void)openWeChatCustomerServiceChat:(FlutterMethodCall *)call result:(FlutterResult)result {
    NSString *url = call.arguments[@"url"];
    NSString *corpId = call.arguments[@"corpId"];
    result(@([WXApi isWXAppInstalled]));
}
```

并未调用打开客服的api, 应当：

```oc
WXOpenCustomerServiceReq *req = [[WXOpenCustomerServiceReq alloc] init];
req.corpid = corpId;	//企业ID
req.url = url;			//客服URL
return [WXApi sendReq:req completion:nil];
```

文档：[https://developers.weixin.qq.com/doc/oplatform/Mobile_App/APP_launch_wechat_customer_service.html](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/APP_launch_wechat_customer_service.html)
