### ISSUE TITLE
新需求 支付分免押授权

### ISSUE THREAD

**Issue by lingying222** [OpenFlutter/fluwx#408]
希望加一个支付分免押授权的功能

**Comment by JarvanMo** [comment]
等我有时间的吧，这东西不能指望我一个人。

**Comment by lingying222** [comment]
好的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月21日(周六) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [OpenFlutter/fluwx] 新需求 支付分免押授权 (#408)




 
等我有时间的吧，这东西不能指望我一个人。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JarvanMo** [comment]
有文档地址吗

**Comment by lingying222** [comment]
在这儿&nbsp;微信支付开发文档 | 微信支付分（服务商） (qq.com)&nbsp; 感谢大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenFlutter/fluwx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月29日(星期天) 上午9:38
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] 新需求 支付分免押授权 (#408)





 
有文档地址吗
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lingying222** [comment]
地址在这儿  [微信支付分开发文档](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pages/payscore_partner.shtml)  感谢大佬

**Comment by mafanwei** [comment]
#458
