### ISSUE TITLE
hello，微信登录成功之后，怎样获取用户的唯一标识？

### ISSUE THREAD

**Issue by hw20101101** [OpenFlutter/fluwx#409]
也就是原生 SDK 中返回的 openid，谢谢！

**Comment by JarvanMo** [comment]
拿到code了就可以自己去请求自己想要的啊，具体去看微信登录文档------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月19日(星期四) 上午9:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] hello，微信登录成功之后，怎样获取用户的唯一标识？ (#409)

**Comment by hw20101101** [comment]
好的，看到了，多谢！

**Comment by hw20101101** [comment]
好的，看到了，多谢！

https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_Login/Authorized_API_call_UnionID.html   授权后接口调用（UnionID）
