### ISSUE TITLE
调起微信失败，Logcat 有个 "heeeeee" 的 Error

### ISSUE THREAD

**Issue by zyty** [OpenFlutter/fluwx#41]
https://github.com/OpenFlutter/fluwx/blob/8f61a2f36335d19813e9a189d290e50097f10190/android/src/main/kotlin/com/jarvan/fluwx/handler/FluwxResponseHandler.kt#L44

这里是不是应该将错误信息打印出来？这样现在无法定位原因

**Comment by JarvanMo** [comment]
感谢指定，但是不需要打印出来。因为所有的信息已经通知flutter了。

**Comment by zyty** [comment]
> 感谢指正，但是不需要打印出来。因为所有的信息已经通知flutter了。

转发调起微信失败目前只能拿到以下两条日志：
`2019-01-28 10:32:46.852 13618-13890/com.qihoo.pumpkinapp E/Luban: Orientation not found
2019-01-28 10:32:47.800 13618-13618/com.qihoo.pumpkinapp E/tag: heeeeee`

**Comment by JarvanMo** [comment]
需要在flutter处理错误信息。

**Comment by JarvanMo** [comment]
拉不起来必然是因为签名不对。

**Comment by JarvanMo** [comment]
errorCode可以在flutter里取到

**Comment by zyty** [comment]
> 拉不起来必然是因为签名不对。

确实是签名不对，谢谢
