### ISSUE TITLE
该商户支付权限已被取消

### ISSUE THREAD

**Issue by 18518278831** [OpenFlutter/fluwx#413]
大佬。这是什么原因呢？

**Comment by JarvanMo** [comment]
去问微信------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月28日(星期六) 上午9:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 该商户支付权限已被取消 (#413)
