### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zhanchi88** [OpenFlutter/fluwx#414]
details：
![Uploading 屏幕截图 2021-08-29 134230.png…]()

**Comment by zhanchi88** [comment]
The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Affected Modules: fluwx

**Comment by JarvanMo** [comment]
稍后修复------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月29日(星期天) 中午1:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/fluwx] Build error (#414)
