### ISSUE TITLE
微信支付提示商户支付下单ID非法

### ISSUE THREAD

**Issue by yueweilu** [OpenFlutter/fluwx#418]
微信支付提示商户支付下单ID非法

**Comment by JarvanMo** [comment]
去问微信or百度------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月31日(星期二) 下午5:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 微信支付提示商户支付下单ID非法 (#418)
