### ISSUE TITLE
Build error !

### ISSUE THREAD

**Issue by zengqiang24** [OpenFlutter/fluwx#419]
`Launching lib\main.dart on ONEPLUS A3000 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (19, 40): Unresolved reference: WXOpenCustomerServiceChat
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (156, 23): Unresolved reference: WXOpenCustomerServiceChat
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (157, 17): Variable expected
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\FluwxPlugin.kt: (159, 17): Variable expected
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxResponseHandler.kt: (23, 40): Unresolved reference: WXOpenCustomerServiceChat
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxResponseHandler.kt: (44, 16): Unresolved reference: WXOpenCustomerServiceChat
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxResponseHandler.kt: (125, 68): Unresolved reference: WXOpenCustomerServiceChat
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\handlers\FluwxResponseHandler.kt: (126, 22): Not enough information to infer type variable V
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\io\ImagesIO.kt: (7, 8): Unresolved reference: id
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\io\ImagesIO.kt: (8, 8): Unresolved reference: id
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\io\ImagesIO.kt: (36, 34): Unresolved reference: Compressor
e: C:\Users\qzeng\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluwx_no_pay-3.6.1\android\src\main\kotlin\com\jarvan\fluwx\io\ImagesIO.kt: (37, 17): Unresolved reference: size

FAILURE: Build failed with an exception.
`

My gradle follow by example:
`buildscript {
    ext.kotlin_version = '1.5.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
`

**Comment by JarvanMo** [comment]
Fixed in 3.6.1+1

**Comment by zengqiang24** [comment]
@JarvanMo  Thanks for your help!    Do you mean  I  need to wait a new release build?  3.6.2?

**Comment by JarvanMo** [comment]
No, It's 3.6.1+2.

**Comment by JarvanMo** [comment]
Because I forgot another issue so I publish another package to solve that.

**Comment by zengqiang24** [comment]
@zengqiang24  I've tested version 3.6.1+2. it works! thanks!
