### ISSUE TITLE
希望可以支持多appId注册

### ISSUE THREAD

**Issue by Jaysonss** [OpenFlutter/fluwx#42]
目前App引入了多个商户，每个商户都是不同的appId，希望可以支持多个appId注册；

**Comment by JarvanMo** [comment]
一个app进行registerWXApi的时候有且仅有一个appID，换了其他appID验证就不会通过的，拉不起来微信。至于支付这种的可以动态传appID。

**Comment by Jaysonss** [comment]
酱紫啊，我知道了，多谢

**Comment by Jaysonss** [comment]
还有一个问题想请教下：我们是混合开发，在集成fluwx到原生端的时候发现fluwx和app都依赖了opensdk导致类冲突，我看了源码发现opensdk的依赖是api，是不是改成implementation就可以了

**Comment by JarvanMo** [comment]
你们原生的可以不用依赖opensdk了。
