### ISSUE TITLE
3.6.1+1 iOS 冷启动APP 无法跳转到对应的页

### ISSUE THREAD

**Issue by zcl0621** [OpenFlutter/fluwx#420]
**Describe the bug**

**To Reproduce**
1. Android APP后台或者未运行 均可打开app并跳转至指定的页面
2. iOS APP如果再后台 可以打开app并跳转至指定页面
3. iOS APP如果未运行 只能打开app 但不能跳转到指定页面

**Which version of Fluwx do you use?**
3.6.1+1

**Which device do you run on**
iPhone 11 Pro Max

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] VS Code (version 1.59.1)
[✓] Connected device (3 available)

猜测
应该是appDelegate.swift 未注册WXApi 
但是无论在这个文件import fluwx 或者在 Runner-Bridging-Header.h 中去引入 include <fluwx/WXApi.h>
WXApi 这个均找不到scope

**Comment by JarvanMo** [comment]
iOS我不太擅长。 但是原因我可以告诉你，冷启动的时候flutter还没加载出来。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月2日(星期四) 下午4:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 3.6.1+1 iOS 冷启动APP 无法跳转到对应的页 (#420)

**Comment by zcl0621** [comment]
启动的时候flutter 确实没加载
看最新的文档需要在AppDelegate中注册WXapi 但是通过import fluwx 是引入不了WXApi的
我把WXAPi拽出来了 能引入 但注册成功后依旧不能跳转
看以前的文档 需要自己处理接收微信的打开协议 但是在某个版本的fluwx文档说 现在不需要了

目前的代码
![image](https://user-images.githubusercontent.com/8233731/131939391-b5b8ca09-5c2e-4576-8948-e912c7462fb8.png)

AppDelegate.swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
 override func application(
   _ application: UIApplication,
   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
 ) -> Bool {
   GeneratedPluginRegistrant.register(with: self)
    WXApi.registerApp("wxxxxxxxxxxxxc",universalLink:"https://xxxxxxxxx/")
   return super.application(application, didFinishLaunchingWithOptions: launchOptions)
}
}

Runner-Bridging-Header.h
#import "GeneratedPluginRegistrant.h"
#import "WXApi.h"

目前的现象 

 

https://user-images.githubusercontent.com/8233731/131939665-8cbb54b1-c7fe-4ddc-84cc-96f5500a24d7.mov


fluwx 3.6.1 还需要自行处理微信的协议么? 和QA(https://github.com/OpenFlutter/fluwx/blob/master/doc/QA.md)中的<Can't receive response after upgrading to 1.0.0 on iOS>一样么?

**Comment by Smilefish2** [comment]
今天在完成这个功能时，发现，有时候传的参数是完整的，wechatextmsg 开头的，有时又会直接是自己定义的数据比如 zihu://qqqq/133，不知道会不会对你有帮助

**Comment by zcl0621** [comment]
@Smilefish2  先用读粘贴板大法绕过去了... 目前看没什么办法

**Comment by Smilefish2** [comment]
@zcl0621 我加了个包uni_links，正常处理app link时，同时解决了这个问题，可以冷启动了
```
    final initialLink = await getInitialLink();
      print("initialLink:" + initialLink.toString());
      if (initialLink != null && initialLink.isNotEmpty) {
        await AppLaunch.jumpToPage(initialLink);
      }
```
getInitialLink 是 uni_links包中的方法，可以试试

**Comment by zcl0621** [comment]
@Smilefish2 这个在android 上冷启动是有效的,但是在iOS冷启动没法唤醒的.这个尝试过了

**Comment by TwoSX** [comment]
目前在iOS上解决方案：
1. 修改 `fluwx/ios/fluwx.podspec` 中的 `s.public_header_files`
```
# 暴露所有头文件
s.public_header_files = 'Classes/**/*.h'
```

2. 在项目 `ios/Runner/Runner-Bridging-Header.h` 文件中新增 (只针对swift，oc是在AppDelegate.m中引入)
```
#import <fluwx_no_pay/WXApi.h>
```

3. 在 `AppDelegate.swift` 中进行注册WXApi

```
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

    // 在此处进行微信注册，确保微信冷启动APP时，可获取到H5的自定义信息
    WXApi.registerApp("APPIDxxxx", universalLink: "https://xxxxxxxx")

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

android 也是使用 `uni_links` 这个插件来解决的

**Comment by ZhangZhiH** [comment]
请问解决了吗  3.9.0+2 IOS启动 能打开但是 getExtMsg 获取null 
我感觉也是注册的问题 到底应该怎么写 官方没有案例 @zcl0621

**Comment by zcl0621** [comment]
@ZhangZhiH  H5把link复制到粘贴板中，冷启动读取下粘贴板，然后跳过去

**Comment by ZhangZhiH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
