### ISSUE TITLE
希望增加对“App打开微信客服”的支付

### ISSUE THREAD

**Issue by hetao29** [OpenFlutter/fluwx#421]
如题，官方介绍：

https://developers.weixin.qq.com/miniprogram/dev/api/open-api/service-chat/wx.openCustomerServiceChat.html

**Comment by JarvanMo** [comment]
最新版的已经支持了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月5日(星期天) 下午4:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 希望增加对“App打一微信客服”的支付 (#421)

**Comment by hetao29** [comment]
感谢感谢~

**Comment by hetao29** [comment]
已经成功接入，感谢~

**Comment by keepgagaga** [comment]
> 最新版的已经支持了------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年9月5日(星期天) 下午4:40 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[OpenFlutter/fluwx] 希望增加对“App打一微信客服”的支付 (#421)

最新版，一直没找到有这个接口，希望有个文档指引下。
