### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<String>'

### ISSUE THREAD

**Issue by Smilefish2** [OpenFlutter/fluwx#422]
getExtMsg方法 是否应该支持nullsafety特性，不然会报错好像：
```
E/flutter (24077): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<String>'
E/flutter (24077): #0      getExtMsg (package:fluwx/src/fluwx_iml.dart:87)
```

**Comment by JarvanMo** [comment]
抽空修复一下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月10日(星期五) 下午2:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] Unhandled Exception: type &#39;Null&#39; is not a subtype of type &#39;FutureOr<String&gt;&#39; (#422)
