### ISSUE TITLE
安卓打包报错

### ISSUE THREAD

**Issue by DongHa0** [OpenFlutter/fluwx#423]
![image](https://user-images.githubusercontent.com/10461205/133092714-c9ff6ce0-2436-4ef1-a9be-af7d5e75e6f1.png)
尝试了开代理和clean 都没有解决，有解决的大佬嘛，求教~

**Comment by JarvanMo** [comment]
把mavencentral加上。正常是没问题的。

**Comment by DongHa0** [comment]
> 把mavencentral加上。正常是没问题的。

加上了的，大佬 哭死~

**Comment by DongHa0** [comment]
把jcenter去掉之后就好了 囧~

**Comment by DongHa0** [comment]
> 把mavencentral加上。正常是没问题的。

谢谢大佬
