### ISSUE TITLE
flutter 还是1.20.由于项目比较重，无法升级到2.12+，如果使用最新版的fluwx呢？

### ISSUE THREAD

**Issue by jackbbhua** [OpenFlutter/fluwx#424]
由于flutter还是比较老的版本，fluwx 3.6.1需要用到fluter 2.1+好像是，有什么办法可以用上新的版本，因为想要用到app直接拉取微信客服功能。谢谢你。

**Comment by JarvanMo** [comment]
没有什么好办法，自己下载代码改改fluwx的flutter代码吧，不多------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月14日(星期二) 凌晨1:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] flutter 还是1.20.由于项目比较重，无法升级到2.12+，如果使用最新版的fluwx呢？ (#424)

**Comment by JarvanMo** [comment]
基本上就是把yaml里的版本限制降低，把？和required去了就差不多------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月14日(星期二) 凌晨1:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] flutter 还是1.20.由于项目比较重，无法升级到2.12+，如果使用最新版的fluwx呢？ (#424)
