### ISSUE TITLE
Flutter 2.5.0   registerWxApi 报错

### ISSUE THREAD

**Issue by linzupeng** [OpenFlutter/fluwx#425]
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
    ! Error: iPhone (4) is not connected. Xcode will continue when iPhone (4) is connected. (code -13)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

Error: 

 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (28621): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
E/flutter (28621): #1      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:375:5)
E/flutter (28621): #2      _channel (package:fluwx/src/fluwx_iml.dart:39:5)
E/flutter (28621): #3      _channel (package:fluwx/src/fluwx_iml.dart)
E/flutter (28621): #4      registerWxApi (package:fluwx/src/fluwx_iml.dart:77:16)
E/flutter (28621): #5      InitAppInfo._registerWx (package:xiaokai_danci/init_app_info.dart:21:5)
E/flutter (28621): #6      InitAppInfo.init (package:xiaokai_danci/init_app_info.dart:9:5)
E/flutter (28621): #7      main (package:xiaokai_danci/main.dart:11:21)
E/flutter (28621): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:145:25)
E/flutter (28621): #9      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (28621): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (28621): #11     _runZoned (dart:async/zone.dart:1863:10)
E/flutter (28621): #12     runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter (28621): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:141:5)
E/flutter (28621): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (28621): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by JarvanMo** [comment]
universalLink 没传？

**Comment by linzupeng** [comment]
我切回2.2.3试试，怀疑是2.5.0的bug

**Comment by linzupeng** [comment]
执行registerWxApi，未 WidgetsFlutterBinding.ensureInitialized();

**Comment by liwangyong** [comment]
> Unhandled Exception: Null check operator used on a null value 你好，这个问题怎么解决的？

你解决了吗
