### ISSUE TITLE
Xcode12 模拟器无法运行

### ISSUE THREAD

**Issue by linzupeng** [OpenFlutter/fluwx#426]
ld: in /Users/mac/xxxx/ios/Pods/WechatOpenSDK_Fuck/OpenSDK1.9.2/libWeChatSDK.a(WechatAuthSDK.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/mac/xxxxx/ios/Pods/WechatOpenSDK_Fuck/OpenSDK1.9.2/libWeChatSDK.a' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

**Comment by linzupeng** [comment]
xcode 直接运行没问题，flutter run 就报错

**Comment by wufd** [comment]
flutter version 2.5.0 ?

**Comment by linzupeng** [comment]
是的 2.5.0

**Comment by linzupeng** [comment]
> flutter version 2.5.0 ?

是的

**Comment by elfensnake** [comment]
同样的问题，flutter 升级到 2.5 之后就会这样

**Comment by ZheGuangZeng** [comment]
+1

**Comment by JarvanMo** [comment]
找到解决办法了。Build Setting Excluded Architecture 加上 arm64

**Comment by bdw9005** [comment]
> 找到解决办法了。Build Setting Excluded Architecture 加上 arm64

我这里用这个方法仍然不可用xcode12.4,模拟器xs， ios12.4，'/Users/xxx/Documents/workspace/flutter/xxx_flutter/ios/Pods/WechatOpenSDK_Fuck/OpenSDK1.9.2/libWeChatSDK.a' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Myfyz** [comment]
升级到2.5.2版本后有了这个问题，xcode直接跑项目模拟器没问题，但是vscode跑项目模拟器报错，不知道咋解决，原来的flutter版2.2.2是不存在这样的问题的，有没有大神知道咋解决

**Comment by wufd** [comment]
m1 xcode13 可不用修改，正常运行

**Comment by yuandalu** [comment]
PodFile
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
   ```
 target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
```
  end
end`

**Comment by chachaxw** [comment]
@JarvanMo 这个亲测有效，👍

**Comment by longdw** [comment]
> m1 xcode13 可不用修改，正常运行

flutter2.5.3，xcode13.1，苹果m1系统，以上所有方法都无效，还是同样的错误。

**Comment by czy** [comment]
m1 pro同样问题

**Comment by 2e2ee95304418f96** [comment]
> > m1 xcode13 可不用修改，正常运行
> 
> flutter2.5.3，xcode13.1，苹果m1系统，以上所有方法都无效，还是同样的错误。

同样问题。

**Comment by bruce3x** [comment]
flutter clean 再运行就ok了
