### ISSUE TITLE
您好，您能不能把拉起微信客服的接口开放出来

### ISSUE THREAD

**Issue by wskkhn-hezhong** [OpenFlutter/fluwx#427]
您好，您能不能把拉起微信客服的接口开放出来，万分感谢

opensdk版本：大于等于6.7.9
调用接口：WXOpenCustomerServiceChat 移动应用跳转到微信客服会话示例：

String appId = "wxd930ea5d5a258f4f"; // 填移动应用(App)的 AppId
IWXAPI api = WXAPIFactory.createWXAPI(context, appId);

// 判断当前版本是否支持拉起客服会话
if (api.getWXAppSupportAPI() >= Build.SUPPORT_OPEN_CUSTOMER_SERVICE_CHAT) {
	String url = kfUrl.getText().toString();
	WXOpenCustomerServiceChat.Req req = new WXOpenCustomerServiceChat.Req();
	req.corpId = "xxxx";							      // 企业ID
	req.url = "https://work.weixin.qq.com/kfid/kfcxxxxx";	// 客服URL
	api.sendReq(req);
}
iOS 开发示例
opensdk版本：大于等于 1.9.2
移动应用跳转到微信客服会话示例：

    WXOpenCustomerServiceReq *req = [[WXOpenCustomerServiceReq alloc] init];
    req.corpid = corpId;	//企业ID
    req.url = url;			//客服URL
    return [WXApi sendReq:req completion:nil];
回调说明

	-(void)onResp:(BaseResp *)resp 
	{
	     if ([resp isKindOfClass:[WXOpenCustomerServiceResp class]])
	     {
	     	  int errCode = resp.errCode;		// 0 为成功，其余为失败
	          NSString *string = resp.extMsg;	// 相关错误信息
	     }
	}

**Comment by JarvanMo** [comment]
已经有了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月17日(星期五) 下午5:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OpenFlutter/fluwx] 您好，您能不能把拉起微信客服的接口开放出来 (#427)

**Comment by wskkhn-hezhong** [comment]
找到了，谢谢
