### ISSUE TITLE
The iOS pod SDK name is not very friendly...

### ISSUE THREAD

**Issue by dingjianjaja** [OpenFlutter/fluwx#429]
In fluwx.podspec file
line 21
  s.dependency 'WechatOpenSDK_Fuck',  '~> 1.9.2'
"WechatOpenSDK_Fuck" is not very frendly...

**Comment by JarvanMo** [comment]
Sorry for this but I have no choices because Wechat doesn't update the official pod for a long time. I have to use a active pod instead.

**Comment by zhbh** [comment]
HI, @JarvanMo. This SDK's writer has the tutorial to teach how to [create the WechatOpenSDK 1.9.2 version of the pod library.](https://juejin.cn/post/7001032742544621581) 

You guys can create a new one for that. I also think its name is so rude and strange for people.

**Comment by JarvanMo** [comment]
@zhbh Thanks for suggestions. Actually, I had published my own pod long time ago but there is some network issues. I had to give up. The best solution is to use official pod but it had been updated for a very long time. Anyway, I'll find a way.
