### ISSUE TITLE
vivo x60检测微信未安装

### ISSUE THREAD

**Issue by yml-222** [OpenFlutter/fluwx#430]
我的手机平时测试都是好的，上架到vivo应用商城使用vivo x60测试微信登录时无法检测到已安装的微信，以下是测试视频

https://user-images.githubusercontent.com/65451783/136503350-0d6339de-e162-4cbd-ae6c-82ed43fb9db8.mp4

**Comment by PigXiuYang** [comment]
你这可能跟Android 11有关。可以尝试在AndroidManifest.xml中添加
`    <queries>
        <package android:name="com.tencent.mm" />   
    </queries>
`
[这是官方文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/Android.html#jump2)
