### ISSUE TITLE
fluwx: 2.6.2  收不到  微信 h5 wx-open-launch-app    打开 APP  的回调呢   

### ISSUE THREAD

**Issue by wkowko** [OpenFlutter/fluwx#435]
使用的  fluwx: 2.6.2    微信wx-open-launch-app    打开 APP     weChatResponseEventHandler.listen((event) {});  这个方法没有回调     getExtMsg();  这个方法也没有    是 fluwx: 2.6.2 这个版本不支持吗

**Comment by JarvanMo** [comment]
这个版本有问题
