### ISSUE TITLE
微信支付时使用微信分身支付，支付失败

### ISSUE THREAD

**Issue by wLingy** [OpenFlutter/fluwx#437]
**Describe the bug**

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

**Comment by JarvanMo** [comment]
分身的问题无能为力
