### ISSUE TITLE
kotlin版本为什么要那么高呢？

### ISSUE THREAD

**Issue by fengqiangboy** [OpenFlutter/fluwx#44]
很多其他插件都不会这个高的kotlin版本。。。导入之后会有冲突

**Comment by JarvanMo** [comment]
技术跟进，你可以使用旧版本。

**Comment by fengqiangboy** [comment]
挺不错的，不过个人认为对于一个三方框架来说，兼容性应该要比技术跟进重要吧~

**Comment by JarvanMo** [comment]
@fengqiangboy 作为一个独立项目fluwx的编译是没问题的，这意味着fluwx是没有问题的。pub上有成千上万的插件，为什么是fluwx兼容他们，或者说fluwx怎么去兼容成千上万的插件。

**Comment by fengqiangboy** [comment]
> @fengqiangboy 作为一个独立项目fluwx的编译是没问题的，这意味着fluwx是没有问题的。pub上有成千上万的插件，为什么是fluwx兼容他们，或者说fluwx怎么去兼容成千上万的插件。

:+1:
