### ISSUE TITLE
MissingPluginException(No implementation found for method sendAuth on channel com.jarvanmo/fluwx)

### ISSUE THREAD

**Issue by rodriguez10100** [OpenFlutter/fluwx#443]
I'm trying to invoke the `sendWeChatAuth()` method but when I try to, I see the `MissingPluginException(No implementation found for method sendAuth on channel com.jarvanmo/fluwx)` exception. 

I'm currently using version 3.6.1+4 of fluwx

**Comment by JarvanMo** [comment]
Please update your kotlin version as the example does.
