### ISSUE TITLE
求助，无法下载com.tencent.mm.opensdk:wechat-sdk-android-without-mta

### ISSUE THREAD

**Issue by 2673542667** [OpenFlutter/fluwx#444]
前几天还好好的，今天打包突然报错，Failed to list versions for com.tencent.mm.opensdk:wechat-sdk-android-withou，然后还有503什么的，是什么问题呢

**Comment by 2673542667** [comment]
![image](https://user-images.githubusercontent.com/27001255/146529557-05f54d4d-3ca8-4d44-b396-a77a27c93f9b.png)

**Comment by JarvanMo** [comment]
确保添加了mavenCentral

**Comment by tjswk2008** [comment]
> 

请问下该如何配置呢？

**Comment by JarvanMo** [comment]
在你的app目录找到project的`build.gradle`:
```
    repositories {
        google()
        mavenCentral()
    }
```
确保mavenCentral()已经添加了

**Comment by tjswk2008** [comment]
我是这么配置的：
![image](https://user-images.githubusercontent.com/17583754/149862152-cce28678-78f2-4f05-8f0e-41b1d54b8584.png)

**Comment by tjswk2008** [comment]
换配置后还是报一样的错误哦：
![image](https://user-images.githubusercontent.com/17583754/149862684-99cfceab-d77e-4c32-bf41-badcdfafb161.png)

**Comment by JarvanMo** [comment]
看看别的地址是不是也设置了代理之类的，不可能找不到sdk。一定就是仓库源配置有问题。你看下面的错误信息他搜索mavenCentral了吗。
[微信SDK就在这里](https://search.maven.org/artifact/com.tencent.mm.opensdk/wechat-sdk-android/6.8.0/aar)。
