### ISSUE TITLE
求助，IOS微信登录不能触发fluwx.responseFromAuth.listen逻辑，为什么？

### ISSUE THREAD

**Issue by todaycoder001** [OpenFlutter/fluwx#45]

**Comment by todaycoder001** [comment]
补充一下，能调起微信，并显示授权的页面，点击确认登录后能回到原APP。

**Comment by JarvanMo** [comment]
[多看readme](https://github.com/OpenFlutter/fluwx/blob/master/doc/RESPONSE_CN.md)

**Comment by todaycoder001** [comment]
好的，多谢

**Comment by todaycoder001** [comment]
问题已解决： 具体参照example里面的AppDelegate.h和AppDelegate.m配置
