### ISSUE TITLE
能否支持一下微信签约的功能  openBusinessView

### ISSUE THREAD

**Issue by zuoxueliangIOS** [OpenFlutter/fluwx#457]
你好，不知道什么时间能支持一下微信签约的功能，微信的SDK1.8.4就已经支持了openBusinessView功能。
https://pay.weixin.qq.com/wiki/doc/api/wxpay_v2/papay/chapter5_2.shtml

**Comment by JarvanMo** [comment]
这个功能有啊

**Comment by JarvanMo** [comment]
@zuoxueliangIOS 我知道怎么回事了。不知道啥时候给删除了。

**Comment by JarvanMo** [comment]
我把dart的代码找找看。

**Comment by mafanwei** [comment]
#458

**Comment by JarvanMo** [comment]
@mafanwei  Thank you and I'll add iOS part later. Once it's done, I'll publish it.

**Comment by JarvanMo** [comment]
3.8.0 is released now.
