### ISSUE TITLE
WXApi registerApp:APP_ID universalLink:UNIVERSAL_LINK] IOS下怎么加，加了报找不到WXApi.h文件

### ISSUE THREAD

**Issue by emptyheadworm** [OpenFlutter/fluwx#459]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    //向微信注册
    [WXApi registerApp:APP_ID
universalLink:UNIVERSAL_LINK];
    return YES;

**Comment by JarvanMo** [comment]
I 'll have a look at this.

**Comment by JarvanMo** [comment]
@emptyheadworm Please try the following code in `3.8.1`:
```oc
#import "FluwxDelegate.h"
[[FluwxDelegate defaultManager] registerWxAPI:@"" universalLink:@""];

```
