### ISSUE TITLE
支付成功后，按物理按键或华为手机自动返回商户APP，fluwx.responseFromPayment.listen无效，监听不到返回数据

### ISSUE THREAD

**Issue by xj728** [OpenFlutter/fluwx#46]
支付成功后，按物理按键或华为手机自动返回商户APP，fluwx.responseFromPayment.listen无效，监听不到返回数据。
如果点击微信支付成功页面的返回商户按钮，则没有问题。

**Comment by JarvanMo** [comment]
恕我无法再现。

**Comment by xj728** [comment]
安卓下，微信支付完成后，如果是自动跳回到APP客户端，就监听不到返回值，如果是手动点击支付成功，返回到APP，就可以监听到

**Comment by see-sea** [comment]
返回你直接去服务器查询是否成功行了

**Comment by xj728** [comment]
是什么原因呢？ 付款完后，有时候微信自动退出，弹出客户端APP，有时候需要手动点击付款成共界面上的付款成功按钮。自动弹出客户端的，监听就失败了
