### ISSUE TITLE
fluwx_no_pay 3.8.0 代码有错误，else if {}  大括号位置比不对

### ISSUE THREAD

**Issue by xiaocode337317439** [OpenFlutter/fluwx#460]
fluwx_no_pay 3.8.0

<img width="930" alt="截屏2022-03-06 下午3 06 56" src="https://user-images.githubusercontent.com/21286091/156912919-6422f9a9-9e45-474b-9179-504a42de1e1f.png">

**Comment by JarvanMo** [comment]
3.8.0+1 released.
