### ISSUE TITLE
Android 12编译报错

### ISSUE THREAD

**Issue by hs029** [OpenFlutter/fluwx#461]
**Describe the bug**
用compileSdkVersion 31编译不通过，报错：

Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

进一步debug，发现是manifest mege错误：

Merging Errors: Info Attribute activity#com.jarvan.fluwx.wxapi.FluwxWXEntryActivity@taskAffinity at AndroidManifest.xml:18:13-52 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 17 Info Attribute activity-alias#${applicationId}.wxapi.WXEntryActivity@name at AndroidManifest.xml:22:13-66 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 21 Info Attribute activity-alias#${applicationId}.wxapi.WXEntryActivity@taskAffinity at AndroidManifest.xml:26:13-52 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 25 Info Attribute activity-alias#${applicationId}.wxapi.WXPayEntryActivity@name at AndroidManifest.xml:36:13-69 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 35 Info Attribute provider#com.jarvan.fluwx.FluwxFileProvider@authorities at AndroidManifest.xml:52:13-65 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 51 Info Attribute activity#com.jarvan.fluwx.wxapi.FluwxWXEntryActivity@taskAffinity at AndroidManifest.xml:18:13-52 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 17 Info Attribute activity-alias#${applicationId}.wxapi.WXEntryActivity@name at AndroidManifest.xml:22:13-66 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 21 Info Attribute activity-alias#${applicationId}.wxapi.WXEntryActivity@taskAffinity at AndroidManifest.xml:26:13-52 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 25 Info Attribute activity-alias#${applicationId}.wxapi.WXPayEntryActivity@name at AndroidManifest.xml:36:13-69 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 35 Info Attribute provider#com.jarvan.fluwx.FluwxFileProvider@authorities at AndroidManifest.xml:52:13-65 requires a placeholder substitution but no value for <applicationId> is provided. android.fluwx main manifest (this file), line 51

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.
3.8.0

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
[✓] VS Code (version 1.64.2)
[✓] Proxy Configuration
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by JarvanMo** [comment]
Please try 3.8.0+1
