### ISSUE TITLE
conflicting names: libwechatsdk.a.

### ISSUE THREAD

**Issue by yuyangkk** [OpenFlutter/fluwx#464]
背景：
iOS原生项目集成flutter，原生已有分享并且集成WeChatOpenSDK: 1.8.7.1，Flutter端集成fluwx_no_pay: 3.8.1

操作：
在原生项目下进行pod install

结果：
控制台输出：[!] The 'Pods-QianGunGun' target has libraries with conflicting names: libwechatsdk.a.

尝试解决：删除原生pod

请问这种怎么解决呢？感谢

**Comment by JarvanMo** [comment]
你fork一份fluwx，并把分支切换到no_pay_nullsafety，然后把里面的 libwechatsdk.a删除掉试试

**Comment by yuyangkk** [comment]
> 你fork一份fluwx，并把分支切换到no_pay_nullsafety，然后把里面的 libwechatsdk.a删除掉试试

感谢大佬百忙之中回复，刚才试了下集成fluwx，目前来看是可以了，后面我再验证验证，然后按照您说的方式尝试一下

**Comment by JarvanMo** [comment]
不过你这原生里已经接入带支付的了，感觉没必要接no_pay了

**Comment by yuyangkk** [comment]
> 不过你这原生里已经接入带支付的了，感觉没必要接no_pay了

嗯嗯，谢谢大佬指导，后面有问题再请教您
