### ISSUE TITLE
fluwx_no_pay 3.7.0 版本之后无法编译安卓版本

### ISSUE THREAD

**Issue by doubletcjs** [OpenFlutter/fluwx#466]
compileSdkVersion 31
buildToolsVersion "30.0.3"

minSdkVersion 17
targetSdkVersion 30

ext.kotlin_version = '1.5.21'
classpath 'com.android.tools.build:gradle:4.2.2'

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip

fluwx_no_pay 3.7.0 之后所有版本，能够flutter run，但是无法flutter build apk。都报下面错误。

* What went wrong:
Execution failed for task ':fluwx_no_pay:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:$HOME/.gradle/caches/transforms-2/files-2.1/a4ae8b6b415f31b46ca6dfa3619b0d4e/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by JarvanMo** [comment]
```
Flutter (Channel stable, 2.10.3, on Deepin 20.5 5.15.24-amd64-desktop, locale zh_CN.UTF-8)
```
新建了一个工程，
```
  fluwx_no_pay: ^3.8.1
```
`flutter build apk`完全没问题。

**Comment by JarvanMo** [comment]
try with Kotlin 1.6.10.

**Comment by JarvanMo** [comment]
Duplicate of #470

**Comment by JarvanMo** [comment]
我才想起来，可能是你们compileSDK版本的问题。
