### ISSUE TITLE
希望加一个自动订阅续费的功能（例如：会员 按月、季度、年 自动续费）

### ISSUE THREAD

**Issue by zuoxueliangIOS** [OpenFlutter/fluwx#467]
这个是微信的续费签约的API 文档
 https://pay.weixin.qq.com/wiki/doc/api/wxpay_v2/papay/chapter3_2.shtml

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/12217375/159857295-33853a28-ea65-4912-89a0-16ed5aeff101.png">

**Comment by JarvanMo** [comment]
看看是不是这个
```dart
autoDeDuctWeChat();
```

**Comment by zuoxueliangIOS** [comment]
不是autoDeduct，autoDeduct虽然也是用了businessType =  12的类型，但是两者所需要的参数是不一样的
autoDeduct
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/12217375/160306428-5ad5ef08-d8e5-49bf-8713-308c4ca9ca34.png">
![image](https://user-images.githubusercontent.com/12217375/160306482-de21375a-4003-4f73-915d-8a4ceff77d41.png)
App签约
![image](https://user-images.githubusercontent.com/12217375/160306482-de21375a-4003-4f73-915d-8a4ceff77d41.png)


> 看看是不是这个
> 
> ```dart
> autoDeDuctWeChat();
> ```

**Comment by JarvanMo** [comment]
应该是一样的。只不过之前的不是我做的。我稍后更新一下吧

**Comment by JarvanMo** [comment]
3.8.2 released
