### ISSUE TITLE
将flutter工程包括fluwx的模块打包成aar，在其他应用调用时候报错，应该如何打包aar？

### ISSUE THREAD

**Issue by jy4618272** [OpenFlutter/fluwx#47]
将flutter工程包括fluwx的模块打包成aar，在其他应用调用时候报错，应该如何打包aar？

**Comment by jy4618272** [comment]
目前主要发现是fluwx的依赖的相关资源未能正常打包到aar中去，需要怎么处理？

**Comment by JarvanMo** [comment]
???

**Comment by jy4618272** [comment]
将fluwx开发的模块集成进旧的原生andriod应用出现以上问题

**Comment by JarvanMo** [comment]
说半天也不知道你说的是什么问题。

**Comment by jy4618272** [comment]
用flutter开发了一个module，里面用到了fluwx，然后将这个module打包成aar，在andriod原生工程里面引用。发现打出来的aar包里面并不包括fluwx的一些依赖资源，如kotlin相关的东西。从而导致原生工程无法正常启动，直接闪退。现在的问题是想在原生里面调用这个模块，该如何解决？

**Comment by JarvanMo** [comment]
1.我都不知道什么错误
2.这个问题属于fluwx

**Comment by chdyiboke** [comment]
@jy4618272 大哥大哥，这个有成功吗？将flutter工程包括fluwx的模块打包成aar，在其他应用调用。
