### ISSUE TITLE
fluwx_no_pay:verifyReleaseResources error 

### ISSUE THREAD

**Issue by weiqingtangx** [OpenFlutter/fluwx#470]
你好，我在打包apk的时候报这个错误，debug版本没有报错，帮忙看看可能是什么问题，谢谢.

[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':fluwx_no_pay:verifyReleaseResources'.
[        ] > A failure occurred while executing
com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > 1 exception was raised by workers:
[        ]      com.android.builder.internal.aapt.v2.Aapt2Exception: Android
resource linking failed
[        ] 
/Users/sunny/.gradle/caches/transforms-2/files-2.1/505e67883c06ec8c5f1806abc6702572/
core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource
android:attr/lStar not found.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 10s

**Comment by weiqingtangx** [comment]
没有解决，回退版本3.8.2-3.4.1临时解决了。

**Comment by adger-me** [comment]
怎么解决的，我也遇到了

**Comment by JarvanMo** [comment]
我才想起来，可能是你们compileSDK版本太低的问题。

**Comment by sunjianan9900** [comment]
同样的问题
compileSdkVersion 是 31
minSdkVersion 是 21
ext.kotlin_version = '1.6.10'
classpath 'com.android.tools.build:gradle:7.0.4'
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:2.0.1'
}
还有哪里不对呢？

**Comment by JarvanMo** [comment]
看其他关联问题
