### ISSUE TITLE
订阅自定义消息在iOS中无法正常返回，android正常。

### ISSUE THREAD

**Issue by tenutos** [OpenFlutter/fluwx#471]
感谢fluwx这个项目。
反馈一个bug:
订阅自定义消息在iOS中无法接收返回，android正常。
日常使用的iOS版本为15.4。(应该和iOS版本没关系，在一个更低版本的iOS中问题照旧)。

**Comment by JarvanMo** [comment]
我没环境测试这个问题，订阅自定义消息是对应哪个方法？

**Comment by tenutos** [comment]
fluwx_iml.dart 177行

/// subscribe WeChat message
Future<bool> subscribeWeChatMsg({
  required String appId,
  required int scene,
  required String templateId,
  String? reserved,
}) async {
  return await _channel.invokeMethod(
    'subscribeMsg',
    {
      'appId': appId,
      'scene': scene,
      'templateId': templateId,
      'reserved': reserved,
    },
  );
}

**Comment by zuoxueliangIOS** [comment]
在FluwxResponseHandler.m中 出现了空指针，修改一下就可以了
修改一下源代码
![image](https://user-images.githubusercontent.com/12217375/163813293-ec4ef14e-ab2f-4729-be01-52656bea073e.png)

**Comment by zuoxueliangIOS** [comment]
> 我没环境测试这个问题，订阅自定义消息是对应哪个方法？

大佬，稍微修改一下这个bug，就是空指针引起的

**Comment by JarvanMo** [comment]
你可以提个PR来修复一下。

**Comment by tenutos** [comment]
最新版=>3.8.4+1 打包后发现问题依旧。

**Comment by JarvanMo** [comment]
@tenutos 改错了，我修复一下

**Comment by tenutos** [comment]
感谢兄弟。

**Comment by tenutos** [comment]
兄弟用最新的3.8.4+2版本重新构建的iOS应用，问题依旧。

**Comment by tenutos** [comment]
最新版3.8.5打包完测试，问题仍然存在。

**Comment by JarvanMo** [comment]
我我可真就不知道了，我没有测试环境，看不出来具体问题。你其他的回调都好用？

**Comment by JarvanMo** [comment]
这东西涉及冷热启动么

**Comment by tenutos** [comment]
不涉及冷热启动，我只使用了3个回调，2个正常，1个异常：

**Comment by JarvanMo** [comment]
能不能抓一下iOS 日志啊，这么猜不行啊。看看是不是空指针还是什么问题

**Comment by tenutos** [comment]
我iOS不熟，然后手上没有mac(只有iphone)，在windows上跑虚拟机构建的ipa。应用里边这个回调也没啥大影响，等手上有mac了，我再找找原因看看。感谢！
