### ISSUE TITLE
Gridle 4.1.1 下，打包会报错 core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found

### ISSUE THREAD

**Issue by adger-me** [OpenFlutter/fluwx#472]
目前解决办法是降低 `androidx.appcompat:appcompat:1.4.1` 到 `androidx.appcompat:appcompat:1.3.1`，能够解决，不知道有没有更好的办法

**Comment by JarvanMo** [comment]
只能选择降低了，因为compileSDK已经升级了。
Duplicate of #470

**Comment by JarvanMo** [comment]
再或者自己fork一份随便改

**Comment by adger-me** [comment]
> 再或者自己fork一份随便改

对目前我是 fork 了
