### ISSUE TITLE
分享能否区分来自那个页面

### ISSUE THREAD

**Issue by liuzehnhang** [OpenFlutter/fluwx#495]
能否在回调里判断分享是那个page调用的

**Comment by JarvanMo** [comment]
官方SDK 支持就支持，不支持就不支持

**Comment by liuzehnhang** [comment]
安卓原生官方支持&nbsp; transaction&nbsp; 字段，可以用来区分，但是我看fluwx&nbsp; 分享并没有这个字段



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月26日(周五) 中午11:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenFlutter/fluwx] 分享能否区分来自那个页面 (Issue #495)




 
官方SDK 支持就支持，不支持就不支持

**Comment by JarvanMo** [comment]
iOS不支持这个字段
