### ISSUE TITLE
ios分享微信小程序，可以拉起微信，但是不能分享。android没有问题。fluwx版本3.9.2，ios版本ios16

### ISSUE THREAD

**Issue by GerJeffrey** [OpenFlutter/fluwx#498]
var model = WeChatShareMiniProgramModel(
      webPageUrl: "https://app.xxxxxx.com",
      userName: "xxxxxxx",
      title: "${currentArticle.value.title}",
      path: "/pages/viewArticle/viewArticle?id=${currentArticle.value.id}",
      description: "${currentArticle.value.title}",
      thumbnail: WeChatImage.network(
          "${Constants.REMOTE_FILE_STORAGE_IP}${Constants.MINI_PROG_PROFILE}"),
    );
    var result = await isWeChatInstalled;
    if (result != true) {
      Get.error(content: Text("请安装微信后再试！"));
    }
    logger.d("shareToWxFriend:$result");
    return shareToWeChat(model);

**Comment by JarvanMo** [comment]
有什么具体现象吗

**Comment by YTiOSer** [comment]
我这里也遇到了，fluwx版本 3.11.0 跳到微信每次都会显示正在链接，链接后进入微信页面没有让选择分享给谁的页面，点击也无法分享

**Comment by YTiOSer** [comment]
我的已解决，是由于linkurl后面的斜杠引起的，去掉就可以了

**Comment by moujunqiang** [comment]
> 我的已解决，是由于linkurl后面的斜杠引起的，去掉就可以了
你好我也碰到了这个问题，想问下linkurl是怎么配置的，我在微信开放平台配置的是https://xxxx/app/
