### ISSUE TITLE
图片分享不显示图片

### ISSUE THREAD

**Issue by wangpingtaohn** [OpenFlutter/fluwx#499]
截图保存图片分享后，分享好友只能在弹窗里看到缩略图，分享出去后，聊天窗口没有图片，而分享到朋友圈时，直接没有图片显示
fluwx_no_pay: ^3.9.0
手机设备：小米 9 Pro 系统版本：10

`
     LogUtils.d('filePath=$filePath');

    WeChatShareImageModel model;
    if (filePath != null) {
      model = WeChatShareImageModel(WeChatImage.file(File(filePath)),
          title: title, description: decs, scene: scene);
    } else if (url != null) {
      model = WeChatShareImageModel(WeChatImage.network(url),
          title: title, description: decs, scene: scene);
    } else if (asset != null) {
      model = WeChatShareImageModel(WeChatImage.asset(asset),
          title: title, description: decs, scene: scene);
    } else {
      throw Exception("缺少图片资源信息");
    }
    shareToWeChat(model);
`
图片路径不为空：filePath=/data/user/0/com.xxx.xxxx/cache2022-09-27T18:32:19.253188.jpg
也没有报什么错误信息：
`
MicroMsg.SDK.WXMsgImplComm(31489): pass
I/MicroMsg.SDK.Util(31489): getFileSize with content url
I/MicroMsg.SDK.WXApiImplV10(31489): sendReq, req type = 2
I/MicroMsg.SDK.WXApiImplV10(31489): getTokenFromWX token is wx6c3dc97df5f86f36--1809121114-1664274739379
D/MicroMsg.SDK.MMessageAct(31489): send, targetPkgName = com.tencent.mm, targetClassName = com.tencent.mm.plugin.base.stub.WXEntryActivity, launchMode = 2
I/MicroMsg.SDK.MMessageAct(31489): sendUsingPendingIntent
D/MicroMsg.SDK.MMessageAct(31489): send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras) }
I/MicroMsg.SDK.MMessageAct(31489): sendUsingPendingIntent onSendFinished resultCode: 0, resultData: null
`

**Comment by QiPg** [comment]
同样呢问题
fluwx: ^3.11.0

**Comment by AlexV525** [comment]
如果新版存在问题，烦请重新开 issue 并提供基于新版的代码示例，谢谢
