### ISSUE TITLE
请问关于iOS插件目录下 fluwx.podspec 文件相关的问题

### ISSUE THREAD

**Issue by OmgKevin** [OpenFlutter/fluwx#50]
问题一：在fluwx.podspec文件中 ，您写的  s.preserve_paths = 'Lib/*.a' 与 s.vendored_libraries = "**/*.a" 有什么区别呢 ？是一样都指向的的路径 ios-Lib-libWeChatSDK.a 这个文件的嘛 ？

问题二：请问要是我除了libWeChatSDK.a 之外还有其他多个的.a或者.framework文件，这个时候我要在fluwx.podspec文件中如何编辑呢 ？

**Comment by JarvanMo** [comment]
我刚接触ios，也不是太懂。
其他的可以参考[tobias](https://github.com/OpenFlutter/tobias)。
具体什么意思恕我无能为力。

**Comment by JarvanMo** [comment]
如果有多个.a，上面的就可以满足，Lib/*.a表示Lib下的所有.a文件。*是通配符。framework同理。如果不同目录应该可以使用['Lib/aa.a','Lib2/bb.a']

**Comment by OmgKevin** [comment]
所以当自己的Lib目录下有多三个.a库与四个.framework库时，我这样写就是可以的对吧 

  s.preserve_paths = 'Lib/*.a'
  s.vendored_libraries = "**/*.a"
  
  s.preserve_paths = 'Lib/*.framework'
  s.vendored_libraries = "**/*.framework"

**Comment by JarvanMo** [comment]
我无法确认。

**Comment by JarvanMo** [comment]
这个问题可以请教熟悉ios的人

**Comment by OmgKevin** [comment]
好的，谢谢你

**Comment by JarvanMo** [comment]
我好像说错了参考项目，可以参考[这个](https://github.com/JarvanMo/OpenAliPaySDK)
