### ISSUE TITLE
ios16调起微信频繁弹框提示剪切板读取

### ISSUE THREAD

**Issue by BugLai** [OpenFlutter/fluwx#500]
微信SDK低版本是通过剪切板进行信息传递，但是在iOS16系统会频繁弹框，严重阻断用户操作，微信SDK新版本已修复，希望可以更新最新最新版1.9.6.

相关资料： https://developers.weixin.qq.com/community/develop/doc/000ac2067c82b85b064e79f0455401

**Comment by JarvanMo** [comment]
谢谢。最近太忙了，我更新一下。

**Comment by JarvanMo** [comment]
try 3.10.0.
