### ISSUE TITLE
微信订阅问题

### ISSUE THREAD

**Issue by chen412115** [OpenFlutter/fluwx#504]
大佬  提个bug
我在测试中  发现微信订阅结果中只返回了openid、templateId、action、reserved、scene几个字断，并没有errorCode和errorStr

WeChatSubscribeMsgResponse这个model在解析到时候，就报错了

fluwx版本： 3.10.0  android系统

应改为
WeChatSubscribeMsgResponse.fromMap(Map map){
      openid = map['openid'];
      templateId = map['templateId'];
      action = map['action'];
      reserved = map['reserved'];
      scene = map['scene'];
  }

**Comment by JarvanMo** [comment]
你可以提交个PR吗。谢谢。

**Comment by chen412115** [comment]
> 你可以提交个PR吗。谢谢。

有两种方式
第一种是 将errCode改为可选类型 和 errStr一样
第二种是如果errorCode为空时，将其置为0   super._(map[_errCode] ?? 0, map[_errStr]);
因为 是否订阅成功，微信有个返回值  action 为 confirm时是成功   cancel是取消，暂时还没有遇到其他的情况

哪种方式好一点

**Comment by JarvanMo** [comment]
我觉得可空的可能更好一些

**Comment by JarvanMo** [comment]
3.11.0 released.
