### ISSUE TITLE
iPhone7 微信支付成功后，返回APP闪退

### ISSUE THREAD

**Issue by chen412115** [OpenFlutter/fluwx#506]
在iPhone7上，使用微信支付完成后 点击“返回商家” 回到APP后闪退
下面是详细信息
![图片](https://user-images.githubusercontent.com/20555613/200509188-d95d01c1-3296-41d0-bdcd-c17064badb7a.png)

其他的手机上没有问题

fluwx 版本是 3.9.2  使用3.11.0也会闪退

**Comment by JarvanMo** [comment]
我看看，应该是extData nil了
