### ISSUE TITLE
3.10 ，微信内h5可以拉起app，但是app内获取启动数据时，为空。

### ISSUE THREAD

**Issue by bladeofgod** [OpenFlutter/fluwx#507]
你好， 微信内部h5，拉起（冷启动）app，并跳转到指定页面，android是正常的，但是ios获取到的 getExtMsg() 为空。
麻烦帮忙看一下，谢谢

**Comment by zhangshuqi** [comment]
解决了吗这个问题

**Comment by ZhangZhiH** [comment]
@bladeofgod  @zhangshuqi  请问ios 你是通过universalLink拉起的吗 如何传参?

**Comment by JarvanMo** [comment]
4.1.0

**Comment by JarvanMo** [comment]
4.2.4
