### ISSUE TITLE
有用户反馈Android 13登录不了的问题，还有人有这样的问题吗？

### ISSUE THREAD

**Issue by zeewell** [OpenFlutter/fluwx#509]
有不少用户反应Android13的手机登录不上（典型的如：vivo的V2231A机器）。手里没有这几个设备，没法调试。还有人有这样的问题吗？

从用户截的几个图来看：
能拉起微信，然后微信还有个转圈的loading，接着不知道是微信退出了，还是微信返回到了App，留在App的界面上，没有任何的提示信息。。

**Comment by JarvanMo** [comment]
看起来和插件本身没有关系，需要看看微信SDK是否进行了升级。

**Comment by JarvanMo** [comment]
有更新的话我会进行更新

**Comment by zeewell** [comment]
如果是SDK的版本问题的话，或者直接改成 `com.tencent.mm.opensdk:wechat-sdk-android:+` 是否合理？

**Comment by JarvanMo** [comment]
你可以fork一份，然后改成用+的形式测试一下。我这之所以不用+是怕微信突然有什么api变更导致编译不过去，有次遇到这样的的情况

**Comment by JarvanMo** [comment]
我现在没有andriod13，也不太方便测试微信相关的东西，不知道你那能不能复现一下？

**Comment by JarvanMo** [comment]
Fluwx android这块最新代码用的确实是最新的sdk，但是我这没环境测试

**Comment by zeewell** [comment]
> 我现在没有andriod13，也不太方便测试微信相关的东西，不知道你那能不能复现一下？

我手头也没有Android 13设备。也是这周突然有几个用户反馈说登录不了，不然都没注意到。

但从后台的数据来看，最近一个月Android13登录了的用户非常非常少，我也不确定那些登录了的用户是不是因为之前是12版本，后来把系统升级到13，还是他们在13上登录成功了。（我的App可以登录使用，也可以不登录使用，功能稍有点限制而已）

**Comment by jacky4631** [comment]
VIVO X80 PRO同样的情况，没有回调

**Comment by zeewell** [comment]
> VIVO X80 PRO同样的情况，没有回调

也是13吗？

**Comment by JarvanMo** [comment]
我现在想测试微信 的东西还是有点麻烦，没有测试应用。

**Comment by JarvanMo** [comment]
不太清楚demo app现在能不能测试登录

**Comment by zeewell** [comment]
看来确实好像是个普遍现象，刚查了下 VIVO X80 PRO 也是Android13

**Comment by JarvanMo** [comment]
大家一起看看吧，人多力量大

**Comment by zeewell** [comment]
> VIVO X80 PRO同样的情况，没有回调

你有设备吗？能调试吗？

**Comment by jacky4631** [comment]
> 

没设备，远程真机，能调试就知道原因了

**Comment by JarvanMo** [comment]
等我抽空再看看

**Comment by jacky4631** [comment]
我这边有一份VIVO X80 PRO的日志文件，就是在操作微信登录时产生的
[点击下载日志文件](https://pan.baidu.com/s/1G-AF6mnoKmvCDJ08_Eb53g?pwd=6nd8)

**Comment by JarvanMo** [comment]
等我周末研究一下吧

**Comment by JarvanMo** [comment]
@jacky4631 @zeewell 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [版本 10.0.19044.2251], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```

手机：OnePlus 10 Plus
Andorid 13。
测试了一下没问题啊

**Comment by JarvanMo** [comment]
![ddefa3fb099ad2a127afde24eb1b351](https://user-images.githubusercontent.com/11608487/205319994-5af30415-2456-496d-b21e-987336d75d5a.jpg)

**Comment by jacky4631** [comment]
VIVO X80 PRO和小米12 PRO试过都不行，没有回调

**Comment by jacky4631** [comment]
VIVO是上架时，官方检测到功能不可用

**Comment by JarvanMo** [comment]
![1669993396354](https://user-images.githubusercontent.com/11608487/205322690-753e85ab-9be7-4b0c-910e-bec0f6eff5b7.png)
特意在优测上租了一台VIVO X80 PRO，demo代码没问题

**Comment by JarvanMo** [comment]
搞错了，我重新试一下

**Comment by zeewell** [comment]
这么看是和厂商定制的ROM相关，是不是有什么系统的默认配置？或者权限什么的？

微信其实也没有报错，但就是数据没传回来。

**Comment by JarvanMo** [comment]
我刚刚的机器不是Android 12. 现在优测只有一台13。都 不是他两个。

**Comment by zeewell** [comment]
还有VIVO的neo7也是有问题的

**Comment by JarvanMo** [comment]
![1669993887879](https://user-images.githubusercontent.com/11608487/205324292-411d1b11-30ae-4992-9b6f-49d380ace79c.png)
 目前来看，我跑的demo代码（appid什么的换了），刚刚在优测上测试了Find X5 Pro，code是可以拿到的。

**Comment by zeewell** [comment]
@JarvanMo 刚看了下，小米云测有12 pro机器。

**Comment by jacky4631** [comment]
compileSdkVersion 33
targetSdkVersion 32
这样可以

compileSdkVersion 33
targetSdkVersion 33
这样就不行了

**Comment by zeewell** [comment]
搜了一下，目前能找到的官方资料是 https://developers.weixin.qq.com/community/develop/doc/0006caacccc4587417cc1b68951001

targetSdkVersion 30
别说33，会不会31都还不支持呢……

**Comment by JarvanMo** [comment]
@jacky4631 @zeewell 哎呀，的确忽略了compile 和target 的问题

**Comment by zeewell** [comment]
https://github.com/OpenFlutter/fluwx/blob/bea5334c733851c1f8da94f2353d090a965dc4a1/android/build.gradle#L28
那是不是在这下面也加一行 `targetSdkVersion 30` ? 就算作为提示也可以。当作一种申明，我只支持到30哈

**Comment by JarvanMo** [comment]
> https://github.com/OpenFlutter/fluwx/blob/bea5334c733851c1f8da94f2353d090a965dc4a1/android/build.gradle#L28
> 
> 
> 那是不是在这下面也加一行 `targetSdkVersion 30` ? 就算作为提示也可以。当作一种申明，我只支持到30哈

这块没用

**Comment by zeewell** [comment]
这个issue关掉了哈，好像问题已经fix了其实。

**Comment by CyJaySong** [comment]
@zeewell  目前来说也不算是完全解决了, targetSdkVersion > 32 是不能正常登录的, compileSdkVersion > 32不影响;临时解决办法就是 targetSdkVersion <= 32

**Comment by CyJaySong** [comment]
@JarvanMo 建议置顶一下，方便其他开发者排查

**Comment by menol** [comment]
我的targetSdkVersion > 32，我自己去掉了intent-filter后可以正常使用，不知道sdk加上这个是实现什么功能?

**Comment by JarvanMo** [comment]
@menol 哪个filter?确定吗？有个intentfilter 是为了处理h5调用app 的

**Comment by JarvanMo** [comment]
如果确定，我想法改一下

**Comment by menol** [comment]
> @menol 哪个filter?确定吗？有个intentfilter 是为了处理h5调用app 的

android 13的intentfilter 变得严格了
https://developer.android.com/guide/components/intents-filters
https://zhuanlan.zhihu.com/p/516291843
由于我不确定那两个intentfilter有什么用所以都给删了

**Comment by JarvanMo** [comment]
等我研究一下

**Comment by JarvanMo** [comment]
![IMG_20221216_162928](https://user-images.githubusercontent.com/11608487/208056786-bda70060-db64-475f-8e9c-0dc650d2f063.jpg)

**Comment by menol** [comment]
这是我的配置
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.jarvan.fluwx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    
    <queries>
        <package android:name="com.tencent.mm" />
    </queries>

    <application>
        <activity
            android:name=".wxapi.FluwxWXEntryActivity"
            android:launchMode="singleTask"
            android:exported="false"
            android:taskAffinity="${applicationId}"
            android:theme="@style/DisablePreviewTheme" />

        <activity-alias
            android:name="${applicationId}.wxapi.WXEntryActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:targetActivity="com.jarvan.fluwx.wxapi.FluwxWXEntryActivity"
            android:taskAffinity="${applicationId}"
            android:theme="@style/DisablePreviewTheme">






        </activity-alias>
        <activity-alias
            android:name="${applicationId}.wxapi.WXPayEntryActivity"
            android:exported="true"
            android:launchMode="singleInstance"
            android:targetActivity="com.jarvan.fluwx.wxapi.FluwxWXEntryActivity"
            android:theme="@style/DisablePreviewTheme">





        </activity-alias>

        <provider
            android:name="com.jarvan.fluwx.FluwxFileProvider"
            android:authorities="${applicationId}.fluwxprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/fluwx_file_provider_paths" />
        </provider>
    </application>
</manifest>

**Comment by JarvanMo** [comment]
好的，感谢，我理解错了。等我研究一下，如果可以就删除了
