### ISSUE TITLE
微信登录

### ISSUE THREAD

**Issue by ws4349893** [OpenFlutter/fluwx#51]
android提示:包名不正确,检查了包名确实没问题啊

**Comment by JarvanMo** [comment]
微信说包名不对就一定是不对的。检查applicationId还要不行就删除app。

**Comment by ws4349893** [comment]
我检查过很多次还是漏了..确实是包名不对..谢谢

**Comment by JarvanMo** [comment]
fluwx本身并不会输出日志信息，回传数据和日志尽量保证原汁原味，所以fluwx的大部分问题都可以百度的到，因为大部分问题是微信SDK的问题或者原生设置有问题。
