### ISSUE TITLE
3.12.0  ios pod 失败 

### ISSUE THREAD

**Issue by shichunlei** [OpenFlutter/fluwx#511]
**Describe the bug**
fluwx :3.12.0 ios pod 失败 

**To Reproduce**
![1670301789995](https://user-images.githubusercontent.com/7146745/205817560-90db11ac-40ab-4acf-ae3a-eef40ea928aa.jpg)

**Which version of Fluwx do you use?**
3.12.0

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)

**Comment by JarvanMo** [comment]
[Podfile ](https://github.com/OpenFlutter/fluwx/blob/master/example/ios/Podfile)  platform改成12.0或者更高
