### ISSUE TITLE
WeChat cannot paste in iOS16

### ISSUE THREAD

**Issue by vampiregain** [OpenFlutter/fluwx#513]
class FluwxResponseHandler need to implement the delegate method [WXApiDelegate onNeedGrantReadPasteBoardPermissionWithURL:] and invoke completion block to enable WeChat to paste when we open timeline share from other app

#Sample Code 
- (void)onNeedGrantReadPasteBoardPermissionWithURL:(nonnull NSURL *)openURL completion:(nonnull WXGrantReadPasteBoardPermissionCompletion)completion {
    dispatch_async(dispatch_get_main_queue(), ^{
        completion();
    });
}

**Comment by JarvanMo** [comment]
Could you please create a PR for this?
