### ISSUE TITLE
安卓flutter微信h5唤醒白屏，应该是跳转到了一个native界面，返回出去是flutterview

### ISSUE THREAD

**Issue by ZHUMINGZHE123** [OpenFlutter/fluwx#514]
安卓flutter微信h5唤醒白屏，应该是跳转到了一个native界面，返回出去是flutterview

**Comment by JarvanMo** [comment]
参看[example](https://github.com/OpenFlutter/fluwx/blob/bea5334c733851c1f8da94f2353d090a965dc4a1/example/android/app/src/main/AndroidManifest.xml#L40)

**Comment by JarvanMo** [comment]
4.1.0 released.
