### ISSUE TITLE
Android原生rom，分享图片时，会请求相册权限

### ISSUE THREAD

**Issue by sinexy** [OpenFlutter/fluwx#518]
Android原生rom，分享图片时，会请求相册权限

`fluwx: ^3.9.2`

使用该方法
```
await shareToWeChat(
          WeChatShareImageModel(WeChatImage.network(imgUrl!), scene: scene));
```
则会出现此问题

flutter doctor
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.2 21D49 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.74.0)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

```

**Comment by JarvanMo** [comment]
等我查一下代码

**Comment by sinexy** [comment]
> 
多谢回复，是andorid版本的问题。该issue已关闭。

**Comment by sinexy** [comment]
我已经看过代码了，是我自己的问题，代码逻辑没问题。在Android7以下必须要通过将图片保存在本地发自我的iPhone------------------ 原始邮件 ------------------发件人: JarvanMo  ***@***.***>发送时间: 2022年12月22日 13:33收件人: OpenFlutter/fluwx ***@***.***>抄送: sinexy ***@***.***>, Author ***@***.***>主题: 回复：[OpenFlutter/fluwx] Android原生rom，分享图片时，会请求相册权限 (Issue #518)
等我查一下代码

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OpenFlutter/fluwx/issues/518#issuecomment-1362438012",
"url": "https://github.com/OpenFlutter/fluwx/issues/518#issuecomment-1362438012",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
