### ISSUE TITLE
与腾讯云函数库同时编译报错

### ISSUE THREAD

**Issue by JackTheNoob** [OpenFlutter/fluwx#519]
**Describe the bug**
# 库使用情况：
### 腾讯云函数
  cloudbase_core: ^0.0.11
  cloudbase_auth: ^0.0.14
  cloudbase_function: ^0.0.2
  cloudbase_storage: ^0.0.3
### 微信SDK插件
  fluwx: ^3.12.2

>
iOS编译报符号重复错误。Error (Xcode): 609 duplicate symbols for architecture x86_64
cloudbase_auth引入WechatOpenSDK库，fluwx引入OpenWeChatSDK库，这2个库符号冲突了。

`
duplicate symbol '_OBJC_IVAR_$_WechatAuthSDK._status' in:
        /Users/*/Desktop/*/ios/Pods/OpenWeChatSDK/Pod/Library/lib/libWeChatSDK.a(WechatAuthSDK.o)
        /Users/*/Desktop/*/ios/Pods/WechatOpenSDK/OpenSDK1.9.9/libWechatOpenSDK.a(WechatAuthSDK.o)
    duplicate symbol '_OBJC_IVAR_$_WechatAuthSDK.timer' in:
        /Users/*/Desktop/*/ios/Pods/OpenWeChatSDK/Pod/Library/lib/libWeChatSDK.a(WechatAuthSDK.o)
        /Users/*/Desktop/*/ios/Pods/WechatOpenSDK/OpenSDK1.9.9/libWechatOpenSDK.a(WechatAuthSDK.o)
    duplicate symbol '_OBJC_IVAR_$_WechatAuthSDK.connection' in:
        /Users/*/Desktop/*/ios/Pods/OpenWeChatSDK/Pod/Library/lib/libWeChatSDK.a(WechatAuthSDK.o)
        /Users/*/Desktop/*/ios/Pods/WechatOpenSDK/OpenSDK1.9.9/libWechatOpenSDK.a(WechatAuthSDK.o)
`

**Comment by JarvanMo** [comment]
之前 有人提过类似的问题，你可以搜搜，可能需要fork一份，然后手动删除libWechatOpenSDK.o或者 WechatAuthSDK.o
