### ISSUE TITLE
分享后，打开微信出现未审核应用

### ISSUE THREAD

**Issue by VFiee** [OpenFlutter/fluwx#52]
![Uploading WechatIMG1.png…]()
如上图，但是已经审核通过。并获取审核通过后的AppID，也在info.plist里面添加appid了.

**Comment by VFiee** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/42051272/54803039-ca137400-4ca8-11e9-9eb5-ce0739a7b430.png)

**Comment by JarvanMo** [comment]
微信说啥就是啥，这都是微信的错误。和fluwx没有关系。建议你百度。
