### ISSUE TITLE
Error running on iPhone in vscode environment

### ISSUE THREAD

**Issue by llmmirror** [OpenFlutter/fluwx#521]
Mac 电脑是 M1芯片 错误信息：

Error (Xcode): In
/Users/xxx/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fluwx_no_pay-3.12.3/io
s/libWeChatSDK.a(WechatAuthSDK.o), building for iOS Simulator, but linking in object file built
for iOS, file
'/Users/xxx/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fluwx_no_pay-3.12.3/i
os/libWeChatSDK.a' for architecture arm64

**Comment by JarvanMo** [comment]
你可以试试新版本，我刚刚升级到了XCframework。

**Comment by JarvanMo** [comment]
不过我没M系列mac。

**Comment by JarvanMo** [comment]
Any progress?
