### ISSUE TITLE
安卓flutter微信h5唤醒冷启动白屏，应该是跳转到了一个native界面，返回出去是flutterview

### ISSUE THREAD

**Issue by loveshort** [OpenFlutter/fluwx#523]
1.按照教程来弄，完整的项目教程，冷启动依然是白屏

**Comment by JarvanMo** [comment]
参考一下[example](https://github.com/OpenFlutter/fluwx/blob/master/example/android/app/src/main/AndroidManifest.xml)配置一下meta-data还有intent filter

**Comment by JarvanMo** [comment]
`4.2.4` solved.
