### ISSUE TITLE
无法获取从小程序返回的ExtMsg

### ISSUE THREAD

**Issue by Dabbit-Chan** [OpenFlutter/fluwx#524]
目前暂且不知道前端同学的“返回App”按钮的实现方法是怎么样的，但他这个按钮确实能返回app。
返回app后触发了FlutterActivity的onRestart，但是intent的category是`android.intent.category.LAUNCHER`，没法触发`handleShowMessageFromWXBundle`。
到最后发现了`FluwxResponseHandler.handleLaunchMiniProgramResponse`，在这里确实能监听到返回的ExtMsg，但是这个方法最后call的是`FluwxPlugin.callingChannel?.invokeMethod("onLaunchMiniProgramResponse", result)`，而onLaunchMiniProgramResponse貌似没有注册，所以也就没能在flutter端监听到。
最后采取了一个简单的方法，在`FluwxResponseHandler.handleLaunchMiniProgramResponse`里加了一条`FluwxPlugin.extMsg = response.extMsg`，这样就可以用`getExtMsg()`获取到。我不确定这到底是前端同学写错了，还是我调用的方法错了，亦或是插件的实现有问题……

**Comment by JarvanMo** [comment]
需要参考[example](https://github.com/OpenFlutter/fluwx/blob/master/example/android/app/src/main/AndroidManifest.xml)配置:
```xml
        <meta-data
            android:name="weChatAppId"
            android:value="12345678" />

        <meta-data
            android:name="handleWeChatRequestByFluwx"
            android:value="true" />

            <intent-filter>
                <action android:name="${applicationId}.FlutterActivity" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data
                    android:host="${applicationId}"
                    android:path="/"
                    android:scheme="wechatextmsg" />
            </intent-filter>
```
还有在[FlutterActivity](https://github.com/OpenFlutter/fluwx/blob/master/example/android/app/src/main/kotlin/com/jarvan/fluwx_example/MainActivity.kt).
`FluwxPlugin.callingChannel`他没调用是因为这个时候Flutter engine并没有初始化完成。这个功能并不是我主力开发的，所以我不是十分了解，但我感觉可以优化，但我又没有调用环境。。

**Comment by Dabbit-Chan** [comment]
我不是从小程序启动app，只是app跳小程序，小程序返回后我需要获得他的回调，Flutter engine肯定初始化完成了。

**Comment by Dabbit-Chan** [comment]
配置我都已经是按照example的了。依旧不行

**Comment by JarvanMo** [comment]
今天或者明天我看看，可能是不小心被删除了

**Comment by JarvanMo** [comment]
现在是小程序的response 没有在flutter 端注册事件是吧

**Comment by Dabbit-Chan** [comment]
对的，onLaunchMiniProgramResponse没有注册，自然也就拿不到回调

**Comment by JarvanMo** [comment]
需要确认几件事情。首先代码我看了，`onLaunchMiniProgramResponse`是注册了的。我想知道：
1. `FluwxPlugin.callingChannel?.invokeMethod("onLaunchMiniProgramResponse", result)`确实调用了？如果调用了，能否看一下`callingChannel`是否为null?
2. `fluwx_iml.dart`的281是否被调用？

**Comment by Dabbit-Chan** [comment]
到FluwxPlugin.callingChannel?.invokeMethod("onLaunchMiniProgramResponse", result)之后我就没看了，明天回去看一下

**Comment by Dabbit-Chan** [comment]
![image](https://user-images.githubusercontent.com/25811834/233006595-a1bad6ea-c4cd-44ef-80bc-0adc74901d1f.png)
![image](https://user-images.githubusercontent.com/25811834/233006659-a789ba68-117b-4edb-903c-98617636c2d8.png)
arguments里有extMsg，但是`weChatResponseEventHandler.listen`监听不到

**Comment by JarvanMo** [comment]
下面的response创建出来了吗？

**Comment by Dabbit-Chan** [comment]
问题解决了，listen的地方要这样监听。。
```
fluwx.weChatResponseEventHandler.listen((event) {
      if (event is fluwx.WeChatLaunchMiniProgramResponse) {
        print('listen -- ${event.extMsg}');
      }
    });
```
