### ISSUE TITLE
添加fluwx: ^3.13.0后变异失败

### ISSUE THREAD

**Issue by huoshulei** [OpenFlutter/fluwx#525]
fluwx: ^3.13.0

* What went wrong:
A problem occurred configuring project ':fluwx'.
> Could not resolve all files for configuration ':fluwx:classpath'.
   > Could not download kotlin-gradle-plugin-1.7.10-gradle70.jar (org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.10/kotlin-gradle-plugin-1.7.10-gradle70.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.10/kotlin-gradle-plugin-1.7.10-gradle70.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-compiler-runner-1.7.10.jar (org.jetbrains.kotlin:kotlin-compiler-runner:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-compiler-runner/1.7.10/kotlin-compiler-runner-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-compiler-runner/1.7.10/kotlin-compiler-runner-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-daemon-client-1.7.10.jar (org.jetbrains.kotlin:kotlin-daemon-client:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-daemon-client/1.7.10/kotlin-daemon-client-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-daemon-client/1.7.10/kotlin-daemon-client-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-tooling-metadata-1.7.10.jar (org.jetbrains.kotlin:kotlin-tooling-metadata:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-tooling-metadata/1.7.10/kotlin-tooling-metadata-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-tooling-metadata/1.7.10/kotlin-tooling-metadata-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-gradle-plugin-model-1.7.10.jar (org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-model/1.7.10/kotlin-gradle-plugin-model-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-model/1.7.10/kotlin-gradle-plugin-model-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-gradle-plugin-api-1.7.10-gradle70.jar (org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.7.10/kotlin-gradle-plugin-api-1.7.10-gradle70.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.7.10/kotlin-gradle-plugin-api-1.7.10-gradle70.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-gradle-plugin-api-1.7.10.jar (org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.7.10/kotlin-gradle-plugin-api-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.7.10/kotlin-gradle-plugin-api-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-project-model-1.7.10.jar (org.jetbrains.kotlin:kotlin-project-model:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-project-model/1.7.10/kotlin-project-model-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-project-model/1.7.10/kotlin-project-model-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-tooling-core-1.7.10.jar (org.jetbrains.kotlin:kotlin-tooling-core:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-tooling-core/1.7.10/kotlin-tooling-core-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-tooling-core/1.7.10/kotlin-tooling-core-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-gradle-plugin-idea-1.7.10.jar (org.jetbrains.kotlin:kotlin-gradle-plugin-idea:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-idea/1.7.10/kotlin-gradle-plugin-idea-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin-idea/1.7.10/kotlin-gradle-plugin-idea-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-util-klib-1.7.10.jar (org.jetbrains.kotlin:kotlin-util-klib:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-util-klib/1.7.10/kotlin-util-klib-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-util-klib/1.7.10/kotlin-util-klib-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-klib-commonizer-api-1.7.10.jar (org.jetbrains.kotlin:kotlin-klib-commonizer-api:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-klib-commonizer-api/1.7.10/kotlin-klib-commonizer-api-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-klib-commonizer-api/1.7.10/kotlin-klib-commonizer-api-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-annotation-processing-gradle-1.7.10.jar (org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-annotation-processing-gradle/1.7.10/kotlin-annotation-processing-gradle-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-annotation-processing-gradle/1.7.10/kotlin-annotation-processing-gradle-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-android-extensions-1.7.10.jar (org.jetbrains.kotlin:kotlin-android-extensions:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-android-extensions/1.7.10/kotlin-android-extensions-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-android-extensions/1.7.10/kotlin-android-extensions-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-compiler-embeddable-1.7.10.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.7.10/kotlin-compiler-embeddable-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.7.10/kotlin-compiler-embeddable-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-scripting-compiler-embeddable-1.7.10.jar (org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable/1.7.10/kotlin-scripting-compiler-embeddable-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable/1.7.10/kotlin-scripting-compiler-embeddable-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-scripting-compiler-impl-embeddable-1.7.10.jar (org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-compiler-impl-embeddable/1.7.10/kotlin-scripting-compiler-impl-embeddable-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-compiler-impl-embeddable/1.7.10/kotlin-scripting-compiler-impl-embeddable-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-native-utils-1.7.10.jar (org.jetbrains.kotlin:kotlin-native-utils:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-native-utils/1.7.10/kotlin-native-utils-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-native-utils/1.7.10/kotlin-native-utils-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-util-io-1.7.10.jar (org.jetbrains.kotlin:kotlin-util-io:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-util-io/1.7.10/kotlin-util-io-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-util-io/1.7.10/kotlin-util-io-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-daemon-embeddable-1.7.10.jar (org.jetbrains.kotlin:kotlin-daemon-embeddable:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-daemon-embeddable/1.7.10/kotlin-daemon-embeddable-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-daemon-embeddable/1.7.10/kotlin-daemon-embeddable-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-build-common-1.7.10.jar (org.jetbrains.kotlin:kotlin-build-common:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-build-common/1.7.10/kotlin-build-common-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-build-common/1.7.10/kotlin-build-common-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-scripting-jvm-1.7.10.jar (org.jetbrains.kotlin:kotlin-scripting-jvm:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-jvm/1.7.10/kotlin-scripting-jvm-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-jvm/1.7.10/kotlin-scripting-jvm-1.7.10.jar'.
            > repo.maven.apache.org
   > Could not download kotlin-scripting-common-1.7.10.jar (org.jetbrains.kotlin:kotlin-scripting-common:1.7.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-common/1.7.10/kotlin-scripting-common-1.7.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-common/1.7.10/kotlin-scripting-common-1.7.10.jar'.
            > repo.maven.apache.org
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':fluwx' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':fluwx' of type org.gradle.api.Project.

**Comment by JarvanMo** [comment]
啊，，这，，自信了。等我晚上看看。

**Comment by huoshulei** [comment]
> 
加个镜像就好了

**Comment by JarvanMo** [comment]
我已经测试了，不需要添加任何镜像就可以。
