### ISSUE TITLE
小米唤起支付失败

### ISSUE THREAD

**Issue by lijiayy** [OpenFlutter/fluwx#527]
[ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(426)] value Redmi
 [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(428)] fontXmlName /data/user/0/com.tencent.mm/code_cache/com.tencent.mm:appbrand0/flutter_custom_fonts2.xml
[ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(541)] use default font mgr

**Comment by lijiayy** [comment]
D/MicroMsg.SDK.WXMsgImplComm(11191): check signature:308202eb30820254a00302010202044d36f7a4300d06092a864886f70d01010505003081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e74301e170d3131303131393134333933325a170d3431303131313134333933325a3081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e7430819f300d06092a864886f70d010101050003818d0030818902818100c05f34b231b083fb1323670bfbe7bdab40c0c0a6efc87ef2072a1ff0d60cc67c8edb0d0847f210bea6cbfaa241be70c86daf56be08b723c859e52428a064555d80db448cdcacc1aea2501eba06f8bad12a4fa49d85cacd7abeb68945a5cb5e061629b52e3254c373550ee4e40cb7c8ae6f7a8151ccd8df582d446f39ae0c5e930203010001300d06092a864886f70d0101050500038181009c8d9d7f2f908c42081b4c764c377109a8b2c70582422125ce545842d5f520aea69550b6bd8bfd94e987b75a3077eb04ad341f481aac266e89d3864456e69fba13df018acdc168b9a19dfd7ad9d9cc6f6ace57c746515f71234df3a053e33ba93ece5cd0fc15f3e389a3f365588a9fcb439e069d3629cd7732a13fff7b891499
D/MicroMsg.SDK.WXMsgImplComm(11191): pass
I/MicroMsg.SDK.WXApiImplV10(11191): sendReq, req type = 5
I/MicroMsg.SDK.WXApiImplV10(11191): getTokenFromWX token is wxfcb51bec491adf3d--923034852-1462088022633531-908
I/MicroMsg.SDK.MMessageAct(11191): send, targetPkgName = com.tencent.mm, targetClassName = com.tencent.mm.plugin.base.stub.WXPayEntryActivity, launchMode = 2
I/MicroMsg.SDK.MMessageAct(11191): sendUsingPendingIntent
E/gralloc4(11191): Empty SMPTE 2094-40 data
D/MicroMsg.SDK.MMessageAct(11191): send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXPayEntryActivity (has extras) }
I/MicroMsg.SDK.MMessageAct(11191): sendUsingPendingIntent onSendFinished resultCode: 0, resultData: null
I/flutter (11191): ---》true
D/CrashReport(11191): >>> com.tidy.client.MainActivity onPaused <<<
I/CrashReport-Native(11191): jni_setNativeInfo: key is 14
I/CrashReport-Native(11191): Set native info: isAppForeground(false)

**Comment by JarvanMo** [comment]
`/data/user/0/com.tencent.mm/code_cache/com.tencent.mm:appbrand0/flutter_custom_fonts2.xml`看起来是微信加载不出来字体了

**Comment by lijiayy** [comment]
> `/data/user/0/com.tencent.mm/code_cache/com.tencent.mm:appbrand0/flutter_custom_fonts2.xml`看起来是微信加载不出来字体了
但是Android11的华为可以调起微信

**Comment by JarvanMo** [comment]
那也不是一个系统啊，从日志上看不出来任何与fluwx 相关的错误。建议你去微信论坛转转

**Comment by JarvanMo** [comment]
而且我也没有小米设备

**Comment by lijiayy** [comment]
> 


> 那也不是一个系统啊，从日志上看不出来任何与fluwx 相关的错误。建议你去微信论坛转转

好的谢谢

**Comment by JarvanMo** [comment]
这个问题有什么进展吗

**Comment by jobn123** [comment]
同样的问题 解决了么 @lijiayy

**Comment by JarvanMo** [comment]
#547
