### ISSUE TITLE
send auth，弹起微信后，返回example app显示其结果是空并且微信报错incorrect signature

### ISSUE THREAD

**Issue by wen2720** [OpenFlutter/fluwx#528]
**Describe the bug**
您好 fluwx开发团队，我叫文浩https://www.linkedin.com/in/profile-wenhao-0727/ 。首先我不确认这是不是bug。想请教一下为什么运行flutter run ./example/lib/main.dart后在点击send auth，弹起微信后，返回example app显示其结果是空并且微信报错incorrect signature bla bla bla。
![4ab90ce59c3b931ca7c3de4b2287f16](https://user-images.githubusercontent.com/21952483/235669961-ac56424d-5c58-48b4-9bf5-f7602f58009f.png)

您觉得什么能导致这样的错误？
**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.
3.13.1
**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.
Pixel 4 API 31 (android-x64 emulator) Android 12.0
**Which Flutter do you use?**
3.7.12
Run `flutter doctor` and paste the output here.
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1555], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by JarvanMo** [comment]
Example 的签名现在不对，请使用自己app的签名信息

**Comment by wen2720** [comment]
> 不仅仅是这个还有applicationId ，微信ID。具体可以参看微信官方文档

我看过您的视频，觉得您的视频太好了而且真的很想实践微信登录这一块。我vue做成过网页的微信登录，现在想要延用fluwx的
fluwx.sendWeChatAuth(
                    scope: 'snsapi_userinfo',
                    state: 'SOMESTATE',
                  )
                  .then((data) {});
想请教一下，是不是要实现这一块需等申请微信appid成功后才能调试？
