### ISSUE TITLE
小白问题  user of undeclared identifier ‘WXApi’

### ISSUE THREAD

**Issue by ismanong** [OpenFlutter/fluwx#53]
按文档上的写ios的回调  然后xcode报这个错误 user of undeclared identifier ‘WXApi’
还请帮帮忙，最好能科普下该怎么理解这种类似的流程

**Comment by JarvanMo** [comment]
1.具体请参考example
2.不是做ios培训的。

**Comment by ismanong** [comment]
好的 理解  我主要看到demo上具体添加代码的那页没有引入import ‘WXApi’；  但是demo没报错，说明我的缺少一些东西，贸然引入别的解决方案，担心会失去包的更新的价值，3q，我在学习学习

**Comment by JarvanMo** [comment]
1.最新的example已经添加了import 。因为我本地不加也是可以的，但是部分人不可以，添加了就行了。
2.Fluwx独立使用是没用的问题的，至少找不到fluwx可能是其他插件的问题，或者项目本身是有问题的。

**Comment by ismanong** [comment]
哦哦  好的谢谢 我比对的是老example  你的不加 确实不报错  3q  我先应急打包   今天晚上在研究一把，两种方式也值得学习
