### ISSUE TITLE
在微信的登录授权方法下，为什么支付的回调通知能收到通知呢

### ISSUE THREAD

**Issue by zjypp** [OpenFlutter/fluwx#530]
最新版本：  fluwx: ^3.13.1

代码同时接入了微信的登录和支付
结果发现每次微信登陆成功以后，支付的监听接口也能收到信息，而且都是支付成功通知

 // 监听支付结果
    weChatResponseEventHandler.listen((event) async {
      print("wechat rsponse ${event}");
  if (event.errCode == 0) {
        print('wxpay === 支付成功');
        Get.snackbar("提示", "微信支付成功，可以使用VIP会员权益.");

**Comment by zhoujia456888** [comment]
应该是把微信的登录和支付返回做了统一了，需要加个判断
 if (event is WeChatAuthResponse) {}
 if (event is WeChatPaymentResponse) {}

**Comment by JarvanMo** [comment]
@zhoujia456888 That's correct. Thanks for your answer.
