### ISSUE TITLE
Error (Xcode): Undefined symbol

### ISSUE THREAD

**Issue by ZhangXingXingo** [OpenFlutter/fluwx#532]
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_AddCardToWXCardPackageReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_AddCardToWXCardPackageResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_GetMessageFromWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_LaunchFromWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_OpenRankListReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_OpenWebviewReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_PayReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_PayResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendAuthReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendAuthResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendMessageToWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendMessageToWXResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_ShowMessageFromWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXApi

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXAppExtendObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXCardItem

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseCardReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseCardResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseInvoiceReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseInvoiceResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXEmoticonObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXFileObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXImageObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXInvoiceAuthInsertResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXLaunchMiniProgramReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXLaunchMiniProgramResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXMediaMessage

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXMiniProgramObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXMusicObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXNontaxPayResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessViewReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessViewResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessWebViewReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessWebViewResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenCustomerServiceReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenCustomerServiceResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXPayInsuranceResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXSubscribeMsgReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXSubscribeMsgResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXVideoObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXWebpageObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WechatAuthSDK

**Comment by ZhangXingXingo** [comment]
4.0.0+2出的这个

**Comment by JarvanMo** [comment]
是否带支付

**Comment by ZhangXingXingo** [comment]
带支付了的

**Comment by JarvanMo** [comment]
GitHub 的action 是跑通了的，你跑 pod install

**Comment by 1D3E** [comment]
> GitHub 的action 是跑通了的，你跑 pod install

尝试了 没有效果

**Comment by ZhangXingXingo** [comment]
这我的
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (3 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

**Comment by ZhangXingXingo** [comment]
我的是m2

**Comment by 1D3E** [comment]
> Mac 是X86还是M1 的

M1

**Comment by JarvanMo** [comment]
看起来应该是CPU 的问题。不过我没有m 的本，正在看看有没有arm 的GitHub action

**Comment by 1D3E** [comment]
> 

之前我使用的是3.12.2没有问题，今天更新为4.0.2才有这个错误提示的

**Comment by 1D3E** [comment]
> 最新的3.x，没有问题？就是更换成xc framework的那个版本

这个指的是3.13.0么 我可以尝试一下

**Comment by JarvanMo** [comment]
3.12不行，得Fluwx 3.13，3.13才换了xc framework

**Comment by JarvanMo** [comment]
[试试这个](https://github.com/flutter/flutter/issues/41900) 。

**Comment by 1D3E** [comment]
> 

我现在尝试了3.12 3.13都出现了同样的问题。

**Comment by 1D3E** [comment]
> [试试这个](https://github.com/flutter/flutter/issues/41900) 。

我看下。

**Comment by JarvanMo** [comment]
或者可以新开个项目，然后看看是不是问题依旧。

**Comment by alook123** [comment]
同样的问题，我也是m1的
另外，新建项目，可以运行，然后导入fluwx就运行不了了

**Comment by JarvanMo** [comment]
麻烦了。没有m 的电脑

**Comment by JarvanMo** [comment]
还有你们iOS 端是swift 还是oc

**Comment by alook123** [comment]
> 还有你们iOS 端是swift 还是oc

swift

**Comment by JarvanMo** [comment]
看来应该是swift 的问题，开启一下modular header试试

**Comment by alook123** [comment]
> 看来应该是swift 的问题，开启一下modular header试试
没理解，这个modular header是怎么开启

**Comment by JarvanMo** [comment]
我现在在外面。你搜一下

**Comment by mhszeto** [comment]
> > 看来应该是swift 的问题，开启一下modular header试试
> 
> 没理解，这个modular header是怎么开启

把Podfile target 'Runner' do下面的
use_frameworks! 改成 use_frameworks! :linkage => :static
然后在 Build Settings -> Apple Clang - Language -Modules -> Allow Non-modular Includes In Framework Modules 改成 YES
就可以跑起来了

**Comment by JarvanMo** [comment]
@mh

> > > 看来应该是swift 的问题，开启一下modular header试试
> > 
> > 
> > 没理解，这个modular header是怎么开启
> 
> 把Podfile target 'Runner' do下面的 use_frameworks! 改成 use_frameworks! :linkage => :static 然后在 Build Settings -> Apple Clang - Language -Modules -> Allow Non-modular Includes In Framework Modules 改成 YES 就可以跑起来了

You rock!!!

**Comment by alook123** [comment]
> > > 看来应该是swift 的问题，开启一下modular header试试
> > 
> > 
> > 没理解，这个modular header是怎么开启
> 
> 把Podfile target 'Runner' do下面的 use_frameworks! 改成 use_frameworks! :linkage => :static 然后在 Build Settings -> Apple Clang - Language -Modules -> Allow Non-modular Includes In Framework Modules 改成 YES 就可以跑起来了

可以了，感谢

**Comment by JarvanMo** [comment]
微信的Xcframework 没有支持模块化是我没有想到的

**Comment by mhszeto** [comment]
fluwx.podspec最下面添加s.static_framework = true
Build Settings -> Apple Clang - Language -Modules -> Allow Non-modular Includes In Framework Modules 改成 YES
这样也行
use_frameworks!就不用改了

**Comment by JarvanMo** [comment]
@mhszeto Ok.我改一下。

**Comment by jasonhe88** [comment]
> > 但是这样修改后会造成其他需要动态链接的Plugin运行出错
> > > > > 看来应该是swift 的问题，开启一下modular header试试
> > > > 
> > > > 
> > > > 没理解，这个modular header是怎么开启
> > > 
> > > 
> > > 把Podfile target 'Runner' do下面的 use_frameworks! 改成 use_frameworks! :linkage => :static 然后在 Build Settings -> Apple Clang - Language -Modules -> Allow Non-modular Includes In Framework Modules 改成 YES 就可以跑起来了
> 
> 那你有啥好的解决方案吗？主要是都2023年，微信的framework 还没有模块化。

对 podfile 不是很熟悉，正在研究

**Comment by JarvanMo** [comment]
感谢 @mhszeto 的提醒，我已经添加了static_framework=true，已发布4.1.0。经过我本机测试，也可以不用加Build Settings -> Apple Clang - Language -Modules -> Allow Non-modular Includes In Framework Modules 。

但要保证`Podfile`里添加了` use_modular_headers!`


```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
```

感谢各位。
