### ISSUE TITLE
 Xcode 14.2。pod 1.12.1版本 运行报错Specs satisfying the fluwx (from .symlinks/plugins/fluwx/ios) dependency were found, but they required a higher minimum deployment

### ISSUE THREAD

**Issue by lovachen** [OpenFlutter/fluwx#533]
老电脑 Xcode 14.2。pod 1.12.1版本 运行报错了，

Specs satisfying the `fluwx (from `.symlinks/plugins/fluwx/ios`)` dependency were found, but they required a higher minimum deployment
    target.
![cf9576eef49e0b0dd9a46671ca5a1569](https://github.com/OpenFlutter/fluwx/assets/13043393/cbaead4e-a100-4e53-b4c5-42cd099fda1a)

**Comment by JarvanMo** [comment]
Podfile 更改一下deployment target ，最低是11还是12来着的

**Comment by JarvanMo** [comment]
具体看example
