### ISSUE TITLE
4.0.1版本的fluwx，还是会遇到监听多次调用的问题。

### ISSUE THREAD

**Issue by zhoujia456888** [OpenFlutter/fluwx#534]
4.0.1版本的微信，还是会遇到监听多次调用的问题，但是使用StreamSubscription<WeChatAuthResponse> 时wxlogin会报null

1.在关闭页面时调用unsubscribeResponse，再重新打开页面订阅subscribeResponse，则会多次收到subscribeResponse的消息。
unsubscribeResponse方法似乎不起作用。

2.使用文档中的[方法](https://github.com/OpenFlutter/fluwx/blob/master/doc/QA_CN.md#listen%E7%9B%91%E5%90%AC%E5%A4%9A%E6%AC%A1%E8%B0%83%E7%94%A8)
实现代码如下
```
late StreamSubscription<WeChatAuthResponse> wxlogin;

 @override
  void onInit() {
    super.onInit();
    //微信登录监听
    wxlogin=fluwx.subscribeResponse((response) {}
}

```
此时会报错type 'Null' is not a subtype of type 'StreamSubscription<WeChatAuthResponse>'

**Comment by zhoujia456888** [comment]
在[fluwx](https://github.com/OpenFlutter/fluwx/tree/master)/[example](https://github.com/OpenFlutter/fluwx/tree/master/example)/[lib](https://github.com/OpenFlutter/fluwx/tree/master/example/lib)/[pages](https://github.com/OpenFlutter/fluwx/tree/master/example/lib/pages)
/launch_mini_program_page.dart里面找到了答案，

此贴关闭

```
late Function(WeChatResponse) responseListener;

  @override
  void dispose() {
    super.dispose();
    _result = null;
    fluwx.unsubscribeResponse(responseListener);
  }

  @override
  void initState() {
    super.initState();
    responseListener = (response) {
      if (response is WeChatLaunchMiniProgramResponse) {
        if (mounted) {
          setState(() {
            _result = 'isSuccessful:${response.isSuccessful}';
          });
        }
      }
    };

    fluwx.subscribeResponse(responseListener);
  }

```

**Comment by JarvanMo** [comment]
我一直好奇重复监听的问题是iOS 上的还是Android 有？还是都有。
