### ISSUE TITLE
运行报错Undefined symbol: _OBJC_CLASS_$_AddCardToWXCardPackageReq

### ISSUE THREAD

**Issue by sioomy** [OpenFlutter/fluwx#535]
**Describe the bug**

Failed to build iOS app
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_AddCardToWXCardPackageReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_AddCardToWXCardPackageResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_GetMessageFromWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_LaunchFromWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_OpenRankListReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_OpenWebviewReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_PayReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_PayResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendAuthReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendAuthResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendMessageToWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_SendMessageToWXResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_ShowMessageFromWXReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXApi

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXAppExtendObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXCardItem

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseCardReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseCardResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseInvoiceReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXChooseInvoiceResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXEmoticonObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXFileObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXImageObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXInvoiceAuthInsertResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXLaunchMiniProgramReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXLaunchMiniProgramResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXMediaMessage

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXMiniProgramObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXMusicObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXNontaxPayResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessViewReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessViewResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessWebViewReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenBusinessWebViewResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenCustomerServiceReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXOpenCustomerServiceResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXPayInsuranceResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXSubscribeMsgReq

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXSubscribeMsgResp

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXVideoObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WXWebpageObject

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WechatAuthSDK

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**Comment by JarvanMo** [comment]
#532

**Comment by JarvanMo** [comment]
4.1.0发布了，应该不用改什么了。具体请看 #532
