### ISSUE TITLE
在多flavorizr情况下，如何使用？

### ISSUE THREAD

**Issue by LinHaoLove** [OpenFlutter/fluwx#536]
尊敬的开发者您好：

之前一直使用[fluwx_no_pay](https://pub.flutter-io.cn/packages/fluwx_no_pay)，准备转[fluwx](https://pub.flutter-io.cn/packages/fluwx)，但是我有一些问题。
问题1：在pubspec.yaml中配置参数，Register WxAPI（手动设置参数），这两者是二选一的吗？
问题2：在问题1上，基于pubspec.yaml中配置参数的话，项目中有多个[flavorizr](https://pub.flutter-io.cn/packages/flutter_flavorizr)，每一个flavorizr都是独立的App，且对应唯一的wechat-key，那我应该如何配置？

非常感谢！

**Comment by JarvanMo** [comment]
1. Yaml 里的ID 目前只是辅助作用，主要是iOS来生成scheme，，也就是还要你手动register。不过Android 这里倒是提醒了我，Android 这里确实使用了这个ID，我得改改。
2.  以前怎么实现的？目前的话确实没有考虑过这个问题。Android 实现得改
3. 那个flavour 我不了解，等我看看

**Comment by JarvanMo** [comment]
你可以等等再升级到4.0，等我appid 变成可选的。Android 那边我重新实现一遍。

**Comment by LinHaoLove** [comment]
> 你可以等等再升级到4.0，等我appid 变成可选的。Android 那边我重新实现一遍。

非常感谢您的回复。那我再等等

**Comment by LinHaoLove** [comment]
> 1. Yaml 里的ID 目前只是辅助作用，主要是iOS来生成scheme，，也就是还要你手动register。不过Android 这里倒是提醒了我，Android 这里确实使用了这个ID，我得改改。
> 2. 以前怎么实现的？目前的话确实没有考虑过这个问题。Android 实现得改
> 3. 那个flavour 我不了解，等我看看

以前的实现方式是：`if(flavorizr==自定义的枚举值){注册}else if(flavorizr==自定义的枚举值){注册}`，flavour可以这样理解：大部分代码共用，通过flavorizr修改小部分代码，导出不同的App，最常见的使用方式：同一套代码导出商家端、客户端。

**Comment by JarvanMo** [comment]
iOS weixin scheme 你怎么实现的

**Comment by LinHaoLove** [comment]
> iOS weixin scheme 你怎么实现的

这么说，我没考虑到这个问题，不过info.plist中键值是应该是可以指向一个变量的，像版本号指向那样。

**Comment by LinHaoLove** [comment]
> iOS weixin scheme 你怎么实现的

我没考虑到这个问题。

**Comment by LinHaoLove** [comment]
> iOS weixin scheme 你怎么实现的

我没有考虑到这个问题。之前只要导出两个App，只有一个App，所以并没有深究，现在要增加输出3个App。
我尝试为每一个[flavorizr](https://pub.flutter-io.cn/packages/flutter_flavorizr)生成对应的plist，也没有看到有效的输出。

**Comment by JarvanMo** [comment]
4.2里appid 可选了
