### ISSUE TITLE
M2芯片macbookpro运行崩溃问题

### ISSUE THREAD

**Issue by sioomy** [OpenFlutter/fluwx#541]
项目没引进fluwx和tobias之前，虚拟机运行都正常，只要引入其中任何一个，不管是DART3版本还是dart2版本，启动都会崩溃，编译是通过的，在simulator中安装后，启动就崩溃
rosatta模式也不行
更改Exclude Architectures也是不行的,有没有根治的方法

**Comment by JarvanMo** [comment]
首先排除一下是哪个library 有问题。

**Comment by sioomy** [comment]
fluwx 和tobias都有问题

**Comment by sioomy** [comment]
不加载这两个就好了

**Comment by sioomy** [comment]
请问这两个插件有在M1 M2芯片的MAC下做过测试么

**Comment by JarvanMo** [comment]
Fluwx 4.0+已经有很多M 系列用户。至于Tobias 也没收到类似反馈。我也没有M电脑

**Comment by JessieSunShine** [comment]
我的是M1 也有这个问题
