### ISSUE TITLE
关于使用4+版本的一个小问题

### ISSUE THREAD

**Issue by WFCN** [OpenFlutter/fluwx#546]
我们公司Android  iOS是不同的appid  请问可以通过脚本分别配置吗

**Comment by JarvanMo** [comment]
Appid 这个参数只在iOS上有用。现在app_id是选填的，这意味着你可以不通过脚本设置URL scheme，依然可以自己手动添加。

**Comment by WFCN** [comment]
> Appid 这个参数只在iOS上有用。现在app_id是选填的，这意味着你可以不通过脚本设置URL scheme，依然可以自己手动添加。

好的  谢谢解惑   感谢
