### ISSUE TITLE
微信支付突然还不能拉起

### ISSUE THREAD

**Issue by Janzon** [OpenFlutter/fluwx#547]
这是一个问题记录，希望能够帮助到一些遇到此类问题，可能是和我一样的原因的。

微信开放平台接入APP支付后测试安卓和ios拉起支付和付款都没有问题，上线后上午还是OK的，突然安卓的就不行了，iOS还是可以的。代码和后台都没有改动，降级fluwx版本都没有用。

最后的结论是因为安卓没有上应用市场（软著申请了但是有坑在变更结果导致延期了），导致限制了拉起微信支付的次数，iOS因为上了APPSTORE所以OK，咨询了微信支付技术客服说如果没有上应用市场appid会被微信后台限制，就拉不起来，上午能拉起来的原因是因为有个100次的调试次数，下午用完了就不行了。iOS能用的原因是因为iOS上架了，微信后台有根据端去限制。让我等安卓上架应用市场后再试。

这里面坑的点就是微信的官方文档上压根就没提这事，只在分享功能上提了这个100次限制的事，让我以为微信支付不会存在这个限制，留个记录没准能帮到大家。

**Comment by Janzon** [comment]
仅作记录

**Comment by JarvanMo** [comment]
Awesome

**Comment by hehe2015** [comment]
是要上架应用宝吗？

**Comment by WilsonTang666** [comment]
> 是要上架应用宝吗？

不一定是应用宝，其他的市场也都行，比如小米应用市场一类的。
在微信公众平台需要对APP进行登记审核，他会要求你填写上架证明，审核通过后他就认为你有这个权限了

**Comment by Janzon** [comment]
> 是要上架应用宝吗？

不一定是应用宝，其他的市场也都行，比如小米应用市场一类的。
在微信公众平台需要对APP进行登记审核，他会要求你填写上架证明，审核通过后他就认为你有这个权限了
