### ISSUE TITLE
 fluwx.register   used failed

### ISSUE THREAD

**Issue by YoungCC2** [OpenFlutter/fluwx#55]
`  _initFluwx() async {
    await fluwx.register(
        appId: "xxxxxxxxxxxx",
        doOnAndroid: true,
        doOnIOS: true,
        enableMTA: false);
        var result = await fluwx.isWeChatInstalled();
        print("is installed $result");
  }`

printed   is installed false.

**Comment by JarvanMo** [comment]
多翻issue 
Duplicate of #38

**Comment by YoungCC2** [comment]
e,模拟器没有安装微信 调用fluwx.isWeChatInstalled() 会返回false.   所以这个地方是合适的返回
