### ISSUE TITLE
Pod Install 错误：wechat_setup.rb

### ISSUE THREAD

**Issue by RealJianhua** [OpenFlutter/fluwx#551]
**Describe the bug**
执行：pod install， 出现错误，日志中指向 fluwx/ios/wechat_setup.rb 。从项目中拿掉fluwx，再执行pod install，错误消失。因此判断和 fluwx 有关。
前因是电脑中刚刚升级了pod版本，版本号是1.12.1，升级之前的版本是 1.11.3。同时升级了ruby，原来是电脑自带的2.6.0，升级后是3.2.2.
我不确定1.11.3是不是好的。

**To Reproduce**
执行 pod install
日志如下：
Analyzing dependencies
5.0.1
using sdk with no_pay
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- plist (LoadError)
        from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/wenjh/.pub-cache/hosted/pub.dev/fluwx-4.2.6/ios/wechat_setup.rb:8:in `<main>'
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 25 dependencies from the Podfile and 33 total pods installed.

**Which version of Fluwx do you use?**
Fluwx Version: 4.2.6 (  fluwx: ^4.2.6)

**Which device do you run on**
设备：Macbook Pro (Apple M2)
操作系统版本: 13.4
Xcode Version: 14.3.1
Pod Version: 1.12.1
Ruby Version: 3.2.2

**Which Flutter do you use?**
Flutter Version: 3.10.1
Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by JarvanMo** [comment]
# step.1 install missing dependencies
sudo gem install plist
# step.2 enter iOS folder(example/ios/,ios/)
cd example/ios/
# step.3 execute
pod install

**Comment by RealJianhua** [comment]
Nice! 好了～～！谢谢
