### ISSUE TITLE
CFBundleURLSchemes不支持纯数字

### ISSUE THREAD

**Issue by fortnightmoon** [OpenFlutter/fluwx#553]
**Describe the bug**
CFBundleURLSchemes不支持纯数字

**To Reproduce**
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>weixin</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>121212</string>
			</array>
		</dict>
ios不支持纯数字的CFBundleURLSchemes。每次运行iphone设备，fluwx插件每次都自动生成类似121212的值，，，太麻烦了。

description = "The following URL schemes found in your app are not in the correct format: [1636657153]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail.";
}’.

**Which version of Fluwx do you use?**
fluwx : 4.2.6

**Which device do you run on**
ios设备

**Which Flutter do you use?**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4.1 22F82 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] Connected device (4 available)
[✓] Network resources

Run `flutter doctor` and paste the output here.

**Comment by JarvanMo** [comment]
正常的wx appid也不是纯数字

**Comment by fortnightmoon** [comment]
> 

我看fluwx文档，以为是ios的appid，原来是微信的key。。。我理解错了。

**Comment by fortnightmoon** [comment]
可以关闭issue了，谢谢作者
