### ISSUE TITLE
你好,请问fluwx: ^4.2.5 的微信分享回调是不是取消了

### ISSUE THREAD

**Issue by lavande820** [OpenFlutter/fluwx#554]
发现responseFromShare和responseEventHandler好像都没有了

**Comment by lavande820** [comment]
发现responseFromShare和responseEventHandler好像都没有了

**Comment by JarvanMo** [comment]
看迁移指南或者demo

**Comment by lavande820** [comment]
> 看迁移指南或者demo

好滴谢谢大佬!
