### ISSUE TITLE
微信浏览器，唤起苹果端应用  应用冷启动后， 调用 fluwx.attemptToResumeMsgFromWx(); 没有任何回调

### ISSUE THREAD

**Issue by lurongshuang** [OpenFlutter/fluwx#555]
微信浏览器，唤起APP    APP冷启动，启动后 调用 fluwx.attemptToResumeMsgFromWx(); 每有任何回调

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.0 22A380 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.0)
[✓] Connected device (4 available)
[✓] Network resources

fluwx: ^4.2.6

  static Fluwx? _fluwx;
  ///初始化
  static Future<bool> wxInit() {
    _fluwx = Fluwx();

    ///添加微信回调监听
    _fluwx!.addSubscriber(weChatResponseSubscriber);
    _fluwx!.attemptToResumeMsgFromWx();
    return _fluwx!.registerApi(
        appId: AppConfig.wxAppId, universalLink: AppConfig.universalLink);
  }

  ///微信调研监听 ）
  static weChatResponseSubscriber(WeChatResponse response) {
    if (response is WeChatLaunchFromWXRequest) {

      if ( (response).extMsg!.isNotEmpty) {
       
      }
    }
  }

**Comment by JarvanMo** [comment]
先注册WXAPI。

**Comment by lurongshuang** [comment]
import 'package:fluwx/fluwx.dart';
import 'package:wordflows/constants/app_config.dart';
import 'package:wordflows/services/unilinkes_services/listen_unilinks_services.dart';
import 'package:wordflows/utils/et/et.dart';
import 'package:wordflows/utils/get_is_registered/get_is_registered.dart';

///微信插件api
class FluWxUtils {
  static Fluwx? _fluwx;

  ///初始化
  static Future<bool> wxInit() {
    _fluwx = Fluwx();

    ///添加微信回调监听
    _fluwx!.addSubscriber(weChatResponseSubscriber);
    return _fluwx!.registerApi(
        appId: AppConfig.wxAppId, universalLink: AppConfig.universalLink);
  }

  static Future<String?> getExtMsg() async {
    await _fluwx!.attemptToResumeMsgFromWx();
    return _fluwx!.getExtMsg();
  }

  static void selfCheck() {
    _fluwx!.selfCheck();
  }

  ///微信调研监听 ）
  static weChatResponseSubscriber(WeChatResponse response) {
    ET.success("有回答");
    if (response is WeChatLaunchFromWXRequest) {
      ///唤起APP
      if (GIR.isR<UniLinksService>() &&
          (response).extMsg != null &&
          (response).extMsg!.isNotEmpty) {
        UniLinksService.to.fromWxUri((response).extMsg!);
      }
    }
  }

  ///分享视频到会话
  ///title 标题
  ///url 打开链接
  ///imageUrl 图片链接
  static Future<bool> shareVideoToSession(
      {required String title,
      required String url,
      String? imageUrl,
      String? description}) {
    return _wxShare(
        title: title,
        url: url,
        description: description,
        thumbnail: imageUrl,
        scene: WeChatScene.session);
  }

  ///分享视频到朋友圈
  ///title 标题
  ///url 打开链接
  ///imageUrl 图片链接
  static Future<bool> shareVideoToTimeline(
      {required String title,
      required String url,
      String? imageUrl,
      String? description}) {
    return _wxShare(
        title: title,
        url: url,
        description: description,
        thumbnail: imageUrl,
        scene: WeChatScene.timeline);
  }

  ///分享网页
  ///title 标题
  ///url 网页承载地址
  ///thumbnail 消息缩略图
  ///description 内容描述
  ///scene 分享类型
  static Future<bool> _wxShare(
      {required String title,
      required String url,
      String? thumbnail,
      String? description,
      WeChatScene scene = WeChatScene.session}) async {
    if (_fluwx == null) {
      if (!await wxInit()) {
        return false;
      }
    }
    if (!await _fluwx!.isWeChatInstalled) {
      ET('检测到您手机当前未安装微信，无法分享');
      return false;
    }
    return _fluwx!.share(WeChatShareWebPageModel(url,
        title: title,
        thumbnail: thumbnail != null ? WeChatImage.network(thumbnail) : null,
        description: description,
        scene: scene));
  }

  ///微信登录
  static Future<bool> wxLogin(
      {required Function(WeChatAuthResponse weChatAuthResponse) listener,
      String? state}) async {
    if (_fluwx == null) {
      if (!await wxInit()) {
        return false;
      }
    }
    if (!await _fluwx!.isWeChatInstalled) {
      ET('检测到您手机当前未安装微信，无法分享');
      return false;
    }
    state ??= ((DateTime.now().microsecond)).toString();
    sharedSubscriber(WeChatResponse response) {
      if (response is WeChatAuthResponse && response.state == state) {
        listener(response);
      }
    }

    _fluwx!.removeSubscriber(sharedSubscriber);
    _fluwx!.addSubscriber(sharedSubscriber);
    return _fluwx!
        .authBy(which: NormalAuth(scope: 'snsapi_userinfo', state: state));
  }
}

ios 端  先注册了 wxapi  在首页调用的getExtMsg

**Comment by lurongshuang** [comment]
调用顺序就是这样

FluWxUtils.wxInit();
之后会在首页调用
FluWxUtils.getExtMsg()

**Comment by lurongshuang** [comment]
https://github.com/OpenFlutter/fluwx/assets/20178753/d752bafa-a0d8-41f6-9d19-d6e913bce351

**Comment by lurongshuang** [comment]
在首页  initState  调用

    WidgetsBinding.instance.addPostFrameCallback((timeStamp) async {
        String? a = await FluWxUtils.getExtMsg();
        ET.success("---$a");
      });
在 main() 里面调用的   
main(){
 WidgetsFlutterBinding.ensureInitialized();
FluWxUtils.wxInit();
 runApp(const MyApp()); 
}

**Comment by lurongshuang** [comment]
@JarvanMo

**Comment by lurongshuang** [comment]
APP在启动的情况下，微信浏览器跳转过来 是没问题的 ，会回调weChatResponseSubscriber，参数也正常，冷启动不行，先就是拿不到 参数

**Comment by lurongshuang** [comment]
我同时也使用了uni_links: ^0.5.1    continueUserActivity:restorationHandler     didFinishLaunchingWithOptions  会有冲突吗？

**Comment by JarvanMo** [comment]
> 我同时也使用了uni_links: ^0.5.1 continueUserActivity:restorationHandler didFinishLaunchingWithOptions 会有冲突吗？

不排除。这个问题我实在帮不了。首先，我不具备测试条件，没有测试账号之类的。其次，这个功能当时我是和一位群友一起调试好用的。

**Comment by lurongshuang** [comment]
我试着把 uni_links 注释了，可是 还是没有生效

**Comment by JarvanMo** [comment]
凡是重写了微信SDK需要那几个方法的都有可能影响，特别一些其他也有微信功能的插件

**Comment by JarvanMo** [comment]
想了想，应该不是其他插件的问题。你可以确认一下，热启动的时候iOS到底回调的是ShowMessageFromWXReq还是LaunchFromWXReq

**Comment by JarvanMo** [comment]
这两个东西并不一样，我也不知道差别

**Comment by JarvanMo** [comment]
也可能冷热启动回调并不一样

**Comment by JarvanMo** [comment]
你可以试试同时监听两个回调

**Comment by lurongshuang** [comment]
热启动 ：LaunchFromWXReq

**Comment by lurongshuang** [comment]
冷启动的时候，我看到一段日志：
  Runner: (Flutter) flutter: FluwxLog: [WXApi.m]+[WXApi handleOpenURL:delegate:]WXLog:url can not be handled by WeChat SDK, registerAppId:wx123123213123, registerUniversalLink:https://xxxxx/universal/, url:https://xxxxxxxx/universal/homeFeeds?feedId=3748831065929231

不知道是不是这个问题，之前您说的的是因为，当时wxSdk 还没有被初始化

**Comment by JarvanMo** [comment]
那应该还是要改app delegate 。把微信初始化前置。
