### ISSUE TITLE
flutter_module 中使用 时候，iOS pod install 无法成功

### ISSUE THREAD

**Issue by zhoupeiyu** [OpenFlutter/fluwx#558]
[!] Failed to load 'fluwx' podspec:
[!] Invalid `fluwx.podspec` file: No such file or directory @ rb_sysopen - /Users/xxx/Desktop/xxx/src/xxx/flutter_module/.ios/.symlinks/plugins/fluwx/ios/pubspec.yaml.

 #  from /Users/xxx/Desktop/xxx/src/xxx/flutter_module/.ios/.symlinks/plugins/fluwx/ios/fluwx.podspec:22
 #  -------------------------------------------
 #  if psych_version_gte_500 == true
 >      cfg = YAML.load_file(File.join(flutter_project_dir, 'pubspec.yaml'), aliases: true)
 #  else
 #  -------------------------------------------

**Comment by JarvanMo** [comment]
模板都不舍得改改么。

**Comment by JarvanMo** [comment]
日志是藏宝藏了吗，也舍不得贴。

**Comment by zhoupeiyu** [comment]
上面那个是什么问题呢

**Comment by JarvanMo** [comment]
Flutter module 的pubspec获取不到了。我还没用过flutter module ，得看看。

**Comment by zhoupeiyu** [comment]
嗯

**Comment by JarvanMo** [comment]
这个问题稍微等下吧。如果以flutter_module的方式运行，可能需要你自己配置universal link和配置url scheme了。

**Comment by JarvanMo** [comment]
我先提个版本，保证你编译过。但是universal-link之类的你要自己手动配置。

**Comment by JarvanMo** [comment]
4.2.7. released.
