### ISSUE TITLE
IOS上和ShareSDK-For-Flutter插件冲突了，怎么解决冲突？

### ISSUE THREAD

**Issue by jethroHuang** [OpenFlutter/fluwx#56]
同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报

target has libraries with conflicting names libwechatsdk.a

我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a

请问该如何解决这个冲突？

**Comment by JarvanMo** [comment]
可以尝试删除其中一个 libwechatsdk.a。其他请咨询擅长ios的人。

**Comment by JarvanMo** [comment]
或者你自己fork一份，sharesdk还是fluwx都行，自己删除 libwechatsdk.a试试。

**Comment by CyJaySong** [comment]
sharesdk的完整版微信SDK里包装了share的桥接文件下载，删了是做不了分享的，删了fluwx中微信SDK的libwechatsdk.a。然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。这样做可以解决冲突

**Comment by howhyone** [comment]
sharesdk 有带支付的微信SDK，s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' ，不用导入微信原生的SDK了

**Comment by GanZhiXiong** [comment]
我通过这里解决了，你们也可以试试看
https://github.com/OpenFlutter/fluwx/blob/master/doc/QUESTIONS_CN.md#sharesdk%E5%88%86%E4%BA%AB%E6%8F%92%E4%BB%B6%E5%92%8Cfluwx%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E6%8F%92%E4%BB%B6%E5%AD%98%E5%9C%A8%E5%86%B2%E7%AA%81

**Comment by Lanhaoo** [comment]
我按照这种方式还是没有解决。我先添加了fluwx，然后删了fluwx中微信SDK的libwechatsdk.a，然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'，最后添加sharesdk并且把sharesdk的podspec中的s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat' 修改成了s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。结果还是报错

> 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报
> 
> target has libraries with conflicting names libwechatsdk.a
> 
> 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a
> 
> 请问该如何解决这个冲突？

我按照这种方式还是没有解决。我先添加了fluwx，然后删了fluwx中微信SDK的libwechatsdk.a，然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'，最后添加sharesdk并且把sharesdk的podspec中的s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat' 修改成了s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。结果还是报错

**Comment by ZhangPingFan** [comment]
fatal
    error: 'WechatOpenSDK/WXApi.h' file not found
    #import <WechatOpenSDK/WXApi.h>

采用 https://github.com/OpenFlutter/fluwx/issues/56#issuecomment-479507888 的修改方案后会报以上错误。

发现是 https://github.com/OpenFlutter/fluwx/commit/5d8eabea89f6c329054ef35e8c92d707c4672ed8 这个提交（原因不明） 回退这个提交后即可正常编译通过

**Comment by Smilefish0** [comment]
变通了一下，把/ios/.symlinks/plugins/sharesdk_plugin/ios/sharesdk_plugin.podspec中的#s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat(Full)' 注释了以后，可以正常运行,也就是shareSDK中不用wechat，需要的地方用fluwx代替，仅供参考（被坑了好久...）,完整配置参考：
`#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'sharesdk_plugin'
  s.version          = '1.1.2'
  s.summary          = 'Flutter plugin for ShareSDK.'
  s.description      = <<-DESC
  ShareSDK is the most comprehensive Social SDK in the world,which share easily with 40+ platforms.
                       DESC
  s.homepage         = 'http://www.mob.com/mobService/sharesdk'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Mob' => 'mobproduct@mob.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'mob_sharesdk'
  s.dependency 'mob_sharesdk/ShareSDKExtension'
  s.dependency 'mob_sharesdk/ShareSDKUI'
  s.dependency 'mob_sharesdk/ShareSDKPlatforms/QQ'
  s.dependency 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/QQ_Lite'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo_Lite'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat_Lite'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/Facebook'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/Twitter'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/Douyin'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/Oasis'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/Line'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/SnapChat'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/WatermelonVideo'
  #s.dependency 'mob_sharesdk/ShareSDKPlatforms/KuaiShou'
  #分享闭环
  #s.dependency 'mob_sharesdk/ShareSDKRestoreScene'
  s.static_framework = true

  s.ios.deployment_target = '8.0'
end

`

**Comment by liangbx361** [comment]
最简单的方案是ShareSDK修改Wechat SDK依赖来规避冲突
s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat_Lite'
