### ISSUE TITLE
使用3.12.2版本，提交审核出现调用sdk情况！！！

### ISSUE THREAD

**Issue by yujunxue** [OpenFlutter/fluwx#560]
![image](https://github.com/OpenFlutter/fluwx/assets/44626661/f6b7968b-1363-4fef-a476-f0bade938d04)
点击不同意时出现调用SDK的情况，所以请问这种情况如何处理，我查了一遍，未发现有这个问题的提交

**Comment by JarvanMo** [comment]
1. Fluwx 本身有没有任何权限要求。
2. 要么升级fluwx, 或者升级微信SDK，再或者升级flutter

**Comment by WangYiOS** [comment]
我小米审核，也遇到了这个问题，郁闷啊，
楼主怎么解决的，可以教教我吗？

**Comment by yujunxue** [comment]
> 我小米审核，也遇到了这个问题，郁闷啊， 楼主怎么解决的，可以教教我吗？

我也是小米审核，出现此问题，所以检查logcat也没有看到什么包启动，但是小米就说sdk启动了

**Comment by WangYiOS** [comment]
> > 我小米审核，也遇到了这个问题，郁闷啊， 楼主怎么解决的，可以教教我吗？
> 
> 我也是小米审核，出现此问题，所以检查logcat也没有看到什么包启动，但是小米就说sdk启动了

我的小米审核问题解决了，把fluwx初始化的位置更改下位置，就通过审核了！

**Comment by yujunxue** [comment]
> > > 我小米审核，也遇到了这个问题，郁闷啊， 楼主怎么解决的，可以教教我吗？
> > 
> > 
> > 我也是小米审核，出现此问题，所以检查logcat也没有看到什么包启动，但是小米就说sdk启动了
> 
> 我的小米审核问题解决了，把fluwx初始化的位置更改下位置，就通过审核了！

请教一下，修改到什么位置，可以成功

**Comment by JarvanMo** [comment]
可以考虑首页。

**Comment by ZhangZhiH** [comment]
我也遇到了 怎么都过不了审核 请问有解决的吗

**Comment by JarvanMo** [comment]
> @JarvanMo 我也遇到了 并且我注册都是 同意协议之后 是不是这个地方导致的 怎么都过不了审核 请问有解决的吗 ![image](https://user-images.githubusercontent.com/14193471/279605891-a5248438-a6d1-4868-803f-c75f474ee4e2.png)
> 
> android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:171)<---android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:149)<---n8.e.b(SourceFile:1)<---n8.e.c(SourceFile:1)<---n8.e.onAttachedToEngine(SourceFile:1)<---eg.b.i(SourceFile:7)<---io.flutter.plugins.GeneratedPluginRegistrant.registerWith(SourceFile:15)<---com.example.gwapp.MainActivity.f(SourceFile:1)<---io.flutter.embedding.android.a.p(SourceFile:8)<---io.flutter.embedding.android.FlutterActivity.onCreate(SourceFile:4)<---com.example.gwapp.MainActivity.onCreate(SourceFile:1)<---android.app.Activity.performCreate(Activity.java:7070)<---android.app.Activity.performCreate(Activity.java:7061)<---android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)<---android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3067)<---android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3191)<---android.app.ActivityThread.-wrap11(Unknown Source:0)<---android.app.ActivityThread$H.handleMessage(ActivityThread.java:1921)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.app.ActivityThread.main(ActivityThread.java:6843)<---java.lang.reflect.Method.invoke(Native Method)<---com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)<---com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

审核相关的我不是太了解，可以尝试升级新版本或者，自己改动一下源码

**Comment by ZhangZhiH** [comment]
> > @JarvanMo 我也遇到了 并且我注册都是 同意协议之后 是不是这个地方导致的 怎么都过不了审核 请问有解决的吗 ![image](https://user-images.githubusercontent.com/14193471/279605891-a5248438-a6d1-4868-803f-c75f474ee4e2.png)
> > android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:171)<---android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:149)<---n8.e.b(SourceFile:1)<---n8.e.c(SourceFile:1)<---n8.e.onAttachedToEngine(SourceFile:1)<---eg.b.i(SourceFile:7)<---io.flutter.plugins.GeneratedPluginRegistrant.registerWith(SourceFile:15)<---com.example.gwapp.MainActivity.f(SourceFile:1)<---io.flutter.embedding.android.a.p(SourceFile:8)<---io.flutter.embedding.android.FlutterActivity.onCreate(SourceFile:4)<---com.example.gwapp.MainActivity.onCreate(SourceFile:1)<---android.app.Activity.performCreate(Activity.java:7070)<---android.app.Activity.performCreate(Activity.java:7061)<---android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)<---android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3067)<---android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3191)<---android.app.ActivityThread.-wrap11(Unknown Source:0)<---android.app.ActivityThread$H.handleMessage(ActivityThread.java:1921)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.app.ActivityThread.main(ActivityThread.java:6843)<---java.lang.reflect.Method.invoke(Native Method)<---com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)<---com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 
> 审核相关的我不是太了解，可以尝试升级新版本或者，自己改动一下源码

跟插件没关系 已经解决了  插件只要换顺序就不影响了

**Comment by JarvanMo** [comment]
> > > @JarvanMo 我也遇到了 并且我注册都是 同意协议之后 是不是这个地方导致的 怎么都过不了审核 请问有解决的吗 ![image](https://user-images.githubusercontent.com/14193471/279605891-a5248438-a6d1-4868-803f-c75f474ee4e2.png)
> > > android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:171)<---android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:149)<---n8.e.b(SourceFile:1)<---n8.e.c(SourceFile:1)<---n8.e.onAttachedToEngine(SourceFile:1)<---eg.b.i(SourceFile:7)<---io.flutter.plugins.GeneratedPluginRegistrant.registerWith(SourceFile:15)<---com.example.gwapp.MainActivity.f(SourceFile:1)<---io.flutter.embedding.android.a.p(SourceFile:8)<---io.flutter.embedding.android.FlutterActivity.onCreate(SourceFile:4)<---com.example.gwapp.MainActivity.onCreate(SourceFile:1)<---android.app.Activity.performCreate(Activity.java:7070)<---android.app.Activity.performCreate(Activity.java:7061)<---android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)<---android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3067)<---android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3191)<---android.app.ActivityThread.-wrap11(Unknown Source:0)<---android.app.ActivityThread$H.handleMessage(ActivityThread.java:1921)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.app.ActivityThread.main(ActivityThread.java:6843)<---java.lang.reflect.Method.invoke(Native Method)<---com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)<---com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> > 
> > 
> > 审核相关的我不是太了解，可以尝试升级新版本或者，自己改动一下源码
> 
> 跟插件没关系 已经解决了 插件只要在同意隐私之后再初始化就不影响了 如果大家遇到flutter 小米审核出现问题 是n8.e.onAttachedToEngine,等问题的时候 可以联系一下客服就知道了 ![694f252e8b57805bfc9f07f00550449](https://user-images.githubusercontent.com/14193471/283317138-fc25ec48-dfd7-43bf-9086-67b653e406cf.png)

Awesome
