### ISSUE TITLE
flutter 3.13.0 shareImage after back app crash

### ISSUE THREAD

**Issue by Bingbing0311** [OpenFlutter/fluwx#561]
<img width="728" alt="截屏2023-08-21 18 41 43" src="https://github.com/OpenFlutter/fluwx/assets/13670665/96e7f1ea-88fd-478c-bb58-b2b179ad707c">

**Comment by Bingbing0311** [comment]
分享图片返回APP之后，APP卡死崩溃

**Comment by luckilyyg** [comment]
分享图片出去 缩略图可以展示吗

**Comment by luckilyyg** [comment]
这是来自QQ邮箱的假期自动回复邮件。
