### ISSUE TITLE
安卓支付无问题，但是iOS支付验证签名失败

### ISSUE THREAD

**Issue by wangzhedong** [OpenFlutter/fluwx#564]
请问下，ios拉起微信支付的时候，在微信的界面上弹了个窗，报“支付验证签名失败”，这个是什么原因引起的，但是在安卓机上支付是正常的。以下是报错的日志：
FluwxLog: [WeChatIdentityHandler.mm]-[WeChatIdentityHandler checkAndRecordTokenToKeychain:contextID:error:]WXLog:Error:set token fail, errCode:4, errLog:wx token[] or contextId[(null)] is nil!

**Comment by JarvanMo** [comment]
跨平台的只是插件，不是支付参数

**Comment by wangzhedong** [comment]
如果支付参数有问题，安卓应该也会有问题的吧

**Comment by JarvanMo** [comment]
> 跨平台的只是插件，不是支付参数

烦请仔细读读和理解理解？

**Comment by dulifu** [comment]
我微信登录也一样报了这个错误

**Comment by terry9309** [comment]
有解决结果吗？我也报了这个错误

**Comment by yfming93** [comment]
一样问题，有结果吗
