### ISSUE TITLE
no_pay设置的问题(有可能比较呆,请见谅)

### ISSUE THREAD

**Issue by WFCN** [OpenFlutter/fluwx#565]
当我设置 no_pay=true的时候  执行pod install   提示 use sdk without pay  install  OpenWeChatSDKNoPay  

当我设置 no_pay=false的时候  执行pod install   提示 use sdk with pay  install  WechatOpenSDK-XCFramework

而文档里说set false to disable payment   所以到底该设置成false还是ture

**Comment by JarvanMo** [comment]
应该是文档搞错了

**Comment by WFCN** [comment]
> 应该是文档搞错了

![image](https://github.com/OpenFlutter/fluwx/assets/12468734/b8078220-4cf3-4445-9865-330b6da0d53a)
这次审核  我的确设置的是no_pay:true    但是苹果审核的人说  我们有财付通SDK   所以才有这个疑问

**Comment by JarvanMo** [comment]
应该不至于有用错framework 的问题，要不然应该有人反映这个问题，可以自己fork一份确认一下那些宏定义对不对

**Comment by JarvanMo** [comment]
还有一点就是确认其他SDK没有捎带上支付

**Comment by WFCN** [comment]
> 还有一点就是确认其他SDK没有捎带上支付

谢谢  解答    我就关了这个了   下个版本建议修改下文档  哈哈

**Comment by JarvanMo** [comment]
你也可以提个PR修复此问题

**Comment by jihchao** [comment]
> > 还有一点就是确认其他SDK没有捎带上支付
> 
> 谢谢 解答 我就关了这个了 下个版本建议修改下文档 哈哈

 你好，你解决了吗？我也是no_pay设置为true，苹果审核依然反馈有wechat pay。
是什么原因的？

**Comment by WFCN** [comment]
> > > 还有一点就是确认其他SDK没有捎带上支付
> > 
> > 
> > 谢谢 解答 我就关了这个了 下个版本建议修改下文档 哈哈
> 
> 你好，你解决了吗？我也是no_pay设置为true，苹果审核依然反馈有wechat pay。 是什么原因的？

看看代码里有没有这个域名(wx.tenpay.com)的字符串常量或者硬编码,或者别的腾讯支付的其他域名字符串

**Comment by jihchao** [comment]
> > > > 还有一点就是确认其他SDK没有捎带上支付
> > > 
> > > 
> > > 谢谢 解答 我就关了这个了 下个版本建议修改下文档 哈哈
> > 
> > 
> > 你好，你解决了吗？我也是no_pay设置为true，苹果审核依然反馈有wechat pay。 是什么原因的？
> 
> 看看代码里有没有这个域名(wx.tenpay.com)的字符串常量或者硬编码,或者别的腾讯支付的其他域名字符串

谢谢，找到了在另一个插件里面有个唤醒小程序的逻辑，也使用了 fluwx，难道同一个项目里面的其他插件使用的fluwx不接受主项目的no_pay 配置吗？

**Comment by JarvanMo** [comment]
> > > > > 还有一点就是确认其他SDK没有捎带上支付
> > > > 
> > > > 
> > > > 谢谢 解答 我就关了这个了 下个版本建议修改下文档 哈哈
> > > 
> > > 
> > > 你好，你解决了吗？我也是no_pay设置为true，苹果审核依然反馈有wechat pay。 是什么原因的？
> > 
> > 
> > 看看代码里有没有这个域名(wx.tenpay.com)的字符串常量或者硬编码,或者别的腾讯支付的其他域名字符串
> 
> 谢谢，找到了在另一个插件里面有个唤醒小程序的逻辑，也使用了 fluwx，难道同一个项目里面的其他插件使用的fluwx不接受主项目的no_pay 配置吗？

No pay 开关只是告诉当前模块打包时到底用哪个framework罢了，没有那么高深

**Comment by jihchao** [comment]
> > > > > > 还有一点就是确认其他SDK没有捎带上支付
> > > > > 
> > > > > 
> > > > > 谢谢 解答 我就关了这个了 下个版本建议修改下文档 哈哈
> > > > 
> > > > 
> > > > 你好，你解决了吗？我也是no_pay设置为true，苹果审核依然反馈有wechat pay。 是什么原因的？
> > > 
> > > 
> > > 看看代码里有没有这个域名(wx.tenpay.com)的字符串常量或者硬编码,或者别的腾讯支付的其他域名字符串
> > 
> > 
> > 谢谢，找到了在另一个插件里面有个唤醒小程序的逻辑，也使用了 fluwx，难道同一个项目里面的其他插件使用的fluwx不接受主项目的no_pay 配置吗？
> 
> No pay 开关只是告诉当前模块打包时到底用哪个framework罢了，没有那么高深

好的，感谢你的回复，这真实一个非常棒的项目。
