### ISSUE TITLE
调起微信客服接口

### ISSUE THREAD

**Issue by keepgagaga** [OpenFlutter/fluwx#566]
真的，既然都做出来了，花两分钟完善下文档不好么？

**Comment by JarvanMo** [comment]
真的，你去对照微信官方文档看看原生方法叫什么，然后对照一下不好吗？然后再提一个PR，改善一下文档不好吗？最次，你把微信官方文档里原生接入文档发一下也行，这样不好吗？
最后，不是所有功能都是我开发的，我不是了解所有的功能

**Comment by JarvanMo** [comment]
很多功能是用户自己添加

**Comment by JarvanMo** [comment]
这个项目里的功能基本都和微信官方文档里的方法名保持高度相似，随便搜两下，也能找个差不多。这个开源项目纯靠爱发电，别动不动两分钟，你两分钟，我两分钟，得多少个两分钟？有那两分钟你也可以找到怎么实现，并提个PR。如果我没记错，我一直和你要微信官方文档吧，你至今也没给出来

**Comment by JarvanMo** [comment]
我看到之前的issue了，你去搜搜CustomerServiceChat，看看能不能搜到，然后应该知道怎么用了吧。好了，麻烦花两分钟，提个PR，改善一下文档。

**Comment by keepgagaga** [comment]
> 我看到之前的issue了，你去搜搜CustomerServiceChat，看看能不能搜到，然后应该知道怎么用了吧。好了，麻烦花两分钟，提个PR，改善一下文档。

去源码里找到了。

**Comment by keepgagaga** [comment]
> 这个项目里的功能基本都和微信官方文档里的方法名保持高度相似，随便搜两下，也能找个差不多。这个开源项目纯靠爱发电，别动不动两分钟，你两分钟，我两分钟，得多少个两分钟？有那两分钟你也可以找到怎么实现，并提个PR。如果我没记错，我一直和你要微信官方文档吧，你至今也没给出来

是我考虑欠缺了，这个确实抱歉

**Comment by JarvanMo** [comment]
> > 我看到之前的issue了，你去搜搜CustomerServiceChat，看看能不能搜到，然后应该知道怎么用了吧。好了，麻烦花两分钟，提个PR，改善一下文档。
> 
> 去源码里找到了。

所以赶紧花两分钟，提个PR，改善一下文档。

**Comment by keepgagaga** [comment]
> 

没问题，让我看看怎么搞

**Comment by keepgagaga** [comment]
> > > 我看到之前的issue了，你去搜搜CustomerServiceChat，看看能不能搜到，然后应该知道怎么用了吧。好了，麻烦花两分钟，提个PR，改善一下文档。
> > 
> > 
> > 去源码里找到了。
> 
> 所以赶紧花两分钟，提个PR，改善一下文档。

没问题，我看看怎么做

**Comment by keepgagaga** [comment]
```dart
 Fluwx().open(
    target: CustomerServiceChat(
      url: '客服 URL',
      corpId: '企业 ID',
      ),
);
```

**Comment by JarvanMo** [comment]
可以更新到文档么

**Comment by JarvanMo** [comment]
周末了，而且你已经知道怎么使用了，可以花两分钟提个PR改进一下文档么？

**Comment by keepgagaga** [comment]
> 周末了，而且你已经知道怎么使用了，可以花两分钟提个PR改进一下文档么？

已提交，主文档不知道加在哪比较合适，就加载方法注释里了，这样当使用的时候在编辑器里也可以看到。
