### ISSUE TITLE
提问一下关于文档的 LAUNCH_APP_FROM_H5 这部分

### ISSUE THREAD

**Issue by lopo12123** [OpenFlutter/fluwx#568]
作者你好，我使用这个库比较久了，之前使用都是正常的，不知道从什么时候开始ios上出问题了：能正常跳转到应用，universallink检查了是对的，但是跳转携带的参数都变成null了。
分享到微信、拉起微信客服、微信支付这些功能都是可用的，只有微信开放标签跳转过来参数获取不到。

我想请问一下这个现象是我没有在 AppDelegate中主动注册WXApi导致的吗。

另外，我想请问作者能不能帮忙提供一下你的示例代码的 swift 版本 (就是[这里](https://github.com/OpenFlutter/fluwx/blob/5ef94a3837e5d7433c7e3835e88acacff8ee3afa/doc/LAUNCH_APP_FROM_H5_CN.md) 的oc代码)。oc 和 swift 我都不会写，看着oc我写不出 swift /(ㄒoㄒ)/~~

感谢作者

**Comment by JarvanMo** [comment]
你是冷启动还是热启动，你怎么获取的参数？

**Comment by JarvanMo** [comment]
获取ext msg参数可以参考example

**Comment by JarvanMo** [comment]
冷启动就比较麻烦了

**Comment by lopo12123** [comment]
冷启动 和 热启动 都试了，获取到的参数都是为 null

以下是我的代码的一些部分

![image](https://github.com/OpenFlutter/fluwx/assets/59609929/f83172b9-e665-4be6-92e5-c803d27cd707)
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/84465c12-d2a3-4eeb-be48-5d948045e81d)
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/67df1d20-d0f4-412e-87ba-fd5efb14fe6c)

冷启动的处理 在安卓上是没问题的，冷启动也能拿到参数
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/46c343e3-4e20-4850-a448-7e9c1ed9548d)
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/dce0bc35-55a7-495f-81db-aaa4e3f65f48)

**Comment by JarvanMo** [comment]
有新写法，看一下example

**Comment by lopo12123** [comment]
> 有新写法，看一下example

你好，我仔细看了一下 example 里的各个例子，想请教两个问题：

1. 看了一下 cold_boot_page.dart 的例子，我的理解如下，请问这两个事件是这个含义吗
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/bdd5f2d5-5d35-4194-919f-b036f1a52161)

2. 我看到你在 main.dart 里还是有使用 `getExtMsg` 方法，请问这个方法和上述的事件监听有什么区别，能麻烦讲解一下吗。
我的用途是解析微信唤起的参数并进行处理，使用事件监听的话是不是就不需要用到 `getExtMsg` 了。
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/e62c8d60-beaa-4d13-b46a-84fe90300be4)

希望您有空的时候解答一下，感谢

**Comment by JarvanMo** [comment]
用监听，不过iOS冷启动应该还是需要在appdelegate 里初始化微信SDK，然后flutter 里面不过过早的监听回调

**Comment by lopo12123** [comment]
我对比了一下安卓和ios的源码和微信的官方文档。

在 ios端 微信唤起应用的时候使用 getExtMsg 获取不到额外参数的原因可能是此处没有对 extMsg 进行缓存以供 `getExtMsg` 获取，导致无法通过 `getExtMsg` 获取到 `LaunchFromWXReq` 事件的参数，而使用监听的方法可以正常获取到参数。

[微信关于 wx-open-launch-app 的文档](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html#%E8%B7%B3%E8%BD%ACAPP%EF%BC%9Awx-open-launch-app)
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/114608b6-d7b4-4bc9-9c4b-098f2d54a9ca)

ios端 onReq 重写代码的截图
![image](https://github.com/OpenFlutter/fluwx/assets/59609929/27656873-5a68-40e0-a696-4b8d46a2f62e)

---

我正在打包准备测试一下，稍后我会再来反馈结果

**Comment by JarvanMo** [comment]
好的，可以把那个加上，可能是不小心删除了。
