### ISSUE TITLE
关于在iOS系统上addSubscriber重复订阅的问题

### ISSUE THREAD

**Issue by tour4x** [OpenFlutter/fluwx#569]
大佬您好，我遇到了addSubscriber重复订阅的问题，代码如下
我的想法是收到授权回调后就取消监听，但似乎不生效，还请帮忙看下代码，我另外试过将listener存在一个单例中进行取消监听，也没有效果,我有看到有人解决了这个问题 [https://github.com/OpenFlutter/fluwx/issues/534](url)， 我们版本有些不一样,我的是最新版本

`static login({Function? complete, Function(String code)? goBind}){

    late WeChatResponseSubscriber listener;
    listener = (res) {
      Fluwx().removeSubscriber(listener);
    };
    Fluwx().addSubscriber(listener);
    Fluwx()
        .authBy(
            which: NormalAuth(
          scope: WX_USERINFO_SCOPE,
          state: WX_LOGIN_STATE,
        ))
        .then((data) {});
  }`

**Comment by JarvanMo** [comment]
你数数你创建了几个fluwx对象

**Comment by tour4x** [comment]
> 你数数你创建了几个fluwx对象

误认为是Fluwx是单例😅，改了代码可以了，感谢大佬

**Comment by lopo12123** [comment]
建议封装一层，以下是个人代码，仅供参考

``` dart
static void _listenOnce<T extends WeChatResponse>(
    void Function(T response) executor) {
  FluwxCancelable? listener;
  listener = _fluwx.addSubscriber((response) {
    if (response is T) {
      executor(response);
      Future.microtask(() => listener?.cancel());
    }
  });
}
```

调用的时候

``` dart
  static Future<bool> requestAuth(
    void Function(Result<String, String> code) callback,
  ) async {
    await _ensureRegistered();

    _listenOnce<WeChatAuthResponse>((response) {
      callback(
        // errCode: -4 取消; -2 关闭; 0 正常
        response.errCode == 0
            ? Result.ok(response.code)
            : Result.err(response.errCode == -4 ? '用户拒绝授权' : '用户关闭授权'),
      );
    });

    return await _fluwx.authBy(
      which: NormalAuth(scope: 'snsapi_userinfo', nonAutomatic: true),
    );
  }
```

这样调用的时候就可以简单的传入 callback 就可以了，或者再封装成 async/await 的形式也可以
