### ISSUE TITLE
 Task :fluwx:testDebugUnitTest FAILED

### ISSUE THREAD

**Issue by shihanjun19** [OpenFlutter/fluwx#572]
**Describe the bug**
项目使用 gradlew build时报错，  Task :fluwx:testDebugUnitTest FAILED

**To Reproduce**
使用android studio， flutter版本 3.10.6    编译报错

**Which version of Fluwx do you use?**
 fluwx: ^4.3.0

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.
使用android 模拟器 api 33
![image](https://github.com/OpenFlutter/fluwx/assets/10006241/1ca7501d-4f82-4447-8789-13986d276ecd)

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.
![image](https://github.com/OpenFlutter/fluwx/assets/10006241/95f33bc0-1559-4186-8ce7-47d267481f4a)

gradlew build --info
![image](https://github.com/OpenFlutter/fluwx/assets/10006241/ebe09a6b-4b58-4fa1-8203-4e5e7213b015)

gradlew build --stacktrace
![image](https://github.com/OpenFlutter/fluwx/assets/10006241/a841aec2-ad79-4983-9999-0598bfab69bc)

com.jarvan.fluwx.FluwxPluginTest.html 日志截图
![image](https://github.com/OpenFlutter/fluwx/assets/10006241/853431cf-ba74-46d4-86bf-841262adccbe)

**Comment by JarvanMo** [comment]
UT失败了，本来这个项目也没有UT，如果影响了ciCd，直接注释掉了就好。而且这个版本fluwx是个旧版本

**Comment by shihanjun19** [comment]
@JarvanMo   请问下应该去哪进行代码注释， 另外，我看了下pubspec.lock  版本应该是 4.3.0.   这个版本是最新版本了吧。
