### ISSUE TITLE
微信8.0.41版本使用了fluwx4.2.7版本分享图片，分享小程序会出现：分享类型不支持

### ISSUE THREAD

**Issue by jimonik** [OpenFlutter/fluwx#573]
微信8.0.41版本使用了fluwx4.2.7版本分享图片，分享小程序会出现：分享类型不支持

**Comment by JarvanMo** [comment]
其他版本的微信没问题？

**Comment by jimonik** [comment]
暂时没有遇到，目前8.0.41应该是最新版本

**Comment by JarvanMo** [comment]
如果其他版本的微信分享确认没有问题，那就说明目前库是没有问题。要么是微信的问题，要么就是SDK有升级

**Comment by JarvanMo** [comment]
而且你说的是哪个平台？

**Comment by jimonik** [comment]
android微信平台8.0.41分享不出去，ios正常，另外，我看你的版本变成了4.3.0，我先去升级试试

**Comment by jimonik** [comment]
4.3.0可以分享出去！
