### ISSUE TITLE
fluwx 与 SpeechXf 发生冲突报 duplicate symbol '_type'

### ISSUE THREAD

**Issue by wskkhn-hezhong** [OpenFlutter/fluwx#575]
**Describe the bug**
duplicate symbol '_type' in:
    /Users/****/Library/Developer/Xcode/DerivedData/Runner-cxjaidkjrfmkticnuwbjakowdsey/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/fluwx/libfluwx.a(FluwxPlugin.o)
    /Users/****/Library/Developer/Xcode/DerivedData/Runner-cxjaidkjrfmkticnuwbjakowdsey/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/speech_xf/libspeech_xf.a(SpeechXfPlugin.o)

**To Reproduce**
1. flutter build ipa 
2.  fluwx 我使用了 3.13.1和 4.3.1   SpeechXf 我是用的是1.2.2,
3.  编译打包报错

**Which version of Fluwx do you use?**
 fluwx 我使用了 3.13.1和 4.3.1

**Which device do you run on**
编译打包报错 

**Which Flutter do you use?**
flutter  3.10.0
Run `flutter doctor` and paste the output here.
[!] Flutter (Channel unknown, 3.10.0, on macOS 13.4.1 22F82 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.10.0 on channel unknown at /Users/hezhong/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by JarvanMo** [comment]
最新的fluwx没发现有显示声明_type

**Comment by wskkhn-hezhong** [comment]
![image](https://github.com/OpenFlutter/fluwx/assets/15773517/54425061-ddb1-4519-a7e4-8e7a229671ea)

**Comment by wskkhn-hezhong** [comment]
我找到你的type定义了
![image](https://github.com/OpenFlutter/fluwx/assets/15773517/1c256a5d-21b2-4c45-bcf5-ab1a3d230c5b)

**Comment by wskkhn-hezhong** [comment]
就是因为这个，讯飞是的里面也有这个type的变量名，导致的冲突

**Comment by wskkhn-hezhong** [comment]
我在本地修改了这个变量名就可以了

**Comment by JarvanMo** [comment]
那你可以提个PR修复这个问题，或者让迅飞改
