### ISSUE TITLE
fluwx  ios分享的时候，微信回到app，app没有再次跳转到微信唤起好友列表，而是停留在app中

### ISSUE THREAD

**Issue by xuelangjie** [OpenFlutter/fluwx#577]
使用 fluwx 分享链接，app会唤起微信，然后微信链接跳转回app，正常流程应该会再跳转回微信，但现在停留在app中，请问这个是什么问题？？？

**Comment by xuelangjie** [comment]
控制台日志：
flutter: FluwxLog: [WeChatIdentityHandler.mm]+[WeChatIdentityHandler loadTokenFromKeychain]WXLog:Error:fail to load Keychain status:-25300, keyData null:1
flutter: FluwxLog: [WeChatIdentityHandler.mm]+[WeChatIdentityHandler loadTokenFromKeychain]WXLog:token[(null)] is null

**Comment by luckilyyg** [comment]
请问你分享出去 缩略图可以展示吗

**Comment by xuelangjie** [comment]
可以的，Android是好的，就是iOS第一次唤起微信的时候有一个微信链接app的流程，现在是这个流程回到app后没有返回微信唤起好友发自我的手机-------- 原始邮件 --------发件人： super果 ***@***.***>日期： 2023年10月10日周二 15:34收件人： OpenFlutter/fluwx ***@***.***>抄送： xuelangjie ***@***.***>, Author ***@***.***>主    题： Re: [OpenFlutter/fluwx] fluwx  ios分享的时候，微信回到app，app没有再次跳转到微信唤起好友列表，而是停留在app中 (Issue #577)
请问你分享出去 缩略图可以展示吗

**Comment by luckilyyg** [comment]
这是来自QQ邮箱的假期自动回复邮件。

**Comment by CoderWeiLee** [comment]
就是啊  修改了universalLink之后  怎么分享到会话  变成直接打开自己的APP了  然后就停留在自己app中了   没有跳转到微信会话列表

**Comment by Pgrammerybj** [comment]
还没有解决吗？

**Comment by Pgrammerybj** [comment]
了解

发件人: xuelangjie ***@***.***>
日期: 星期三, 2024年1月24日 15:17
收件人: OpenFlutter/fluwx ***@***.***>
抄送: 杨保疆 ***@***.***>, Comment ***@***.***>
主题: Re: [OpenFlutter/fluwx] fluwx ios分享的时候，微信回到app，app没有再次跳转到微信唤起好友列表，而是停留在app中 (Issue #577)

还没有解决吗？

解决了，是一个其他库引起的bug，换一个就好了

―

**Comment by yanxinchen** [comment]
我也遇到了相同的问题，有些ios手机和微信建立连接会失败，报错：WXLog:Error:fail to load Keychain status:-25300, keyData null:1。请问你是怎么解决的呀？

**Comment by luckilyyg** [comment]
这是来自QQ邮箱的假期自动回复邮件。

**Comment by yanxinchen** [comment]
@xuelangjie 是什么库导致的问题呀？

**Comment by dulifu** [comment]
> > 还没有解决吗？
> 
> 解决了，是一个其他库引起的bug，换一个就好了

是什么库引起的，我现在也遇到了一样的问题，iOS同样的操作
，换了一个unversal link url就不行了
