### ISSUE TITLE
版本4.3.2 通过open api打开小程序报 -canOpenURL: failed for URL: "weixinURLParamsAPI://" 

### ISSUE THREAD

**Issue by runningfan123** [OpenFlutter/fluwx#579]
在info中配置了weixinURLParamsAPI，依旧报该项错误
 **Runner[5292:1934475] -canOpenURL: failed for URL: "weixinURLParamsAPI://" - error: "未能完成操作。（OSStatus错误-10814。）"**

并在pubspec.yaml 中配置
fluwx:
  ios:
    debug_logging: true # Logging in debug mode.
    universal_link: ************

***
fluwx: ^4.3.2

fluwx .open(
            target: MiniProgram(
              username: SystemBaseConfig.miniProgramId,
              path: 'subpack_middlePay/pages/appPay/index?$params',
              miniProgramType: WXMiniProgramType.preview,
            ))

**Comment by JarvanMo** [comment]
自己对照微信官方文档看看，肯定是配置不对

**Comment by runningfan123** [comment]
是手机问题，重启手机就好了
