### ISSUE TITLE
微信支付完，监听不到支付结果

### ISSUE THREAD

**Issue by ganisback** [OpenFlutter/fluwx#58]
微信支付完，监听不到支付结果

**Comment by JarvanMo** [comment]
多看文档和以前的issue

**Comment by ganisback** [comment]
@JarvanMo 我觉得这个问题很容易重现吧，我在苹果和安卓这个问题都重现了，之前有个issue 也是这个问题，最后你们也是直接close了

**Comment by JarvanMo** [comment]
首先，Fluwx 100%没问题。其次，appdelegate该配置的得配置，如果你自己手动配置了WxPayEntryActivity请自行解决。最后，你们服务端做的对不对我不得而知，我也不懂。

**Comment by ganisback** [comment]
现在比较棘手的是我把你写的Tobias 和fluwx 都集成了，在appdelegate 会有接口冲突。不知道你们会有什么解决方案，感激不尽。

**Comment by JarvanMo** [comment]
很简单，直接依次handle，直接return YES或者return true就行了。

**Comment by ganisback** [comment]
🙏,非常感谢，我试试

**Comment by ganisback** [comment]
已打赏，事实证明 你的组件perfect.

**Comment by JarvanMo** [comment]
感谢支持@ganisback
