### ISSUE TITLE
使用[Fluwx-4.3.2]版本通过微信冷启动打开 App，没有走 WeChatResponseSubscriber 回调

### ISSUE THREAD

**Issue by josercc** [OpenFlutter/fluwx#580]
**Describe the bug**
使用[Fluwx-4.3.2]版本通过微信冷启动打开 App，没有走 WeChatResponseSubscriber 回调。
已经按照相关的问题配置安卓的  xml 文件

问题如下 我们在微信走微信标签注册，在微信外部浏览器使用 moblink 服务

**App 处于后台**

✅ 通过外部浏览器打开 App 正常获取到闭环的参数

✅ 在微信通过微信标签打开 App 正常获取到闭环参数

**App  关闭状态**

✅ 通过外部浏览器打开 App 正常获取到闭环的参数

❌ 在微信通过微信标签打开 App 获取不到闭环参数

**To Reproduce**
1  从 App 分享网页到微信
2  关闭当前 App
3  点击微信分享网页
4  点击网页的打开 App 按钮
5  微信提示打开 App
6  点击打开跳转到 App 冷启动打开
7  查看日志没有 WeChatResponseSubscriber 回调

**Which version of Fluwx do you use?**
4.3.2

**Which device do you run on**
红米 K60 Pro MiUI 14.0 版本

**Which Flutter do you use?**
flutter-3.13.2

Run `flutter doctor` and paste the output here.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F770820d darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.83.0)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by JarvanMo** [comment]
首先这个功能我没用过，也不了解，但理论上应该是没有问题的。这个问题本质上是因为冷启动的时候微信启动app的时候flutter engine 并没有ready 。所以
1. 该功能原生代码应该回调哪什么req？
2. Fluwx初始化成功以后，，涉及冷启动，flutter应该主动调用attempToResumeMsgFromWx

**Comment by josercc** [comment]
> 首先这个功能我没用过，也不了解，但理论上应该是没有问题的。这个问题本质上是因为冷启动的时候微信启动app的时候flutter engine 并没有ready 。所以
> 
> 1. 该功能原生代码应该回调哪什么req？
> 2. Fluwx初始化成功以后，，涉及冷启动，flutter应该主动调用attempToResumeMsgFromWx

我猜测也是微信已经调用 App的初始化回调但是还没有初始化引擎 这个问题导致的
attempToResumeMsgFromWx 这个函数我看一下 🙏
