### ISSUE TITLE
版本4.3.2，能在pubspec文件中不强制universal_link吗？我在Xcode中根据不同渠道配置的，有些渠道版本没用这个库，导致切换时，库中的universal_link带过来了。

### ISSUE THREAD

**Issue by chentl666** [OpenFlutter/fluwx#581]
版本4.3.2，能在pubspec文件中不强制universal_link吗？我在Xcode中根据不同渠道配置的，有些渠道版本没用这个库，导致切换时，库中的universal_link带过来了。
Xcode中配了两个，每次都要手动删掉一个
<img width="539" alt="image" src="https://github.com/OpenFlutter/fluwx/assets/39117506/c239b758-e93d-4723-b017-dfa0eb93a7bc">

**Comment by JarvanMo** [comment]
等我有空更新一下

**Comment by JarvanMo** [comment]
See v4.4.0.
