### ISSUE TITLE
新版本iOS分享，分享后thumbnail缩略图不显示问题

### ISSUE THREAD

**Issue by TYJ1990** [OpenFlutter/fluwx#584]
**Describe the bug**

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

**Comment by TYJ1990** [comment]
不好意思，没编辑内容就发送出去了。
老版本在FluwxShareHandler.m里做了初始化赋值
- (instancetype)initWithRegistrar:(NSObject <FlutterPluginRegistrar> *)registrar {
    self = [super init];
    if (self) {
        _fluwxRegistrar = registrar;
        thumbnailWidth = 150;
    }
    return self;
}
而新版本合并了代码，在FluwxPlugin里，没有给_fluwxRegistrar赋值，
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
    FlutterMethodChannel *channel =
        [FlutterMethodChannel methodChannelWithName:@"com.jarvanmo/fluwx"
                                    binaryMessenger:[registrar messenger]];
    FluwxPlugin *instance = [[FluwxPlugin alloc] initWithChannel:channel];
    [registrar addApplicationDelegate:instance];
    [registrar addMethodCallDelegate:instance channel:channel];
}
导致获取图片时，key为nil
- (NSString *)readFileFromAssets:(NSString *)imagePath {
    NSArray *array = [self formatAssets:imagePath];
    NSString *key;
    if ([FluwxStringUtil isBlank:array[1]]) {
        key = [_fluwxRegistrar lookupKeyForAsset:array[0]];
    } else {
        key = [_fluwxRegistrar lookupKeyForAsset:array[0] fromPackage:array[1]];
    }

    return [[NSBundle mainBundle] pathForResource:key ofType:nil];
}
需要加个赋值代码
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
    //
    _fluwxRegistrar = registrar;
    FlutterMethodChannel *channel =
        [FlutterMethodChannel methodChannelWithName:@"com.jarvanmo/fluwx"
                                    binaryMessenger:[registrar messenger]];
    FluwxPlugin *instance = [[FluwxPlugin alloc] initWithChannel:channel];
    [registrar addApplicationDelegate:instance];
    [registrar addMethodCallDelegate:instance channel:channel];
}

**Comment by JarvanMo** [comment]
麻烦提个PR呗

**Comment by TYJ1990** [comment]
> 麻烦提个PR呗

提好了

**Comment by JarvanMo** [comment]
Fixed in `4.4.3`
