### ISSUE TITLE
flutter_flavorizr 如何配置fluwx的app_id

### ISSUE THREAD

**Issue by CrassusX** [OpenFlutter/fluwx#588]
如果多渠道打包，不同包名的app_id不同，那请问pubspec.yaml怎么配置不同的app_id
fluwx:
  app_id: "xxxxx"
  debug_logging: true # Logging in debug mode.
  android:

**Comment by JarvanMo** [comment]
appid可以不填。但是要去微信官网看看需要手动配置什么，然后对应配置就行
