### ISSUE TITLE
目前是否支持发送各种请求到微信

### ISSUE THREAD

**Issue by huangjianke** [OpenFlutter/fluwx#59]
目前看源码好像没有相关的实现，目前有这方面的需求，还望作者看下
![image](https://user-images.githubusercontent.com/8692455/56480743-05929f80-64ee-11e9-82b4-811f61b00c1e.png)

**Comment by JarvanMo** [comment]
你再看看人文档是怎么说的，只支持几种。常用的我都已经实现了。如果有其他需求随时欢迎PR。
