### ISSUE TITLE
这个是啥问题呀

### ISSUE THREAD

**Issue by icc-tips** [OpenFlutter/fluwx#595]
e: /Users/wjf/.pub-cache/hosted/pub.flutter-io.cn/fluwx-4.4.9/android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt: (104, 21): Unresolved reference: FluwxConfigurations
e: /Users/wjf/.pub-cache/hosted/pub.flutter-io.cn/fluwx-4.4.9/android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt: (361, 21): Unresolved reference: FluwxConfigurations
e: /Users/wjf/.pub-cache/hosted/pub.flutter-io.cn/fluwx-4.4.9/android/src/main/kotlin/com/jarvan/fluwx/utils/FluwxExtensions.kt: (10, 25): Unresolved reference: FluwxConfigurations
e: /Users/wjf/.pub-cache/hosted/pub.flutter-io.cn/fluwx-4.4.9/android/src/main/kotlin/com/jarvan/fluwx/utils/FluwxExtensions.kt: (35, 16): Unresolved reference: FluwxConfigurations
e: /Users/wjf/.pub-cache/hosted/pub.flutter-io.cn/fluwx-4.4.9/android/src/main/kotlin/com/jarvan/fluwx/utils/FluwxExtensions.kt: (39, 53): Unresolved reference: FluwxConfigurations

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluwx:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by JarvanMo** [comment]
你是怎么出来的这个问题？
