### ISSUE TITLE
`parse_xml': wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by ahkela21** [OpenFlutter/fluwx#597]
**Describe the bug**
```
using sdk with pay
ignore_security: 
app_id: wxb78d31de1a434b74 universal_link: https://bluente.link/
/opt/homebrew/lib/ruby/gems/3.1.0/gems/plist-3.6.0/lib/plist/parser.rb:29:in `parse_xml': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/gitlab/.pub-cache/hosted/pub.dev/fluwx-4.4.9/ios/wechat_setup.rb:80:in `block (2 levels) in <main>'
	from /Users/gitlab/.pub-cache/hosted/pub.dev/fluwx-4.4.9/ios/wechat_setup.rb:71:in `each'
	from /Users/gitlab/.pub-cache/hosted/pub.dev/fluwx-4.4.9/ios/wechat_setup.rb:71:in `block in <main>'
	from /Users/gitlab/.pub-cache/hosted/pub.dev/fluwx-4.4.9/ios/wechat_setup.rb:54:in `each'
	from /Users/gitlab/.pub-cache/hosted/pub.dev/fluwx-4.4.9/ios/wechat_setup.rb:54:in `<main>'
```

**To Reproduce**
1. pod install --repo-update

**Which version of Fluwx do you use?**
4.4.9

**Which Flutter do you use?**
3.19.0

Run `flutter doctor` and paste the output here.
✓] Flutter (Channel stable, 3.19.0, on macOS 12.6 21G115 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

**Comment by JarvanMo** [comment]
ignore_security: true # Set to true to disable security seetings.
