### ISSUE TITLE
iOS构建时包路径问题

### ISSUE THREAD

**Issue by lianjianjie** [OpenFlutter/fluwx#6]
<img width="634" alt="20180903221651" src="https://user-images.githubusercontent.com/16377699/44991753-af590680-afc7-11e8-9816-94da067b9338.png">
<img width="670" alt="20180903221720" src="https://user-images.githubusercontent.com/16377699/44991756-b122ca00-afc7-11e8-8fba-25196f392dd2.png">

- 每次`flutter packages get`后都会报这个路径问题，我都是手动把路径改好，不知道是不是个例。

**Comment by JarvanMo** [comment]
试试0.1.1

**Comment by lianjianjie** [comment]
好的。另外，分享的TimeLine和Favorite好像弄反了

**Comment by JarvanMo** [comment]
应该没有搞错啊。
