### ISSUE TITLE
iOS 分享文件使用 .share(WeChatShareFileModel(WeChatFile.network())) 

### ISSUE THREAD

**Issue by bigmendan** [OpenFlutter/fluwx#601]
```
 Fluwx()
        .share(
      WeChatShareFileModel(
        WeChatFile.network(
          'http://************.pdf',
          suffix: '.pdf',
        ),
        title: 'xx.pdf',
      ),
    ).then((value) {
      Navigator.of(context).pop();
    });
```

android 可以分享文件
iOS 输出错误日志
`
FluwxLog: [AppCommunicateData.m]-[AppCommunicateData MakeLinkObject:]WXLog:Error:object lose some param
FluwxLog: [AppCommunicateData.m]-[AppCommunicateData MakeMediaMessage:]WXLog:Error:make link object fail
FluwxLog: [AppCommunicateData.m]-[AppCommunicateData ReqToData:withMediaInternalMessage:]WXLog:Error:covert req to data fail
 FluwxLog: [WXApi.m]+[WXApi sendReq:isAutoResend:forceScheme:completion:]WXLog:Error:send req fail, fill appdata fail!
`
而尝试分享其他类型 ，如 Text , WebPage 都是可以的

**Comment by JarvanMo** [comment]
这个不好弄，我没ios app环境测试

**Comment by bigmendan** [comment]
感谢回复，我换了一种方式，iOS端我先下载本地，然后分享本地文件的方式成功。

**Comment by JarvanMo** [comment]
> 感谢回复，我换了一种方式，iOS端我先下载本地，然后分享本地文件的方式成功。

感谢，iOS我确实不是很熟悉，
