### ISSUE TITLE
关于 iOS 隐私清单的问题

### ISSUE THREAD

**Issue by naivetoby** [OpenFlutter/fluwx#603]
腾讯最新的 SDK 已经发布，包含了隐私清单

2.0.4

- 增加privacy manifest文件
- 修复跳微信可能卡顿的问题

https://developers.weixin.qq.com/doc/oplatform/Downloads/iOS_Resource.html

但是，CocoaPods 他们只发布了 `直接提供.a静态库文件的形式` 的版本
https://github.com/CocoaPods/Specs/blob/master/Specs/f/f/3/WechatOpenSDK

`XCFramework的形式` 的版本他们应该是忘记更新了！！！
https://github.com/CocoaPods/Specs/tree/dbc8d545ea79fb87cbf4ff67ae9d68f880c7668a/Specs/9/7/f/WechatOpenSDK-XCFramework

你可以去催催他们么？

对了，记得更新依赖。

**Comment by JarvanMo** [comment]
等我看看。这个我催不了啊，只能发邮件问问。他们的尿性就这样，总漏更。以前我都是自己发pod ，但是自从被说了就不用了

**Comment by naivetoby** [comment]
'WechatOpenSDK-XCFramework','~> 2.0.4' 这个是正常的

目前是 nopay 的版本可能需要自己发，或者手动集成

**Comment by JarvanMo** [comment]
感谢

**Comment by naivetoby** [comment]
我只是写了一个 DEMO 供参考，请谨慎合并

**Comment by JarvanMo** [comment]
想起来了，nopay 的pod他们一直就没有，现在用的应该是我自己发布的，等我回家看看

**Comment by naivetoby** [comment]
好像正常了，我只是手动集成了官方的 2.0.4 版本，并且拷贝他们的隐私配置到插件的隐私配置中，目前测试正常

**Comment by JarvanMo** [comment]
try with `4.5.2`.

**Comment by naivetoby** [comment]
ios/Resources/PrivacyInfo.xcprivacy  这个文件呢？是不是也要改一下？

**Comment by JarvanMo** [comment]
> ios/Resources/PrivacyInfo.xcprivacy 这个文件呢？是不是也要改一下？

不知道啊，iOS我不是很了解

**Comment by naivetoby** [comment]
先观察吧，哈哈哈
