### ISSUE TITLE
The pod "WechatOpenSDK-XCFramework" required by the plugin "fluwx" requires a higher minimum iOS deployment version than the plugin's reported minimum version.

### ISSUE THREAD

**Issue by SheepYang1993** [OpenFlutter/fluwx#607]
Error: The pod "WechatOpenSDK-XCFramework" required by the plugin "fluwx" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "fluwx", or contact the plugin's developers for assistance.
Error: Error running pod install

**Comment by JarvanMo** [comment]
> Error: The pod "WechatOpenSDK-XCFramework" required by the plugin "fluwx" requires a higher minimum iOS deployment version than the plugin's reported minimum version. To build, remove the plugin "fluwx", or contact the plugin's developers for assistance. Error: Error running pod install

https://m.youdao.com/translate

**Comment by yaolu0311** [comment]
+1

**Comment by SheepYang1993** [comment]
> +1

别+1了，作者让自己去翻译翻译 ...

**Comment by MrQiYin** [comment]
我遇到的问题是pod中存在WechatOpenSDK-XCFramework的缓存2.0.2版本，实际上fluwx需要的是2.0.4版本，但是它的报错却是“requires a higher minimum iOS deployment version”，所以我删除了Pod.lock以及Pod文件夹，执行了"pod cache clean --all"命令清除了所有的缓存，再次编译后，成功了。
