### ISSUE TITLE
iOS端配置无支付版本问题

### ISSUE THREAD

**Issue by devbravesy** [OpenFlutter/fluwx#608]
yaml的配置入下：
fluwx: 
    app_id: '123456'
    debug_logging: true # Logging in debug mode.
    android:
    ios:
      universal_link: ​https://testdomain.com/
      no_pay: false # Set to false to disable payment.
flutter pub get拉取依赖报错，请问是格式对齐问题吗，我试着对齐上面的依赖没有办法解决Error on line 190, column 5 of pubspec.yaml: A dependency may only have one source.
    ╷
190 │ ┌     app_id: '123456'
191 │ │     debug_logging: true # Logging in debug mode.
192 │ │     android:
193 │ │     ios:
194 │ │       universal_link: https://testdomain.com/
195 │ │       no_pay: false # Set to false to disable payment.

**Comment by JarvanMo** [comment]
不行就直接复制demo里的配置

**Comment by pickView** [comment]
我也遇到了该问题
