### ISSUE TITLE
Invalid `fluwx.podspec` file:

### ISSUE THREAD

**Issue by moonljt521** [OpenFlutter/fluwx#612]
我使用的是 4.2.5 版本，仍然这个错误：
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.88.0)
[✓] Connected device (3 available)
! Device adb-f9ebb660-9IA8Vr._adb-tls-connect._tcp. is offline.
[✓] Network resources

报错：
Analyzing dependencies
5.0.1
[!] Failed to load 'fluwx' podspec:
[!] Invalid fluwx.podspec file: No such file or directory @ rb_sysopen - /Users/moon/Documents/joinu/flutter_mixed/flutter_mixed/.ios/.symlinks/plugins/fluwx/ios/pubspec.yaml.

from /Users/moon/Documents/joinu/flutter_mixed/flutter_mixed/.ios/.symlinks/plugins/fluwx/ios/fluwx.podspec:22
-------------------------------------------
if psych_version_gte_500 == true
 cfg = YAML.load_file(File.join(flutter_project_dir, 'pubspec.yaml'), aliases: true)
else
-------------------------------------------

**Comment by JarvanMo** [comment]
你的项目肯定不是一个常规flutter项目

**Comment by moonljt521** [comment]
是Flutter module

**Comment by JarvanMo** [comment]
那你自己魔改一下，把自动化配置相关的代码删除了
