### ISSUE TITLE
PlatformException(Unassigned WxApi, please config wxapi first, null, null)

### ISSUE THREAD

**Issue by knight0zh** [OpenFlutter/fluwx#615]
无论是调用微信支付还是微信登录都报错，之前调通了今天突然就不想了。

Unhandled Exception: PlatformException(Unassigned WxApi, please config wxapi first, null, null)

**Comment by dingdangdog** [comment]
怎么解决的呀大佬

**Comment by dingdangdog** [comment]
![Image](https://github.com/user-attachments/assets/459b2eea-75dd-45c7-a551-6e934227698b)

我的问题解决了， `isWeChatInstalled` 调整到 `registerApi` 之后调用就可以了。😅
