### ISSUE TITLE
拉起微信客服功能

### ISSUE THREAD

**Issue by ZoeyGit** [OpenFlutter/fluwx#616]
想问下 version 4.5.5 版本  拉起微信客服会话的功能是取消了吗?

**Comment by JarvanMo** [comment]
没有，具体看example

**Comment by ZoeyGit** [comment]
看了一下 是订阅消息这个方法吗？

**Comment by ZoeyGit** [comment]
fluwx.open(target:CustomerServiceChat(corpId: "", url: "url"));  找到了
