### ISSUE TITLE
/ios/wechat_setup.rb 文件可能没执行或里面部分内容可能没走到，导致 CFBundleURLTypes 未自动写入

### ISSUE THREAD

**Issue by kawayiLinLin** [OpenFlutter/fluwx#617]
+ fluwx 版本4.5.5
+ flutter 3.19.0

执行命令 flutter build ipa --verbose

图里这个 print 没打印的样子
没有手动配 CFBundleURLTypes 参数，理论上应该走进去
<img width="683" alt="image" src="https://github.com/OpenFlutter/fluwx/assets/52342691/5aa86fa4-f38e-4863-8263-3b46e45f3bd6">
看起来这个脚本 /ios/wechat_setup.rb 是用来自动配置参数的

最后生成的 ipa 文件里的 info.plist 也没有 CFBundleURLTypes 这一项

我应该如何排查？

**Comment by JarvanMo** [comment]
如果脚步对你来说不好用，那就手动填吧。一样的

**Comment by JarvanMo** [comment]
还有应该先pod install

**Comment by kawayiLinLin** [comment]
> 还有应该先pod install

好的，我知道了，没有正常走 pod install 就不会触发这个脚本，谢谢~
