### ISSUE TITLE
incompatible with app_links package

### ISSUE THREAD

**Issue by qijia2045579** [OpenFlutter/fluwx#618]
**Describe the bug**
if [app_links](https://pub.dev/packages/app_links) package is installed, this fluwx will not work

**To Reproduce**
just put this package to the pubspec.yaml will cause the response won't be listen, not sure why.

**Which version of Fluwx do you use?**
4.5.2

**Which device do you run on**
Iphone 10

**Which Flutter do you use?**

[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3.1 23D60 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by JarvanMo** [comment]
It's not bug of fluwx but app_link consumes links that fluwx need.
