### ISSUE TITLE
微信分享拉起微信特别慢，有时候能等20秒才能拉起微信

### ISSUE THREAD

**Issue by shichunlei** [OpenFlutter/fluwx#620]
fluwx: ^4.5.5

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)

**Comment by JarvanMo** [comment]
自己把图片处理一下。
