### ISSUE TITLE
android.net.ssl.SSLSockets

### ISSUE THREAD

**Issue by glj0209** [OpenFlutter/fluwx#625]
**Describe the bug**
当执行
WeChatShareMiniProgramModel(
      webPageUrl: webPageUrl,
      userName: username ?? kMiniAppId,
      miniProgramType: miniProgramType,
      title: title,
      path: path,
      description: description ,
      thumbnail: WeChatImage.network(imgUrl),
    )
在 安卓如下设备会出现闪退
JAD-AL00
NCO-AL00
NAM-AL00
NTH-AN00
TFY-AN00
**To Reproduce**
分享小程序卡片

android.net.ssl.SSLSockets 位置 <clinit> 行 2
系统
android.net.ssl.SSLSockets 位置 isSupportedSocket
系统
va.a 位置 a 行 6
系统
ua.b 位置 e 行 30
系统
pa.f 位置 i 行 72
系统
pa.f 位置 m 行 53
系统
pa.f 位置 f 行 197
系统
pa.d 位置 b 行 284
系统
pa.d 位置 c 行 1
系统
pa.d 位置 a 行 48
系统
pa.e 位置 q 行 34
系统
pa.a 位置 intercept 行 12
系统
qa.g 位置 proceed 行 167
系统
na.a 位置 intercept 行 194
系统
qa.g 位置 proceed 行 167
系统
qa.a 位置 intercept 行 168
系统
qa.g 位置 proceed 行 167
系统
qa.j 位置 intercept 行 35
系统
qa.g 位置 proceed 行 167
系统
pa.e 位置 p 行 114
系统
pa.e 位置 execute 行 28
系统
com.kwad.sdk.core.network.a.c 位置 doPost 行 7
系统
com.kwad.sdk.core.network.c.b 位置 doPost 行 1
系统
com.

**Which version of Fluwx do you use?**
fluwx_no_pay 2.2.0

**Which device do you run on**
HUAWEI and the OS is Android 11
![WechatIMG325](https://github.com/OpenFlutter/fluwx/assets/8816552/17ad6a05-7cfd-4712-b8a5-841c2e27952a)

**Which Flutter do you use?**
[!] Flutter (Channel [user-branch], 3.13.10-0.0.pre.1, on macOS 14.4.1 23E224 darwin-arm64
    (Rosetta), locale zh-Hans-CN)
    ! Flutter version 3.13.10-0.0.pre.1 on channel [user-branch] at /Users/gaolijun/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository git@codeup.aliyun.com:5ee5b627f0e06f96cfd22d38/app/flutter.git is not a
      standard remote.
      Set environment variable "FLUTTER_GIT_URL" to
      git@codeup.aliyun.com:5ee5b627f0e06f96cfd22d38/app/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[✓] VS Code (version 1.90.0)
[✓] Connected device (3 available)

**Comment by JarvanMo** [comment]
图片得https
