### ISSUE TITLE
分享不同webPage到朋友圈，url和标题还有缩略图都不会跟着变，像是固定了一样，ios正常

### ISSUE THREAD

**Issue by wcedla** [OpenFlutter/fluwx#631]
如题，android分享不同网页到朋友圈，但是朋友圈显示的链接和标题都是同一个，不会变化，分享到好友是正常变化的，ios分享好友和朋友圈都会变化，debug调试android代码也发现传参没问题，但是就是不会变化，有没有人遇到同样问题的，求解决方案

**Comment by JarvanMo** [comment]
Fixed in 5.0

**Comment by wangwei2-ola** [comment]
遇到了同样的问题，还在分析中

**Comment by wcedla** [comment]
找到问题了，url要加随机数www.baidu.com?s=随机数这样子
