### ISSUE TITLE
Example 无法吊起微信支付，其余功能正常

### ISSUE THREAD

**Issue by HannibalKcc** [OpenFlutter/fluwx#64]
手机型号 huawei hry-al100a

在example应用中吊起支付会闪黑屏，然后响应结果-1

**Comment by JarvanMo** [comment]
支付demo仅供参考。支付用的是SDK的demo。

**Comment by JarvanMo** [comment]
而且不要更改demo里的任何配置项

**Comment by HannibalKcc** [comment]
感谢及时的回复

> 而且不要更改demo里的任何配置项

呃，那我在自己的项目中慢慢测吧

**Comment by JarvanMo** [comment]
支付的参数以及加密是极其严格的。建议仔细阅读微信支付官网文档。
