### ISSUE TITLE
ShareSDK(分享插件)和Fluwx(微信支付插件)存在冲突解决办法失效

### ISSUE THREAD

**Issue by lin-11111** [OpenFlutter/fluwx#640]
我按照文档中的思路找到了Fluwx中的libWeChatSDK.a，但没有找到，我删除了WechatOpenSDK-XCFramework文件夹，编译出现了问题。
Running Xcode build...                                          
Xcode build done.                                           21.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/f_/vf8f7rhs71l80bv1gzl81lrh0000gr/T/flutter_tools.XqlPGH/flutter_ios_build_temp_dirqxQmGF/temporary_xcresult_bundle

    Selected xcframework slice ios-arm64_armv7
    rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" "/Users/cha/Desktop/vih/ios/Pods/WechatOpenSDK-XCFramework/WechatOpenSDK-XCFramework.xcframework/ios-arm64_armv7/*" "/Users/cha/Desktop/vih/build/ios/Release-iphoneos/XCFrameworkIntermediates/WechatOpenSDK-XCFramework"
    building file list ... rsync: link_stat "/Users/cha/Desktop/vih/ios/Pods/WechatOpenSDK-XCFramework/WechatOpenSDK-XCFramework.xcframework/ios-arm64_armv7//*" failed: No such file or directory (2)
    done

    sent 29 bytes  received 20 bytes  98.00 bytes/sec
    total size is 0  speedup is 0.00
    rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/bc10cbcd-3cda-11ee-b8ac-16228a05f5d2/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /AppleInternal/Library/BuildRoots/bc10cbcd-3cda-11ee-b8ac-16228a05f5d2/Library/Caches/com.apple.xbs/Sources/rsync/rsync/rsync.c(244) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/f_/vf8f7rhs71l80bv1gzl81lrh0000gr/T/flutter_tools.XqlPGH/flutter_ios_build_temp_dirqxQmGF/temporary_xcresult_bundle

Encountered error while building for device.
Process finished with exit code 1

**Comment by JarvanMo** [comment]
问问身边懂iOS的吧
