### ISSUE TITLE
fluwx 5.0.0版本，在ios下，WeChatImageToShare 的 assert 会触发 Platform.isAndroid 必定报错的问题

### ISSUE THREAD

**Issue by wenboLee** [OpenFlutter/fluwx#642]
**Describe the bug**

**To Reproduce**
示例代码
```
final source = WeChatImageToShare(imgBytes, null, null);
posterImgBytes = null;
fluwx.share(WeChatShareImageModel(source));
```

** 异常错误信息 **
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:fluwx/src/foundation/share_models.dart': Failed assertion: line 343 pos 16: 'Platform.isAndroid &&
            (uint8List != null || localImagePath != null)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new WeChatImageToShare (package:fluwx/src/foundation/share_models.dart:343:16)
```

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.

**Which device do you run on**
iOS 18.0.1, iphone 13

**Which Flutter do you use?**
flutter 3.24.3

Run `flutter doctor` and paste the output here.

**Comment by wenboLee** [comment]
![image](https://github.com/user-attachments/assets/b00093ff-4edf-4458-ba4f-b23874f5b670)
我的设备是 iOS，也会走这个 assert 断言，就直接报错了

**Comment by wenboLee** [comment]
坏了，还有别的问题。
修改源码，移除上面 assert 后，oc原生会报错。

错误日志：
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull data]: unrecognized selector sent to instance 0x1f577b748'
*** First throw call stack:
(0x1907fd08c 0x18daff2e4 0x1909037c8 0x19079a888 0x19079a1b0 0x10a7b898c 0x105a78a30 0x105a7a71c 0x105a8ade8 0x105a8a9a4 0x1907cff64 0x1907cd188 0x1907cc5b8 0x1dc2621c4 0x1933222c0 0x1933d0ddc 0x1936fdb20 0x109d1e4b4 0x109d1e42c 0x109d1e530 0x1b5fa0d34)
libc++abi: terminating due to uncaught exception of type NSException

oc的水平有限没看懂，麻烦大佬也看看 :(

![image](https://github.com/user-attachments/assets/e4589c2d-f1b9-4b00-a104-f18051d73989)

**Comment by JarvanMo** [comment]
544行报错？等我回去看看能不能测试，我现在没有可用app

**Comment by wenboLee** [comment]
不确定，但范围应该是 dispatch_async 代码块~

![image](https://github.com/user-attachments/assets/12cbc20a-b180-4803-b87c-c95c64e7dd1a)
