### ISSUE TITLE
paymentController没有释放

### ISSUE THREAD

**Issue by rockingdice** [OpenFlutter/fluwx#65]
lib/src/fluwx_iml.dart 

![image](https://user-images.githubusercontent.com/3458134/58366496-b59c6380-7f05-11e9-9f55-0895ce0e3925.png)

  if (authResponse) {
    _responseAuthController.close();
  }
  if (launchMiniProgramResponse) {
    _responseLaunchMiniProgramController.close();
  }

  if (paymentResponse) {
    _responseAuthController.close();     /////这里应该是_responsePaymentController
  }

**Comment by JarvanMo** [comment]
可以直接发起PR来修复这个问题。
