### ISSUE TITLE
新版没法分享图片，分享链接的图片也是

### ISSUE THREAD

**Issue by douweier** [OpenFlutter/fluwx#650]
fluwx: ^4.5.6版本及之前采用的是thumbnail，WeChatImage.network(imageUrl)就能分享链接显示图片，

但是[4.6.0]版本后改成了Uint8List? thumbData，传入Uint8List格式图片后直接报错了checkArgs fail, thumbData is invalid，

看了其它人最近提到的issues都遇到了分享图片直接导致崩溃，应该就是这个问题导致的，请修复，辛苦了

**Comment by JarvanMo** [comment]
> fluwx: ^4.5.6版本及之前采用的是thumbnail，WeChatImage.network(imageUrl)就能分享链接显示图片，
> 
> 但是[4.6.0]版本后改成了Uint8List? thumbData，传入Uint8List格式图片后直接报错了checkArgs fail, thumbData is invalid，
> 
> 看了其它人最近提到的issues都遇到了分享图片直接导致崩溃，应该就是这个问题导致的，请修复，辛苦了

新版本要和native SDK对齐，不再额外对图片进行操作，原因在于很多时候fluwx 的压缩很不理想，而且gif有时候会变成静态图片

**Comment by mqguoliang** [comment]
这个thumbData值该如何传呢？
我进行了图片压缩以及分辨率调整到100以下都不显示
还有thumbDataHash这个值是必须要传的吗？
有没有示例帮助一下，之前用的好好的，现在分享视频时缩略图都是黑的

**Comment by AlexV525** [comment]
4.6.1 修复了使用 thumbnail 的问题，可以继续使用该字段。

**Comment by xuelangjie** [comment]
有解决吗？ 我用最新的 5.5.2版本还是这个错误，有demo吗
