### ISSUE TITLE
分享图片大小最多支持多少k，分享图片失败

### ISSUE THREAD

**Issue by winter-tech** [OpenFlutter/fluwx#652]
fluwx.share(WeChatShareImageModel(WeChatImageToShare(uint8List: data)));

、、、
I/MicroMsg.SDK.MMessageAct(18483): send, targetPkgName = com.tencent.mm, targetClassName = com.tencent.mm.plugin.base.stub.WXEntryActivity, launchMode = 2
I/MicroMsg.SDK.MMessageAct(18483): sendUsingPendingIntent
E/JavaBinder(18483): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1241592)
E/MicroMsg.SDK.MMessageAct(18483): sendUsingPendingIntent fail, ex = android.os.TransactionTooLargeException: data parcel size 1241592 bytes
E/JavaBinder(18483): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1241620)
E/MicroMsg.SDK.MMessageAct(18483): send fail, ex = java.lang.RuntimeException: Failure from system
E/MicroMsg.SDK.MMessageAct(18483): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1749)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1095)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1066)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:421)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.tencent.mm.opensdk.channel.MMessageActV2.sendUsingPendingIntent(Unknown Source:69)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.tencent.mm.opensdk.channel.MMessageActV2.send(Unknown Source:213)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.tencent.mm.opensdk.openapi.BaseWXApiImplV10.doLaunchApp(Unknown Source:81)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.tencent.mm.opensdk.openapi.BaseWXApiImplV10.sendReq(Unknown Source:790)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.tencent.mm.opensdk.openapi.BaseWXApiImplV10.sendReq(Unknown Source:1)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$sendRequestInMain$2.invokeSuspend(FluwxShareHandler.kt:268)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$sendRequestInMain$2.invoke(Unknown Source:8)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$sendRequestInMain$2.invoke(Unknown Source:4)
E/MicroMsg.SDK.MMessageAct(18483): 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
E/MicroMsg.SDK.MMessageAct(18483): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
E/MicroMsg.SDK.MMessageAct(18483): 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$DefaultImpls.sendRequestInMain(FluwxShareHandler.kt:267)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$DefaultImpls.access$sendRequestInMain(FluwxShareHandler.kt:45)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$shareImage$1.invokeSuspend(FluwxShareHandler.kt:159)
E/MicroMsg.SDK.MMessageAct(18483): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/MicroMsg.SDK.MMessageAct(18483): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.os.Looper.loop(Looper.java:299)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.app.ActivityThread.main(ActivityThread.java:8292)
E/MicroMsg.SDK.MMessageAct(18483): 	at java.lang.reflect.Method.invoke(Native Method)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MicroMsg.SDK.MMessageAct(18483): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/MicroMsg.SDK.MMessageAct(18483): Caused by: android.os.TransactionTooLargeException: data parcel size 1241620 bytes
E/MicroMsg.SDK.MMessageAct(18483): 	at android.os.BinderProxy.transactNative(Native Method)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.os.BinderProxy.transact(BinderProxy.java:624)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2664)
E/MicroMsg.SDK.MMessageAct(18483): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
、、、

**Comment by winter-tech** [comment]
安卓限制1m，得用本地图片的方式，参数要和iOS分开

**Comment by JarvanMo** [comment]
> 安卓限制1m，得用本地图片的方式，参数要和iOS分开

emm 提醒我了，可以优化一下Android逻辑，Android应该默认优先使用locale，而不是使用uint8

**Comment by LiWenHui96** [comment]
> 安卓限制1m，得用本地图片的方式，参数要和iOS分开

字段 | 类型 | 含义 | 备注
-- | -- | -- | --
imageData | byte[] | 图片的二进制数据 | 内容大小不超过 1MB
imagePath | String | 图片的本地路径 | 对应图片内容大小不超过 25MB

(⊙o⊙)…如果使用`localImagePath`字段，我想他的上限可能是25MB...
