### ISSUE TITLE
鸿蒙官网提供的flutter还是3.7的，无法安装当前5.1.0，怎么破

### ISSUE THREAD

**Issue by gzyunke** [OpenFlutter/fluwx#653]
鸿蒙官网提供的flutter还是3.7的，无法安装当前5.1.0，怎么破，因为依赖版本不一样

**Comment by JarvanMo** [comment]
不有flutter 3.22么？不过你可以使用https://github.com/yeliulee/fluwx/tree/ohos-3.7.12 作为替代

**Comment by gzyunke** [comment]
> 不有flutter 3.22么？不过你可以使用https://github.com/yeliulee/fluwx/tree/ohos-3.7.12 作为替代

华为提供的flutter只有3.7，没有3.22版本，或者是我漏了？

感谢提供的链接，我试下
