### ISSUE TITLE
关于新版本5.2.2中iOS分享视频不能显示缩略图问题

### ISSUE THREAD

**Issue by mqguoliang** [OpenFlutter/fluwx#661]
经我们多次测试，iOS中视频分享缩略图不能正常显示但Android版本是可以的。
经查代码是FluwxPlugin.m中sendVideoURL代码使用问题，我们不理解为什么唯独视频分享使用这样的代码
[message setThumbImage:thumbImage];
而其他分享模式，如网页分享的缩略图，则是这样的ThumbData: thumbData，
所以我们尝试改一下视频分享的iOS代码
改为message.ThumbData = thumbData;
这样就可以正常分享了。
我之前在#650中提出这个问题，管理员可能理解错了，故关闭了问题。

**Comment by JarvanMo** [comment]
可以提交pr么？谢谢。我测试不了这样的问题

**Comment by AlexV525** [comment]
提供一下你的调用代码，thumbnail 参数是不是传了内容

**Comment by mqguoliang** [comment]
> 提供一下你的调用代码，缩略图参数不是传递了内容

现在的只能传thumbData这个参数吧？你可以试一下WeChatShareVideoModel中的thumbData能不能正常显示，在iOS端。
这个thumbnail参数在哪？是旧版本参数吧，在5.2.2中能调用？

**Comment by AlexV525** [comment]
> 现在的只能传thumbData这个参数吧？你可以试一下WeChatShareVideoModel中的thumbData能不能正常显示，在iOS端。 这个thumbnail参数在哪？是旧版本参数吧，在5.2.2中能调用？

看了下最新的代码，确实有几处没有正确设置 thumbdata

**Comment by mqguoliang** [comment]
> > 现在的只能传thumbData这个参数吧？你可以试一下WeChatShareVideoModel中的thumbData不能正常显示，在iOS端。这个thumbnail参数在哪？是旧版本参数吧，在5.2.2中可以调用？
> 
> 查看了下最新的代码，确实有几处没有正确设置拇指数据

感谢处理，希望尽快更新新版本

**Comment by AlexV525** [comment]
@mqguoliang 可以测试下 #662 是否解决了问题？

**Comment by mqguoliang** [comment]
> @mqguoliang 可以测试下 #662 是否解决了问题？

测了下，正常了
