### ISSUE TITLE
demo  无法传大图分享

### ISSUE THREAD

**Issue by ismanong** [OpenFlutter/fluwx#67]
String _imagePath =
      "https://panda-test-img.oss-cn-shanghai.aliyuncs.com/share_invite_code/share_invite_code_1559251765957.png";

会报 send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras) }

demo自己也会报ignore wechat app signature validation
请跑一下验证一下， 谢谢，不知道哪里出问题了

**Comment by JarvanMo** [comment]
微信SDK的确对分享图片的大小有限制。但你这个图片没有超出限制。ignore wechat app signature validation 这个问题有问过了，翻issue吧。

**Comment by JarvanMo** [comment]
ignore wechat app signature validation 是app签名验证出了问题。

**Comment by TigerLau** [comment]
![image](https://user-images.githubusercontent.com/8511596/60559299-9a333c80-9d7e-11e9-87e4-200b9163fb2a.png)
分享大图，失败；分享小图，成功。

**Comment by JarvanMo** [comment]
@tenfar 分享的图片需要自己压缩

**Comment by JarvanMo** [comment]
@TigerLau 分享的图片需要你自己去压缩

**Comment by TigerLau** [comment]
微信的分享API中，关于图片分享大小限制为10M；但是，我操作分享的图片资源，也就600K~700K。

**Comment by JarvanMo** [comment]
@TigerLau @ismanong 我知道怎么回事了。我稍后修复。

**Comment by JarvanMo** [comment]
@TigerLau @ismanong 我升级了一下，现在可以分享超过５１２Ｋ的图片了，其中的注意事项请参阅readme。

**Comment by ismanong** [comment]
谢谢

**Comment by TigerLau** [comment]
Nick work! @JarvanMo

**Comment by solody** [comment]
flutter_image_compress 用这个
