### ISSUE TITLE
iphone15  ios:17.5.1系统，分享好友，及朋友圈，能拉起微信，进入微信页面之后，无法选择好友

### ISSUE THREAD

**Issue by 1129798217** [OpenFlutter/fluwx#675]
**Describe the bug**
分享好友，及朋友圈，能拉起微信，进行微信页面之后，无法选择好友，也无法分享朋友圈，
微信登录也不可以。
使用的是fluwx 5.3.1 切换到4.5.0也不行。
但是iphone12  ios:17.5.1系统是可以的。

**Which device do you run on**
iphone15  ios:17.5.1系统 xcode 15.1

**Which Flutter do you use?**
Flutter (Channel stable, 3.24.3,
flutter: FluwxLog: [WeChatIdentityHandler.mm]+[WeChatIdentityHandler loadTokenFromKeychain]WXLog:Error:fail to load Keychain status:-25300, keyData null:1
flutter: FluwxLog: [WeChatIdentityHandler.mm]+[WeChatIdentityHandler loadTokenFromKeychain]WXLog:token[(null)] is null
flutter: FluwxLog: [WXApi.m]+[WXApi launchApplicationWithUrl:completion:]_block_invokeWXLog:launch app with ul only success

**Comment by lonely-clownn** [comment]
请问有没有遇到这个问题：Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Module 'fluwx' has no member named 'registerWXApi'
/Users/admin/Documents/project/watermark-clouds-flutter-master/ios/Runner/AppDelegate.swift:12:8

Swift Compiler Error (Xcode): Module 'fluwx' has no member named 'handleOpenURL'
/Users/admin/Documents/project/watermark-clouds-flutter-master/ios/Runner/AppDelegate.swift:16:13

**Comment by 1129798217** [comment]
> 请问有没有遇到这个问题：Could not build the precompiled application for the device. Swift Compiler Error (Xcode): Module 'fluwx' has no member named 'registerWXApi' /Users/admin/Documents/project/watermark-clouds-flutter-master/ios/Runner/AppDelegate.swift:12:8
> 
> Swift Compiler Error (Xcode): Module 'fluwx' has no member named 'handleOpenURL' /Users/admin/Documents/project/watermark-clouds-flutter-master/ios/Runner/AppDelegate.swift:16:13

我之前也是想在这个文件里面改的，没有改好。最后放弃了在AppDelegate.swift里面修改。

**Comment by 1129798217** [comment]
> **Describe the bug** 分享好友，及朋友圈，能拉起微信，进行微信页面之后，无法选择好友，也无法分享朋友圈， 微信登录也不可以。 使用的是fluwx 5.3.1 切换到4.5.0也不行。 但是iphone12 ios:17.5.1系统是可以的。
> 
> **Which device do you run on** iphone15 ios:17.5.1系统 xcode 15.1
> 
> **Which Flutter do you use?** Flutter (Channel stable, 3.24.3, flutter: FluwxLog: [WeChatIdentityHandler.mm]+[WeChatIdentityHandler loadTokenFromKeychain]WXLog:Error:fail to load Keychain status:-25300, keyData null:1 flutter: FluwxLog: [WeChatIdentityHandler.mm]+[WeChatIdentityHandler loadTokenFromKeychain]WXLog:token[(null)] is null flutter: FluwxLog: [WXApi.m]+[WXApi launchApplicationWithUrl:completion:]_block_invokeWXLog:launch app with ul only success

这个问题解决了，因为fluwx的单例实现在不同机器上可能不同，我把fluwx全局共有一个实例，解决了。之前是创建了多个对象。不过还是有一点奇怪，之前的多个对象在大部分机器上都是正常的。只有iphone15遇到了问题。

**Comment by 1129798217** [comment]
解决了，全局共用一个fluwx对象就可以了。
