### ISSUE TITLE
flutter进行鸿蒙软件开发，引用 fluwx因为dart版本问题报错

### ISSUE THREAD

**Issue by hczhhm** [OpenFlutter/fluwx#676]
使用flutter进行鸿蒙软件开发，引用 fluwx因为dart版本问题报错，fluwx支持的dart版本是3.0，鸿蒙的flutter_flutter中的dart版本是2.19.6，请问怎么处理这个问题呀，谢谢。

<img width="969" alt="截屏2024-12-02 10 23 20" src="https://github.com/user-attachments/assets/6debb8c6-a8f9-4ee3-b407-b29d39bb1765">

<img width="746" alt="截屏2024-12-02 10 16 27" src="https://github.com/user-attachments/assets/a04b7c8a-93ef-4c0a-9d84-edc0e792d3db">

**Comment by JarvanMo** [comment]
1. 升级flutter 
2. 搜搜看看有没有人问过这个问题

**Comment by hczhhm** [comment]
> 1. 升级flutter
因为鸿蒙所用的flutter是自己维护的，官方的flutter不支持鸿蒙，所以无法通过升级到官方的flutetr解决这个问题，我看到你们维护的[tobias](https://github.com/OpenFlutter/tobias) 支持的dart版本是	2.12 ，是可以支持鸿蒙的，所以是不是fluwx也可以参照一下tobias。
> 2. 搜搜看看有没有人问过这个问题
目前搜鸿蒙和ohos没有找到对应的问题。

**Comment by JarvanMo** [comment]
> > 1. 升级flutter
> >    因为鸿蒙所用的flutter是自己维护的，官方的flutter不支持鸿蒙，所以无法通过升级到官方的flutetr解决这个问题，我看到你们维护的[tobias](https://github.com/OpenFlutter/tobias) 支持的dart版本是	2.12 ，是可以支持鸿蒙的，所以是不是fluwx也可以参照一下tobias。
> > 2. 搜搜看看有没有人问过这个问题
> >    目前搜鸿蒙和ohos没有找到对应的问题。

1. 鸿蒙是有更高版本的flutter 
2. 为什么不搜搜fluwx 的issues

**Comment by supergraceful** [comment]
https://gitee.com/harmonycommando_flutter/flutter 这个版本的可以用
