### ISSUE TITLE
在进行微信支付时，支付页面闪退了一下，debug签名配置以及appid和sign都是正确的。想知道这个是什么原因。

### ISSUE THREAD

**Issue by SunLongbri** [OpenFlutter/fluwx#69]
debug和release的签名配置是这样的
//-------------------------------------------------
    signingConfigs{

        debug{
            storeFile file("copystation.jks")
            storePassword "sun@17839192937"
            keyAlias "copystation"
            keyPassword "sun@17839192937"
        }

        release{
            storeFile file("copystation.jks")
            storePassword "sun@17839192937"
            keyAlias "copystation"
            keyPassword "sun@17839192937"
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
//--------------------------------------------------------------------
方法的调用是这样的
//-------------------------------------
  _pay(_url) async {
    var result = await postHttp(_url);
    print('返回来的结果为:${result}');
    print(result['appid']);
    print(result["timestamp"]);
    fluwx
        .pay(
      appId: result['appid'].toString(),
      partnerId: result['partnerid'].toString(),
      prepayId: result['prepayid'].toString(),
      packageValue: result['package'].toString(),
      nonceStr: result['noncestr'].toString(),
      timeStamp: result['timestamp'],
      sign: result['sign'].toString(),
    )
        .then((data) {
      print("---》$data");
    });
  }
//------------------------------------------------------
服务端的数据是这样的：
//----------------------------------
{
  "appid": "wx8eaa46b891bb15c5",
  "partnerid": "1900000109",
  "package": "Sign=WXPay",
  "noncestr": "95d42e9ae772918b45e1d5e105babd9f",
  "timestamp": 1398746574,
  "prepayid": "1101000000140415649af9fc314aa427",
  "sign": "a437fe49f4bffd60502c097f7e243258",
  "nonceStr": "1101000000140429eb40476f8896f4c9"
}
//---------------------------------------------------

我想知道，是我使用的方法不太对吗？希望作者大神能告知一下。

**Comment by SunLongbri** [comment]
buildTypes是这样写的，依然有问题：
    buildTypes {

        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }

        debug {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

**Comment by SunLongbri** [comment]
我看有log信息输入好像是这这样的：
V/InputMethodManager(31292): Reporting focus gain, without startInput
D/ActivityThread(31292): Remove activity client record, r= ActivityRecord{c2386e5 token=android.os.BinderProxy@4922cae {com.heaven.copy_station/com.heaven.copy_sta
tion.wxapi.WXPayEntryActivity}} token= android.os.BinderProxy@4922cae

**Comment by SunLongbri** [comment]
监听回调的信息如下：
 data.extData : null data.errCode : -1  data.errStr : null

**Comment by JarvanMo** [comment]
应用签名，支付签名问题。自己排查，fluwx本身肯定没问题。建议多去看看微信支付文档。这里不教你如何进行签名。

**Comment by SunLongbri** [comment]
你好，我从视频中得到app获取签名的方式是通过微信支付文档中下载的一个apk文件，然后安装到手机端，获取到的应用签名，其他配置信息是例子中默认的配置信息，我只想把微信支付的页面显示出来，希望大神能再给点提示，谢谢。

**Comment by JarvanMo** [comment]
我已经告诉你了。如果可以分享就是你的支付信息有问题，如果不可以分享就是你的apk签名有问题。再怎么问也是这个答案。麻烦多看看微信支付文档。我能告诉你的都告诉了，不行你在身边找个有经验的人帮帮你啊

**Comment by blbfxm** [comment]
我碰到同样的问题，对照微信支付文档，找到了原因，原来是我从 jks文件中拷出的md5签名中的字母是大写，文档中都是小写,而且没有冒号，实在太粗心了
[https://pay.weixin.qq.com/wiki/doc/api/img/chapter8_5_2.png](url)

**Comment by xiejibiao** [comment]
> 你好，我从视频中得到app获取签名的方式是通过微信支付文档中下载的一个apk文件，然后安装到手机端，获取到的应用签名，其他配置信息是例子中默认的配置信息，我只想把微信支付的页面显示出来，希望大神能再给点提示，谢谢。

您好，我现在也出现这个问题，请问您是怎么解决的？
