### ISSUE TITLE
请问需要改 android 包中的内容吗？

### ISSUE THREAD

**Issue by HackSoul** [OpenFlutter/fluwx#7]
大佬您好，我照着你的 example ，把 android 整个复制到我的项目里面了，但是我把 debug.keystore 改成我自己的 keystore 后就不好使了。
请问能写一下配置的过程吗。
感谢。

**Comment by JarvanMo** [comment]
这个需要原生知识。
跑example是万万不能换debug.keystore的。applicationId以`WXEntryAcitity`那个包也不能换。
要想在自己的项目上好用你得去微信开放平台申请自己的appid。
这过程需要生成签名等等。
官网说的比我详细，这里一时半会也说不清楚。

**Comment by HackSoul** [comment]
可以了，换成我自己的签名了，第一次弄微信没经验。现在这个套路了解了。感谢！！！

**Comment by JarvanMo** [comment]
Ok，解决了就行。
