### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by gaojuanjuan** [OpenFlutter/fluwx#70]
![image](https://user-images.githubusercontent.com/14133759/59172034-782c0d00-8b78-11e9-95e9-944be21fc8ca.png)
运行的时候报了这个错

**Comment by gaojuanjuan** [comment]
是关于kotlin的，我项目中没有引入kotlin，是这个原因吗？

**Comment by JarvanMo** [comment]
kotlin没下载下来

**Comment by gaojuanjuan** [comment]
要翻墙吗？

**Comment by JarvanMo** [comment]
理论上是不需要的，换个好的网络吧

**Comment by gaojuanjuan** [comment]
![image](https://user-images.githubusercontent.com/14133759/59174715-12924d80-8b85-11e9-9cca-a79fa82f6d1f.png)
我在浏览器打开了一下kotlin的其中一个下载地址，报了这个错，是网络问题是吗？

**Comment by JarvanMo** [comment]
不清楚。这个问题需要自行解决了

**Comment by gaojuanjuan** [comment]
好的，谢谢了

**Comment by gaojuanjuan** [comment]
Finished with error: Gradle task assembleDebug failed with exit code 1
运行你项目中的demo报了这个错

**Comment by JarvanMo** [comment]
我不知道发生了什么。demo运行起来肯定没问题。

**Comment by gaojuanjuan** [comment]
![image](https://user-images.githubusercontent.com/14133759/59180028-66f1f900-8b96-11e9-9b9a-f1941e4031fc.png)

你好，又出现了这个问题

**Comment by JarvanMo** [comment]
类似网络引起的环境问题不再回复。
