### ISSUE TITLE
如果和share plugin结合使用

### ISSUE THREAD

**Issue by geasyheart** [OpenFlutter/fluwx#71]
我在项目中使用了[share plugin](https://github.com/flutter/plugins/tree/master/packages/share)，我想问问这两者是否可以结合使用？
问题点：
1. 使用Share.share就可以调用系统里面的分享方式（这个对没有移动开发经验的我来讲非常友好），但是只能分享文字，所以能不能结合起来分享其他类型的内容。
2. 如果不行，问作者大大一个问题，如何调用起如问题1中系统里面的分享方式，也就是说不用自己写了（emmm，我现在可以使用showModalBottomSheet方式实现），然后再触发自己想要的动作，比如分享文字，分享其他内容等。

非常期待你的回答，谢谢！！

**Comment by JarvanMo** [comment]
这是两个完全不同的插件。

**Comment by JarvanMo** [comment]
而且我也没有用过share plugin。他们肯定是不能结合的。
