### ISSUE TITLE
更换安卓密钥后分享功能异常。

### ISSUE THREAD

**Issue by KignorChan** [OpenFlutter/fluwx#75]
大家好。我最近将安卓的密钥由debug改成release的，微信开放平台的密钥也同步更新了，但微信分享的功能就用不了。触发微信分享，能调出联系人列表，但点击其中一个联系人时没有反应。有人遇到过类似情况吗？

**Comment by KignorChan** [comment]
我懂了。我在 android/app/build.gradle 里：
android -> buildTypes -> release里用了
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

去掉这几行就好了。

**Comment by JarvanMo** [comment]
需要混淆可以自己配置
