### ISSUE TITLE
调起支付接口闪一下

### ISSUE THREAD

**Issue by xiao453177912** [OpenFlutter/fluwx#89]
D/MicroMsg.SDK.WXMsgImplComm( 2697): ignore wechat app signature validation
I/MicroMsg.SDK.WXApiImplV10( 2697): sendReq, req type = 5
D/ActivityThread( 2697): hoder:android.app.IActivityManager$ContentProviderHolder@2b44e1b5,provider,holder.Provider:android.content.ContentProviderProxy@3017704a
D/MicroMsg.SDK.WXApiImplV10( 2697): pay, set wxappPayEntryClassname = com.tencent.mm.plugin.base.stub.WXPayEntryActivity
D/MicroMsg.SDK.MMessageAct( 2697): send, targetPkgName = com.tencent.mm, targetClassName = com.tencent.mm.plugin.base.stub.WXPayEntryActivity
D/MicroMsg.SDK.MMessageAct( 2697): send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXPayEntryActivity (has extras) }
I/flutter ( 2697): {platform: android, result: true}
I/MicroMsg.SDK.WXApiImplV10( 2697): handleIntent, cmd = 5
V/PhoneWindow( 2697): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{14eff0ad com.gwbit.guweizihua/com.gwbit.guweizihua.MainActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{3ad39be7 I.E..... R....... 0,0-1080,1920}
I/flutter ( 2697): 3333333333
I/flutter ( 2697): Instance of 'WeChatPaymentResponse'
I/SurfaceView( 2697): updateWindow -- onWindowVisibilityChanged, visibility = 4, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=false, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Cur surface: Surface(name=null)/@0x2887df73, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): New surface: Surface(name=null)/@0x2de15e30, vis=false, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Callback --> surfaceDestroyed, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceDestroyed callback +, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
D/MALI    ( 2697): eglDestroyContext:559: [MALI] eglDestroyContext display 0x7f88c60080, context 0x7f7037cd10 here.
D/MALI    ( 2697): gles_context_delete:435: Destroy GLES ctx 0x7f7c104008 successfully
D/Surface ( 2697): Surface::disconnect(this=0x7f88e7bc00,api=1)
I/SurfaceView( 2697): surfaceDestroyed callback -, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
V/SurfaceView( 2697): Layout: x=0 y=0 w=1080 h=1920, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
D/OpenGLRenderer( 2697): Flushing caches (mode 0)
D/Surface ( 2697): Surface::disconnect(this=0x7f88e77600,api=1)
D/OpenGLRenderer( 2697): Flushing caches (mode 0)
V/PhoneWindow( 2697): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{14eff0ad com.gwbit.guweizihua/com.gwbit.guweizihua.MainActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{3ad39be7 V.E..... R.....ID 0,0-1080,1920}
V/InputMethodManager( 2697): onWindowFocus: io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920} softInputMode=272 first=false flags=#81810100
I/SurfaceView( 2697): updateWindow -- onWindowVisibilityChanged, visibility = 0, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=false mRequestedVisible=true, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Cur surface: Surface(name=null)/@0x2887df73, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): New surface: Surface(name=null)/@0x2de15e30, vis=true, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Callback --> surfaceCreated, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceCreated callback +, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
D/MALI    ( 2697): eglCreateContext:206: [MALI] eglCreateContext display 0x7f88c60080, share context 0x7f700f5d80 here.
D/MALI    ( 2697): gles_context_new:248: Create GLES ctx 0x7f7c104008 successfully
D/MALI    ( 2697): eglCreateContext:543: [MALI] eglCreateContext end. Created context 0x7f54bfaee8 here.
D/Surface ( 2697): Surface::connect(this=0x7f88e77600,api=1)
D/mali_winsys( 2697): new_window_surface returns 0x3000
I/SurfaceView( 2697): surfaceCreated callback -, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceChanged -- format=4 w=1080 h=1920, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceChanged callback +, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceChanged callback -, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
V/SurfaceView( 2697): Layout: x=0 y=0 w=1080 h=1920, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
D/OpenGLRenderer( 2697): CanvasContext() 0x7f88f2aa40 initialize 0x7f88e7ca10
D/Surface ( 2697): Surface::connect(this=0x7f88e7ca00,api=1)
I/SurfaceView( 2697): Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
D/mali_winsys( 2697): new_window_surface returns 0x3000
I/SurfaceView( 2697): Cur surface: Surface(name=null)/@0x2887df73, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
D/Surface ( 2697): Surface::allocateBuffers(this=0x7f88e7ca00)
I/SurfaceView( 2697): New surface: Surface(name=null)/@0x2de15e30, vis=true, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceRedrawNeeded, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): finishedDrawing, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
V/SurfaceView( 2697): Layout: x=0 y=0 w=1080 h=1920, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
V/InputMethodManager( 2697): onWindowFocus: io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920} softInputMode=16 first=false flags=#81810100
I/SurfaceView( 2697): Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Cur surface: Surface(name=null)/@0x2887df73, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): New surface: Surface(name=null)/@0x2de15e30, vis=true, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): surfaceRedrawNeeded, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): finishedDrawing, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
V/SurfaceView( 2697): Layout: x=0 y=0 w=1080 h=1920, frame=Rect(0, 0 - 1080, 1920), this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}
I/SurfaceView( 2697): Punch a hole(dispatchDraw), w = 1080, h = 1920, this = io.flutter.view.FlutterView{1ad2212c VFE..... .F...... 0,0-1080,1920}

**Comment by xiao453177912** [comment]
var payRes = await fluwx.pay(
            appId: data["appid"],
            partnerId: data["partnerid"],
            prepayId: data["prepayid"],
            packageValue: data["package"],
            nonceStr: data["noncestr"],
            timeStamp: int.parse(data["timestamp"]),    
            sign: data["sign"],
          );
          print(payRes);
          fluwx.responseFromShare.listen((response) {
            //do something
            print("1111111111");
            print(response);
          });
          fluwx.responseFromAuth.listen((response) {
            //do something
            print("2222222222");
            print(response);
          });
          fluwx.responseFromPayment.listen((response) {
            //do something
            print("3333333333");
            print(response);
          });

我不知道是不是某些步骤没做，

**Comment by JarvanMo** [comment]
请翻阅之前的issue，并仔细阅读微信支付官方文档。多半是支付签名或者应用签名有问题。

**Comment by xiao453177912** [comment]
应用签名：根据项目的应用包名和编译使用的keystore，可由签名工具生成一个32位的md5串，在调试的手机上安装签名工具后，运行可生成应用签名串，如图8.9所示，绿色串即应用签名

这个是要在手机上生成签名，然后修改应用平台上的应用签名吗

**Comment by xiao453177912** [comment]
这个东西下了，点击安装没反应

**Comment by JarvanMo** [comment]
那我不清楚了。微信有个官方工具获取一下就行了。我只能告诉你这么多了，其他的查阅资料吧。

**Comment by JarvanMo** [comment]
在fluw文档也有提过。

**Comment by unclexiao** [comment]
@xiao453177912 这个我遇到过，官方文档有个巨大的坑，就是keystore工具生成的MD5需要**去除横杆**并且全部**转换为小写**，然后配置到**build.gradle**：
```
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }

        debug {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
```
