### ISSUE TITLE
求助，用户登录授权后获取不到响应信息

### ISSUE THREAD

**Issue by HackSoul** [OpenFlutter/fluwx#9]
安卓平台，用您 exmaple 下的 包名，keystore 和 appid 是可以的。

当换成我自己的 包名，keystore，和 appid  后，点击登录能跳转到微信登录界面，但是用户点击授权登录后，在代码里获取不到响应信息，使用 onErr 回掉也捕获不到报错信息。

不知道哪里出错了，没有报错信息，fluwx 的分享倒是能用，登录也能跳到微信授权界面，但是获取不到响应信息。

我在微信开放平台里面已经开通微信登录了。

不知道差了哪一步。

求助，感谢。

**Comment by HackSoul** [comment]
错了，不是求职，是求助，抱歉，笔误。

**Comment by HackSoul** [comment]
fluwx 版本是用的 0.1.4

**Comment by JarvanMo** [comment]
`WXEntryActivity`所以在包必须是`在微信官网注册的包名.wxapi`。

**Comment by HackSoul** [comment]
解决了，没写 .wxapi 。感谢，感谢。
