### ISSUE TITLE
使用1.0.4版本 IOS无法完成跳转和监听response

### ISSUE THREAD

**Issue by CoolBerry** [OpenFlutter/fluwx#90]
用Flutter开发之前没有开发过IOS。看了readme，和Quesionn，说1.0.0之后不用再重写AppDelegate了，于是只在Info里面添加了URL Scheme，别的没有另写其他代码，但似乎不能完成从微信到App的跳转。求助～

另：看到原来已经有一个AppDelegate.swift的文件了。看样子是override了一个application的func，传了一个launchOptions，不是很懂，就没动。

fluwx：1.0.4
Flutter:  1.7.8
Xcode:  10.3

**Comment by CoolBerry** [comment]
url scheme里面要填appid。。。

**Comment by Colaman0** [comment]
> url scheme里面要填appid。。。

请问是什么意思呢？我现在也是没法跳回app，url scheme直接用了bundleid，AppDelegate也需要配置？
