### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_WXOpenBusinessWebViewReq", referenced from:       objc-class-ref in libfluwx.a(FluwxAutoDeductHandler.o)   "_OBJC_CLASS_$_WXOpenBusinessWebViewResp", referenced from:       objc-class-ref in libfluwx.a(FluwxResponseHandler.o) ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by topjx** [OpenFlutter/fluwx#91]
ShareSDK(分享插件)和Fluwx(微信支付插件)存在冲突
1、将S hareSDK 的/ios/sharesdk.podspec里的 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat' 改为 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
2、删除 fluwx 的/ios/Lib里的libWeChatSDK.a，在/ios/fluwx.podspec里添加s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'

删除之后libWeChatSDK.a后一直报错

Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_WXOpenBusinessWebViewReq", referenced from:       objc-class-ref in libfluwx.a(FluwxAutoDeductHandler.o)   "_OBJC_CLASS_$_WXOpenBusinessWebViewResp", referenced from:       objc-class-ref in libfluwx.a(FluwxResponseHandler.o) ld: symbol(s) not found for architecture arm64

**Comment by JarvanMo** [comment]
ios的问题不懂。相关连的其他插件问题更不懂。

**Comment by kennenfromchina** [comment]
@topjx 你现在解决这个问题了吗？
