### ISSUE TITLE
share

### ISSUE THREAD

**Issue by tianweicc** [OpenFlutter/fluwx#93]
fluwx.share(fluwx.WeChatShareTextModel(
                text: "test",
                  scene: fluwx.WeChatScene.TIMELINE
              ));
share text  模式 朋友圈  微信会闪一下

微信已经注册打印 是true

**Comment by tianweicc** [comment]
debug模式下

**Comment by JarvanMo** [comment]
之前的issue有人问了无数遍，readme里有提过，视频也说过。自己去翻答案

**Comment by unclexiao** [comment]
已经有很多类似问题了，比如 #89 #69 
务必注意几个前置步骤：

1. 接入了微信开放平台
2. 确认关联了Bundle ID和Package Name
2. 确保生成了准确的应用签名（MD5去除横线并转为小写）
4. 编译时（debug或release）带上了签名信息（signingConfigs）

这个问题确实与本插件无关，都是微信平台的规则限定，先去熟悉文档吧～～

**Comment by samwuu** [comment]
@unclexiao 怎么带上在开发工具生成的签名信息？我感觉demo真的完全没有 现在支付调试了几天起不来
