### ISSUE TITLE
运行的时候找不到类GlobalScope导致崩溃

### ISSUE THREAD

**Issue by g472786315** [OpenFlutter/fluwx#94]
1.没有开启任何混淆
2. native工程的kotlin版本是1.3.41，已经是最新版本

 [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/GlobalScope;
08-10 14:42:53.597 24399 24399 E flutter : 	at com.jarvan.fluwx.handler.FluwxShareHandler.shareMiniProgram(FluwxShareHandler.kt:117)
08-10 14:42:53.597 24399 24399 E flutter : 	at com.jarvan.fluwx.handler.FluwxShareHandler.handle(FluwxShareHandler.kt:68)
08-10 14:42:53.597 24399 24399 E flutter : 	at com.jarvan.fluwx.FluwxPlugin.onMethodCall(FluwxPlugin.kt:115)
08-10 14:42:53.597 24399 24399 E flutter : 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
08-10 14:42:53.597 24399 24399 E flutter : 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
08-10 14:42:53.597 24399 24399 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
08-10 14:42:53.597 24399 24399 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-10 14:42:53.597 24399 24399 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:332)
08-10 14:42:53.597 24399 24399 E flutter : 	at android.os.Looper.loop(Looper.java:150)
08-10 14:42:53.597 24399 24399 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:6996)
08-10 14:42:53.597 24399 24399 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
08-10 14:42:53.597 24399 24399 E flutter : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-10 14:42:53.597 24399 24399 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
08-10 14:42:53.597 24399 24399 E flutter : Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.GlobalScope" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.homelink.im-zNJK2HMLpe3VW8HxpQxanQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.homelink.im-zNJK2HMLpe3VW8HxpQxanQ==/lib/arm, /data/app/com.homelink.im-zNJK2HMLpe3VW8HxpQxanQ==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
08-10 14:42:53.597 24399 24399 E flutter : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
08-10 14:42:53.597 24399 24399 E flutter : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-10 14:42:53.597 24399 24399 E flutter : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by JarvanMo** [comment]
宿主app kotlin版本不支持kotlinx。
