### ISSUE TITLE
请支持androidx

### ISSUE THREAD

**Issue by rockingdice** [OpenFlutter/fluwx#95]
目前用最新版的flutter打包会报错

具体可参考：
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by JarvanMo** [comment]
请PR。

**Comment by unclexiao** [comment]
只会报警告/提示不会报错误吧～ 
何况目前国内几乎没有Android X的设备，其它插件的迁移成本也很高，你确定要这么做？

**Comment by rockingdice** [comment]
可以分个branch做（本来也就是改几个参数的事儿），flutter自己也是分了稳定版本和一个最新版本针对不同情况。
目前我自己本地改了，以后有人需要再说吧。
