### ISSUE TITLE
分享小程序图片未压缩

### ISSUE THREAD

**Issue by ws4349893** [OpenFlutter/fluwx#97]
- (void)shareMiniProgram:(FlutterMethodCall *)call result:(FlutterResult)result {
    dispatch_queue_t globalQueue = dispatch_get_global_queue(0,0);
    dispatch_async(globalQueue, ^{

        NSString *thumbnail = call.arguments[fluwxKeyThumbnail];

        UIImage *thumbnailImage = [self getThumbnail:thumbnail size:120 * 1024];

        NSData *hdImageData = nil;

        NSString *hdImagePath = call.arguments[@"hdImagePath"];
        if (![StringUtil isBlank:hdImagePath]) {
            if ([hdImagePath hasPrefix:SCHEMA_ASSETS]) {
                hdImageData = [NSData dataWithContentsOfFile:[self readImageFromAssets:hdImagePath]];

            } else if ([hdImagePath hasPrefix:SCHEMA_FILE]) {
                NSUInteger startIndex = SCHEMA_FILE.length;

//        int startIndex = SCHEMA_FILE.e
                NSString *imagePathWithoutUri = [hdImagePath substringFromIndex:startIndex];
                hdImageData = [NSData dataWithContentsOfFile:imagePathWithoutUri];
            } else {
                NSURL *hdImageURL = [NSURL URLWithString:hdImagePath];
                hdImageData = [NSData dataWithContentsOfURL:hdImageURL];
            }
        }
这一段是分享小程序的代码,微信要求分享hdImageData不能大于128k,现在没有对 hdImageData 进行压缩,反而对弃用的thumbnailImage 压缩了.

**Comment by JarvanMo** [comment]
除了缩略图请自行压缩。因为lib压缩无法保证得到你想要的效果。

**Comment by ws4349893** [comment]
好的 谢谢
