### ISSUE TITLE
why the "timestamp" is not the type String but int? 

### ISSUE THREAD

**Issue by RRRMannn** [OpenFlutter/fluwx#98]
it make some problem with me

**Comment by JarvanMo** [comment]
because timestamp is int in iOS.

**Comment by RRRMannn** [comment]
got it ,thanks bro




------------------ 原始邮件 ------------------
发件人: "JarvanMo"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 中午11:51
收件人: "OpenFlutter/fluwx"<fluwx@noreply.github.com>; 
抄送: "满、"<975254814@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [OpenFlutter/fluwx] why the "timestamp" is not the type Stringbut int?  (#98)




because timestamp is int in iOS.
